DROP TABLE gpsqlweb.report
GO

CREATE TABLE  gpsqlweb.report (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    report_group_id BIGINT,
    data_source_id BIGINT,
    name varchar(255) NOT NULL,
    description VARCHAR(32000),
    query VARCHAR(32000) NOT NULL,
    uses BIGINT NOT NULL DEFAULT '0',
    chart char(1),
    enabled char(1) DEFAULT 'Y',
    deleted char(1) DEFAULT 'N',
    created_at timestamp,
    created_by VARCHAR(20),
    updated_at timestamp,
    updated_by VARCHAR(20),
    CONSTRAINT gpsqlweb.pk_report_id PRIMARY KEY (id),
    FOREIGN KEY (report_group_id) REFERENCES report_group(id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id)
)
GO

/*
CREATE TABLE  `tesoreria`.`report` (
  `id` int(11) NOT NULL DEFAULT '0',
  `report_group_id` int(11) DEFAULT NULL,
  `data_source_id` int(11) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `count_query` text,
  `query` text NOT NULL,
  `uses` int(11) DEFAULT '0',
  `chart` char(1) DEFAULT NULL,
  `enabled` char(1) DEFAULT NULL,
  `deleted` char(1) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
*/