DROP TABLE gpsqlweb.data_source
GO

CREATE TABLE gpsqlweb.data_source (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    connecton_type VARCHAR(20) NOT NULL,
    jndi VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    driver VARCHAR(255) NOT NULL,
    host VARCHAR(255) NOT NULL,
    dbname VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled char(1) DEFAULT 'Y',
    deleted char(1) DEFAULT 'N',
    created_at timestamp,
    created_by VARCHAR(20),
    updated_at timestamp,
    updated_by VARCHAR(20),
    CONSTRAINT gpsqlweb.pk_data_source_id PRIMARY KEY (id)
)
GO
/*

CREATE TABLE  `tesoreria`.`data_source` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `connecton_type` varchar(20) NOT NULL,
  `jndi` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `driver` varchar(255) DEFAULT NULL,
  `host` varchar(255) DEFAULT NULL,
  `dbname` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `enabled` char(1) DEFAULT 'Y',
  `deleted` char(1) DEFAULT 'N',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

*/