package ve.com.sios.gpff.message;

import ve.com.sios.gpff.sockets.DecimalField;
import ve.com.sios.gpff.sockets.MessageRecord;
import ve.com.sios.gpff.sockets.CharacterField;
import ve.com.sios.gpff.sockets.MessageField;
import java.io.*;
import java.math.*;

import java.util.*;

/**
* Class generated by AS/400 CRTCLASS command from WTIPMNUB physical file definition.
* 
* File level identifier is 1130110160205.
* Record format level identifier is 3EB5E9F372D35.
*/

public class WTIPMNUBMessage extends MessageRecord
{
  final static String fldnames[] = {
                                     "HPGM",
                                     "HDAT",
                                     "HTIM",
                                     "HUSR",
                                     "HENV",
                                     "HPRO",
                                     "HRIN",
                                     "HNRE",
                                     "HRRL",
                                     "HTOT",
                                     "HFLI",
                                     "HAREA",
                                     "EFLG0",
                                     "EDSC0",
                                     "ACTIVO",
                                     "NOMPGM",
                                     "DESCRI"
                                   };
  final static String tnames[] = {
                                   "HPGM",
                                   "HDAT",
                                   "HTIM",
                                   "HUSR",
                                   "HENV",
                                   "HPRO",
                                   "HRIN",
                                   "HNRE",
                                   "HRRL",
                                   "HTOT",
                                   "HFLI",
                                   "HAREA",
                                   "EFLG0",
                                   "EDSC0",
                                   "ACTIVO",
                                   "NOMPGM",
                                   "DESCRI"
                                 };
  final static String fid = "1130110160205";
  final static String rid = "3EB5E9F372D35";
  final static String fmtname = "WTIPMNUB";
  final int FIELDCOUNT = 17;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldHPGM = null;
  private DecimalField fieldHDAT = null;
  private DecimalField fieldHTIM = null;
  private CharacterField fieldHUSR = null;
  private CharacterField fieldHENV = null;
  private CharacterField fieldHPRO = null;
  private DecimalField fieldHRIN = null;
  private DecimalField fieldHNRE = null;
  private DecimalField fieldHRRL = null;
  private DecimalField fieldHTOT = null;
  private CharacterField fieldHFLI = null;
  private CharacterField fieldHAREA = null;
  private CharacterField fieldEFLG0 = null;
  private CharacterField fieldEDSC0 = null;
  private CharacterField fieldACTIVO = null;
  private CharacterField fieldNOMPGM = null;
  private CharacterField fieldDESCRI = null;

  /**
  * Constructor for WTIPMNUBMessage.
  */
  public WTIPMNUBMessage()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 633;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldHPGM =
    new CharacterField(message, HEADERSIZE + 0, 10, "HPGM");
    fields[1] = fieldHDAT =
    new DecimalField(message, HEADERSIZE + 10, 7, 0, "HDAT");
    fields[2] = fieldHTIM =
    new DecimalField(message, HEADERSIZE + 17, 7, 0, "HTIM");
    fields[3] = fieldHUSR =
    new CharacterField(message, HEADERSIZE + 24, 10, "HUSR");
    fields[4] = fieldHENV =
    new CharacterField(message, HEADERSIZE + 34, 1, "HENV");
    fields[5] = fieldHPRO =
    new CharacterField(message, HEADERSIZE + 35, 4, "HPRO");
    fields[6] = fieldHRIN =
    new DecimalField(message, HEADERSIZE + 39, 6, 0, "HRIN");
    fields[7] = fieldHNRE =
    new DecimalField(message, HEADERSIZE + 45, 4, 0, "HNRE");
    fields[8] = fieldHRRL =
    new DecimalField(message, HEADERSIZE + 49, 9, 0, "HRRL");
    fields[9] = fieldHTOT =
    new DecimalField(message, HEADERSIZE + 58, 8, 0, "HTOT");
    fields[10] = fieldHFLI =
    new CharacterField(message, HEADERSIZE + 66, 1, "HFLI");
    fields[11] = fieldHAREA =
    new CharacterField(message, HEADERSIZE + 67, 4, "HAREA");
    fields[12] = fieldEFLG0 =
    new CharacterField(message, HEADERSIZE + 71, 1, "EFLG0");
    fields[13] = fieldEDSC0 =
    new CharacterField(message, HEADERSIZE + 72, 500, "EDSC0");
    fields[14] = fieldACTIVO =
    new CharacterField(message, HEADERSIZE + 572, 1, "ACTIVO");
    fields[15] = fieldNOMPGM =
    new CharacterField(message, HEADERSIZE + 573, 10, "NOMPGM");
    fields[16] = fieldDESCRI =
    new CharacterField(message, HEADERSIZE + 583, 50, "DESCRI");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field HPGM using a String value.
  */
  public void setHPGM(String newvalue)
  {
    fieldHPGM.setString(newvalue);
  }

  /**
  * Get value of field HPGM as a String.
  */
  public String getHPGM()
  {
    return fieldHPGM.getString();
  }

  /**
  * Set field HDAT using a String value.
  */
  public void setHDAT(String newvalue)
  {
    fieldHDAT.setString(newvalue);
  }

  /**
  * Get value of field HDAT as a String.
  */
  public String getHDAT()
  {
    return fieldHDAT.getString();
  }

  /**
  * Set numeric field HDAT using a BigDecimal value.
  */
  public void setHDAT(BigDecimal newvalue)
  {
    fieldHDAT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HDAT as a BigDecimal.
  */
  public BigDecimal getBigDecimalHDAT()
  {
    return fieldHDAT.getBigDecimal();
  }

  /**
  * Set field HTIM using a String value.
  */
  public void setHTIM(String newvalue)
  {
    fieldHTIM.setString(newvalue);
  }

  /**
  * Get value of field HTIM as a String.
  */
  public String getHTIM()
  {
    return fieldHTIM.getString();
  }

  /**
  * Set numeric field HTIM using a BigDecimal value.
  */
  public void setHTIM(BigDecimal newvalue)
  {
    fieldHTIM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HTIM as a BigDecimal.
  */
  public BigDecimal getBigDecimalHTIM()
  {
    return fieldHTIM.getBigDecimal();
  }

  /**
  * Set field HUSR using a String value.
  */
  public void setHUSR(String newvalue)
  {
    fieldHUSR.setString(newvalue);
  }

  /**
  * Get value of field HUSR as a String.
  */
  public String getHUSR()
  {
    return fieldHUSR.getString();
  }

  /**
  * Set field HENV using a String value.
  */
  public void setHENV(String newvalue)
  {
    fieldHENV.setString(newvalue);
  }

  /**
  * Get value of field HENV as a String.
  */
  public String getHENV()
  {
    return fieldHENV.getString();
  }

  /**
  * Set field HPRO using a String value.
  */
  public void setHPRO(String newvalue)
  {
    fieldHPRO.setString(newvalue);
  }

  /**
  * Get value of field HPRO as a String.
  */
  public String getHPRO()
  {
    return fieldHPRO.getString();
  }

  /**
  * Set field HRIN using a String value.
  */
  public void setHRIN(String newvalue)
  {
    fieldHRIN.setString(newvalue);
  }

  /**
  * Get value of field HRIN as a String.
  */
  public String getHRIN()
  {
    return fieldHRIN.getString();
  }

  /**
  * Set numeric field HRIN using a BigDecimal value.
  */
  public void setHRIN(BigDecimal newvalue)
  {
    fieldHRIN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HRIN as a BigDecimal.
  */
  public BigDecimal getBigDecimalHRIN()
  {
    return fieldHRIN.getBigDecimal();
  }

  /**
  * Set field HNRE using a String value.
  */
  public void setHNRE(String newvalue)
  {
    fieldHNRE.setString(newvalue);
  }

  /**
  * Get value of field HNRE as a String.
  */
  public String getHNRE()
  {
    return fieldHNRE.getString();
  }

  /**
  * Set numeric field HNRE using a BigDecimal value.
  */
  public void setHNRE(BigDecimal newvalue)
  {
    fieldHNRE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HNRE as a BigDecimal.
  */
  public BigDecimal getBigDecimalHNRE()
  {
    return fieldHNRE.getBigDecimal();
  }

  /**
  * Set field HRRL using a String value.
  */
  public void setHRRL(String newvalue)
  {
    fieldHRRL.setString(newvalue);
  }

  /**
  * Get value of field HRRL as a String.
  */
  public String getHRRL()
  {
    return fieldHRRL.getString();
  }

  /**
  * Set numeric field HRRL using a BigDecimal value.
  */
  public void setHRRL(BigDecimal newvalue)
  {
    fieldHRRL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HRRL as a BigDecimal.
  */
  public BigDecimal getBigDecimalHRRL()
  {
    return fieldHRRL.getBigDecimal();
  }

  /**
  * Set field HTOT using a String value.
  */
  public void setHTOT(String newvalue)
  {
    fieldHTOT.setString(newvalue);
  }

  /**
  * Get value of field HTOT as a String.
  */
  public String getHTOT()
  {
    return fieldHTOT.getString();
  }

  /**
  * Set numeric field HTOT using a BigDecimal value.
  */
  public void setHTOT(BigDecimal newvalue)
  {
    fieldHTOT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HTOT as a BigDecimal.
  */
  public BigDecimal getBigDecimalHTOT()
  {
    return fieldHTOT.getBigDecimal();
  }

  /**
  * Set field HFLI using a String value.
  */
  public void setHFLI(String newvalue)
  {
    fieldHFLI.setString(newvalue);
  }

  /**
  * Get value of field HFLI as a String.
  */
  public String getHFLI()
  {
    return fieldHFLI.getString();
  }

  /**
  * Set field HAREA using a String value.
  */
  public void setHAREA(String newvalue)
  {
    fieldHAREA.setString(newvalue);
  }

  /**
  * Get value of field HAREA as a String.
  */
  public String getHAREA()
  {
    return fieldHAREA.getString();
  }

  /**
  * Set field EFLG0 using a String value.
  */
  public void setEFLG0(String newvalue)
  {
    fieldEFLG0.setString(newvalue);
  }

  /**
  * Get value of field EFLG0 as a String.
  */
  public String getEFLG0()
  {
    return fieldEFLG0.getString();
  }

  /**
  * Set field EDSC0 using a String value.
  */
  public void setEDSC0(String newvalue)
  {
    fieldEDSC0.setString(newvalue);
  }

  /**
  * Get value of field EDSC0 as a String.
  */
  public String getEDSC0()
  {
    return fieldEDSC0.getString();
  }

  /**
  * Set field ACTIVO using a String value.
  */
  public void setACTIVO(String newvalue)
  {
    fieldACTIVO.setString(newvalue);
  }

  /**
  * Get value of field ACTIVO as a String.
  */
  public String getACTIVO()
  {
    return fieldACTIVO.getString();
  }

  /**
  * Set field NOMPGM using a String value.
  */
  public void setNOMPGM(String newvalue)
  {
    fieldNOMPGM.setString(newvalue);
  }

  /**
  * Get value of field NOMPGM as a String.
  */
  public String getNOMPGM()
  {
    return fieldNOMPGM.getString();
  }

  /**
  * Set field DESCRI using a String value.
  */
  public void setDESCRI(String newvalue)
  {
    fieldDESCRI.setString(newvalue);
  }

  /**
  * Get value of field DESCRI as a String.
  */
  public String getDESCRI()
  {
    return fieldDESCRI.getString();
  }

}
