
-- DROP PROCEDURE GPSQLWEB.procUpdatePerfil
    
CREATE PROCEDURE GPSQLWEB.procUpdatePerfil
(
    IN P_PRFPRF VARCHAR(10),
    IN P_PRFNOM VARCHAR(45),
    IN P_PRFCED VARCHAR(12),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  UPDATE GPDATWEB.PERFIL SET PRFNOM= P_PRFNOM, PRFCED= P_PRFCED  WHERE PRFPRF=P_PRFPRF;
  SET P_MSGCODE = 0;
  Set StringSQL = 'UPDATE GPDATWEB.PERFIL SET PRFNOM= '''||P_PRFNOM || ''' , PRFCED= '''||P_PRFCED || '''  WHERE PRFPRF= '''||P_PRFPRF || ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdatePerfil', StringSQL);
END
GO


