--DROP PROCEDURE GPSQLWEB.procCreateAa2mcli
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2mcli
(
    IN P_CLIEMP VARCHAR(2),
    IN P_CLIDEL VARCHAR(2),
    IN P_CLINIF VARCHAR(12),
    IN P_CLIASO NUMERIC(7 , 0),
    IN P_CLIANA DECIMAL(8 , 0),
    IN P_CLINOM VARCHAR(20),
    IN P_CLIAPE VARCHAR(15),
    IN P_CLIAP2 VARCHAR(15),
    IN P_CLICAL VARCHAR(2),
    IN P_CLIDI1 VARCHAR(30),
    IN P_CLIDI2 VARCHAR(30),
    IN P_CLIPOS VARCHAR(9),
    IN P_CLIPRO VARCHAR(25),
    IN P_CLIPAI NUMERIC(3 , 0),
    IN P_CLIPOB VARCHAR(27),
    IN P_CLIGES NUMERIC(2 , 0),
    IN P_CLITC1 NUMERIC(2 , 0),
    IN P_CLICLS NUMERIC(2 , 0),
    IN P_CLISEX VARCHAR(1),
    IN P_CLITEL DECIMAL(10 , 0),
    IN P_CLITE2 DECIMAL(10 , 0),
    IN P_CLITE3 DECIMAL(10 , 0),
    IN P_CLIFAX VARCHAR(15),
    IN P_CLIFA2 VARCHAR(15),
    IN P_CLIFA3 VARCHAR(15),
    IN P_CLITC2 NUMERIC(3 , 0),
    IN P_CLIRES NUMERIC(3 , 0),
    IN P_CLICOR NUMERIC(9 , 0),
    IN P_CLITCO VARCHAR(1),
    IN P_CLIEXC VARCHAR(1),
    IN P_CLIOBS VARCHAR(50),
    IN P_CLIREG VARCHAR(1),
    IN P_CLIOCU VARCHAR(1),
    IN P_CLIGRU NUMERIC(3 , 0),
    IN P_CLIPAS VARCHAR(1),
    IN P_CLIORD VARCHAR(15),
    IN P_CLINUM DECIMAL(5 , 0),
    IN P_CLICRE VARCHAR(6),
    IN P_CLITID VARCHAR(1),
    IN P_CLINAC NUMERIC(1 , 0),
    IN P_CLIMEF VARCHAR(10),
    IN P_CLIESC NUMERIC(2 , 0),
    IN P_CLIGID VARCHAR(6),
    IN P_CLIDPR VARCHAR(16),
    IN P_CLIDAT DECIMAL(9 , 0),
    IN P_CLIVOZ DECIMAL(4 , 0),
    IN P_CLIDPD VARCHAR(16),
    IN P_CLIFEA DECIMAL(8 , 0),
    IN P_CLIFEB DECIMAL(8 , 0),
    IN P_CLIUSU VARCHAR(10),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_CLICLA INTEGER,
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
    DECLARE StringSQL Varchar(32000) Default '';
    DECLARE V_AREA VARCHAR(4) DEFAULT '';
    Declare V_CANT INT DEFAULT 0;

    SET V_AREA = P_CLIEMP || P_CLIDEL;


    SELECT COUNT(1) INTO V_CANT FROM gpdatweb.aa2tfide WHERE TRIM(FIDCLA) =  P_CLIEMP || P_CLIDEL;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1002;
        SET StringSQL = '1002 - AREA NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TDIV WHERE DIVCLA=P_CLITC2;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1004;
        SET StringSQL = '1004 - DIVISA NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TPAIS WHERE PAICLA=P_CLIPAI;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1012;
        SET StringSQL = '1012 - CODIGO PAIS NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    select count(1) into V_CANT from GPDATWEB.AA2TIPCL where TICCLA = P_CLITC1;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1007;
        SET StringSQL = '1007 - TIPO DE ENTIDAD / CLIENTE NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;
    
    select count(1) into V_CANT from GPDATWEB.AA2GESTO where substring(GESCLA, 14, 2) = P_CLIGES;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1013;
        SET StringSQL = '1013 - CODIGO EJECUTIVO NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    select count(1) into V_CANT from GPDATWEB.TABCCLI where CODIGO = P_CLICLS;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1014;
        SET StringSQL = '1014 - CODIGO CATEGORIA CLIENTE NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    select count(1) into V_CANT from GPDATWEB.AA2COCOR where CODCOR = P_CLICOR;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1015;
        SET StringSQL = '1015 - CODIGO COORPORATICO NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;


    SELECT  COALESCE(MAX(CLICLA), 0) +1 INTO P_CLICLA FROM GPDATWEB.AA2MCLI;

    IF P_CLIASO IS NULL OR P_CLIASO = 0 THEN
        SET P_CLIASO = P_CLICLA;
    END IF;

    SELECT 
        CAST (YEAR(current timestamp) || substr( digits (MONTH(current timestamp)),9) || substr( digits (DAY(current timestamp)),9) AS DECIMAL(8,0))
         INTO P_CLIFEA FROM SYSIBM.SYSDUMMY1;

    SET P_CLIUSU =  SUBSTRING(P_USERNAME, 0, 11);

    INSERT INTO GPDATWEB.AA2MCLI (CLICLA, CLIEMP ,CLIDEL ,CLINIF ,CLIASO ,CLIANA ,CLINOM ,CLIAPE ,CLIAP2 ,CLICAL ,CLIDI1 ,CLIDI2 ,CLIPOS ,CLIPRO ,CLIPAI ,CLIPOB ,CLIGES ,CLITC1 ,CLICLS ,CLISEX ,CLITEL ,CLITE2 ,CLITE3 ,CLIFAX ,CLIFA2 ,CLIFA3 ,CLITC2 ,CLIRES ,CLICOR ,CLITCO ,CLIEXC ,CLIOBS ,CLIREG ,CLIOCU ,CLIGRU ,CLIPAS ,CLIORD ,CLINUM ,CLICRE ,CLITID ,CLINAC ,CLIMEF ,CLIESC ,CLIGID ,CLIDPR ,CLIDAT ,CLIVOZ ,CLIDPD ,CLIFEA ,CLIFEB ,CLIUSU ) 
        VALUES (P_CLICLA,  P_CLIEMP , P_CLIDEL , P_CLINIF , P_CLIASO , P_CLIANA , P_CLINOM , P_CLIAPE , P_CLIAP2 , P_CLICAL , P_CLIDI1 , P_CLIDI2 , P_CLIPOS , P_CLIPRO , P_CLIPAI , P_CLIPOB , P_CLIGES , P_CLITC1 , P_CLICLS , P_CLISEX , P_CLITEL , P_CLITE2 , P_CLITE3 , P_CLIFAX , P_CLIFA2 , P_CLIFA3 , P_CLITC2 , P_CLIRES , P_CLICOR , P_CLITCO , P_CLIEXC , P_CLIOBS , P_CLIREG , P_CLIOCU , P_CLIGRU , P_CLIPAS , P_CLIORD , P_CLINUM , P_CLICRE , P_CLITID , P_CLINAC , P_CLIMEF , P_CLIESC , P_CLIGID , P_CLIDPR , P_CLIDAT , P_CLIVOZ , P_CLIDPD , P_CLIFEA , P_CLIFEB , P_CLIUSU );
    SET P_MSGCODE = 5000; 
    --Set StringSQL = 'INSERT INTO GPDATWEB.AA2MCLI (CLICLA CLIEMP ,CLIDEL ,CLINIF ,CLIASO ,CLIANA ,CLINOM ,CLIAPE ,CLIAP2 ,CLICAL ,CLIDI1 ,CLIDI2 ,CLIPOS ,CLIPRO ,CLIPAI ,CLIPOB ,CLIGES ,CLITC1 ,CLICLS ,CLISEX ,CLITEL ,CLITE2 ,CLITE3 ,CLIFAX ,CLIFA2 ,CLIFA3 ,CLITC2 ,CLIRES ,CLICOR ,CLITCO ,CLIEXC ,CLIOBS ,CLIREG ,CLIOCU ,CLIGRU ,CLIPAS ,CLIORD ,CLINUM ,CLICRE ,CLITID ,CLINAC ,CLIMEF ,CLIESC ,CLIGID ,CLIDPR ,CLIDAT ,CLIVOZ ,CLIDPD ,CLIFEA ,CLIFEB ,CLIUSU ) VALUES (''' || P_CLICLA  ||''' ,  '''|| P_CLIEMP || ''' , '''|| P_CLIDEL || ''' , '''|| P_CLINIF || ''' , '''|| P_CLIASO || ''' , '''|| P_CLIANA || ''' , '''|| P_CLINOM || ''' , '''|| P_CLIAPE || ''' , '''|| P_CLIAP2 || ''' , '''|| P_CLICAL || ''' , '''|| P_CLIDI1 || ''' , '''|| P_CLIDI2 || ''' , '''|| P_CLIPOS || ''' , '''|| P_CLIPRO || ''' , '''|| P_CLIPAI || ''' , '''|| P_CLIPOB || ''' , '''|| P_CLIGES || ''' , '''|| P_CLITC1 || ''' , '''|| P_CLICLS || ''' , '''|| P_CLISEX || ''' , '''|| P_CLITEL || ''' , '''|| P_CLITE2 || ''' , '''|| P_CLITE3 || ''' , '''|| P_CLIFAX || ''' , '''|| P_CLIFA2 || ''' , '''|| P_CLIFA3 || ''' , '''|| P_CLITC2 || ''' , '''|| P_CLIRES || ''' , '''|| P_CLICOR || ''' , '''|| P_CLITCO || ''' , '''|| P_CLIEXC || ''' , '''|| P_CLIOBS || ''' , '''|| P_CLIREG || ''' , '''|| P_CLIOCU || ''' , '''|| P_CLIGRU || ''' , '''|| P_CLIPAS || ''' , '''|| P_CLIORD || ''' , '''|| P_CLINUM || ''' , '''|| P_CLICRE || ''' , '''|| P_CLITID || ''' , '''|| P_CLINAC || ''' , '''|| P_CLIMEF || ''' , '''|| P_CLIESC || ''' , '''|| P_CLIGID || ''' , '''|| P_CLIDPR || ''' , '''|| P_CLIDAT || ''' , '''|| P_CLIVOZ || ''' , '''|| P_CLIDPD || ''' , '''|| P_CLIFEA || ''' , '''|| P_CLIFEB || ''' , '''|| P_CLIUSU || ''' )'; 
    --CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);

    -- Si es Nuevo y CLITC1 = 2:
    -- Hay que ejecutar el programa CLCRECTA4
    IF P_CLITC1 = 2 THEN
        CALL GPSQLWEB.PROCCLCRECTA4(P_CLICLA, P_CLITC1, P_CLINOM, P_CLIAPE, P_CLIAP2, P_CLISEX, V_AREA);
        SET P_MSGCODE = 0;
    END IF;

    --Si es Nuevo y CLITC1 <> 2:
    --Marcar el campo CLIREG='E' Y ejecutar CRECTA7
    IF P_CLITC1 <> 2 THEN
        UPDATE GPDATWEB.AA2MCLI SET CLIREG='E' WHERE CLICLA = P_CLICLA;
        CALL GPSQLWEB.PROCCLCRECTA7(P_CLIEMP, P_CLIDEL, P_CLICLA);
        SET P_MSGCODE = 0;
    END IF;

    --Si es Nuevo y CLITC1 = 50:
    --Hay que ejecutar el programa CTLFO2PMP
    IF P_CLITC1 = 50 THEN
        CALL GPSQLWEB.PROCCLCTLFO2PM(V_AREA, P_CLICLA, P_CLITC2);
        SET P_MSGCODE = 0;
    END IF;

    SET P_MSGCODE = 0; 

END
GO


