
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2mcli
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2mcli
(
    IN P_CLIEMP CHAR(2),
    IN P_CLIDEL CHAR(2),
    IN P_CLICLA  NUMERIC(7 , 0),
    IN P_CLINIF CHAR(12),
    IN P_CLIASO NUMERIC(7 , 0),
    IN P_CLIANA DECIMAL(8 , 0),
    IN P_CLINOM CHAR(20),
    IN P_CLIAPE CHAR(15),
    IN P_CLIAP2 CHAR(15),
    IN P_CLICAL CHAR(2),
    IN P_CLIDI1 CHAR(30),
    IN P_CLIDI2 CHAR(30),
    IN P_CLIPOS CHAR(9),
    IN P_CLIPRO CHAR(25),
    IN P_CLIPAI NUMERIC(3 , 0),
    IN P_CLIPOB CHAR(27),
    IN P_CLIGES NUMERIC(2 , 0),
    IN P_CLITC1 NUMERIC(2 , 0),
    IN P_CLICLS NUMERIC(2 , 0),
    IN P_CLISEX CHAR(1),
    IN P_CLITEL DECIMAL(10 , 0),
    IN P_CLITE2 DECIMAL(10 , 0),
    IN P_CLITE3 DECIMAL(10 , 0),
    IN P_CLIFAX CHAR(15),
    IN P_CLIFA2 CHAR(15),
    IN P_CLIFA3 CHAR(15),
    IN P_CLITC2 NUMERIC(3 , 0),
    IN P_CLIRES NUMERIC(3 , 0),
    IN P_CLICOR NUMERIC(9 , 0),
    IN P_CLITCO CHAR(1),
    IN P_CLIEXC CHAR(1),
    IN P_CLIOBS CHAR(50),
    IN P_CLIREG CHAR(1),
    IN P_CLIOCU CHAR(1),
    IN P_CLIGRU NUMERIC(3 , 0),
    IN P_CLIPAS CHAR(1),
    IN P_CLIORD CHAR(15),
    IN P_CLINUM DECIMAL(5 , 0),
    IN P_CLICRE CHAR(6),
    IN P_CLITID CHAR(1),
    IN P_CLINAC NUMERIC(1 , 0),
    IN P_CLIMEF CHAR(10),
    IN P_CLIESC NUMERIC(2 , 0),
    IN P_CLIGID CHAR(6),
    IN P_CLIDPR CHAR(16),
    IN P_CLIDAT DECIMAL(9 , 0),
    IN P_CLIVOZ DECIMAL(4 , 0),
    IN P_CLIDPD CHAR(16),
    IN P_CLIFEA DECIMAL(8 , 0),
    IN P_CLIFEB DECIMAL(8 , 0),
    IN P_CLIUSU CHAR(10),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
    Declare StringSQL Varchar(32000) Default '';
    Declare V_CANT INT DEFAULT 0;
    DECLARE V_AREA VARCHAR(4) DEFAULT '';
    SET V_AREA = P_CLIEMP || P_CLIDEL;

    SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2MCLI WHERE CLICLA = P_CLICLA;

    IF V_CANT > 1 THEN
          SET P_MSGCODE = 9001;
          SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
          CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2mcli', StringSQL);
          RETURN;
    END IF;

    IF V_CANT = 0 THEN
          SET P_MSGCODE = 9000;
          SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
          CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2mcli', StringSQL);
          RETURN;
    END IF;


    SELECT COUNT(1) INTO V_CANT FROM gpdatweb.aa2tfide WHERE TRIM(FIDCLA) =  P_CLIEMP || P_CLIDEL;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1002;
        SET StringSQL = '1002 - AREA NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TDIV WHERE DIVCLA=P_CLITC2;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1004;
        SET StringSQL = '1004 - DIVISA NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TPAIS WHERE PAICLA=P_CLIPAI;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1012;
        SET StringSQL = '1012 - CODIGO PAIS NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    select count(1) into V_CANT from GPDATWEB.AA2TIPCL where TICCLA = P_CLITC1;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1007;
        SET StringSQL = '1007 - TIPO DE ENTIDAD / CLIENTE NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;
    
    select count(1) into V_CANT from GPDATWEB.AA2GESTO where substring(GESCLA, 14, 2) = P_CLIGES;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1013;
        SET StringSQL = '1013 - CODIGO EJECUTIVO NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    select count(1) into V_CANT from GPDATWEB.TABCCLI where CODIGO = P_CLICLS;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1014;
        SET StringSQL = '1014 - CODIGO CATEGORIA CLIENTE NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;

    select count(1) into V_CANT from GPDATWEB.AA2COCOR where CODCOR = P_CLICOR;
    IF V_CANT = 0 THEN
	SET P_MSGCODE = 1015;
        SET StringSQL = '1015 - CODIGO COORPORATICO NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mcli', StringSQL);
        RETURN;
    END IF;


    UPDATE GPDATWEB.AA2MCLI SET CLIEMP= P_CLIEMP , CLIDEL= P_CLIDEL , CLINIF= P_CLINIF , CLIASO= P_CLIASO , CLIANA= P_CLIANA , CLINOM= P_CLINOM , CLIAPE= P_CLIAPE , CLIAP2= P_CLIAP2 , CLICAL= P_CLICAL , CLIDI1= P_CLIDI1 , CLIDI2= P_CLIDI2 , CLIPOS= P_CLIPOS , CLIPRO= P_CLIPRO , CLIPAI= P_CLIPAI , CLIPOB= P_CLIPOB , CLIGES= P_CLIGES , CLITC1= P_CLITC1 , CLICLS= P_CLICLS , CLISEX= P_CLISEX , CLITEL= P_CLITEL , CLITE2= P_CLITE2 , CLITE3= P_CLITE3 , CLIFAX= P_CLIFAX , CLIFA2= P_CLIFA2 , CLIFA3= P_CLIFA3 , CLITC2= P_CLITC2 , CLIRES= P_CLIRES , CLICOR= P_CLICOR , CLITCO= P_CLITCO , CLIEXC= P_CLIEXC , CLIOBS= P_CLIOBS , CLIREG= P_CLIREG , CLIOCU= P_CLIOCU , CLIGRU= P_CLIGRU , CLIPAS= P_CLIPAS , CLIORD= P_CLIORD , CLINUM= P_CLINUM , CLICRE= P_CLICRE , CLITID= P_CLITID , CLINAC= P_CLINAC , CLIMEF= P_CLIMEF , CLIESC= P_CLIESC , CLIGID= P_CLIGID , CLIDPR= P_CLIDPR , CLIDAT= P_CLIDAT , CLIVOZ= P_CLIVOZ , CLIDPD= P_CLIDPD , CLIFEA= P_CLIFEA , CLIFEB= P_CLIFEB , CLIUSU= P_CLIUSU  WHERE CLICLA= P_CLICLA ;
    SET P_MSGCODE = 5000;
    --Set StringSQL = 'UPDATE GPDATWEB.AA2MCLI SET CLIEMP= '''||P_CLIEMP || ''' , CLIDEL= '''||P_CLIDEL || ''' , CLINIF= '''||P_CLINIF || ''' , CLIASO= '''||P_CLIASO || ''' , CLIANA= '''||P_CLIANA || ''' , CLINOM= '''||P_CLINOM || ''' , CLIAPE= '''||P_CLIAPE || ''' , CLIAP2= '''||P_CLIAP2 || ''' , CLICAL= '''||P_CLICAL || ''' , CLIDI1= '''||P_CLIDI1 || ''' , CLIDI2= '''||P_CLIDI2 || ''' , CLIPOS= '''||P_CLIPOS || ''' , CLIPRO= '''||P_CLIPRO || ''' , CLIPAI= '''||P_CLIPAI || ''' , CLIPOB= '''||P_CLIPOB || ''' , CLIGES= '''||P_CLIGES || ''' , CLITC1= '''||P_CLITC1 || ''' , CLICLS= '''||P_CLICLS || ''' , CLISEX= '''||P_CLISEX || ''' , CLITEL= '''||P_CLITEL || ''' , CLITE2= '''||P_CLITE2 || ''' , CLITE3= '''||P_CLITE3 || ''' , CLIFAX= '''||P_CLIFAX || ''' , CLIFA2= '''||P_CLIFA2 || ''' , CLIFA3= '''||P_CLIFA3 || ''' , CLITC2= '''||P_CLITC2 || ''' , CLIRES= '''||P_CLIRES || ''' , CLICOR= '''||P_CLICOR || ''' , CLITCO= '''||P_CLITCO || ''' , CLIEXC= '''||P_CLIEXC || ''' , CLIOBS= '''||P_CLIOBS || ''' , CLIREG= '''||P_CLIREG || ''' , CLIOCU= '''||P_CLIOCU || ''' , CLIGRU= '''||P_CLIGRU || ''' , CLIPAS= '''||P_CLIPAS || ''' , CLIORD= '''||P_CLIORD || ''' , CLINUM= '''||P_CLINUM || ''' , CLICRE= '''||P_CLICRE || ''' , CLITID= '''||P_CLITID || ''' , CLINAC= '''||P_CLINAC || ''' , CLIMEF= '''||P_CLIMEF || ''' , CLIESC= '''||P_CLIESC || ''' , CLIGID= '''||P_CLIGID || ''' , CLIDPR= '''||P_CLIDPR || ''' , CLIDAT= '''||P_CLIDAT || ''' , CLIVOZ= '''||P_CLIVOZ || ''' , CLIDPD= '''||P_CLIDPD || ''' , CLIFEA= '''||P_CLIFEA || ''' , CLIFEB= '''||P_CLIFEB || ''' , CLIUSU= '''||P_CLIUSU || '''  WHERE CLICLA= '''||P_CLICLA|| ''' ;';
    --CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2mcli', StringSQL);

    --Si es Modificar y CLITC1 = 2:
    --Hay que ejecutar el programa CLCRECTA4
    IF P_CLITC1 = 2 THEN
        CALL GPSQLWEB.PROCCLCRECTA4(P_CLICLA, P_CLITC1, P_CLINOM, P_CLIAPE, P_CLIAP2, P_CLISEX, V_AREA);
        SET P_MSGCODE = 0;
    END IF;
    
    --Si es Modificación y CLITC1 <> 2:
    --Marcar el campo CLIREG='E' y actualizar
    --Hay que actualizar el campo ejecutar el programa CRECTA7
    IF P_CLITC1 <> 2 THEN
        UPDATE GPDATWEB.AA2MCLI SET CLIREG='E' WHERE CLICLA = P_CLICLA;
        CALL GPSQLWEB.PROCCLCRECTA7(P_CLIEMP, P_CLIDEL, P_CLICLA);
        SET P_MSGCODE = 0;
    END IF;

    --Si es Nuevo y CLITC1 = 50:
    --Hay que ejecutar el programa CTLFO2PMP
    IF P_CLITC1 = 50 THEN
        CALL GPSQLWEB.PROCCLCTLFO2PM(V_AREA, P_CLICLA, P_CLITC2);
        SET P_MSGCODE = 0;
    END IF;

END
GO


