
--drop PROCEDURE procCreateWebAudit
CREATE PROCEDURE procCreateWebAudit
( 
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    IN P_USERNAME VARCHAR(50),
    IN P_ACTION VARCHAR(255),
    IN P_OBJECTNAME VARCHAR(255),
    IN P_DESCRIPTION  VARCHAR(500)
)
LANGUAGE SQL
BEGIN
  INSERT INTO  WebAudit (IPADDRESS, USERAGENT, WUSERNAME, SUSERNAME, CREATION, ACTION, OBJECTNAME, DESCRIPTION)  
        VALUES (P_IPADDRESS, P_USERAGENT, P_USERNAME, USER, CURRENT_TIMESTAMP, P_ACTION, P_OBJECTNAME,  REPLACE ( P_DESCRIPTION , '''', ' ' ) , 1000   );
END
GO

