
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2atoh
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2atoh
(
    IN P_ROWID BIGINT,
 IN P_ATOEMP varchar(2),
 IN P_ATODEL varchar(2),
 IN P_ATOFEC INTEGER,
 IN P_ATODTO INTEGER,
 IN P_ATONRO BIGINT,
 IN P_ATODIV INTEGER,
 IN P_ATOCTA BIGINT,
 IN P_ATOIMD double,
 IN P_ATOIMP double,
 IN P_ATOCON varchar(3),
 IN P_ATOVAL BIGINT,
 IN P_ATODH varchar(1),
 IN P_ATOFCO BIGINT,
 IN P_ATOMAT varchar(1),
 IN P_ATOBAJ varchar(1),
 IN P_ATOUSU varchar(6),
 IN P_ATOCLI BIGINT,
 IN P_ATOCOY BIGINT,
 IN P_ATOVAY BIGINT,
 IN P_ATORE1 varchar(3),
 IN P_ATORE2 BIGINT,
 IN P_ATODPR varchar(1),
 IN P_ATOBVI BIGINT,

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2ATOH WHERE RRN(GPDATWEB.AA2ATOH) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2atoh', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2atoh', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2ATOH SET ATOEMP= P_ATOEMP , ATODEL= P_ATODEL , ATOFEC= P_ATOFEC , ATODTO= P_ATODTO , ATONRO= P_ATONRO , ATODIV= P_ATODIV , ATOCTA= P_ATOCTA , ATOIMD= P_ATOIMD , ATOIMP= P_ATOIMP , ATOCON= P_ATOCON , ATOVAL= P_ATOVAL , ATODH= P_ATODH , ATOFCO= P_ATOFCO , ATOMAT= P_ATOMAT , ATOBAJ= P_ATOBAJ , ATOUSU= P_ATOUSU , ATOCLI= P_ATOCLI , ATOCOY= P_ATOCOY , ATOVAY= P_ATOVAY , ATORE1= P_ATORE1 , ATORE2= P_ATORE2 , ATODPR= P_ATODPR , ATOBVI= P_ATOBVI  WHERE RRN(GPDATWEB.AA2ATOH) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AA2ATOH SET ATOEMP= '''||P_ATOEMP || ''' , ATODEL= '''||P_ATODEL || ''' , ATOFEC= '''||P_ATOFEC || ''' , ATODTO= '''||P_ATODTO || ''' , ATONRO= '''||P_ATONRO || ''' , ATODIV= '''||P_ATODIV || ''' , ATOCTA= '''||P_ATOCTA || ''' , ATOIMD= '''||P_ATOIMD || ''' , ATOIMP= '''||P_ATOIMP || ''' , ATOCON= '''||P_ATOCON || ''' , ATOVAL= '''||P_ATOVAL || ''' , ATODH= '''||P_ATODH || ''' , ATOFCO= '''||P_ATOFCO || ''' , ATOMAT= '''||P_ATOMAT || ''' , ATOBAJ= '''||P_ATOBAJ || ''' , ATOUSU= '''||P_ATOUSU || ''' , ATOCLI= '''||P_ATOCLI || ''' , ATOCOY= '''||P_ATOCOY || ''' , ATOVAY= '''||P_ATOVAY || ''' , ATORE1= '''||P_ATORE1 || ''' , ATORE2= '''||P_ATORE2 || ''' , ATODPR= '''||P_ATODPR || ''' , ATOBVI= '''||P_ATOBVI || '''  WHERE RRN(GPDATWEB.AA2ATOH) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2atoh', StringSQL);
END
GO


