
-- DROP PROCEDURE GPSQLWEB.procUpdateTabsdb
    
CREATE PROCEDURE GPSQLWEB.procUpdateTabsdb
(
IN P_TSBMOD VARCHAR(3),
IN P_TSBDIN INTEGER,
IN P_TSBTIN INTEGER,
IN P_TSBCIN INTEGER,
IN P_TSBNSI INTEGER,
IN P_TSBCRE INTEGER,
IN P_TSBIDI INTEGER,

IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.TABSDB WHERE TSBMOD = P_TSBMOD;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabsdb', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabsdb', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.TABSDB SET TSBDIN= P_TSBDIN , TSBTIN= P_TSBTIN , TSBCIN= P_TSBCIN , TSBNSI= P_TSBNSI , TSBCRE= P_TSBCRE , TSBIDI= P_TSBIDI  WHERE TSBMOD= P_TSBMOD ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.TABSDB SET TSBDIN= '''||P_TSBDIN || ''' , TSBTIN= '''||P_TSBTIN || ''' , TSBCIN= '''||P_TSBCIN || ''' , TSBNSI= '''||P_TSBNSI || ''' , TSBCRE= '''||P_TSBCRE || ''' , TSBIDI= '''||P_TSBIDI || '''  WHERE TSBMOD= '''||P_TSBMOD|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabsdb', StringSQL);
END
GO


