
-- DROP PROCEDURE GPSQLWEB.procUpdateApoderad
    
CREATE PROCEDURE GPSQLWEB.procUpdateApoderad
(
    IN P_ROWID BIGINT,
 IN P_NUMAPO INTEGER,
 IN P_NOMAPO varchar(50),
 IN P_ECAPO varchar(10),
 IN P_PROAPO varchar(50),
 IN P_POBAPO varchar(50),
 IN P_CEDAPO varchar(71),
 IN P_FOLAPO varchar(50),
 IN P_TOMAPO varchar(50),
 IN P_ASIAPO varchar(50),
 IN P_REPPOR varchar(30),

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.APODERAD WHERE RRN(GPDATWEB.APODERAD) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateApoderad', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateApoderad', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.APODERAD SET NUMAPO= P_NUMAPO , NOMAPO= P_NOMAPO , ECAPO= P_ECAPO , PROAPO= P_PROAPO , POBAPO= P_POBAPO , CEDAPO= P_CEDAPO , FOLAPO= P_FOLAPO , TOMAPO= P_TOMAPO , ASIAPO= P_ASIAPO , REPPOR= P_REPPOR  WHERE RRN(GPDATWEB.APODERAD) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.APODERAD SET NUMAPO= '''||P_NUMAPO || ''' , NOMAPO= '''||P_NOMAPO || ''' , ECAPO= '''||P_ECAPO || ''' , PROAPO= '''||P_PROAPO || ''' , POBAPO= '''||P_POBAPO || ''' , CEDAPO= '''||P_CEDAPO || ''' , FOLAPO= '''||P_FOLAPO || ''' , TOMAPO= '''||P_TOMAPO || ''' , ASIAPO= '''||P_ASIAPO || ''' , REPPOR= '''||P_REPPOR || '''  WHERE RRN(GPDATWEB.APODERAD) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateApoderad', StringSQL);
END
GO


