
    
--DROP PROCEDURE GPSQLWEB.procCreateApoderad
    
CREATE PROCEDURE GPSQLWEB.procCreateApoderad
(
   IN P_NUMAPO INTEGER,
 IN P_NOMAPO VARCHAR(50),
 IN P_ECAPO VARCHAR(10),
 IN P_PROAPO VARCHAR(50),
 IN P_POBAPO VARCHAR(50),
 IN P_CEDAPO VARCHAR(71),
 IN P_FOLAPO VARCHAR(50),
 IN P_TOMAPO VARCHAR(50),
 IN P_ASIAPO VARCHAR(50),
 IN P_REPPOR VARCHAR(30),

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.APODERAD (NUMAPO ,NOMAPO ,ECAPO ,PROAPO ,POBAPO ,CEDAPO ,FOLAPO ,TOMAPO ,ASIAPO ,REPPOR ) VALUES ( P_NUMAPO , P_NOMAPO , P_ECAPO , P_PROAPO , P_POBAPO , P_CEDAPO , P_FOLAPO , P_TOMAPO , P_ASIAPO , P_REPPOR );

  Set StringSQL = 'INSERT INTO GPDATWEB.APODERAD (NUMAPO ,NOMAPO ,ECAPO ,PROAPO ,POBAPO ,CEDAPO ,FOLAPO ,TOMAPO ,ASIAPO ,REPPOR ) VALUES ( '''|| P_NUMAPO || ''' , '''|| P_NOMAPO || ''' , '''|| P_ECAPO || ''' , '''|| P_PROAPO || ''' , '''|| P_POBAPO || ''' , '''|| P_CEDAPO || ''' , '''|| P_FOLAPO || ''' , '''|| P_TOMAPO || ''' , '''|| P_ASIAPO || ''' , '''|| P_REPPOR || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateApoderad', StringSQL);
  SET P_MSGCODE = 0;
END
GO


