-- DROP PROCEDURE GPSQLWEB.procUpdateCuentas
    
CREATE PROCEDURE GPSQLWEB.procUpdateCuentas
(
IN P_CTCCLI DECIMAL(7 , 0),
IN P_CTCCTA VARCHAR(20),
IN P_CTCEMP VARCHAR(2),
IN P_CTCDEL VARCHAR(2),
IN P_CTCTIP VARCHAR(1),
IN P_CTCAGE DECIMAL(7 , 0),
IN P_CTCSAL NUMERIC(14 , 2),
IN P_CTCDIV DECIMAL(3 , 0),
IN P_CTCAUX VARCHAR(14),
IN P_CTCREF VARCHAR(12),
IN P_CTCBAN VARCHAR(40),
IN P_CTCDES VARCHAR(1),
IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
	Declare StringSQL Varchar(32000) Default '';
	Declare V_CANT INT DEFAULT 0;

	IF P_CTCCLI IS NULL
		OR P_CTCCTA IS NULL
		OR P_CTCEMP IS NULL 
		OR P_CTCDEL IS NULL
		OR P_CTCTIP IS NULL 
		OR P_CTCAGE IS NULL
		OR P_CTCSAL IS NULL 
		OR P_CTCDIV IS NULL
		OR P_CTCAUX IS NULL
		OR P_CTCREF IS NULL 
		OR P_CTCBAN IS NULL
		OR P_CTCDES IS NULL THEN
	SET P_MSGCODE = 9003;
		SET StringSQL = '9003 - PARAMETROS REQUERIDOS ESTAN VACIOS';
		CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateCuentas', StringSQL);
		RETURN;
	END IF;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.CUENTAS WHERE CTCCTA = P_CTCCTA AND CTCCLI = P_CTCCLI;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCuentas', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCuentas', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.CUENTAS SET CTCEMP= P_CTCEMP , CTCDEL= P_CTCDEL , CTCTIP= P_CTCTIP , CTCAGE= P_CTCAGE , CTCSAL= P_CTCSAL , CTCDIV= P_CTCDIV , CTCAUX= P_CTCAUX , CTCREF= P_CTCREF , CTCBAN= P_CTCBAN , CTCDES= P_CTCDES WHERE CTCCTA = P_CTCCTA AND CTCCLI = P_CTCCLI;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.CUENTAS SET CTCEMP= '''||P_CTCEMP || ''' , CTCDEL= '''||P_CTCDEL || ''' , CTCTIP= '''||P_CTCTIP || ''' , CTCAGE= '''||P_CTCAGE || ''' , CTCSAL= '''||P_CTCSAL || ''' , CTCDIV= '''||P_CTCDIV || ''' , CTCAUX= '''||P_CTCAUX || ''' , CTCREF= '''||P_CTCREF || ''' , CTCBAN= '''||P_CTCBAN || ''' , CTCDES= '''||P_CTCDES || '''  WHERE CTCCTA= '''||P_CTCCTA|| ''' AND CTCCLI= '''||P_CTCCLI || '''  ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCuentas', StringSQL);
END
GO


