
-- DROP PROCEDURE GPSQLWEB.procUpdateEmbargos
    
CREATE PROCEDURE GPSQLWEB.procUpdateEmbargos
(
    IN P_ROWID BIGINT,
 IN P_EEMPRE varchar(2),
 IN P_EDELEG varchar(2),
 IN P_EMOVNI varchar(12),
 IN P_EMONTO double,
 IN P_EMONTT double,
 IN P_EFECHA BIGINT,
 IN P_EFECHF BIGINT,
 IN P_EUSUAR varchar(10),
 IN P_EPANTA varchar(10),
 IN P_EFECMO BIGINT,

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.EMBARGOS WHERE RRN(GPDATWEB.EMBARGOS) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateEmbargos', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateEmbargos', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.EMBARGOS SET EEMPRE= P_EEMPRE , EDELEG= P_EDELEG , EMOVNI= P_EMOVNI , EMONTO= P_EMONTO , EMONTT= P_EMONTT , EFECHA= P_EFECHA , EFECHF= P_EFECHF , EUSUAR= P_EUSUAR , EPANTA= P_EPANTA , EFECMO= P_EFECMO  WHERE RRN(GPDATWEB.EMBARGOS) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.EMBARGOS SET EEMPRE= '''||P_EEMPRE || ''' , EDELEG= '''||P_EDELEG || ''' , EMOVNI= '''||P_EMOVNI || ''' , EMONTO= '''||P_EMONTO || ''' , EMONTT= '''||P_EMONTT || ''' , EFECHA= '''||P_EFECHA || ''' , EFECHF= '''||P_EFECHF || ''' , EUSUAR= '''||P_EUSUAR || ''' , EPANTA= '''||P_EPANTA || ''' , EFECMO= '''||P_EFECMO || '''  WHERE RRN(GPDATWEB.EMBARGOS) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateEmbargos', StringSQL);
END
GO


