--DROP PROCEDURE GPSQLWEB.procCreateAa2cab
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2cab
(
    IN P_AREA VARCHAR(4),
    IN P_NAREA VARCHAR(60),
    IN P_USUARIO VARCHAR(10),
    IN P_PANTALLA VARCHAR(10),
    IN P_FECHA BIGINT,
    IN P_LITERAL1 VARCHAR(60),
    IN P_LITERAL2 VARCHAR(60),
    IN P_NCTA VARCHAR(20),
    IN P_NCTAC VARCHAR(20),
    IN P_NCTACU VARCHAR(20),
    IN P_NCTCHE VARCHAR(20),
    IN P_NCTCHA VARCHAR(20),
    IN P_NCTBCV VARCHAR(20),
    IN P_NCTAFL VARCHAR(20),
    IN P_NCTAIS VARCHAR(20),
    IN P_NCTGAO VARCHAR(20),
    IN P_NCTRIV VARCHAR(20),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
  INSERT INTO GPDATWEB.AA2CAB (AREA ,NAREA ,USUARIO ,PANTALLA ,FECHA ,LITERAL1 ,LITERAL2 ,NCTA ,NCTAC ,NCTACU ,NCTCHE ,NCTCHA ,NCTBCV ,NCTAFL ,NCTAIS ,NCTGAO ,NCTRIV ) VALUES ( P_AREA , P_NAREA , P_USUARIO , P_PANTALLA , P_FECHA , P_LITERAL1 , P_LITERAL2 , P_NCTA , P_NCTAC , P_NCTACU , P_NCTCHE , P_NCTCHA , P_NCTBCV , P_NCTAFL , P_NCTAIS , P_NCTGAO , P_NCTRIV );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2CAB (AREA ,NAREA ,USUARIO ,PANTALLA ,FECHA ,LITERAL1 ,LITERAL2 ,NCTA ,NCTAC ,NCTACU ,NCTCHE ,NCTCHA ,NCTBCV ,NCTAFL ,NCTAIS ,NCTGAO ,NCTRIV ) VALUES ( '''|| P_AREA || ''' , '''|| P_NAREA || ''' , '''|| P_USUARIO || ''' , '''|| P_PANTALLA || ''' , '''|| P_FECHA || ''' , '''|| P_LITERAL1 || ''' , '''|| P_LITERAL2 || ''' , '''|| P_NCTA || ''' , '''|| P_NCTAC || ''' , '''|| P_NCTACU || ''' , '''|| P_NCTCHE || ''' , '''|| P_NCTCHA || ''' , '''|| P_NCTBCV || ''' , '''|| P_NCTAFL || ''' , '''|| P_NCTAIS || ''' , '''|| P_NCTGAO || ''' , '''|| P_NCTRIV || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2cab', StringSQL);
  SET P_MSGCODE = 0;
END
GO

