
    
--DROP PROCEDURE GPSQLWEB.procCreateAuxcont
    
CREATE PROCEDURE GPSQLWEB.procCreateAuxcont
(
   IN P_AXCARE VARCHAR(4),
 IN P_AXCNCT BIGINT,
 IN P_AXCCAP INTEGER,
 IN P_AXCCPP INTEGER,
 IN P_AXCAMP INTEGER,
 IN P_AXCEDM INTEGER,
 IN P_AXCEMH INTEGER,
 IN P_AXCEMM INTEGER,
 IN P_AXCPRT DOUBLE,

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.AUXCONT (AXCARE ,AXCNCT ,AXCCAP ,AXCCPP ,AXCAMP ,AXCEDM ,AXCEMH ,AXCEMM ,AXCPRT ) VALUES ( P_AXCARE , P_AXCNCT , P_AXCCAP , P_AXCCPP , P_AXCAMP , P_AXCEDM , P_AXCEMH , P_AXCEMM , P_AXCPRT );

  Set StringSQL = 'INSERT INTO GPDATWEB.AUXCONT (AXCARE ,AXCNCT ,AXCCAP ,AXCCPP ,AXCAMP ,AXCEDM ,AXCEMH ,AXCEMM ,AXCPRT ) VALUES ( '''|| P_AXCARE || ''' , '''|| P_AXCNCT || ''' , '''|| P_AXCCAP || ''' , '''|| P_AXCCPP || ''' , '''|| P_AXCAMP || ''' , '''|| P_AXCEDM || ''' , '''|| P_AXCEMH || ''' , '''|| P_AXCEMM || ''' , '''|| P_AXCPRT || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAuxcont', StringSQL);
  SET P_MSGCODE = 0;
END
GO


