
-- DROP PROCEDURE GPSQLWEB.procUpdateAuxcont
    
CREATE PROCEDURE GPSQLWEB.procUpdateAuxcont
(
    IN P_ROWID BIGINT,
 IN P_AXCARE varchar(4),
 IN P_AXCNCT BIGINT,
 IN P_AXCCAP INTEGER,
 IN P_AXCCPP INTEGER,
 IN P_AXCAMP INTEGER,
 IN P_AXCEDM INTEGER,
 IN P_AXCEMH INTEGER,
 IN P_AXCEMM INTEGER,
 IN P_AXCPRT double,

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AUXCONT WHERE RRN(GPDATWEB.AUXCONT) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAuxcont', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAuxcont', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AUXCONT SET AXCARE= P_AXCARE , AXCNCT= P_AXCNCT , AXCCAP= P_AXCCAP , AXCCPP= P_AXCCPP , AXCAMP= P_AXCAMP , AXCEDM= P_AXCEDM , AXCEMH= P_AXCEMH , AXCEMM= P_AXCEMM , AXCPRT= P_AXCPRT  WHERE RRN(GPDATWEB.AUXCONT) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AUXCONT SET AXCARE= '''||P_AXCARE || ''' , AXCNCT= '''||P_AXCNCT || ''' , AXCCAP= '''||P_AXCCAP || ''' , AXCCPP= '''||P_AXCCPP || ''' , AXCAMP= '''||P_AXCAMP || ''' , AXCEDM= '''||P_AXCEDM || ''' , AXCEMH= '''||P_AXCEMH || ''' , AXCEMM= '''||P_AXCEMM || ''' , AXCPRT= '''||P_AXCPRT || '''  WHERE RRN(GPDATWEB.AUXCONT) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAuxcont', StringSQL);
END
GO


