
--DROP PROCEDURE GPSQLWEB.procDeleteAa2tprcl

CREATE PROCEDURE GPSQLWEB.procDeleteAa2tprcl (
    IN P_ROWID BIGINT,
    IN P_PCLEMP VARCHAR(2),
    IN P_PCLDEL VARCHAR(2),
    IN P_PCLCLA NUMERIC(15 , 0),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
Declare StringSQL Varchar(32000) Not Null Default '';
Declare V_CANT INT DEFAULT 0;
DECLARE V_CTAEMP VARCHAR(2);
DECLARE V_CTADEL VARCHAR(2);
DECLARE V_CTAGEN VARCHAR(12);
DECLARE END_TABLE INT DEFAULT 0 ;
DECLARE V_TABCLA VARCHAR ( 4 ) DEFAULT '' ;
DECLARE C CURSOR FOR SELECT upper( TABEMP CONCAT TABDEL) FROM GPDATWEB . AA2MTAB WHERE TABORI = P_PCLEMP CONCAT P_PCLDEL and upper( TABEMP CONCAT TABDEL) <> P_PCLEMP CONCAT P_PCLDEL;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET END_TABLE = 1 ;
  
SET P_MSGCODE = 9999;

  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TPRCL WHERE RRN(GPDATWEB.AA2TPRCL) = P_ROWID;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Eliminar', 'procDeleteAa2tprcl', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Eliminar', 'procDeleteAa2tprcl', StringSQL);
        RETURN;
  END IF;
  
  DELETE FROM GPDATWEB.AA2TPRCL WHERE RRN(GPDATWEB.AA2TPRCL) = P_ROWID;
  
  Set StringSQL = 'DELETE FROM GPDATWEB.AA2TPRCL WHERE RRN(GPDATWEB.AA2TPRCL) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Eliminar', 'procDeleteAa2tprcl', StringSQL);
  
  OPEN C ;
    FETCH FROM C INTO V_TABCLA ;

    WHILE END_TABLE = 0 DO
        IF ( V_TABCLA != ( P_PCLEMP CONCAT P_PCLDEL ) ) THEN
            DELETE FROM GPDATWEB.AA2TPRCL
                WHERE PCLEMP=SUBSTR (V_TABCLA , 1 , 2 )  AND PCLDEL= SUBSTR ( V_TABCLA , 3 , 2 ) AND PCLCLA= P_PCLCLA ;
        END IF;
    FETCH FROM C INTO V_TABCLA ;
    END WHILE ;

  CLOSE C ;
  SET P_MSGCODE = 0;

END
GO
