
    
--DROP PROCEDURE GPSQLWEB.procCreateAa2tprcl
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2tprcl
(
   IN P_PCLEMP VARCHAR(2),
    IN P_PCLDEL VARCHAR(2),
    IN P_PCLCLA NUMERIC(15 , 0),
    IN P_PCLNOM VARCHAR(40),
    IN P_PCLCTA VARCHAR(12),

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_PROD INT DEFAULT 0;
  Declare V_TIPCL INT DEFAULT 0;
  Declare V_CANT INT DEFAULT 0;
  Declare V_CTA INT DEFAULT 0;

DECLARE V_CTAEMP VARCHAR(2);
DECLARE V_CTADEL VARCHAR(2);
DECLARE V_CTAGEN VARCHAR(12);
DECLARE END_TABLE INT DEFAULT 0 ;
DECLARE V_TABCLA VARCHAR ( 4 ) DEFAULT '' ;
DECLARE C CURSOR FOR SELECT upper( TABEMP CONCAT TABDEL) FROM GPDATWEB . AA2MTAB WHERE TABORI = P_PCLEMP CONCAT P_PCLDEL and upper( TABEMP CONCAT TABDEL) <> P_PCLEMP CONCAT P_PCLDEL;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET END_TABLE = 1 ;

  SET P_MSGCODE = 9999;  
   
  select count(1) into V_PROD from GPDATWEB.AA2TTPRO where CAST ( substring(PROCLA,12,3 ) AS INTEGER) = CAST ( substring(P_PCLCLA,10,3 ) AS INTEGER) and PROEMP = P_PCLEMP AND  PRODEL = P_PCLDEL;
  IF V_PROD = 0 THEN
	SET P_MSGCODE = 1006;
        SET StringSQL = '1006 - CODIGO DE ENLACE CONTABLE NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2tprcl', StringSQL);
        RETURN;
  END IF;

  select count(1) into V_TIPCL from GPDATWEB.AA2TIPCL where TICCLA = CAST ( substring(P_PCLCLA,13,2 ) AS INTEGER);
  IF V_TIPCL = 0 THEN
	SET P_MSGCODE = 1007;
        SET StringSQL = '1007 - TIPO DE ENTIDAD / CLIENTE NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2tprcl', StringSQL);
        RETURN;
  END IF;

  SELECT COUNT(1) INTO V_CTA FROM GPDATWEB.AA2CTA where CTAGEN = P_PCLCTA and  CTAEMP=P_PCLEMP  and  CTADEL=P_PCLDEL;
  IF V_CTA = 0 THEN
	SET P_MSGCODE = 1008;
        SET StringSQL = '1008 - LA CUENTA NO EXISTE EN EL PLAN CONTABLE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2tprcl', StringSQL);
        RETURN;
  END IF;

  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TPRCL WHERE PCLCLA =  P_PCLCLA  and PCLEMP = P_PCLEMP AND  PCLDEL = P_PCLDEL;
  IF V_CANT > 0 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2tprcl', StringSQL);
        RETURN;
  END IF;
  
  INSERT INTO GPDATWEB.AA2TPRCL (PCLEMP ,PCLDEL ,PCLCLA ,PCLNOM ,PCLCTA ) VALUES ( P_PCLEMP , P_PCLDEL , P_PCLCLA , P_PCLNOM , P_PCLCTA );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2TPRCL (PCLEMP ,PCLDEL ,PCLCLA ,PCLNOM ,PCLCTA ) VALUES ( '''|| P_PCLEMP || ''' , '''|| P_PCLDEL || ''' , '''|| P_PCLCLA || ''' , '''|| P_PCLNOM || ''' , '''|| P_PCLCTA || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2tprcl', StringSQL);
  

  OPEN C ;
    FETCH FROM C INTO V_TABCLA ;

    WHILE END_TABLE = 0 DO
        IF ( V_TABCLA != ( P_PCLEMP CONCAT P_PCLDEL ) ) THEN
            INSERT INTO GPDATWEB.AA2TPRCL (PCLEMP ,PCLDEL ,PCLCLA ,PCLNOM ,PCLCTA ) 
                VALUES ( SUBSTR (V_TABCLA , 1 , 2 ) , SUBSTR ( V_TABCLA , 3 , 2 ) , P_PCLCLA , P_PCLNOM , P_PCLCTA );
        END IF;
    FETCH FROM C INTO V_TABCLA ;
    END WHILE ;

  CLOSE C ;
 
  SET P_MSGCODE = 0;
END
GO


