
-- DROP PROCEDURE GPSQLWEB.procUpdateContratoau
    
CREATE PROCEDURE GPSQLWEB.procUpdateContratoau
(
    IN P_ROWID BIGINT,
    IN P_CONEMA varchar(2),
    IN P_CONDEA varchar(2),
    IN P_COSAMI DECIMAL(9 , 6),
    IN P_MOSAMI NUMERIC(15 , 2),
    IN P_SALMIN NUMERIC(15 , 2),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.CONTRATOAU WHERE RRN(GPDATWEB.CONTRATOAU) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateContratoau', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateContratoau', StringSQL);
        RETURN;
  END IF;

  SELECT COUNT(1) INTO V_CANT FROM gpdatweb.aa2tfide WHERE TRIM(FIDCLA) =  P_CONEMA || P_CONDEA;
  IF V_CANT = 0 THEN
        SET P_MSGCODE = 1002;
        SET StringSQL = '1002 - AREA NO EXISTE';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateCgmaxmin', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.CONTRATOAU SET CONEMA= P_CONEMA , CONDEA= P_CONDEA , COSAMI= P_COSAMI , MOSAMI= P_MOSAMI , SALMIN= P_SALMIN  WHERE RRN(GPDATWEB.CONTRATOAU) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.CONTRATOAU SET CONEMA= '''||P_CONEMA || ''' , CONDEA= '''||P_CONDEA || ''' , COSAMI= '''||P_COSAMI || ''' , MOSAMI= '''||P_MOSAMI || ''' , SALMIN= '''||P_SALMIN || '''  WHERE RRN(GPDATWEB.CONTRATOAU) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateContratoau', StringSQL);
END
GO


