
-- DROP PROCEDURE GPSQLWEB.procUpdateFlucon
    
CREATE PROCEDURE GPSQLWEB.procUpdateFlucon
(
IN P_FLCEMP VARCHAR(2),
IN P_FLCDEL VARCHAR(2),
IN P_FLCCLI INTEGER,
IN P_FLCTIP VARCHAR(1),
IN P_FLCCOD INTEGER,
IN P_FLCCON VARCHAR(30),
IN P_FLCHOR INTEGER,
IN P_FLCPAN VARCHAR(10),
IN P_FLCUSU VARCHAR(10),
IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.FLUCON WHERE FLCCOD = P_FLCCOD;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateFlucon', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateFlucon', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.FLUCON SET FLCEMP= P_FLCEMP , FLCDEL= P_FLCDEL , FLCCLI= P_FLCCLI , FLCTIP= P_FLCTIP , FLCCON= P_FLCCON , FLCHOR= P_FLCHOR , FLCPAN= P_FLCPAN , FLCUSU= P_FLCUSU  WHERE FLCCOD= P_FLCCOD ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.FLUCON SET FLCEMP= '''||P_FLCEMP || ''' , FLCDEL= '''||P_FLCDEL || ''' , FLCCLI= '''||P_FLCCLI || ''' , FLCTIP= '''||P_FLCTIP || ''' , FLCCON= '''||P_FLCCON || ''' , FLCHOR= '''||P_FLCHOR || ''' , FLCPAN= '''||P_FLCPAN || ''' , FLCUSU= '''||P_FLCUSU || '''  WHERE FLCCOD= '''||P_FLCCOD|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateFlucon', StringSQL);
END
GO


