
    
--DROP PROCEDURE GPSQLWEB.procCreateAa2tesp
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2tesp
(
   IN P_ESPEMP VARCHAR(2),
 IN P_ESPDEL VARCHAR(2),
 IN P_ESPCLA BIGINT,
 IN P_ESPTIP DOUBLE,

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  SET P_MSGCODE = 9999;
  
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TESP WHERE ESPCLA =  P_ESPCLA AND ESPEMP= P_ESPEMP AND ESPDEL=P_ESPDEL ;

  IF V_CANT > 0 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2tesp', StringSQL);
        RETURN;
  END IF;

 INSERT INTO GPDATWEB.AA2TESP (ESPEMP ,ESPDEL ,ESPCLA ,ESPTIP ) VALUES ( P_ESPEMP , P_ESPDEL , P_ESPCLA , P_ESPTIP );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2TESP (ESPEMP ,ESPDEL ,ESPCLA ,ESPTIP ) VALUES ( '''|| P_ESPEMP || ''' , '''|| P_ESPDEL || ''' , '''|| P_ESPCLA || ''' , '''|| P_ESPTIP || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2tesp', StringSQL);
  SET P_MSGCODE = 0;
END
GO


