
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2clipo
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2clipo
(
    IN P_ROWID BIGINT,
 IN P_CLPCLA BIGINT,
 IN P_CLPNOM varchar(20),
 IN P_CLPAPE varchar(15),
 IN P_CLPAP2 varchar(15),
 IN P_CLPDI1 varchar(30),
 IN P_CLPDI2 varchar(30),
 IN P_CLPPOS varchar(9),
 IN P_CLPPRO varchar(25),
 IN P_CLPPAI INTEGER,
 IN P_CLPPOB varchar(27),
 IN P_CLPANA BIGINT,
 IN P_CLPTID varchar(1),
 IN P_CLPNIF varchar(12),
 IN P_CLPTEL BIGINT,
 IN P_CLPUSU varchar(10),

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2CLIPO WHERE RRN(GPDATWEB.AA2CLIPO) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2clipo', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2clipo', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2CLIPO SET CLPCLA= P_CLPCLA , CLPNOM= P_CLPNOM , CLPAPE= P_CLPAPE , CLPAP2= P_CLPAP2 , CLPDI1= P_CLPDI1 , CLPDI2= P_CLPDI2 , CLPPOS= P_CLPPOS , CLPPRO= P_CLPPRO , CLPPAI= P_CLPPAI , CLPPOB= P_CLPPOB , CLPANA= P_CLPANA , CLPTID= P_CLPTID , CLPNIF= P_CLPNIF , CLPTEL= P_CLPTEL , CLPUSU= P_CLPUSU  WHERE RRN(GPDATWEB.AA2CLIPO) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AA2CLIPO SET CLPCLA= '''||P_CLPCLA || ''' , CLPNOM= '''||P_CLPNOM || ''' , CLPAPE= '''||P_CLPAPE || ''' , CLPAP2= '''||P_CLPAP2 || ''' , CLPDI1= '''||P_CLPDI1 || ''' , CLPDI2= '''||P_CLPDI2 || ''' , CLPPOS= '''||P_CLPPOS || ''' , CLPPRO= '''||P_CLPPRO || ''' , CLPPAI= '''||P_CLPPAI || ''' , CLPPOB= '''||P_CLPPOB || ''' , CLPANA= '''||P_CLPANA || ''' , CLPTID= '''||P_CLPTID || ''' , CLPNIF= '''||P_CLPNIF || ''' , CLPTEL= '''||P_CLPTEL || ''' , CLPUSU= '''||P_CLPUSU || '''  WHERE RRN(GPDATWEB.AA2CLIPO) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2clipo', StringSQL);
END
GO


