
    
--DROP PROCEDURE GPSQLWEB.procCreateAa2clipo
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2clipo
(
   IN P_CLPCLA BIGINT,
 IN P_CLPNOM VARCHAR(20),
 IN P_CLPAPE VARCHAR(15),
 IN P_CLPAP2 VARCHAR(15),
 IN P_CLPDI1 VARCHAR(30),
 IN P_CLPDI2 VARCHAR(30),
 IN P_CLPPOS VARCHAR(9),
 IN P_CLPPRO VARCHAR(25),
 IN P_CLPPAI INTEGER,
 IN P_CLPPOB VARCHAR(27),
 IN P_CLPANA BIGINT,
 IN P_CLPTID VARCHAR(1),
 IN P_CLPNIF VARCHAR(12),
 IN P_CLPTEL BIGINT,
 IN P_CLPUSU VARCHAR(10),

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.AA2CLIPO (CLPCLA ,CLPNOM ,CLPAPE ,CLPAP2 ,CLPDI1 ,CLPDI2 ,CLPPOS ,CLPPRO ,CLPPAI ,CLPPOB ,CLPANA ,CLPTID ,CLPNIF ,CLPTEL ,CLPUSU ) VALUES ( P_CLPCLA , P_CLPNOM , P_CLPAPE , P_CLPAP2 , P_CLPDI1 , P_CLPDI2 , P_CLPPOS , P_CLPPRO , P_CLPPAI , P_CLPPOB , P_CLPANA , P_CLPTID , P_CLPNIF , P_CLPTEL , P_CLPUSU );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2CLIPO (CLPCLA ,CLPNOM ,CLPAPE ,CLPAP2 ,CLPDI1 ,CLPDI2 ,CLPPOS ,CLPPRO ,CLPPAI ,CLPPOB ,CLPANA ,CLPTID ,CLPNIF ,CLPTEL ,CLPUSU ) VALUES ( '''|| P_CLPCLA || ''' , '''|| P_CLPNOM || ''' , '''|| P_CLPAPE || ''' , '''|| P_CLPAP2 || ''' , '''|| P_CLPDI1 || ''' , '''|| P_CLPDI2 || ''' , '''|| P_CLPPOS || ''' , '''|| P_CLPPRO || ''' , '''|| P_CLPPAI || ''' , '''|| P_CLPPOB || ''' , '''|| P_CLPANA || ''' , '''|| P_CLPTID || ''' , '''|| P_CLPNIF || ''' , '''|| P_CLPTEL || ''' , '''|| P_CLPUSU || ''' )'; 
  --CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2clipo', StringSQL);
  SET P_MSGCODE = 0;
END
GO


