package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from ANTCONFM physical file
 * definition.
 * 
* File level identifier is 1140322131014. Record format level identifier is
 * 38A37DB561F7F.
 */
public class ANTCONFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "FIDNOM",
        "CLINIF",
        "PORAPL",
        "NOMBRE",
        "CUENTAC",
        "AUXMNT",
        "WOCON",
        "FECAP",
        "DATPRMX",
        "DISMNT",
        "PORPAN",
        "MONCOM",
        "MONCARE",
        "MOVPGO",
        "TEXTO",
        "AUXMNT1",
        "DISMNT1",
        "MONCOM1",
        "IDBCOM",
        "CHE",
        "IDBCHE",
        "MONCAR1E",
        "CLAVEWW"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "FIDNOM",
        "CLINIF",
        "PORAPL",
        "NOMBRE",
        "CUENTAC",
        "AUXMNT",
        "WOCON",
        "FECAP",
        "DATPRMX",
        "DISMNT",
        "PORPAN",
        "MONCOM",
        "MONCARE",
        "MOVPGO",
        "TEXTO",
        "AUXMNT1",
        "DISMNT1",
        "MONCOM1",
        "IDBCOM",
        "CHE",
        "IDBCHE",
        "MONCAR1E",
        "CLAVEWW"
    };
    final static String fid = "1140322131014";
    final static String rid = "38A37DB561F7F";
    final static String fmtname = "ANTCONFM";
    final int FIELDCOUNT = 35;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldPOSCUR = null;
    private CharacterField fieldFIDNOM = null;
    private CharacterField fieldCLINIF = null;
    private DecimalField fieldPORAPL = null;
    private CharacterField fieldNOMBRE = null;
    private CharacterField fieldCUENTAC = null;
    private DecimalField fieldAUXMNT = null;
    private DecimalField fieldWOCON = null;
    private DecimalField fieldFECAP = null;
    private DecimalField fieldDATPRMX = null;
    private DecimalField fieldDISMNT = null;
    private DecimalField fieldPORPAN = null;
    private DecimalField fieldMONCOM = null;
    private DecimalField fieldMONCARE = null;
    private DecimalField fieldMOVPGO = null;
    private CharacterField fieldTEXTO = null;
    private DecimalField fieldAUXMNT1 = null;
    private DecimalField fieldDISMNT1 = null;
    private DecimalField fieldMONCOM1 = null;
    private DecimalField fieldIDBCOM = null;
    private DecimalField fieldCHE = null;
    private DecimalField fieldIDBCHE = null;
    private DecimalField fieldMONCAR1E = null;
    private CharacterField fieldCLAVEWW = null;

    /**
     * Constructor for ANTCONFMMessage.
     */
    public ANTCONFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 568;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 171, 10, "CAMCUR");
        fields[11] = fieldPOSCUR
                = new DecimalField(message, HEADERSIZE + 181, 5, 0, "POSCUR");
        fields[12] = fieldFIDNOM
                = new CharacterField(message, HEADERSIZE + 186, 40, "FIDNOM");
        fields[13] = fieldCLINIF
                = new CharacterField(message, HEADERSIZE + 226, 12, "CLINIF");
        fields[14] = fieldPORAPL
                = new DecimalField(message, HEADERSIZE + 238, 7, 2, "PORAPL");
        fields[15] = fieldNOMBRE
                = new CharacterField(message, HEADERSIZE + 245, 50, "NOMBRE");
        fields[16] = fieldCUENTAC
                = new CharacterField(message, HEADERSIZE + 295, 20, "CUENTAC");
        fields[17] = fieldAUXMNT
                = new DecimalField(message, HEADERSIZE + 315, 17, 2, "AUXMNT");
        fields[18] = fieldWOCON
                = new DecimalField(message, HEADERSIZE + 332, 3, 0, "WOCON");
        fields[19] = fieldFECAP
                = new DecimalField(message, HEADERSIZE + 335, 7, 0, "FECAP");
        fields[20] = fieldDATPRMX
                = new DecimalField(message, HEADERSIZE + 342, 7, 2, "DATPRMX");
        fields[21] = fieldDISMNT
                = new DecimalField(message, HEADERSIZE + 349, 17, 2, "DISMNT");
        fields[22] = fieldPORPAN
                = new DecimalField(message, HEADERSIZE + 366, 11, 6, "PORPAN");
        fields[23] = fieldMONCOM
                = new DecimalField(message, HEADERSIZE + 377, 17, 2, "MONCOM");
        fields[24] = fieldMONCARE
                = new DecimalField(message, HEADERSIZE + 394, 17, 2, "MONCARE");
        fields[25] = fieldMOVPGO
                = new DecimalField(message, HEADERSIZE + 411, 3, 0, "MOVPGO");
        fields[26] = fieldTEXTO
                = new CharacterField(message, HEADERSIZE + 414, 30, "TEXTO");
        fields[27] = fieldAUXMNT1
                = new DecimalField(message, HEADERSIZE + 444, 17, 2, "AUXMNT1");
        fields[28] = fieldDISMNT1
                = new DecimalField(message, HEADERSIZE + 461, 17, 2, "DISMNT1");
        fields[29] = fieldMONCOM1
                = new DecimalField(message, HEADERSIZE + 478, 17, 2, "MONCOM1");
        fields[30] = fieldIDBCOM
                = new DecimalField(message, HEADERSIZE + 495, 17, 2, "IDBCOM");
        fields[31] = fieldCHE
                = new DecimalField(message, HEADERSIZE + 512, 17, 2, "CHE");
        fields[32] = fieldIDBCHE
                = new DecimalField(message, HEADERSIZE + 529, 17, 2, "IDBCHE");
        fields[33] = fieldMONCAR1E
                = new DecimalField(message, HEADERSIZE + 546, 17, 2, "MONCAR1E");
        fields[34] = fieldCLAVEWW
                = new CharacterField(message, HEADERSIZE + 563, 5, "CLAVEWW");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field POSCUR using a String value.
     */
    public void setPOSCUR(String newvalue) {
        fieldPOSCUR.setString(newvalue);
    }

    /**
     * Get value of field POSCUR as a String.
     */
    public String getPOSCUR() {
        return fieldPOSCUR.getString();
    }

    /**
     * Set numeric field POSCUR using a BigDecimal value.
     */
    public void setPOSCUR(BigDecimal newvalue) {
        fieldPOSCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field POSCUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalPOSCUR() {
        return fieldPOSCUR.getBigDecimal();
    }

    /**
     * Set field FIDNOM using a String value.
     */
    public void setFIDNOM(String newvalue) {
        fieldFIDNOM.setString(newvalue);
    }

    /**
     * Get value of field FIDNOM as a String.
     */
    public String getFIDNOM() {
        return fieldFIDNOM.getString();
    }

    /**
     * Set field CLINIF using a String value.
     */
    public void setCLINIF(String newvalue) {
        fieldCLINIF.setString(newvalue);
    }

    /**
     * Get value of field CLINIF as a String.
     */
    public String getCLINIF() {
        return fieldCLINIF.getString();
    }

    /**
     * Set field PORAPL using a String value.
     */
    public void setPORAPL(String newvalue) {
        fieldPORAPL.setString(newvalue);
    }

    /**
     * Get value of field PORAPL as a String.
     */
    public String getPORAPL() {
        return fieldPORAPL.getString();
    }

    /**
     * Set numeric field PORAPL using a BigDecimal value.
     */
    public void setPORAPL(BigDecimal newvalue) {
        fieldPORAPL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field PORAPL as a BigDecimal.
     */
    public BigDecimal getBigDecimalPORAPL() {
        return fieldPORAPL.getBigDecimal();
    }

    /**
     * Set field NOMBRE using a String value.
     */
    public void setNOMBRE(String newvalue) {
        fieldNOMBRE.setString(newvalue);
    }

    /**
     * Get value of field NOMBRE as a String.
     */
    public String getNOMBRE() {
        return fieldNOMBRE.getString();
    }

    /**
     * Set field CUENTAC using a String value.
     */
    public void setCUENTAC(String newvalue) {
        fieldCUENTAC.setString(newvalue);
    }

    /**
     * Get value of field CUENTAC as a String.
     */
    public String getCUENTAC() {
        return fieldCUENTAC.getString();
    }

    /**
     * Set field AUXMNT using a String value.
     */
    public void setAUXMNT(String newvalue) {
        fieldAUXMNT.setString(newvalue);
    }

    /**
     * Get value of field AUXMNT as a String.
     */
    public String getAUXMNT() {
        return fieldAUXMNT.getString();
    }

    /**
     * Set numeric field AUXMNT using a BigDecimal value.
     */
    public void setAUXMNT(BigDecimal newvalue) {
        fieldAUXMNT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field AUXMNT as a BigDecimal.
     */
    public BigDecimal getBigDecimalAUXMNT() {
        return fieldAUXMNT.getBigDecimal();
    }

    /**
     * Set field WOCON using a String value.
     */
    public void setWOCON(String newvalue) {
        fieldWOCON.setString(newvalue);
    }

    /**
     * Get value of field WOCON as a String.
     */
    public String getWOCON() {
        return fieldWOCON.getString();
    }

    /**
     * Set numeric field WOCON using a BigDecimal value.
     */
    public void setWOCON(BigDecimal newvalue) {
        fieldWOCON.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field WOCON as a BigDecimal.
     */
    public BigDecimal getBigDecimalWOCON() {
        return fieldWOCON.getBigDecimal();
    }

    /**
     * Set field FECAP using a String value.
     */
    public void setFECAP(String newvalue) {
        fieldFECAP.setString(newvalue);
    }

    /**
     * Get value of field FECAP as a String.
     */
    public String getFECAP() {
        return fieldFECAP.getString();
    }

    /**
     * Set numeric field FECAP using a BigDecimal value.
     */
    public void setFECAP(BigDecimal newvalue) {
        fieldFECAP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECAP as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECAP() {
        return fieldFECAP.getBigDecimal();
    }

    /**
     * Set field DATPRMX using a String value.
     */
    public void setDATPRMX(String newvalue) {
        fieldDATPRMX.setString(newvalue);
    }

    /**
     * Get value of field DATPRMX as a String.
     */
    public String getDATPRMX() {
        return fieldDATPRMX.getString();
    }

    /**
     * Set numeric field DATPRMX using a BigDecimal value.
     */
    public void setDATPRMX(BigDecimal newvalue) {
        fieldDATPRMX.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATPRMX as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATPRMX() {
        return fieldDATPRMX.getBigDecimal();
    }

    /**
     * Set field DISMNT using a String value.
     */
    public void setDISMNT(String newvalue) {
        fieldDISMNT.setString(newvalue);
    }

    /**
     * Get value of field DISMNT as a String.
     */
    public String getDISMNT() {
        return fieldDISMNT.getString();
    }

    /**
     * Set numeric field DISMNT using a BigDecimal value.
     */
    public void setDISMNT(BigDecimal newvalue) {
        fieldDISMNT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DISMNT as a BigDecimal.
     */
    public BigDecimal getBigDecimalDISMNT() {
        return fieldDISMNT.getBigDecimal();
    }

    /**
     * Set field PORPAN using a String value.
     */
    public void setPORPAN(String newvalue) {
        fieldPORPAN.setString(newvalue);
    }

    /**
     * Get value of field PORPAN as a String.
     */
    public String getPORPAN() {
        return fieldPORPAN.getString();
    }

    /**
     * Set numeric field PORPAN using a BigDecimal value.
     */
    public void setPORPAN(BigDecimal newvalue) {
        fieldPORPAN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field PORPAN as a BigDecimal.
     */
    public BigDecimal getBigDecimalPORPAN() {
        return fieldPORPAN.getBigDecimal();
    }

    /**
     * Set field MONCOM using a String value.
     */
    public void setMONCOM(String newvalue) {
        fieldMONCOM.setString(newvalue);
    }

    /**
     * Get value of field MONCOM as a String.
     */
    public String getMONCOM() {
        return fieldMONCOM.getString();
    }

    /**
     * Set numeric field MONCOM using a BigDecimal value.
     */
    public void setMONCOM(BigDecimal newvalue) {
        fieldMONCOM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MONCOM as a BigDecimal.
     */
    public BigDecimal getBigDecimalMONCOM() {
        return fieldMONCOM.getBigDecimal();
    }

    /**
     * Set field MONCARE using a String value.
     */
    public void setMONCARE(String newvalue) {
        fieldMONCARE.setString(newvalue);
    }

    /**
     * Get value of field MONCARE as a String.
     */
    public String getMONCARE() {
        return fieldMONCARE.getString();
    }

    /**
     * Set numeric field MONCARE using a BigDecimal value.
     */
    public void setMONCARE(BigDecimal newvalue) {
        fieldMONCARE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MONCARE as a BigDecimal.
     */
    public BigDecimal getBigDecimalMONCARE() {
        return fieldMONCARE.getBigDecimal();
    }

    /**
     * Set field MOVPGO using a String value.
     */
    public void setMOVPGO(String newvalue) {
        fieldMOVPGO.setString(newvalue);
    }

    /**
     * Get value of field MOVPGO as a String.
     */
    public String getMOVPGO() {
        return fieldMOVPGO.getString();
    }

    /**
     * Set numeric field MOVPGO using a BigDecimal value.
     */
    public void setMOVPGO(BigDecimal newvalue) {
        fieldMOVPGO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MOVPGO as a BigDecimal.
     */
    public BigDecimal getBigDecimalMOVPGO() {
        return fieldMOVPGO.getBigDecimal();
    }

    /**
     * Set field TEXTO using a String value.
     */
    public void setTEXTO(String newvalue) {
        fieldTEXTO.setString(newvalue);
    }

    /**
     * Get value of field TEXTO as a String.
     */
    public String getTEXTO() {
        return fieldTEXTO.getString();
    }

    /**
     * Set field AUXMNT1 using a String value.
     */
    public void setAUXMNT1(String newvalue) {
        fieldAUXMNT1.setString(newvalue);
    }

    /**
     * Get value of field AUXMNT1 as a String.
     */
    public String getAUXMNT1() {
        return fieldAUXMNT1.getString();
    }

    /**
     * Set numeric field AUXMNT1 using a BigDecimal value.
     */
    public void setAUXMNT1(BigDecimal newvalue) {
        fieldAUXMNT1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field AUXMNT1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalAUXMNT1() {
        return fieldAUXMNT1.getBigDecimal();
    }

    /**
     * Set field DISMNT1 using a String value.
     */
    public void setDISMNT1(String newvalue) {
        fieldDISMNT1.setString(newvalue);
    }

    /**
     * Get value of field DISMNT1 as a String.
     */
    public String getDISMNT1() {
        return fieldDISMNT1.getString();
    }

    /**
     * Set numeric field DISMNT1 using a BigDecimal value.
     */
    public void setDISMNT1(BigDecimal newvalue) {
        fieldDISMNT1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DISMNT1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDISMNT1() {
        return fieldDISMNT1.getBigDecimal();
    }

    /**
     * Set field MONCOM1 using a String value.
     */
    public void setMONCOM1(String newvalue) {
        fieldMONCOM1.setString(newvalue);
    }

    /**
     * Get value of field MONCOM1 as a String.
     */
    public String getMONCOM1() {
        return fieldMONCOM1.getString();
    }

    /**
     * Set numeric field MONCOM1 using a BigDecimal value.
     */
    public void setMONCOM1(BigDecimal newvalue) {
        fieldMONCOM1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MONCOM1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalMONCOM1() {
        return fieldMONCOM1.getBigDecimal();
    }

    /**
     * Set field IDBCOM using a String value.
     */
    public void setIDBCOM(String newvalue) {
        fieldIDBCOM.setString(newvalue);
    }

    /**
     * Get value of field IDBCOM as a String.
     */
    public String getIDBCOM() {
        return fieldIDBCOM.getString();
    }

    /**
     * Set numeric field IDBCOM using a BigDecimal value.
     */
    public void setIDBCOM(BigDecimal newvalue) {
        fieldIDBCOM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IDBCOM as a BigDecimal.
     */
    public BigDecimal getBigDecimalIDBCOM() {
        return fieldIDBCOM.getBigDecimal();
    }

    /**
     * Set field CHE using a String value.
     */
    public void setCHE(String newvalue) {
        fieldCHE.setString(newvalue);
    }

    /**
     * Get value of field CHE as a String.
     */
    public String getCHE() {
        return fieldCHE.getString();
    }

    /**
     * Set numeric field CHE using a BigDecimal value.
     */
    public void setCHE(BigDecimal newvalue) {
        fieldCHE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CHE as a BigDecimal.
     */
    public BigDecimal getBigDecimalCHE() {
        return fieldCHE.getBigDecimal();
    }

    /**
     * Set field IDBCHE using a String value.
     */
    public void setIDBCHE(String newvalue) {
        fieldIDBCHE.setString(newvalue);
    }

    /**
     * Get value of field IDBCHE as a String.
     */
    public String getIDBCHE() {
        return fieldIDBCHE.getString();
    }

    /**
     * Set numeric field IDBCHE using a BigDecimal value.
     */
    public void setIDBCHE(BigDecimal newvalue) {
        fieldIDBCHE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IDBCHE as a BigDecimal.
     */
    public BigDecimal getBigDecimalIDBCHE() {
        return fieldIDBCHE.getBigDecimal();
    }

    /**
     * Set field MONCAR1E using a String value.
     */
    public void setMONCAR1E(String newvalue) {
        fieldMONCAR1E.setString(newvalue);
    }

    /**
     * Get value of field MONCAR1E as a String.
     */
    public String getMONCAR1E() {
        return fieldMONCAR1E.getString();
    }

    /**
     * Set numeric field MONCAR1E using a BigDecimal value.
     */
    public void setMONCAR1E(BigDecimal newvalue) {
        fieldMONCAR1E.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MONCAR1E as a BigDecimal.
     */
    public BigDecimal getBigDecimalMONCAR1E() {
        return fieldMONCAR1E.getBigDecimal();
    }

    /**
     * Set field CLAVEWW using a String value.
     */
    public void setCLAVEWW(String newvalue) {
        fieldCLAVEWW.setString(newvalue);
    }

    /**
     * Get value of field CLAVEWW as a String.
     */
    public String getCLAVEWW() {
        return fieldCLAVEWW.getString();
    }

}
