package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from ANUAPOFM physical file
 * definition.
 * 
* File level identifier is 1140322125140. Record format level identifier is
 * 448E9D5A461C7.
 */
public class ANUAPOFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "CLINIF",
        "FEC1",
        "FEC2",
        "HMOMN1",
        "HMOIN1",
        "HMONE1",
        "NOMBRE",
        "CLVTOD",
        "CLVTOA",
        "CLVTON",
        "CLVTOP",
        "CLVTOG",
        "CLVTOB",
        "FECAP",
        "SEL",
        "FEC11",
        "FEC22",
        "HMOMNT",
        "SIT",
        "HMOSIT",
        "HMOINT",
        "CLVNIF"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "CLINIF",
        "FEC1",
        "FEC2",
        "HMOMN1",
        "HMOIN1",
        "HMONE1",
        "NOMBRE",
        "CLVTOD",
        "CLVTOA",
        "CLVTON",
        "CLVTOP",
        "CLVTOG",
        "CLVTOB",
        "FECAP",
        "SEL",
        "FEC11",
        "FEC22",
        "HMOMNT",
        "SIT",
        "HMOSIT",
        "HMOINT",
        "CLVNIF"
    };
    final static String fid = "1140322125140";
    final static String rid = "448E9D5A461C7";
    final static String fmtname = "ANUAPOFM";
    final int FIELDCOUNT = 34;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldPOSCUR = null;
    private CharacterField fieldCLINIF = null;
    private DecimalField fieldFEC1 = null;
    private DecimalField fieldFEC2 = null;
    private DecimalField fieldHMOMN1 = null;
    private DecimalField fieldHMOIN1 = null;
    private DecimalField fieldHMONE1 = null;
    private CharacterField fieldNOMBRE = null;
    private DecimalField fieldCLVTOD = null;
    private DecimalField fieldCLVTOA = null;
    private DecimalField fieldCLVTON = null;
    private DecimalField fieldCLVTOP = null;
    private DecimalField fieldCLVTOG = null;
    private DecimalField fieldCLVTOB = null;
    private DecimalField fieldFECAP = null;
    private CharacterField fieldSEL = null;
    private DecimalField fieldFEC11 = null;
    private DecimalField fieldFEC22 = null;
    private DecimalField fieldHMOMNT = null;
    private CharacterField fieldSIT = null;
    private CharacterField fieldHMOSIT = null;
    private DecimalField fieldHMOINT = null;
    private CharacterField fieldCLVNIF = null;

    /**
     * Constructor for ANUAPOFMMessage.
     */
    public ANUAPOFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 494;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 171, 10, "CAMCUR");
        fields[11] = fieldPOSCUR
                = new DecimalField(message, HEADERSIZE + 181, 5, 0, "POSCUR");
        fields[12] = fieldCLINIF
                = new CharacterField(message, HEADERSIZE + 186, 12, "CLINIF");
        fields[13] = fieldFEC1
                = new DecimalField(message, HEADERSIZE + 198, 7, 0, "FEC1");
        fields[14] = fieldFEC2
                = new DecimalField(message, HEADERSIZE + 205, 7, 0, "FEC2");
        fields[15] = fieldHMOMN1
                = new DecimalField(message, HEADERSIZE + 212, 17, 2, "HMOMN1");
        fields[16] = fieldHMOIN1
                = new DecimalField(message, HEADERSIZE + 229, 17, 2, "HMOIN1");
        fields[17] = fieldHMONE1
                = new DecimalField(message, HEADERSIZE + 246, 17, 2, "HMONE1");
        fields[18] = fieldNOMBRE
                = new CharacterField(message, HEADERSIZE + 263, 50, "NOMBRE");
        fields[19] = fieldCLVTOD
                = new DecimalField(message, HEADERSIZE + 313, 17, 2, "CLVTOD");
        fields[20] = fieldCLVTOA
                = new DecimalField(message, HEADERSIZE + 330, 17, 2, "CLVTOA");
        fields[21] = fieldCLVTON
                = new DecimalField(message, HEADERSIZE + 347, 17, 2, "CLVTON");
        fields[22] = fieldCLVTOP
                = new DecimalField(message, HEADERSIZE + 364, 17, 2, "CLVTOP");
        fields[23] = fieldCLVTOG
                = new DecimalField(message, HEADERSIZE + 381, 17, 2, "CLVTOG");
        fields[24] = fieldCLVTOB
                = new DecimalField(message, HEADERSIZE + 398, 17, 2, "CLVTOB");
        fields[25] = fieldFECAP
                = new DecimalField(message, HEADERSIZE + 415, 7, 0, "FECAP");
        fields[26] = fieldSEL
                = new CharacterField(message, HEADERSIZE + 422, 1, "SEL");
        fields[27] = fieldFEC11
                = new DecimalField(message, HEADERSIZE + 423, 7, 0, "FEC11");
        fields[28] = fieldFEC22
                = new DecimalField(message, HEADERSIZE + 430, 7, 0, "FEC22");
        fields[29] = fieldHMOMNT
                = new DecimalField(message, HEADERSIZE + 437, 17, 2, "HMOMNT");
        fields[30] = fieldSIT
                = new CharacterField(message, HEADERSIZE + 454, 10, "SIT");
        fields[31] = fieldHMOSIT
                = new CharacterField(message, HEADERSIZE + 464, 1, "HMOSIT");
        fields[32] = fieldHMOINT
                = new DecimalField(message, HEADERSIZE + 465, 17, 2, "HMOINT");
        fields[33] = fieldCLVNIF
                = new CharacterField(message, HEADERSIZE + 482, 12, "CLVNIF");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field POSCUR using a String value.
     */
    public void setPOSCUR(String newvalue) {
        fieldPOSCUR.setString(newvalue);
    }

    /**
     * Get value of field POSCUR as a String.
     */
    public String getPOSCUR() {
        return fieldPOSCUR.getString();
    }

    /**
     * Set numeric field POSCUR using a BigDecimal value.
     */
    public void setPOSCUR(BigDecimal newvalue) {
        fieldPOSCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field POSCUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalPOSCUR() {
        return fieldPOSCUR.getBigDecimal();
    }

    /**
     * Set field CLINIF using a String value.
     */
    public void setCLINIF(String newvalue) {
        fieldCLINIF.setString(newvalue);
    }

    /**
     * Get value of field CLINIF as a String.
     */
    public String getCLINIF() {
        return fieldCLINIF.getString();
    }

    /**
     * Set field FEC1 using a String value.
     */
    public void setFEC1(String newvalue) {
        fieldFEC1.setString(newvalue);
    }

    /**
     * Get value of field FEC1 as a String.
     */
    public String getFEC1() {
        return fieldFEC1.getString();
    }

    /**
     * Set numeric field FEC1 using a BigDecimal value.
     */
    public void setFEC1(BigDecimal newvalue) {
        fieldFEC1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC1() {
        return fieldFEC1.getBigDecimal();
    }

    /**
     * Set field FEC2 using a String value.
     */
    public void setFEC2(String newvalue) {
        fieldFEC2.setString(newvalue);
    }

    /**
     * Get value of field FEC2 as a String.
     */
    public String getFEC2() {
        return fieldFEC2.getString();
    }

    /**
     * Set numeric field FEC2 using a BigDecimal value.
     */
    public void setFEC2(BigDecimal newvalue) {
        fieldFEC2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC2() {
        return fieldFEC2.getBigDecimal();
    }

    /**
     * Set field HMOMN1 using a String value.
     */
    public void setHMOMN1(String newvalue) {
        fieldHMOMN1.setString(newvalue);
    }

    /**
     * Get value of field HMOMN1 as a String.
     */
    public String getHMOMN1() {
        return fieldHMOMN1.getString();
    }

    /**
     * Set numeric field HMOMN1 using a BigDecimal value.
     */
    public void setHMOMN1(BigDecimal newvalue) {
        fieldHMOMN1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HMOMN1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalHMOMN1() {
        return fieldHMOMN1.getBigDecimal();
    }

    /**
     * Set field HMOIN1 using a String value.
     */
    public void setHMOIN1(String newvalue) {
        fieldHMOIN1.setString(newvalue);
    }

    /**
     * Get value of field HMOIN1 as a String.
     */
    public String getHMOIN1() {
        return fieldHMOIN1.getString();
    }

    /**
     * Set numeric field HMOIN1 using a BigDecimal value.
     */
    public void setHMOIN1(BigDecimal newvalue) {
        fieldHMOIN1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HMOIN1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalHMOIN1() {
        return fieldHMOIN1.getBigDecimal();
    }

    /**
     * Set field HMONE1 using a String value.
     */
    public void setHMONE1(String newvalue) {
        fieldHMONE1.setString(newvalue);
    }

    /**
     * Get value of field HMONE1 as a String.
     */
    public String getHMONE1() {
        return fieldHMONE1.getString();
    }

    /**
     * Set numeric field HMONE1 using a BigDecimal value.
     */
    public void setHMONE1(BigDecimal newvalue) {
        fieldHMONE1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HMONE1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalHMONE1() {
        return fieldHMONE1.getBigDecimal();
    }

    /**
     * Set field NOMBRE using a String value.
     */
    public void setNOMBRE(String newvalue) {
        fieldNOMBRE.setString(newvalue);
    }

    /**
     * Get value of field NOMBRE as a String.
     */
    public String getNOMBRE() {
        return fieldNOMBRE.getString();
    }

    /**
     * Set field CLVTOD using a String value.
     */
    public void setCLVTOD(String newvalue) {
        fieldCLVTOD.setString(newvalue);
    }

    /**
     * Get value of field CLVTOD as a String.
     */
    public String getCLVTOD() {
        return fieldCLVTOD.getString();
    }

    /**
     * Set numeric field CLVTOD using a BigDecimal value.
     */
    public void setCLVTOD(BigDecimal newvalue) {
        fieldCLVTOD.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLVTOD as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLVTOD() {
        return fieldCLVTOD.getBigDecimal();
    }

    /**
     * Set field CLVTOA using a String value.
     */
    public void setCLVTOA(String newvalue) {
        fieldCLVTOA.setString(newvalue);
    }

    /**
     * Get value of field CLVTOA as a String.
     */
    public String getCLVTOA() {
        return fieldCLVTOA.getString();
    }

    /**
     * Set numeric field CLVTOA using a BigDecimal value.
     */
    public void setCLVTOA(BigDecimal newvalue) {
        fieldCLVTOA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLVTOA as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLVTOA() {
        return fieldCLVTOA.getBigDecimal();
    }

    /**
     * Set field CLVTON using a String value.
     */
    public void setCLVTON(String newvalue) {
        fieldCLVTON.setString(newvalue);
    }

    /**
     * Get value of field CLVTON as a String.
     */
    public String getCLVTON() {
        return fieldCLVTON.getString();
    }

    /**
     * Set numeric field CLVTON using a BigDecimal value.
     */
    public void setCLVTON(BigDecimal newvalue) {
        fieldCLVTON.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLVTON as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLVTON() {
        return fieldCLVTON.getBigDecimal();
    }

    /**
     * Set field CLVTOP using a String value.
     */
    public void setCLVTOP(String newvalue) {
        fieldCLVTOP.setString(newvalue);
    }

    /**
     * Get value of field CLVTOP as a String.
     */
    public String getCLVTOP() {
        return fieldCLVTOP.getString();
    }

    /**
     * Set numeric field CLVTOP using a BigDecimal value.
     */
    public void setCLVTOP(BigDecimal newvalue) {
        fieldCLVTOP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLVTOP as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLVTOP() {
        return fieldCLVTOP.getBigDecimal();
    }

    /**
     * Set field CLVTOG using a String value.
     */
    public void setCLVTOG(String newvalue) {
        fieldCLVTOG.setString(newvalue);
    }

    /**
     * Get value of field CLVTOG as a String.
     */
    public String getCLVTOG() {
        return fieldCLVTOG.getString();
    }

    /**
     * Set numeric field CLVTOG using a BigDecimal value.
     */
    public void setCLVTOG(BigDecimal newvalue) {
        fieldCLVTOG.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLVTOG as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLVTOG() {
        return fieldCLVTOG.getBigDecimal();
    }

    /**
     * Set field CLVTOB using a String value.
     */
    public void setCLVTOB(String newvalue) {
        fieldCLVTOB.setString(newvalue);
    }

    /**
     * Get value of field CLVTOB as a String.
     */
    public String getCLVTOB() {
        return fieldCLVTOB.getString();
    }

    /**
     * Set numeric field CLVTOB using a BigDecimal value.
     */
    public void setCLVTOB(BigDecimal newvalue) {
        fieldCLVTOB.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLVTOB as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLVTOB() {
        return fieldCLVTOB.getBigDecimal();
    }

    /**
     * Set field FECAP using a String value.
     */
    public void setFECAP(String newvalue) {
        fieldFECAP.setString(newvalue);
    }

    /**
     * Get value of field FECAP as a String.
     */
    public String getFECAP() {
        return fieldFECAP.getString();
    }

    /**
     * Set numeric field FECAP using a BigDecimal value.
     */
    public void setFECAP(BigDecimal newvalue) {
        fieldFECAP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECAP as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECAP() {
        return fieldFECAP.getBigDecimal();
    }

    /**
     * Set field SEL using a String value.
     */
    public void setSEL(String newvalue) {
        fieldSEL.setString(newvalue);
    }

    /**
     * Get value of field SEL as a String.
     */
    public String getSEL() {
        return fieldSEL.getString();
    }

    /**
     * Set field FEC11 using a String value.
     */
    public void setFEC11(String newvalue) {
        fieldFEC11.setString(newvalue);
    }

    /**
     * Get value of field FEC11 as a String.
     */
    public String getFEC11() {
        return fieldFEC11.getString();
    }

    /**
     * Set numeric field FEC11 using a BigDecimal value.
     */
    public void setFEC11(BigDecimal newvalue) {
        fieldFEC11.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC11 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC11() {
        return fieldFEC11.getBigDecimal();
    }

    /**
     * Set field FEC22 using a String value.
     */
    public void setFEC22(String newvalue) {
        fieldFEC22.setString(newvalue);
    }

    /**
     * Get value of field FEC22 as a String.
     */
    public String getFEC22() {
        return fieldFEC22.getString();
    }

    /**
     * Set numeric field FEC22 using a BigDecimal value.
     */
    public void setFEC22(BigDecimal newvalue) {
        fieldFEC22.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC22 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC22() {
        return fieldFEC22.getBigDecimal();
    }

    /**
     * Set field HMOMNT using a String value.
     */
    public void setHMOMNT(String newvalue) {
        fieldHMOMNT.setString(newvalue);
    }

    /**
     * Get value of field HMOMNT as a String.
     */
    public String getHMOMNT() {
        return fieldHMOMNT.getString();
    }

    /**
     * Set numeric field HMOMNT using a BigDecimal value.
     */
    public void setHMOMNT(BigDecimal newvalue) {
        fieldHMOMNT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HMOMNT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHMOMNT() {
        return fieldHMOMNT.getBigDecimal();
    }

    /**
     * Set field SIT using a String value.
     */
    public void setSIT(String newvalue) {
        fieldSIT.setString(newvalue);
    }

    /**
     * Get value of field SIT as a String.
     */
    public String getSIT() {
        return fieldSIT.getString();
    }

    /**
     * Set field HMOSIT using a String value.
     */
    public void setHMOSIT(String newvalue) {
        fieldHMOSIT.setString(newvalue);
    }

    /**
     * Get value of field HMOSIT as a String.
     */
    public String getHMOSIT() {
        return fieldHMOSIT.getString();
    }

    /**
     * Set field HMOINT using a String value.
     */
    public void setHMOINT(String newvalue) {
        fieldHMOINT.setString(newvalue);
    }

    /**
     * Get value of field HMOINT as a String.
     */
    public String getHMOINT() {
        return fieldHMOINT.getString();
    }

    /**
     * Set numeric field HMOINT using a BigDecimal value.
     */
    public void setHMOINT(BigDecimal newvalue) {
        fieldHMOINT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HMOINT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHMOINT() {
        return fieldHMOINT.getBigDecimal();
    }

    /**
     * Set field CLVNIF using a String value.
     */
    public void setCLVNIF(String newvalue) {
        fieldCLVNIF.setString(newvalue);
    }

    /**
     * Get value of field CLVNIF as a String.
     */
    public String getCLVNIF() {
        return fieldCLVNIF.getString();
    }

}
