package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from ANUGR1FM physical file
 * definition.
 * 
* File level identifier is 1140322133738. Record format level identifier is
 * 3995EEEB7279E.
 */
public class ANUGR1FMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "CLINIF",
        "FEC1",
        "FEC2",
        "HMOMN1",
        "NOMBRE",
        "SEL",
        "FEC11",
        "FEC22",
        "HMOMNT",
        "SIT",
        "HMOSIT"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "CLINIF",
        "FEC1",
        "FEC2",
        "HMOMN1",
        "NOMBRE",
        "SEL",
        "FEC11",
        "FEC22",
        "HMOMNT",
        "SIT",
        "HMOSIT"
    };
    final static String fid = "1140322133738";
    final static String rid = "3995EEEB7279E";
    final static String fmtname = "ANUGR1FM";
    final int FIELDCOUNT = 23;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldPOSCUR = null;
    private CharacterField fieldCLINIF = null;
    private DecimalField fieldFEC1 = null;
    private DecimalField fieldFEC2 = null;
    private DecimalField fieldHMOMN1 = null;
    private CharacterField fieldNOMBRE = null;
    private CharacterField fieldSEL = null;
    private DecimalField fieldFEC11 = null;
    private DecimalField fieldFEC22 = null;
    private DecimalField fieldHMOMNT = null;
    private CharacterField fieldSIT = null;
    private CharacterField fieldHMOSIT = null;

    /**
     * Constructor for ANUGR1FMMessage.
     */
    public ANUGR1FMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 322;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 171, 10, "CAMCUR");
        fields[11] = fieldPOSCUR
                = new DecimalField(message, HEADERSIZE + 181, 5, 0, "POSCUR");
        fields[12] = fieldCLINIF
                = new CharacterField(message, HEADERSIZE + 186, 12, "CLINIF");
        fields[13] = fieldFEC1
                = new DecimalField(message, HEADERSIZE + 198, 7, 0, "FEC1");
        fields[14] = fieldFEC2
                = new DecimalField(message, HEADERSIZE + 205, 7, 0, "FEC2");
        fields[15] = fieldHMOMN1
                = new DecimalField(message, HEADERSIZE + 212, 17, 2, "HMOMN1");
        fields[16] = fieldNOMBRE
                = new CharacterField(message, HEADERSIZE + 229, 50, "NOMBRE");
        fields[17] = fieldSEL
                = new CharacterField(message, HEADERSIZE + 279, 1, "SEL");
        fields[18] = fieldFEC11
                = new DecimalField(message, HEADERSIZE + 280, 7, 0, "FEC11");
        fields[19] = fieldFEC22
                = new DecimalField(message, HEADERSIZE + 287, 7, 0, "FEC22");
        fields[20] = fieldHMOMNT
                = new DecimalField(message, HEADERSIZE + 294, 17, 2, "HMOMNT");
        fields[21] = fieldSIT
                = new CharacterField(message, HEADERSIZE + 311, 10, "SIT");
        fields[22] = fieldHMOSIT
                = new CharacterField(message, HEADERSIZE + 321, 1, "HMOSIT");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field POSCUR using a String value.
     */
    public void setPOSCUR(String newvalue) {
        fieldPOSCUR.setString(newvalue);
    }

    /**
     * Get value of field POSCUR as a String.
     */
    public String getPOSCUR() {
        return fieldPOSCUR.getString();
    }

    /**
     * Set numeric field POSCUR using a BigDecimal value.
     */
    public void setPOSCUR(BigDecimal newvalue) {
        fieldPOSCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field POSCUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalPOSCUR() {
        return fieldPOSCUR.getBigDecimal();
    }

    /**
     * Set field CLINIF using a String value.
     */
    public void setCLINIF(String newvalue) {
        fieldCLINIF.setString(newvalue);
    }

    /**
     * Get value of field CLINIF as a String.
     */
    public String getCLINIF() {
        return fieldCLINIF.getString();
    }

    /**
     * Set field FEC1 using a String value.
     */
    public void setFEC1(String newvalue) {
        fieldFEC1.setString(newvalue);
    }

    /**
     * Get value of field FEC1 as a String.
     */
    public String getFEC1() {
        return fieldFEC1.getString();
    }

    /**
     * Set numeric field FEC1 using a BigDecimal value.
     */
    public void setFEC1(BigDecimal newvalue) {
        fieldFEC1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC1() {
        return fieldFEC1.getBigDecimal();
    }

    /**
     * Set field FEC2 using a String value.
     */
    public void setFEC2(String newvalue) {
        fieldFEC2.setString(newvalue);
    }

    /**
     * Get value of field FEC2 as a String.
     */
    public String getFEC2() {
        return fieldFEC2.getString();
    }

    /**
     * Set numeric field FEC2 using a BigDecimal value.
     */
    public void setFEC2(BigDecimal newvalue) {
        fieldFEC2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC2() {
        return fieldFEC2.getBigDecimal();
    }

    /**
     * Set field HMOMN1 using a String value.
     */
    public void setHMOMN1(String newvalue) {
        fieldHMOMN1.setString(newvalue);
    }

    /**
     * Get value of field HMOMN1 as a String.
     */
    public String getHMOMN1() {
        return fieldHMOMN1.getString();
    }

    /**
     * Set numeric field HMOMN1 using a BigDecimal value.
     */
    public void setHMOMN1(BigDecimal newvalue) {
        fieldHMOMN1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HMOMN1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalHMOMN1() {
        return fieldHMOMN1.getBigDecimal();
    }

    /**
     * Set field NOMBRE using a String value.
     */
    public void setNOMBRE(String newvalue) {
        fieldNOMBRE.setString(newvalue);
    }

    /**
     * Get value of field NOMBRE as a String.
     */
    public String getNOMBRE() {
        return fieldNOMBRE.getString();
    }

    /**
     * Set field SEL using a String value.
     */
    public void setSEL(String newvalue) {
        fieldSEL.setString(newvalue);
    }

    /**
     * Get value of field SEL as a String.
     */
    public String getSEL() {
        return fieldSEL.getString();
    }

    /**
     * Set field FEC11 using a String value.
     */
    public void setFEC11(String newvalue) {
        fieldFEC11.setString(newvalue);
    }

    /**
     * Get value of field FEC11 as a String.
     */
    public String getFEC11() {
        return fieldFEC11.getString();
    }

    /**
     * Set numeric field FEC11 using a BigDecimal value.
     */
    public void setFEC11(BigDecimal newvalue) {
        fieldFEC11.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC11 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC11() {
        return fieldFEC11.getBigDecimal();
    }

    /**
     * Set field FEC22 using a String value.
     */
    public void setFEC22(String newvalue) {
        fieldFEC22.setString(newvalue);
    }

    /**
     * Get value of field FEC22 as a String.
     */
    public String getFEC22() {
        return fieldFEC22.getString();
    }

    /**
     * Set numeric field FEC22 using a BigDecimal value.
     */
    public void setFEC22(BigDecimal newvalue) {
        fieldFEC22.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC22 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC22() {
        return fieldFEC22.getBigDecimal();
    }

    /**
     * Set field HMOMNT using a String value.
     */
    public void setHMOMNT(String newvalue) {
        fieldHMOMNT.setString(newvalue);
    }

    /**
     * Get value of field HMOMNT as a String.
     */
    public String getHMOMNT() {
        return fieldHMOMNT.getString();
    }

    /**
     * Set numeric field HMOMNT using a BigDecimal value.
     */
    public void setHMOMNT(BigDecimal newvalue) {
        fieldHMOMNT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HMOMNT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHMOMNT() {
        return fieldHMOMNT.getBigDecimal();
    }

    /**
     * Set field SIT using a String value.
     */
    public void setSIT(String newvalue) {
        fieldSIT.setString(newvalue);
    }

    /**
     * Get value of field SIT as a String.
     */
    public String getSIT() {
        return fieldSIT.getString();
    }

    /**
     * Set field HMOSIT using a String value.
     */
    public void setHMOSIT(String newvalue) {
        fieldHMOSIT.setString(newvalue);
    }

    /**
     * Get value of field HMOSIT as a String.
     */
    public String getHMOSIT() {
        return fieldHMOSIT.getString();
    }

}
