package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from CONARFM physical file
 * definition.
 * 
* File level identifier is 1140223224733. Record format level identifier is
 * 440933F1E2EE7.
 */
public class CONARFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "OPEEMP",
        "OPEDEL",
        "OPENUM",
        "OPC",
        "TXT",
        "OP2FVL1",
        "OPEMNT",
        "FIDNO2",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "TABNOM",
        "TOT1",
        "TOT2",
        "CODFID",
        "FIDNO3",
        "FIDTXT",
        "TOT3",
        "TOT4",
        "OP2FEC",
        "OPECLI",
        "NOMAPP",
        "CIRIF",
        "OPEREC",
        "OPECTA",
        "OPEBAN",
        "TEXT2",
        "OPEOBS",
        "OPEUSU",
        "DIVNOM",
        "NOTIPO",
        "OPECOM",
        "OPEVAL",
        "OPEVLO",
        "OPECMT",
        "OPEFIC",
        "AP",
        "RE",
        "AR",
        "VA",
        "FEC6DE",
        "FEC6HA"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "OPEEMP",
        "OPEDEL",
        "OPENUM",
        "OPC",
        "TXT",
        "OP2FVL1",
        "OPEMNT",
        "FIDNO2",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "TABNOM",
        "TOT1",
        "TOT2",
        "CODFID",
        "FIDNO3",
        "FIDTXT",
        "TOT3",
        "TOT4",
        "OP2FEC",
        "OPECLI",
        "NOMAPP",
        "CIRIF",
        "OPEREC",
        "OPECTA",
        "OPEBAN",
        "TEXT2",
        "OPEOBS",
        "OPEUSU",
        "DIVNOM",
        "NOTIPO",
        "OPECOM",
        "OPEVAL",
        "OPEVLO",
        "OPECMT",
        "OPEFIC",
        "AP",
        "RE",
        "AR",
        "VA",
        "FEC6DE",
        "FEC6HA"
    };
    final static String fid = "1140223224733";
    final static String rid = "440933F1E2EE7";
    final static String fmtname = "CONARFM";
    final int FIELDCOUNT = 51;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldOPEEMP = null;
    private CharacterField fieldOPEDEL = null;
    private DecimalField fieldOPENUM = null;
    private CharacterField fieldOPC = null;
    private CharacterField fieldTXT = null;
    private DecimalField fieldOP2FVL1 = null;
    private DecimalField fieldOPEMNT = null;
    private CharacterField fieldFIDNO2 = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldPOSCUR = null;
    private CharacterField fieldTABNOM = null;
    private DecimalField fieldTOT1 = null;
    private DecimalField fieldTOT2 = null;
    private CharacterField fieldCODFID = null;
    private CharacterField fieldFIDNO3 = null;
    private CharacterField fieldFIDTXT = null;
    private DecimalField fieldTOT3 = null;
    private DecimalField fieldTOT4 = null;
    private DecimalField fieldOP2FEC = null;
    private DecimalField fieldOPECLI = null;
    private CharacterField fieldNOMAPP = null;
    private CharacterField fieldCIRIF = null;
    private DecimalField fieldOPEREC = null;
    private CharacterField fieldOPECTA = null;
    private CharacterField fieldOPEBAN = null;
    private CharacterField fieldTEXT2 = null;
    private CharacterField fieldOPEOBS = null;
    private CharacterField fieldOPEUSU = null;
    private CharacterField fieldDIVNOM = null;
    private CharacterField fieldNOTIPO = null;
    private DecimalField fieldOPECOM = null;
    private CharacterField fieldOPEVAL = null;
    private CharacterField fieldOPEVLO = null;
    private DecimalField fieldOPECMT = null;
    private DecimalField fieldOPEFIC = null;
    private CharacterField fieldAP = null;
    private CharacterField fieldRE = null;
    private CharacterField fieldAR = null;
    private CharacterField fieldVA = null;
    private DecimalField fieldFEC6DE = null;
    private DecimalField fieldFEC6HA = null;

    /**
     * Constructor for CONARFMMessage.
     */
    public CONARFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 927;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldOPEEMP
                = new CharacterField(message, HEADERSIZE + 161, 2, "OPEEMP");
        fields[10] = fieldOPEDEL
                = new CharacterField(message, HEADERSIZE + 163, 2, "OPEDEL");
        fields[11] = fieldOPENUM
                = new DecimalField(message, HEADERSIZE + 165, 9, 0, "OPENUM");
        fields[12] = fieldOPC
                = new CharacterField(message, HEADERSIZE + 174, 1, "OPC");
        fields[13] = fieldTXT
                = new CharacterField(message, HEADERSIZE + 175, 2, "TXT");
        fields[14] = fieldOP2FVL1
                = new DecimalField(message, HEADERSIZE + 177, 7, 0, "OP2FVL1");
        fields[15] = fieldOPEMNT
                = new DecimalField(message, HEADERSIZE + 184, 16, 2, "OPEMNT");
        fields[16] = fieldFIDNO2
                = new CharacterField(message, HEADERSIZE + 200, 40, "FIDNO2");
        fields[17] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 240, 10, "REGCUR");
        fields[18] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 250, 10, "CAMCUR");
        fields[19] = fieldPOSCUR
                = new DecimalField(message, HEADERSIZE + 260, 5, 0, "POSCUR");
        fields[20] = fieldTABNOM
                = new CharacterField(message, HEADERSIZE + 265, 40, "TABNOM");
        fields[21] = fieldTOT1
                = new DecimalField(message, HEADERSIZE + 305, 17, 2, "TOT1");
        fields[22] = fieldTOT2
                = new DecimalField(message, HEADERSIZE + 322, 17, 2, "TOT2");
        fields[23] = fieldCODFID
                = new CharacterField(message, HEADERSIZE + 339, 4, "CODFID");
        fields[24] = fieldFIDNO3
                = new CharacterField(message, HEADERSIZE + 343, 40, "FIDNO3");
        fields[25] = fieldFIDTXT
                = new CharacterField(message, HEADERSIZE + 383, 14, "FIDTXT");
        fields[26] = fieldTOT3
                = new DecimalField(message, HEADERSIZE + 397, 17, 2, "TOT3");
        fields[27] = fieldTOT4
                = new DecimalField(message, HEADERSIZE + 414, 17, 2, "TOT4");
        fields[28] = fieldOP2FEC
                = new DecimalField(message, HEADERSIZE + 431, 7, 0, "OP2FEC");
        fields[29] = fieldOPECLI
                = new DecimalField(message, HEADERSIZE + 438, 8, 0, "OPECLI");
        fields[30] = fieldNOMAPP
                = new CharacterField(message, HEADERSIZE + 446, 50, "NOMAPP");
        fields[31] = fieldCIRIF
                = new CharacterField(message, HEADERSIZE + 496, 12, "CIRIF");
        fields[32] = fieldOPEREC
                = new DecimalField(message, HEADERSIZE + 508, 9, 0, "OPEREC");
        fields[33] = fieldOPECTA
                = new CharacterField(message, HEADERSIZE + 517, 20, "OPECTA");
        fields[34] = fieldOPEBAN
                = new CharacterField(message, HEADERSIZE + 537, 20, "OPEBAN");
        fields[35] = fieldTEXT2
                = new CharacterField(message, HEADERSIZE + 557, 30, "TEXT2");
        fields[36] = fieldOPEOBS
                = new CharacterField(message, HEADERSIZE + 587, 200, "OPEOBS");
        fields[37] = fieldOPEUSU
                = new CharacterField(message, HEADERSIZE + 787, 10, "OPEUSU");
        fields[38] = fieldDIVNOM
                = new CharacterField(message, HEADERSIZE + 797, 40, "DIVNOM");
        fields[39] = fieldNOTIPO
                = new CharacterField(message, HEADERSIZE + 837, 30, "NOTIPO");
        fields[40] = fieldOPECOM
                = new DecimalField(message, HEADERSIZE + 867, 12, 2, "OPECOM");
        fields[41] = fieldOPEVAL
                = new CharacterField(message, HEADERSIZE + 879, 1, "OPEVAL");
        fields[42] = fieldOPEVLO
                = new CharacterField(message, HEADERSIZE + 880, 12, "OPEVLO");
        fields[43] = fieldOPECMT
                = new DecimalField(message, HEADERSIZE + 892, 8, 0, "OPECMT");
        fields[44] = fieldOPEFIC
                = new DecimalField(message, HEADERSIZE + 900, 9, 0, "OPEFIC");
        fields[45] = fieldAP
                = new CharacterField(message, HEADERSIZE + 909, 1, "AP");
        fields[46] = fieldRE
                = new CharacterField(message, HEADERSIZE + 910, 1, "RE");
        fields[47] = fieldAR
                = new CharacterField(message, HEADERSIZE + 911, 1, "AR");
        fields[48] = fieldVA
                = new CharacterField(message, HEADERSIZE + 912, 1, "VA");
        fields[49] = fieldFEC6DE
                = new DecimalField(message, HEADERSIZE + 913, 7, 0, "FEC6DE");
        fields[50] = fieldFEC6HA
                = new DecimalField(message, HEADERSIZE + 920, 7, 0, "FEC6HA");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field OPEEMP using a String value.
     */
    public void setOPEEMP(String newvalue) {
        fieldOPEEMP.setString(newvalue);
    }

    /**
     * Get value of field OPEEMP as a String.
     */
    public String getOPEEMP() {
        return fieldOPEEMP.getString();
    }

    /**
     * Set field OPEDEL using a String value.
     */
    public void setOPEDEL(String newvalue) {
        fieldOPEDEL.setString(newvalue);
    }

    /**
     * Get value of field OPEDEL as a String.
     */
    public String getOPEDEL() {
        return fieldOPEDEL.getString();
    }

    /**
     * Set field OPENUM using a String value.
     */
    public void setOPENUM(String newvalue) {
        fieldOPENUM.setString(newvalue);
    }

    /**
     * Get value of field OPENUM as a String.
     */
    public String getOPENUM() {
        return fieldOPENUM.getString();
    }

    /**
     * Set numeric field OPENUM using a BigDecimal value.
     */
    public void setOPENUM(BigDecimal newvalue) {
        fieldOPENUM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OPENUM as a BigDecimal.
     */
    public BigDecimal getBigDecimalOPENUM() {
        return fieldOPENUM.getBigDecimal();
    }

    /**
     * Set field OPC using a String value.
     */
    public void setOPC(String newvalue) {
        fieldOPC.setString(newvalue);
    }

    /**
     * Get value of field OPC as a String.
     */
    public String getOPC() {
        return fieldOPC.getString();
    }

    /**
     * Set field TXT using a String value.
     */
    public void setTXT(String newvalue) {
        fieldTXT.setString(newvalue);
    }

    /**
     * Get value of field TXT as a String.
     */
    public String getTXT() {
        return fieldTXT.getString();
    }

    /**
     * Set field OP2FVL1 using a String value.
     */
    public void setOP2FVL1(String newvalue) {
        fieldOP2FVL1.setString(newvalue);
    }

    /**
     * Get value of field OP2FVL1 as a String.
     */
    public String getOP2FVL1() {
        return fieldOP2FVL1.getString();
    }

    /**
     * Set numeric field OP2FVL1 using a BigDecimal value.
     */
    public void setOP2FVL1(BigDecimal newvalue) {
        fieldOP2FVL1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OP2FVL1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalOP2FVL1() {
        return fieldOP2FVL1.getBigDecimal();
    }

    /**
     * Set field OPEMNT using a String value.
     */
    public void setOPEMNT(String newvalue) {
        fieldOPEMNT.setString(newvalue);
    }

    /**
     * Get value of field OPEMNT as a String.
     */
    public String getOPEMNT() {
        return fieldOPEMNT.getString();
    }

    /**
     * Set numeric field OPEMNT using a BigDecimal value.
     */
    public void setOPEMNT(BigDecimal newvalue) {
        fieldOPEMNT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OPEMNT as a BigDecimal.
     */
    public BigDecimal getBigDecimalOPEMNT() {
        return fieldOPEMNT.getBigDecimal();
    }

    /**
     * Set field FIDNO2 using a String value.
     */
    public void setFIDNO2(String newvalue) {
        fieldFIDNO2.setString(newvalue);
    }

    /**
     * Get value of field FIDNO2 as a String.
     */
    public String getFIDNO2() {
        return fieldFIDNO2.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field POSCUR using a String value.
     */
    public void setPOSCUR(String newvalue) {
        fieldPOSCUR.setString(newvalue);
    }

    /**
     * Get value of field POSCUR as a String.
     */
    public String getPOSCUR() {
        return fieldPOSCUR.getString();
    }

    /**
     * Set numeric field POSCUR using a BigDecimal value.
     */
    public void setPOSCUR(BigDecimal newvalue) {
        fieldPOSCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field POSCUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalPOSCUR() {
        return fieldPOSCUR.getBigDecimal();
    }

    /**
     * Set field TABNOM using a String value.
     */
    public void setTABNOM(String newvalue) {
        fieldTABNOM.setString(newvalue);
    }

    /**
     * Get value of field TABNOM as a String.
     */
    public String getTABNOM() {
        return fieldTABNOM.getString();
    }

    /**
     * Set field TOT1 using a String value.
     */
    public void setTOT1(String newvalue) {
        fieldTOT1.setString(newvalue);
    }

    /**
     * Get value of field TOT1 as a String.
     */
    public String getTOT1() {
        return fieldTOT1.getString();
    }

    /**
     * Set numeric field TOT1 using a BigDecimal value.
     */
    public void setTOT1(BigDecimal newvalue) {
        fieldTOT1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TOT1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalTOT1() {
        return fieldTOT1.getBigDecimal();
    }

    /**
     * Set field TOT2 using a String value.
     */
    public void setTOT2(String newvalue) {
        fieldTOT2.setString(newvalue);
    }

    /**
     * Get value of field TOT2 as a String.
     */
    public String getTOT2() {
        return fieldTOT2.getString();
    }

    /**
     * Set numeric field TOT2 using a BigDecimal value.
     */
    public void setTOT2(BigDecimal newvalue) {
        fieldTOT2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TOT2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalTOT2() {
        return fieldTOT2.getBigDecimal();
    }

    /**
     * Set field CODFID using a String value.
     */
    public void setCODFID(String newvalue) {
        fieldCODFID.setString(newvalue);
    }

    /**
     * Get value of field CODFID as a String.
     */
    public String getCODFID() {
        return fieldCODFID.getString();
    }

    /**
     * Set field FIDNO3 using a String value.
     */
    public void setFIDNO3(String newvalue) {
        fieldFIDNO3.setString(newvalue);
    }

    /**
     * Get value of field FIDNO3 as a String.
     */
    public String getFIDNO3() {
        return fieldFIDNO3.getString();
    }

    /**
     * Set field FIDTXT using a String value.
     */
    public void setFIDTXT(String newvalue) {
        fieldFIDTXT.setString(newvalue);
    }

    /**
     * Get value of field FIDTXT as a String.
     */
    public String getFIDTXT() {
        return fieldFIDTXT.getString();
    }

    /**
     * Set field TOT3 using a String value.
     */
    public void setTOT3(String newvalue) {
        fieldTOT3.setString(newvalue);
    }

    /**
     * Get value of field TOT3 as a String.
     */
    public String getTOT3() {
        return fieldTOT3.getString();
    }

    /**
     * Set numeric field TOT3 using a BigDecimal value.
     */
    public void setTOT3(BigDecimal newvalue) {
        fieldTOT3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TOT3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalTOT3() {
        return fieldTOT3.getBigDecimal();
    }

    /**
     * Set field TOT4 using a String value.
     */
    public void setTOT4(String newvalue) {
        fieldTOT4.setString(newvalue);
    }

    /**
     * Get value of field TOT4 as a String.
     */
    public String getTOT4() {
        return fieldTOT4.getString();
    }

    /**
     * Set numeric field TOT4 using a BigDecimal value.
     */
    public void setTOT4(BigDecimal newvalue) {
        fieldTOT4.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TOT4 as a BigDecimal.
     */
    public BigDecimal getBigDecimalTOT4() {
        return fieldTOT4.getBigDecimal();
    }

    /**
     * Set field OP2FEC using a String value.
     */
    public void setOP2FEC(String newvalue) {
        fieldOP2FEC.setString(newvalue);
    }

    /**
     * Get value of field OP2FEC as a String.
     */
    public String getOP2FEC() {
        return fieldOP2FEC.getString();
    }

    /**
     * Set numeric field OP2FEC using a BigDecimal value.
     */
    public void setOP2FEC(BigDecimal newvalue) {
        fieldOP2FEC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OP2FEC as a BigDecimal.
     */
    public BigDecimal getBigDecimalOP2FEC() {
        return fieldOP2FEC.getBigDecimal();
    }

    /**
     * Set field OPECLI using a String value.
     */
    public void setOPECLI(String newvalue) {
        fieldOPECLI.setString(newvalue);
    }

    /**
     * Get value of field OPECLI as a String.
     */
    public String getOPECLI() {
        return fieldOPECLI.getString();
    }

    /**
     * Set numeric field OPECLI using a BigDecimal value.
     */
    public void setOPECLI(BigDecimal newvalue) {
        fieldOPECLI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OPECLI as a BigDecimal.
     */
    public BigDecimal getBigDecimalOPECLI() {
        return fieldOPECLI.getBigDecimal();
    }

    /**
     * Set field NOMAPP using a String value.
     */
    public void setNOMAPP(String newvalue) {
        fieldNOMAPP.setString(newvalue);
    }

    /**
     * Get value of field NOMAPP as a String.
     */
    public String getNOMAPP() {
        return fieldNOMAPP.getString();
    }

    /**
     * Set field CIRIF using a String value.
     */
    public void setCIRIF(String newvalue) {
        fieldCIRIF.setString(newvalue);
    }

    /**
     * Get value of field CIRIF as a String.
     */
    public String getCIRIF() {
        return fieldCIRIF.getString();
    }

    /**
     * Set field OPEREC using a String value.
     */
    public void setOPEREC(String newvalue) {
        fieldOPEREC.setString(newvalue);
    }

    /**
     * Get value of field OPEREC as a String.
     */
    public String getOPEREC() {
        return fieldOPEREC.getString();
    }

    /**
     * Set numeric field OPEREC using a BigDecimal value.
     */
    public void setOPEREC(BigDecimal newvalue) {
        fieldOPEREC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OPEREC as a BigDecimal.
     */
    public BigDecimal getBigDecimalOPEREC() {
        return fieldOPEREC.getBigDecimal();
    }

    /**
     * Set field OPECTA using a String value.
     */
    public void setOPECTA(String newvalue) {
        fieldOPECTA.setString(newvalue);
    }

    /**
     * Get value of field OPECTA as a String.
     */
    public String getOPECTA() {
        return fieldOPECTA.getString();
    }

    /**
     * Set field OPEBAN using a String value.
     */
    public void setOPEBAN(String newvalue) {
        fieldOPEBAN.setString(newvalue);
    }

    /**
     * Get value of field OPEBAN as a String.
     */
    public String getOPEBAN() {
        return fieldOPEBAN.getString();
    }

    /**
     * Set field TEXT2 using a String value.
     */
    public void setTEXT2(String newvalue) {
        fieldTEXT2.setString(newvalue);
    }

    /**
     * Get value of field TEXT2 as a String.
     */
    public String getTEXT2() {
        return fieldTEXT2.getString();
    }

    /**
     * Set field OPEOBS using a String value.
     */
    public void setOPEOBS(String newvalue) {
        fieldOPEOBS.setString(newvalue);
    }

    /**
     * Get value of field OPEOBS as a String.
     */
    public String getOPEOBS() {
        return fieldOPEOBS.getString();
    }

    /**
     * Set field OPEUSU using a String value.
     */
    public void setOPEUSU(String newvalue) {
        fieldOPEUSU.setString(newvalue);
    }

    /**
     * Get value of field OPEUSU as a String.
     */
    public String getOPEUSU() {
        return fieldOPEUSU.getString();
    }

    /**
     * Set field DIVNOM using a String value.
     */
    public void setDIVNOM(String newvalue) {
        fieldDIVNOM.setString(newvalue);
    }

    /**
     * Get value of field DIVNOM as a String.
     */
    public String getDIVNOM() {
        return fieldDIVNOM.getString();
    }

    /**
     * Set field NOTIPO using a String value.
     */
    public void setNOTIPO(String newvalue) {
        fieldNOTIPO.setString(newvalue);
    }

    /**
     * Get value of field NOTIPO as a String.
     */
    public String getNOTIPO() {
        return fieldNOTIPO.getString();
    }

    /**
     * Set field OPECOM using a String value.
     */
    public void setOPECOM(String newvalue) {
        fieldOPECOM.setString(newvalue);
    }

    /**
     * Get value of field OPECOM as a String.
     */
    public String getOPECOM() {
        return fieldOPECOM.getString();
    }

    /**
     * Set numeric field OPECOM using a BigDecimal value.
     */
    public void setOPECOM(BigDecimal newvalue) {
        fieldOPECOM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OPECOM as a BigDecimal.
     */
    public BigDecimal getBigDecimalOPECOM() {
        return fieldOPECOM.getBigDecimal();
    }

    /**
     * Set field OPEVAL using a String value.
     */
    public void setOPEVAL(String newvalue) {
        fieldOPEVAL.setString(newvalue);
    }

    /**
     * Get value of field OPEVAL as a String.
     */
    public String getOPEVAL() {
        return fieldOPEVAL.getString();
    }

    /**
     * Set field OPEVLO using a String value.
     */
    public void setOPEVLO(String newvalue) {
        fieldOPEVLO.setString(newvalue);
    }

    /**
     * Get value of field OPEVLO as a String.
     */
    public String getOPEVLO() {
        return fieldOPEVLO.getString();
    }

    /**
     * Set field OPECMT using a String value.
     */
    public void setOPECMT(String newvalue) {
        fieldOPECMT.setString(newvalue);
    }

    /**
     * Get value of field OPECMT as a String.
     */
    public String getOPECMT() {
        return fieldOPECMT.getString();
    }

    /**
     * Set numeric field OPECMT using a BigDecimal value.
     */
    public void setOPECMT(BigDecimal newvalue) {
        fieldOPECMT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OPECMT as a BigDecimal.
     */
    public BigDecimal getBigDecimalOPECMT() {
        return fieldOPECMT.getBigDecimal();
    }

    /**
     * Set field OPEFIC using a String value.
     */
    public void setOPEFIC(String newvalue) {
        fieldOPEFIC.setString(newvalue);
    }

    /**
     * Get value of field OPEFIC as a String.
     */
    public String getOPEFIC() {
        return fieldOPEFIC.getString();
    }

    /**
     * Set numeric field OPEFIC using a BigDecimal value.
     */
    public void setOPEFIC(BigDecimal newvalue) {
        fieldOPEFIC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OPEFIC as a BigDecimal.
     */
    public BigDecimal getBigDecimalOPEFIC() {
        return fieldOPEFIC.getBigDecimal();
    }

    /**
     * Set field AP using a String value.
     */
    public void setAP(String newvalue) {
        fieldAP.setString(newvalue);
    }

    /**
     * Get value of field AP as a String.
     */
    public String getAP() {
        return fieldAP.getString();
    }

    /**
     * Set field RE using a String value.
     */
    public void setRE(String newvalue) {
        fieldRE.setString(newvalue);
    }

    /**
     * Get value of field RE as a String.
     */
    public String getRE() {
        return fieldRE.getString();
    }

    /**
     * Set field AR using a String value.
     */
    public void setAR(String newvalue) {
        fieldAR.setString(newvalue);
    }

    /**
     * Get value of field AR as a String.
     */
    public String getAR() {
        return fieldAR.getString();
    }

    /**
     * Set field VA using a String value.
     */
    public void setVA(String newvalue) {
        fieldVA.setString(newvalue);
    }

    /**
     * Get value of field VA as a String.
     */
    public String getVA() {
        return fieldVA.getString();
    }

    /**
     * Set field FEC6DE using a String value.
     */
    public void setFEC6DE(String newvalue) {
        fieldFEC6DE.setString(newvalue);
    }

    /**
     * Get value of field FEC6DE as a String.
     */
    public String getFEC6DE() {
        return fieldFEC6DE.getString();
    }

    /**
     * Set numeric field FEC6DE using a BigDecimal value.
     */
    public void setFEC6DE(BigDecimal newvalue) {
        fieldFEC6DE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC6DE as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC6DE() {
        return fieldFEC6DE.getBigDecimal();
    }

    /**
     * Set field FEC6HA using a String value.
     */
    public void setFEC6HA(String newvalue) {
        fieldFEC6HA.setString(newvalue);
    }

    /**
     * Get value of field FEC6HA as a String.
     */
    public String getFEC6HA() {
        return fieldFEC6HA.getString();
    }

    /**
     * Set numeric field FEC6HA using a BigDecimal value.
     */
    public void setFEC6HA(BigDecimal newvalue) {
        fieldFEC6HA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FEC6HA as a BigDecimal.
     */
    public BigDecimal getBigDecimalFEC6HA() {
        return fieldFEC6HA.getBigDecimal();
    }

}
