package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from CONINVFM physical file
 * definition.
 * 
* File level identifier is 1140216204848. Record format level identifier is
 * 4CBD63B96D2A1.
 */
public class CONINVFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "FIDES",
        "FIDNOM",
        "FECCON",
        "FECPRO",
        "VLOCOA",
        "VLONOM",
        "INVVNO",
        "INTANT",
        "TAVI",
        "FECEMI",
        "INTDEX",
        "FECADQ",
        "FECVTO",
        "INTCOB",
        "FECCUP",
        "PRECOM",
        "INTPEN",
        "VALADQ",
        "BASC",
        "BASD",
        "INVNOP",
        "SFNRO",
        "SFECV",
        "SFBVI",
        "SFRE1",
        "SFRE2",
        "OPCION",
        "INVVAL",
        "OPERA",
        "CLIENTE",
        "FCOBCUP",
        "NRR",
        "TINTANT",
        "TINTDEX",
        "TINTCOB",
        "TINTPEN",
        "CFEC",
        "CUPMNT",
        "FCOB",
        "CUPVEN",
        "CUPMCB",
        "CUPCBT"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "FIDES",
        "FIDNOM",
        "FECCON",
        "FECPRO",
        "VLOCOA",
        "VLONOM",
        "INVVNO",
        "INTANT",
        "TAVI",
        "FECEMI",
        "INTDEX",
        "FECADQ",
        "FECVTO",
        "INTCOB",
        "FECCUP",
        "PRECOM",
        "INTPEN",
        "VALADQ",
        "BASC",
        "BASD",
        "INVNOP",
        "SFNRO",
        "SFECV",
        "SFBVI",
        "SFRE1",
        "SFRE2",
        "OPCION",
        "INVVAL",
        "OPERA",
        "CLIENTE",
        "FCOBCUP",
        "NRR",
        "TINTANT",
        "TINTDEX",
        "TINTCOB",
        "TINTPEN",
        "CFEC",
        "CUPMNT",
        "FCOB",
        "CUPVEN",
        "CUPMCB",
        "CUPCBT"
    };
    final static String fid = "1140216204848";
    final static String rid = "4CBD63B96D2A1";
    final static String fmtname = "CONINVFM";
    final int FIELDCOUNT = 51;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldFIDES = null;
    private CharacterField fieldFIDNOM = null;
    private DecimalField fieldFECCON = null;
    private DecimalField fieldFECPRO = null;
    private CharacterField fieldVLOCOA = null;
    private CharacterField fieldVLONOM = null;
    private DecimalField fieldINVVNO = null;
    private DecimalField fieldINTANT = null;
    private DecimalField fieldTAVI = null;
    private DecimalField fieldFECEMI = null;
    private DecimalField fieldINTDEX = null;
    private DecimalField fieldFECADQ = null;
    private DecimalField fieldFECVTO = null;
    private DecimalField fieldINTCOB = null;
    private DecimalField fieldFECCUP = null;
    private DecimalField fieldPRECOM = null;
    private DecimalField fieldINTPEN = null;
    private DecimalField fieldVALADQ = null;
    private DecimalField fieldBASC = null;
    private DecimalField fieldBASD = null;
    private DecimalField fieldINVNOP = null;
    private DecimalField fieldSFNRO = null;
    private DecimalField fieldSFECV = null;
    private DecimalField fieldSFBVI = null;
    private CharacterField fieldSFRE1 = null;
    private DecimalField fieldSFRE2 = null;
    private CharacterField fieldOPCION = null;
    private CharacterField fieldINVVAL = null;
    private DecimalField fieldOPERA = null;
    private DecimalField fieldCLIENTE = null;
    private DecimalField fieldFCOBCUP = null;
    private DecimalField fieldNRR = null;
    private DecimalField fieldTINTANT = null;
    private DecimalField fieldTINTDEX = null;
    private DecimalField fieldTINTCOB = null;
    private DecimalField fieldTINTPEN = null;
    private DecimalField fieldCFEC = null;
    private DecimalField fieldCUPMNT = null;
    private DecimalField fieldFCOB = null;
    private CharacterField fieldCUPVEN = null;
    private CharacterField fieldCUPMCB = null;
    private CharacterField fieldCUPCBT = null;

    /**
     * Constructor for CONINVFMMessage.
     */
    public CONINVFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 591;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldFIDES
                = new CharacterField(message, HEADERSIZE + 161, 4, "FIDES");
        fields[10] = fieldFIDNOM
                = new CharacterField(message, HEADERSIZE + 165, 40, "FIDNOM");
        fields[11] = fieldFECCON
                = new DecimalField(message, HEADERSIZE + 205, 7, 0, "FECCON");
        fields[12] = fieldFECPRO
                = new DecimalField(message, HEADERSIZE + 212, 9, 0, "FECPRO");
        fields[13] = fieldVLOCOA
                = new CharacterField(message, HEADERSIZE + 221, 12, "VLOCOA");
        fields[14] = fieldVLONOM
                = new CharacterField(message, HEADERSIZE + 233, 40, "VLONOM");
        fields[15] = fieldINVVNO
                = new DecimalField(message, HEADERSIZE + 273, 17, 2, "INVVNO");
        fields[16] = fieldINTANT
                = new DecimalField(message, HEADERSIZE + 290, 13, 2, "INTANT");
        fields[17] = fieldTAVI
                = new DecimalField(message, HEADERSIZE + 303, 8, 3, "TAVI");
        fields[18] = fieldFECEMI
                = new DecimalField(message, HEADERSIZE + 311, 9, 0, "FECEMI");
        fields[19] = fieldINTDEX
                = new DecimalField(message, HEADERSIZE + 320, 13, 2, "INTDEX");
        fields[20] = fieldFECADQ
                = new DecimalField(message, HEADERSIZE + 333, 9, 0, "FECADQ");
        fields[21] = fieldFECVTO
                = new DecimalField(message, HEADERSIZE + 342, 9, 0, "FECVTO");
        fields[22] = fieldINTCOB
                = new DecimalField(message, HEADERSIZE + 351, 13, 2, "INTCOB");
        fields[23] = fieldFECCUP
                = new DecimalField(message, HEADERSIZE + 364, 9, 0, "FECCUP");
        fields[24] = fieldPRECOM
                = new DecimalField(message, HEADERSIZE + 373, 8, 3, "PRECOM");
        fields[25] = fieldINTPEN
                = new DecimalField(message, HEADERSIZE + 381, 13, 2, "INTPEN");
        fields[26] = fieldVALADQ
                = new DecimalField(message, HEADERSIZE + 394, 15, 2, "VALADQ");
        fields[27] = fieldBASC
                = new DecimalField(message, HEADERSIZE + 409, 2, 0, "BASC");
        fields[28] = fieldBASD
                = new DecimalField(message, HEADERSIZE + 411, 2, 0, "BASD");
        fields[29] = fieldINVNOP
                = new DecimalField(message, HEADERSIZE + 413, 11, 0, "INVNOP");
        fields[30] = fieldSFNRO
                = new DecimalField(message, HEADERSIZE + 424, 8, 0, "SFNRO");
        fields[31] = fieldSFECV
                = new DecimalField(message, HEADERSIZE + 432, 7, 0, "SFECV");
        fields[32] = fieldSFBVI
                = new DecimalField(message, HEADERSIZE + 439, 6, 0, "SFBVI");
        fields[33] = fieldSFRE1
                = new CharacterField(message, HEADERSIZE + 445, 3, "SFRE1");
        fields[34] = fieldSFRE2
                = new DecimalField(message, HEADERSIZE + 448, 8, 0, "SFRE2");
        fields[35] = fieldOPCION
                = new CharacterField(message, HEADERSIZE + 456, 1, "OPCION");
        fields[36] = fieldINVVAL
                = new CharacterField(message, HEADERSIZE + 457, 12, "INVVAL");
        fields[37] = fieldOPERA
                = new DecimalField(message, HEADERSIZE + 469, 11, 0, "OPERA");
        fields[38] = fieldCLIENTE
                = new DecimalField(message, HEADERSIZE + 480, 8, 0, "CLIENTE");
        fields[39] = fieldFCOBCUP
                = new DecimalField(message, HEADERSIZE + 488, 7, 0, "FCOBCUP");
        fields[40] = fieldNRR
                = new DecimalField(message, HEADERSIZE + 495, 5, 0, "NRR");
        fields[41] = fieldTINTANT
                = new DecimalField(message, HEADERSIZE + 500, 15, 2, "TINTANT");
        fields[42] = fieldTINTDEX
                = new DecimalField(message, HEADERSIZE + 515, 15, 2, "TINTDEX");
        fields[43] = fieldTINTCOB
                = new DecimalField(message, HEADERSIZE + 530, 15, 2, "TINTCOB");
        fields[44] = fieldTINTPEN
                = new DecimalField(message, HEADERSIZE + 545, 15, 2, "TINTPEN");
        fields[45] = fieldCFEC
                = new DecimalField(message, HEADERSIZE + 560, 9, 0, "CFEC");
        fields[46] = fieldCUPMNT
                = new DecimalField(message, HEADERSIZE + 569, 10, 5, "CUPMNT");
        fields[47] = fieldFCOB
                = new DecimalField(message, HEADERSIZE + 579, 9, 0, "FCOB");
        fields[48] = fieldCUPVEN
                = new CharacterField(message, HEADERSIZE + 588, 1, "CUPVEN");
        fields[49] = fieldCUPMCB
                = new CharacterField(message, HEADERSIZE + 589, 1, "CUPMCB");
        fields[50] = fieldCUPCBT
                = new CharacterField(message, HEADERSIZE + 590, 1, "CUPCBT");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field FIDES using a String value.
     */
    public void setFIDES(String newvalue) {
        fieldFIDES.setString(newvalue);
    }

    /**
     * Get value of field FIDES as a String.
     */
    public String getFIDES() {
        return fieldFIDES.getString();
    }

    /**
     * Set field FIDNOM using a String value.
     */
    public void setFIDNOM(String newvalue) {
        fieldFIDNOM.setString(newvalue);
    }

    /**
     * Get value of field FIDNOM as a String.
     */
    public String getFIDNOM() {
        return fieldFIDNOM.getString();
    }

    /**
     * Set field FECCON using a String value.
     */
    public void setFECCON(String newvalue) {
        fieldFECCON.setString(newvalue);
    }

    /**
     * Get value of field FECCON as a String.
     */
    public String getFECCON() {
        return fieldFECCON.getString();
    }

    /**
     * Set numeric field FECCON using a BigDecimal value.
     */
    public void setFECCON(BigDecimal newvalue) {
        fieldFECCON.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECCON as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECCON() {
        return fieldFECCON.getBigDecimal();
    }

    /**
     * Set field FECPRO using a String value.
     */
    public void setFECPRO(String newvalue) {
        fieldFECPRO.setString(newvalue);
    }

    /**
     * Get value of field FECPRO as a String.
     */
    public String getFECPRO() {
        return fieldFECPRO.getString();
    }

    /**
     * Set numeric field FECPRO using a BigDecimal value.
     */
    public void setFECPRO(BigDecimal newvalue) {
        fieldFECPRO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECPRO as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECPRO() {
        return fieldFECPRO.getBigDecimal();
    }

    /**
     * Set field VLOCOA using a String value.
     */
    public void setVLOCOA(String newvalue) {
        fieldVLOCOA.setString(newvalue);
    }

    /**
     * Get value of field VLOCOA as a String.
     */
    public String getVLOCOA() {
        return fieldVLOCOA.getString();
    }

    /**
     * Set field VLONOM using a String value.
     */
    public void setVLONOM(String newvalue) {
        fieldVLONOM.setString(newvalue);
    }

    /**
     * Get value of field VLONOM as a String.
     */
    public String getVLONOM() {
        return fieldVLONOM.getString();
    }

    /**
     * Set field INVVNO using a String value.
     */
    public void setINVVNO(String newvalue) {
        fieldINVVNO.setString(newvalue);
    }

    /**
     * Get value of field INVVNO as a String.
     */
    public String getINVVNO() {
        return fieldINVVNO.getString();
    }

    /**
     * Set numeric field INVVNO using a BigDecimal value.
     */
    public void setINVVNO(BigDecimal newvalue) {
        fieldINVVNO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVVNO as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVVNO() {
        return fieldINVVNO.getBigDecimal();
    }

    /**
     * Set field INTANT using a String value.
     */
    public void setINTANT(String newvalue) {
        fieldINTANT.setString(newvalue);
    }

    /**
     * Get value of field INTANT as a String.
     */
    public String getINTANT() {
        return fieldINTANT.getString();
    }

    /**
     * Set numeric field INTANT using a BigDecimal value.
     */
    public void setINTANT(BigDecimal newvalue) {
        fieldINTANT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INTANT as a BigDecimal.
     */
    public BigDecimal getBigDecimalINTANT() {
        return fieldINTANT.getBigDecimal();
    }

    /**
     * Set field TAVI using a String value.
     */
    public void setTAVI(String newvalue) {
        fieldTAVI.setString(newvalue);
    }

    /**
     * Get value of field TAVI as a String.
     */
    public String getTAVI() {
        return fieldTAVI.getString();
    }

    /**
     * Set numeric field TAVI using a BigDecimal value.
     */
    public void setTAVI(BigDecimal newvalue) {
        fieldTAVI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TAVI as a BigDecimal.
     */
    public BigDecimal getBigDecimalTAVI() {
        return fieldTAVI.getBigDecimal();
    }

    /**
     * Set field FECEMI using a String value.
     */
    public void setFECEMI(String newvalue) {
        fieldFECEMI.setString(newvalue);
    }

    /**
     * Get value of field FECEMI as a String.
     */
    public String getFECEMI() {
        return fieldFECEMI.getString();
    }

    /**
     * Set numeric field FECEMI using a BigDecimal value.
     */
    public void setFECEMI(BigDecimal newvalue) {
        fieldFECEMI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECEMI as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECEMI() {
        return fieldFECEMI.getBigDecimal();
    }

    /**
     * Set field INTDEX using a String value.
     */
    public void setINTDEX(String newvalue) {
        fieldINTDEX.setString(newvalue);
    }

    /**
     * Get value of field INTDEX as a String.
     */
    public String getINTDEX() {
        return fieldINTDEX.getString();
    }

    /**
     * Set numeric field INTDEX using a BigDecimal value.
     */
    public void setINTDEX(BigDecimal newvalue) {
        fieldINTDEX.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INTDEX as a BigDecimal.
     */
    public BigDecimal getBigDecimalINTDEX() {
        return fieldINTDEX.getBigDecimal();
    }

    /**
     * Set field FECADQ using a String value.
     */
    public void setFECADQ(String newvalue) {
        fieldFECADQ.setString(newvalue);
    }

    /**
     * Get value of field FECADQ as a String.
     */
    public String getFECADQ() {
        return fieldFECADQ.getString();
    }

    /**
     * Set numeric field FECADQ using a BigDecimal value.
     */
    public void setFECADQ(BigDecimal newvalue) {
        fieldFECADQ.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECADQ as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECADQ() {
        return fieldFECADQ.getBigDecimal();
    }

    /**
     * Set field FECVTO using a String value.
     */
    public void setFECVTO(String newvalue) {
        fieldFECVTO.setString(newvalue);
    }

    /**
     * Get value of field FECVTO as a String.
     */
    public String getFECVTO() {
        return fieldFECVTO.getString();
    }

    /**
     * Set numeric field FECVTO using a BigDecimal value.
     */
    public void setFECVTO(BigDecimal newvalue) {
        fieldFECVTO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECVTO as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECVTO() {
        return fieldFECVTO.getBigDecimal();
    }

    /**
     * Set field INTCOB using a String value.
     */
    public void setINTCOB(String newvalue) {
        fieldINTCOB.setString(newvalue);
    }

    /**
     * Get value of field INTCOB as a String.
     */
    public String getINTCOB() {
        return fieldINTCOB.getString();
    }

    /**
     * Set numeric field INTCOB using a BigDecimal value.
     */
    public void setINTCOB(BigDecimal newvalue) {
        fieldINTCOB.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INTCOB as a BigDecimal.
     */
    public BigDecimal getBigDecimalINTCOB() {
        return fieldINTCOB.getBigDecimal();
    }

    /**
     * Set field FECCUP using a String value.
     */
    public void setFECCUP(String newvalue) {
        fieldFECCUP.setString(newvalue);
    }

    /**
     * Get value of field FECCUP as a String.
     */
    public String getFECCUP() {
        return fieldFECCUP.getString();
    }

    /**
     * Set numeric field FECCUP using a BigDecimal value.
     */
    public void setFECCUP(BigDecimal newvalue) {
        fieldFECCUP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECCUP as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECCUP() {
        return fieldFECCUP.getBigDecimal();
    }

    /**
     * Set field PRECOM using a String value.
     */
    public void setPRECOM(String newvalue) {
        fieldPRECOM.setString(newvalue);
    }

    /**
     * Get value of field PRECOM as a String.
     */
    public String getPRECOM() {
        return fieldPRECOM.getString();
    }

    /**
     * Set numeric field PRECOM using a BigDecimal value.
     */
    public void setPRECOM(BigDecimal newvalue) {
        fieldPRECOM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field PRECOM as a BigDecimal.
     */
    public BigDecimal getBigDecimalPRECOM() {
        return fieldPRECOM.getBigDecimal();
    }

    /**
     * Set field INTPEN using a String value.
     */
    public void setINTPEN(String newvalue) {
        fieldINTPEN.setString(newvalue);
    }

    /**
     * Get value of field INTPEN as a String.
     */
    public String getINTPEN() {
        return fieldINTPEN.getString();
    }

    /**
     * Set numeric field INTPEN using a BigDecimal value.
     */
    public void setINTPEN(BigDecimal newvalue) {
        fieldINTPEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INTPEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalINTPEN() {
        return fieldINTPEN.getBigDecimal();
    }

    /**
     * Set field VALADQ using a String value.
     */
    public void setVALADQ(String newvalue) {
        fieldVALADQ.setString(newvalue);
    }

    /**
     * Get value of field VALADQ as a String.
     */
    public String getVALADQ() {
        return fieldVALADQ.getString();
    }

    /**
     * Set numeric field VALADQ using a BigDecimal value.
     */
    public void setVALADQ(BigDecimal newvalue) {
        fieldVALADQ.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VALADQ as a BigDecimal.
     */
    public BigDecimal getBigDecimalVALADQ() {
        return fieldVALADQ.getBigDecimal();
    }

    /**
     * Set field BASC using a String value.
     */
    public void setBASC(String newvalue) {
        fieldBASC.setString(newvalue);
    }

    /**
     * Get value of field BASC as a String.
     */
    public String getBASC() {
        return fieldBASC.getString();
    }

    /**
     * Set numeric field BASC using a BigDecimal value.
     */
    public void setBASC(BigDecimal newvalue) {
        fieldBASC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BASC as a BigDecimal.
     */
    public BigDecimal getBigDecimalBASC() {
        return fieldBASC.getBigDecimal();
    }

    /**
     * Set field BASD using a String value.
     */
    public void setBASD(String newvalue) {
        fieldBASD.setString(newvalue);
    }

    /**
     * Get value of field BASD as a String.
     */
    public String getBASD() {
        return fieldBASD.getString();
    }

    /**
     * Set numeric field BASD using a BigDecimal value.
     */
    public void setBASD(BigDecimal newvalue) {
        fieldBASD.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BASD as a BigDecimal.
     */
    public BigDecimal getBigDecimalBASD() {
        return fieldBASD.getBigDecimal();
    }

    /**
     * Set field INVNOP using a String value.
     */
    public void setINVNOP(String newvalue) {
        fieldINVNOP.setString(newvalue);
    }

    /**
     * Get value of field INVNOP as a String.
     */
    public String getINVNOP() {
        return fieldINVNOP.getString();
    }

    /**
     * Set numeric field INVNOP using a BigDecimal value.
     */
    public void setINVNOP(BigDecimal newvalue) {
        fieldINVNOP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVNOP as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVNOP() {
        return fieldINVNOP.getBigDecimal();
    }

    /**
     * Set field SFNRO using a String value.
     */
    public void setSFNRO(String newvalue) {
        fieldSFNRO.setString(newvalue);
    }

    /**
     * Get value of field SFNRO as a String.
     */
    public String getSFNRO() {
        return fieldSFNRO.getString();
    }

    /**
     * Set numeric field SFNRO using a BigDecimal value.
     */
    public void setSFNRO(BigDecimal newvalue) {
        fieldSFNRO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SFNRO as a BigDecimal.
     */
    public BigDecimal getBigDecimalSFNRO() {
        return fieldSFNRO.getBigDecimal();
    }

    /**
     * Set field SFECV using a String value.
     */
    public void setSFECV(String newvalue) {
        fieldSFECV.setString(newvalue);
    }

    /**
     * Get value of field SFECV as a String.
     */
    public String getSFECV() {
        return fieldSFECV.getString();
    }

    /**
     * Set numeric field SFECV using a BigDecimal value.
     */
    public void setSFECV(BigDecimal newvalue) {
        fieldSFECV.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SFECV as a BigDecimal.
     */
    public BigDecimal getBigDecimalSFECV() {
        return fieldSFECV.getBigDecimal();
    }

    /**
     * Set field SFBVI using a String value.
     */
    public void setSFBVI(String newvalue) {
        fieldSFBVI.setString(newvalue);
    }

    /**
     * Get value of field SFBVI as a String.
     */
    public String getSFBVI() {
        return fieldSFBVI.getString();
    }

    /**
     * Set numeric field SFBVI using a BigDecimal value.
     */
    public void setSFBVI(BigDecimal newvalue) {
        fieldSFBVI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SFBVI as a BigDecimal.
     */
    public BigDecimal getBigDecimalSFBVI() {
        return fieldSFBVI.getBigDecimal();
    }

    /**
     * Set field SFRE1 using a String value.
     */
    public void setSFRE1(String newvalue) {
        fieldSFRE1.setString(newvalue);
    }

    /**
     * Get value of field SFRE1 as a String.
     */
    public String getSFRE1() {
        return fieldSFRE1.getString();
    }

    /**
     * Set field SFRE2 using a String value.
     */
    public void setSFRE2(String newvalue) {
        fieldSFRE2.setString(newvalue);
    }

    /**
     * Get value of field SFRE2 as a String.
     */
    public String getSFRE2() {
        return fieldSFRE2.getString();
    }

    /**
     * Set numeric field SFRE2 using a BigDecimal value.
     */
    public void setSFRE2(BigDecimal newvalue) {
        fieldSFRE2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SFRE2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalSFRE2() {
        return fieldSFRE2.getBigDecimal();
    }

    /**
     * Set field OPCION using a String value.
     */
    public void setOPCION(String newvalue) {
        fieldOPCION.setString(newvalue);
    }

    /**
     * Get value of field OPCION as a String.
     */
    public String getOPCION() {
        return fieldOPCION.getString();
    }

    /**
     * Set field INVVAL using a String value.
     */
    public void setINVVAL(String newvalue) {
        fieldINVVAL.setString(newvalue);
    }

    /**
     * Get value of field INVVAL as a String.
     */
    public String getINVVAL() {
        return fieldINVVAL.getString();
    }

    /**
     * Set field OPERA using a String value.
     */
    public void setOPERA(String newvalue) {
        fieldOPERA.setString(newvalue);
    }

    /**
     * Get value of field OPERA as a String.
     */
    public String getOPERA() {
        return fieldOPERA.getString();
    }

    /**
     * Set numeric field OPERA using a BigDecimal value.
     */
    public void setOPERA(BigDecimal newvalue) {
        fieldOPERA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field OPERA as a BigDecimal.
     */
    public BigDecimal getBigDecimalOPERA() {
        return fieldOPERA.getBigDecimal();
    }

    /**
     * Set field CLIENTE using a String value.
     */
    public void setCLIENTE(String newvalue) {
        fieldCLIENTE.setString(newvalue);
    }

    /**
     * Get value of field CLIENTE as a String.
     */
    public String getCLIENTE() {
        return fieldCLIENTE.getString();
    }

    /**
     * Set numeric field CLIENTE using a BigDecimal value.
     */
    public void setCLIENTE(BigDecimal newvalue) {
        fieldCLIENTE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLIENTE as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLIENTE() {
        return fieldCLIENTE.getBigDecimal();
    }

    /**
     * Set field FCOBCUP using a String value.
     */
    public void setFCOBCUP(String newvalue) {
        fieldFCOBCUP.setString(newvalue);
    }

    /**
     * Get value of field FCOBCUP as a String.
     */
    public String getFCOBCUP() {
        return fieldFCOBCUP.getString();
    }

    /**
     * Set numeric field FCOBCUP using a BigDecimal value.
     */
    public void setFCOBCUP(BigDecimal newvalue) {
        fieldFCOBCUP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FCOBCUP as a BigDecimal.
     */
    public BigDecimal getBigDecimalFCOBCUP() {
        return fieldFCOBCUP.getBigDecimal();
    }

    /**
     * Set field NRR using a String value.
     */
    public void setNRR(String newvalue) {
        fieldNRR.setString(newvalue);
    }

    /**
     * Get value of field NRR as a String.
     */
    public String getNRR() {
        return fieldNRR.getString();
    }

    /**
     * Set numeric field NRR using a BigDecimal value.
     */
    public void setNRR(BigDecimal newvalue) {
        fieldNRR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NRR as a BigDecimal.
     */
    public BigDecimal getBigDecimalNRR() {
        return fieldNRR.getBigDecimal();
    }

    /**
     * Set field TINTANT using a String value.
     */
    public void setTINTANT(String newvalue) {
        fieldTINTANT.setString(newvalue);
    }

    /**
     * Get value of field TINTANT as a String.
     */
    public String getTINTANT() {
        return fieldTINTANT.getString();
    }

    /**
     * Set numeric field TINTANT using a BigDecimal value.
     */
    public void setTINTANT(BigDecimal newvalue) {
        fieldTINTANT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TINTANT as a BigDecimal.
     */
    public BigDecimal getBigDecimalTINTANT() {
        return fieldTINTANT.getBigDecimal();
    }

    /**
     * Set field TINTDEX using a String value.
     */
    public void setTINTDEX(String newvalue) {
        fieldTINTDEX.setString(newvalue);
    }

    /**
     * Get value of field TINTDEX as a String.
     */
    public String getTINTDEX() {
        return fieldTINTDEX.getString();
    }

    /**
     * Set numeric field TINTDEX using a BigDecimal value.
     */
    public void setTINTDEX(BigDecimal newvalue) {
        fieldTINTDEX.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TINTDEX as a BigDecimal.
     */
    public BigDecimal getBigDecimalTINTDEX() {
        return fieldTINTDEX.getBigDecimal();
    }

    /**
     * Set field TINTCOB using a String value.
     */
    public void setTINTCOB(String newvalue) {
        fieldTINTCOB.setString(newvalue);
    }

    /**
     * Get value of field TINTCOB as a String.
     */
    public String getTINTCOB() {
        return fieldTINTCOB.getString();
    }

    /**
     * Set numeric field TINTCOB using a BigDecimal value.
     */
    public void setTINTCOB(BigDecimal newvalue) {
        fieldTINTCOB.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TINTCOB as a BigDecimal.
     */
    public BigDecimal getBigDecimalTINTCOB() {
        return fieldTINTCOB.getBigDecimal();
    }

    /**
     * Set field TINTPEN using a String value.
     */
    public void setTINTPEN(String newvalue) {
        fieldTINTPEN.setString(newvalue);
    }

    /**
     * Get value of field TINTPEN as a String.
     */
    public String getTINTPEN() {
        return fieldTINTPEN.getString();
    }

    /**
     * Set numeric field TINTPEN using a BigDecimal value.
     */
    public void setTINTPEN(BigDecimal newvalue) {
        fieldTINTPEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TINTPEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalTINTPEN() {
        return fieldTINTPEN.getBigDecimal();
    }

    /**
     * Set field CFEC using a String value.
     */
    public void setCFEC(String newvalue) {
        fieldCFEC.setString(newvalue);
    }

    /**
     * Get value of field CFEC as a String.
     */
    public String getCFEC() {
        return fieldCFEC.getString();
    }

    /**
     * Set numeric field CFEC using a BigDecimal value.
     */
    public void setCFEC(BigDecimal newvalue) {
        fieldCFEC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CFEC as a BigDecimal.
     */
    public BigDecimal getBigDecimalCFEC() {
        return fieldCFEC.getBigDecimal();
    }

    /**
     * Set field CUPMNT using a String value.
     */
    public void setCUPMNT(String newvalue) {
        fieldCUPMNT.setString(newvalue);
    }

    /**
     * Get value of field CUPMNT as a String.
     */
    public String getCUPMNT() {
        return fieldCUPMNT.getString();
    }

    /**
     * Set numeric field CUPMNT using a BigDecimal value.
     */
    public void setCUPMNT(BigDecimal newvalue) {
        fieldCUPMNT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CUPMNT as a BigDecimal.
     */
    public BigDecimal getBigDecimalCUPMNT() {
        return fieldCUPMNT.getBigDecimal();
    }

    /**
     * Set field FCOB using a String value.
     */
    public void setFCOB(String newvalue) {
        fieldFCOB.setString(newvalue);
    }

    /**
     * Get value of field FCOB as a String.
     */
    public String getFCOB() {
        return fieldFCOB.getString();
    }

    /**
     * Set numeric field FCOB using a BigDecimal value.
     */
    public void setFCOB(BigDecimal newvalue) {
        fieldFCOB.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FCOB as a BigDecimal.
     */
    public BigDecimal getBigDecimalFCOB() {
        return fieldFCOB.getBigDecimal();
    }

    /**
     * Set field CUPVEN using a String value.
     */
    public void setCUPVEN(String newvalue) {
        fieldCUPVEN.setString(newvalue);
    }

    /**
     * Get value of field CUPVEN as a String.
     */
    public String getCUPVEN() {
        return fieldCUPVEN.getString();
    }

    /**
     * Set field CUPMCB using a String value.
     */
    public void setCUPMCB(String newvalue) {
        fieldCUPMCB.setString(newvalue);
    }

    /**
     * Get value of field CUPMCB as a String.
     */
    public String getCUPMCB() {
        return fieldCUPMCB.getString();
    }

    /**
     * Set field CUPCBT using a String value.
     */
    public void setCUPCBT(String newvalue) {
        fieldCUPCBT.setString(newvalue);
    }

    /**
     * Get value of field CUPCBT as a String.
     */
    public String getCUPCBT() {
        return fieldCUPCBT.getString();
    }

}
