package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from CONTR2FM physical file
 * definition.
 * 
* File level identifier is 1140213211956. Record format level identifier is
 * 4B5532DEF716A.
 */
public class CONTR2FMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "POSCUR",
        "CAMCUR",
        "NUCONT",
        "NUMAPO",
        "NUMOFI",
        "OFINOM",
        "CLINIF",
        "TODO",
        "CEDFID",
        "NOMFID",
        "CEEMP",
        "RP",
        "NOMRE",
        "CEDRE",
        "ECRE",
        "PRORE",
        "POBRE",
        "CERE",
        "TOMRE",
        "FOLRE",
        "ASIRE",
        "OPCION",
        "COSDIV",
        "TEX2",
        "CONMNT",
        "NTAB",
        "NOMTAB",
        "FIJVAR",
        "COMANF",
        "MNTCO1",
        "COMAPF",
        "COMAEF",
        "COMCOF",
        "COMMOF",
        "MNTCOM",
        "CONFFI",
        "FRMPA",
        "TEXT1",
        "RENOV",
        "CODCTA",
        "FECVT",
        "SECCI",
        "VIGEN",
        "CEDUL1",
        "PEAUT1",
        "CEDUL2",
        "PEAUT2",
        "CEDUL3",
        "PEAUT3",
        "OPC1",
        "OPC2",
        "TEXERR",
        "CTEI",
        "NCTEI",
        "CTEP",
        "NCTEP",
        "AHOI",
        "NAHOI",
        "AHOP",
        "NAHOP",
        "FALI",
        "NFALI",
        "FALO",
        "NFALP",
        "CHEI",
        "CHEP",
        "REII",
        "REIP",
        "DATGA1",
        "DATGA2",
        "COMAPO",
        "ICOAPO",
        "COMRET",
        "ICORET",
        "COMFIN",
        "ICOFIN",
        "GESCOD",
        "NGESCOD",
        "COAUT1",
        "NCOAUT1",
        "BENE1",
        "ECBEN1",
        "NABEN1",
        "PRBEN1",
        "POBEN1",
        "CEBEN1",
        "BENE2",
        "ECBEN2",
        "NABEN2",
        "PRBEN2",
        "POBEN2",
        "CEBEN2",
        "BENE3",
        "ECBEN3",
        "NABEN3",
        "PRBEN3",
        "POBEN3",
        "CEBEN3",
        "TOMRE1",
        "FOLRE1",
        "ASIRE1",
        "FECPR1",
        "FECEJ1",
        "OBJ1",
        "OBJ2",
        "OBJ3",
        "OBJ5",
        "OBJ4",
        "NROPRO",
        "CUEN1",
        "CUEN2",
        "CUEN3"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "POSCUR",
        "CAMCUR",
        "NUCONT",
        "NUMAPO",
        "NUMOFI",
        "OFINOM",
        "CLINIF",
        "TODO",
        "CEDFID",
        "NOMFID",
        "CEEMP",
        "RP",
        "NOMRE",
        "CEDRE",
        "ECRE",
        "PRORE",
        "POBRE",
        "CERE",
        "TOMRE",
        "FOLRE",
        "ASIRE",
        "OPCION",
        "COSDIV",
        "TEX2",
        "CONMNT",
        "NTAB",
        "NOMTAB",
        "FIJVAR",
        "COMANF",
        "MNTCO1",
        "COMAPF",
        "COMAEF",
        "COMCOF",
        "COMMOF",
        "MNTCOM",
        "CONFFI",
        "FRMPA",
        "TEXT1",
        "RENOV",
        "CODCTA",
        "FECVT",
        "SECCI",
        "VIGEN",
        "CEDUL1",
        "PEAUT1",
        "CEDUL2",
        "PEAUT2",
        "CEDUL3",
        "PEAUT3",
        "OPC1",
        "OPC2",
        "TEXERR",
        "CTEI",
        "NCTEI",
        "CTEP",
        "NCTEP",
        "AHOI",
        "NAHOI",
        "AHOP",
        "NAHOP",
        "FALI",
        "NFALI",
        "FALO",
        "NFALP",
        "CHEI",
        "CHEP",
        "REII",
        "REIP",
        "DATGA1",
        "DATGA2",
        "COMAPO",
        "ICOAPO",
        "COMRET",
        "ICORET",
        "COMFIN",
        "ICOFIN",
        "GESCOD",
        "NGESCOD",
        "COAUT1",
        "NCOAUT1",
        "BENE1",
        "ECBEN1",
        "NABEN1",
        "PRBEN1",
        "POBEN1",
        "CEBEN1",
        "BENE2",
        "ECBEN2",
        "NABEN2",
        "PRBEN2",
        "POBEN2",
        "CEBEN2",
        "BENE3",
        "ECBEN3",
        "NABEN3",
        "PRBEN3",
        "POBEN3",
        "CEBEN3",
        "TOMRE1",
        "FOLRE1",
        "ASIRE1",
        "FECPR1",
        "FECEJ1",
        "OBJ1",
        "OBJ2",
        "OBJ3",
        "OBJ5",
        "OBJ4",
        "NROPRO",
        "CUEN1",
        "CUEN2",
        "CUEN3"
    };
    final static String fid = "1140213211956";
    final static String rid = "4B5532DEF716A";
    final static String fmtname = "CONTR2FM";
    final int FIELDCOUNT = 122;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private DecimalField fieldPOSCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldNUCONT = null;
    private DecimalField fieldNUMAPO = null;
    private DecimalField fieldNUMOFI = null;
    private CharacterField fieldOFINOM = null;
    private CharacterField fieldCLINIF = null;
    private CharacterField fieldTODO = null;
    private CharacterField fieldCEDFID = null;
    private CharacterField fieldNOMFID = null;
    private CharacterField fieldCEEMP = null;
    private CharacterField fieldRP = null;
    private CharacterField fieldNOMRE = null;
    private CharacterField fieldCEDRE = null;
    private CharacterField fieldECRE = null;
    private CharacterField fieldPRORE = null;
    private CharacterField fieldPOBRE = null;
    private CharacterField fieldCERE = null;
    private CharacterField fieldTOMRE = null;
    private CharacterField fieldFOLRE = null;
    private CharacterField fieldASIRE = null;
    private CharacterField fieldOPCION = null;
    private DecimalField fieldCOSDIV = null;
    private CharacterField fieldTEX2 = null;
    private DecimalField fieldCONMNT = null;
    private DecimalField fieldNTAB = null;
    private CharacterField fieldNOMTAB = null;
    private CharacterField fieldFIJVAR = null;
    private DecimalField fieldCOMANF = null;
    private DecimalField fieldMNTCO1 = null;
    private DecimalField fieldCOMAPF = null;
    private DecimalField fieldCOMAEF = null;
    private DecimalField fieldCOMCOF = null;
    private DecimalField fieldCOMMOF = null;
    private DecimalField fieldMNTCOM = null;
    private DecimalField fieldCONFFI = null;
    private DecimalField fieldFRMPA = null;
    private CharacterField fieldTEXT1 = null;
    private CharacterField fieldRENOV = null;
    private CharacterField fieldCODCTA = null;
    private DecimalField fieldFECVT = null;
    private CharacterField fieldSECCI = null;
    private CharacterField fieldVIGEN = null;
    private CharacterField fieldCEDUL1 = null;
    private CharacterField fieldPEAUT1 = null;
    private CharacterField fieldCEDUL2 = null;
    private CharacterField fieldPEAUT2 = null;
    private CharacterField fieldCEDUL3 = null;
    private CharacterField fieldPEAUT3 = null;
    private CharacterField fieldOPC1 = null;
    private CharacterField fieldOPC2 = null;
    private CharacterField fieldTEXERR = null;
    private CharacterField fieldCTEI = null;
    private CharacterField fieldNCTEI = null;
    private CharacterField fieldCTEP = null;
    private CharacterField fieldNCTEP = null;
    private CharacterField fieldAHOI = null;
    private CharacterField fieldNAHOI = null;
    private CharacterField fieldAHOP = null;
    private CharacterField fieldNAHOP = null;
    private CharacterField fieldFALI = null;
    private CharacterField fieldNFALI = null;
    private CharacterField fieldFALO = null;
    private CharacterField fieldNFALP = null;
    private CharacterField fieldCHEI = null;
    private CharacterField fieldCHEP = null;
    private CharacterField fieldREII = null;
    private CharacterField fieldREIP = null;
    private DecimalField fieldDATGA1 = null;
    private DecimalField fieldDATGA2 = null;
    private DecimalField fieldCOMAPO = null;
    private DecimalField fieldICOAPO = null;
    private DecimalField fieldCOMRET = null;
    private DecimalField fieldICORET = null;
    private DecimalField fieldCOMFIN = null;
    private DecimalField fieldICOFIN = null;
    private DecimalField fieldGESCOD = null;
    private CharacterField fieldNGESCOD = null;
    private CharacterField fieldCOAUT1 = null;
    private CharacterField fieldNCOAUT1 = null;
    private CharacterField fieldBENE1 = null;
    private CharacterField fieldECBEN1 = null;
    private DecimalField fieldNABEN1 = null;
    private CharacterField fieldPRBEN1 = null;
    private CharacterField fieldPOBEN1 = null;
    private CharacterField fieldCEBEN1 = null;
    private CharacterField fieldBENE2 = null;
    private CharacterField fieldECBEN2 = null;
    private DecimalField fieldNABEN2 = null;
    private CharacterField fieldPRBEN2 = null;
    private CharacterField fieldPOBEN2 = null;
    private CharacterField fieldCEBEN2 = null;
    private CharacterField fieldBENE3 = null;
    private CharacterField fieldECBEN3 = null;
    private DecimalField fieldNABEN3 = null;
    private CharacterField fieldPRBEN3 = null;
    private CharacterField fieldPOBEN3 = null;
    private CharacterField fieldCEBEN3 = null;
    private CharacterField fieldTOMRE1 = null;
    private CharacterField fieldFOLRE1 = null;
    private CharacterField fieldASIRE1 = null;
    private DecimalField fieldFECPR1 = null;
    private DecimalField fieldFECEJ1 = null;
    private CharacterField fieldOBJ1 = null;
    private CharacterField fieldOBJ2 = null;
    private CharacterField fieldOBJ3 = null;
    private CharacterField fieldOBJ5 = null;
    private CharacterField fieldOBJ4 = null;
    private CharacterField fieldNROPRO = null;
    private CharacterField fieldCUEN1 = null;
    private CharacterField fieldCUEN2 = null;
    private CharacterField fieldCUEN3 = null;

    /**
     * Constructor for CONTR2FMMessage.
     */
    public CONTR2FMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 2880;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldPOSCUR
                = new DecimalField(message, HEADERSIZE + 171, 5, 0, "POSCUR");
        fields[11] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 176, 10, "CAMCUR");
        fields[12] = fieldNUCONT
                = new DecimalField(message, HEADERSIZE + 186, 9, 0, "NUCONT");
        fields[13] = fieldNUMAPO
                = new DecimalField(message, HEADERSIZE + 195, 3, 0, "NUMAPO");
        fields[14] = fieldNUMOFI
                = new DecimalField(message, HEADERSIZE + 198, 8, 0, "NUMOFI");
        fields[15] = fieldOFINOM
                = new CharacterField(message, HEADERSIZE + 206, 50, "OFINOM");
        fields[16] = fieldCLINIF
                = new CharacterField(message, HEADERSIZE + 256, 12, "CLINIF");
        fields[17] = fieldTODO
                = new CharacterField(message, HEADERSIZE + 268, 50, "TODO");
        fields[18] = fieldCEDFID
                = new CharacterField(message, HEADERSIZE + 318, 12, "CEDFID");
        fields[19] = fieldNOMFID
                = new CharacterField(message, HEADERSIZE + 330, 43, "NOMFID");
        fields[20] = fieldCEEMP
                = new CharacterField(message, HEADERSIZE + 373, 71, "CEEMP");
        fields[21] = fieldRP
                = new CharacterField(message, HEADERSIZE + 444, 30, "RP");
        fields[22] = fieldNOMRE
                = new CharacterField(message, HEADERSIZE + 474, 50, "NOMRE");
        fields[23] = fieldCEDRE
                = new CharacterField(message, HEADERSIZE + 524, 12, "CEDRE");
        fields[24] = fieldECRE
                = new CharacterField(message, HEADERSIZE + 536, 10, "ECRE");
        fields[25] = fieldPRORE
                = new CharacterField(message, HEADERSIZE + 546, 50, "PRORE");
        fields[26] = fieldPOBRE
                = new CharacterField(message, HEADERSIZE + 596, 50, "POBRE");
        fields[27] = fieldCERE
                = new CharacterField(message, HEADERSIZE + 646, 71, "CERE");
        fields[28] = fieldTOMRE
                = new CharacterField(message, HEADERSIZE + 717, 50, "TOMRE");
        fields[29] = fieldFOLRE
                = new CharacterField(message, HEADERSIZE + 767, 50, "FOLRE");
        fields[30] = fieldASIRE
                = new CharacterField(message, HEADERSIZE + 817, 50, "ASIRE");
        fields[31] = fieldOPCION
                = new CharacterField(message, HEADERSIZE + 867, 1, "OPCION");
        fields[32] = fieldCOSDIV
                = new DecimalField(message, HEADERSIZE + 868, 4, 0, "COSDIV");
        fields[33] = fieldTEX2
                = new CharacterField(message, HEADERSIZE + 872, 30, "TEX2");
        fields[34] = fieldCONMNT
                = new DecimalField(message, HEADERSIZE + 902, 16, 2, "CONMNT");
        fields[35] = fieldNTAB
                = new DecimalField(message, HEADERSIZE + 918, 3, 0, "NTAB");
        fields[36] = fieldNOMTAB
                = new CharacterField(message, HEADERSIZE + 921, 30, "NOMTAB");
        fields[37] = fieldFIJVAR
                = new CharacterField(message, HEADERSIZE + 951, 1, "FIJVAR");
        fields[38] = fieldCOMANF
                = new DecimalField(message, HEADERSIZE + 952, 11, 6, "COMANF");
        fields[39] = fieldMNTCO1
                = new DecimalField(message, HEADERSIZE + 963, 11, 2, "MNTCO1");
        fields[40] = fieldCOMAPF
                = new DecimalField(message, HEADERSIZE + 974, 12, 2, "COMAPF");
        fields[41] = fieldCOMAEF
                = new DecimalField(message, HEADERSIZE + 986, 12, 2, "COMAEF");
        fields[42] = fieldCOMCOF
                = new DecimalField(message, HEADERSIZE + 998, 11, 6, "COMCOF");
        fields[43] = fieldCOMMOF
                = new DecimalField(message, HEADERSIZE + 1009, 12, 2, "COMMOF");
        fields[44] = fieldMNTCOM
                = new DecimalField(message, HEADERSIZE + 1021, 11, 2, "MNTCOM");
        fields[45] = fieldCONFFI
                = new DecimalField(message, HEADERSIZE + 1032, 7, 0, "CONFFI");
        fields[46] = fieldFRMPA
                = new DecimalField(message, HEADERSIZE + 1039, 3, 0, "FRMPA");
        fields[47] = fieldTEXT1
                = new CharacterField(message, HEADERSIZE + 1042, 30, "TEXT1");
        fields[48] = fieldRENOV
                = new CharacterField(message, HEADERSIZE + 1072, 1, "RENOV");
        fields[49] = fieldCODCTA
                = new CharacterField(message, HEADERSIZE + 1073, 20, "CODCTA");
        fields[50] = fieldFECVT
                = new DecimalField(message, HEADERSIZE + 1093, 7, 0, "FECVT");
        fields[51] = fieldSECCI
                = new CharacterField(message, HEADERSIZE + 1100, 30, "SECCI");
        fields[52] = fieldVIGEN
                = new CharacterField(message, HEADERSIZE + 1130, 30, "VIGEN");
        fields[53] = fieldCEDUL1
                = new CharacterField(message, HEADERSIZE + 1160, 12, "CEDUL1");
        fields[54] = fieldPEAUT1
                = new CharacterField(message, HEADERSIZE + 1172, 50, "PEAUT1");
        fields[55] = fieldCEDUL2
                = new CharacterField(message, HEADERSIZE + 1222, 12, "CEDUL2");
        fields[56] = fieldPEAUT2
                = new CharacterField(message, HEADERSIZE + 1234, 50, "PEAUT2");
        fields[57] = fieldCEDUL3
                = new CharacterField(message, HEADERSIZE + 1284, 12, "CEDUL3");
        fields[58] = fieldPEAUT3
                = new CharacterField(message, HEADERSIZE + 1296, 50, "PEAUT3");
        fields[59] = fieldOPC1
                = new CharacterField(message, HEADERSIZE + 1346, 1, "OPC1");
        fields[60] = fieldOPC2
                = new CharacterField(message, HEADERSIZE + 1347, 1, "OPC2");
        fields[61] = fieldTEXERR
                = new CharacterField(message, HEADERSIZE + 1348, 30, "TEXERR");
        fields[62] = fieldCTEI
                = new CharacterField(message, HEADERSIZE + 1378, 1, "CTEI");
        fields[63] = fieldNCTEI
                = new CharacterField(message, HEADERSIZE + 1379, 20, "NCTEI");
        fields[64] = fieldCTEP
                = new CharacterField(message, HEADERSIZE + 1399, 1, "CTEP");
        fields[65] = fieldNCTEP
                = new CharacterField(message, HEADERSIZE + 1400, 20, "NCTEP");
        fields[66] = fieldAHOI
                = new CharacterField(message, HEADERSIZE + 1420, 1, "AHOI");
        fields[67] = fieldNAHOI
                = new CharacterField(message, HEADERSIZE + 1421, 20, "NAHOI");
        fields[68] = fieldAHOP
                = new CharacterField(message, HEADERSIZE + 1441, 1, "AHOP");
        fields[69] = fieldNAHOP
                = new CharacterField(message, HEADERSIZE + 1442, 20, "NAHOP");
        fields[70] = fieldFALI
                = new CharacterField(message, HEADERSIZE + 1462, 1, "FALI");
        fields[71] = fieldNFALI
                = new CharacterField(message, HEADERSIZE + 1463, 20, "NFALI");
        fields[72] = fieldFALO
                = new CharacterField(message, HEADERSIZE + 1483, 1, "FALO");
        fields[73] = fieldNFALP
                = new CharacterField(message, HEADERSIZE + 1484, 20, "NFALP");
        fields[74] = fieldCHEI
                = new CharacterField(message, HEADERSIZE + 1504, 1, "CHEI");
        fields[75] = fieldCHEP
                = new CharacterField(message, HEADERSIZE + 1505, 1, "CHEP");
        fields[76] = fieldREII
                = new CharacterField(message, HEADERSIZE + 1506, 1, "REII");
        fields[77] = fieldREIP
                = new CharacterField(message, HEADERSIZE + 1507, 1, "REIP");
        fields[78] = fieldDATGA1
                = new DecimalField(message, HEADERSIZE + 1508, 7, 2, "DATGA1");
        fields[79] = fieldDATGA2
                = new DecimalField(message, HEADERSIZE + 1515, 14, 2, "DATGA2");
        fields[80] = fieldCOMAPO
                = new DecimalField(message, HEADERSIZE + 1529, 11, 6, "COMAPO");
        fields[81] = fieldICOAPO
                = new DecimalField(message, HEADERSIZE + 1540, 17, 2, "ICOAPO");
        fields[82] = fieldCOMRET
                = new DecimalField(message, HEADERSIZE + 1557, 11, 6, "COMRET");
        fields[83] = fieldICORET
                = new DecimalField(message, HEADERSIZE + 1568, 17, 2, "ICORET");
        fields[84] = fieldCOMFIN
                = new DecimalField(message, HEADERSIZE + 1585, 11, 6, "COMFIN");
        fields[85] = fieldICOFIN
                = new DecimalField(message, HEADERSIZE + 1596, 17, 2, "ICOFIN");
        fields[86] = fieldGESCOD
                = new DecimalField(message, HEADERSIZE + 1613, 3, 0, "GESCOD");
        fields[87] = fieldNGESCOD
                = new CharacterField(message, HEADERSIZE + 1616, 40, "NGESCOD");
        fields[88] = fieldCOAUT1
                = new CharacterField(message, HEADERSIZE + 1656, 1, "COAUT1");
        fields[89] = fieldNCOAUT1
                = new CharacterField(message, HEADERSIZE + 1657, 15, "NCOAUT1");
        fields[90] = fieldBENE1
                = new CharacterField(message, HEADERSIZE + 1672, 50, "BENE1");
        fields[91] = fieldECBEN1
                = new CharacterField(message, HEADERSIZE + 1722, 10, "ECBEN1");
        fields[92] = fieldNABEN1
                = new DecimalField(message, HEADERSIZE + 1732, 7, 0, "NABEN1");
        fields[93] = fieldPRBEN1
                = new CharacterField(message, HEADERSIZE + 1739, 50, "PRBEN1");
        fields[94] = fieldPOBEN1
                = new CharacterField(message, HEADERSIZE + 1789, 50, "POBEN1");
        fields[95] = fieldCEBEN1
                = new CharacterField(message, HEADERSIZE + 1839, 71, "CEBEN1");
        fields[96] = fieldBENE2
                = new CharacterField(message, HEADERSIZE + 1910, 50, "BENE2");
        fields[97] = fieldECBEN2
                = new CharacterField(message, HEADERSIZE + 1960, 10, "ECBEN2");
        fields[98] = fieldNABEN2
                = new DecimalField(message, HEADERSIZE + 1970, 7, 0, "NABEN2");
        fields[99] = fieldPRBEN2
                = new CharacterField(message, HEADERSIZE + 1977, 50, "PRBEN2");
        fields[100] = fieldPOBEN2
                = new CharacterField(message, HEADERSIZE + 2027, 50, "POBEN2");
        fields[101] = fieldCEBEN2
                = new CharacterField(message, HEADERSIZE + 2077, 71, "CEBEN2");
        fields[102] = fieldBENE3
                = new CharacterField(message, HEADERSIZE + 2148, 50, "BENE3");
        fields[103] = fieldECBEN3
                = new CharacterField(message, HEADERSIZE + 2198, 10, "ECBEN3");
        fields[104] = fieldNABEN3
                = new DecimalField(message, HEADERSIZE + 2208, 7, 0, "NABEN3");
        fields[105] = fieldPRBEN3
                = new CharacterField(message, HEADERSIZE + 2215, 50, "PRBEN3");
        fields[106] = fieldPOBEN3
                = new CharacterField(message, HEADERSIZE + 2265, 50, "POBEN3");
        fields[107] = fieldCEBEN3
                = new CharacterField(message, HEADERSIZE + 2315, 71, "CEBEN3");
        fields[108] = fieldTOMRE1
                = new CharacterField(message, HEADERSIZE + 2386, 50, "TOMRE1");
        fields[109] = fieldFOLRE1
                = new CharacterField(message, HEADERSIZE + 2436, 50, "FOLRE1");
        fields[110] = fieldASIRE1
                = new CharacterField(message, HEADERSIZE + 2486, 50, "ASIRE1");
        fields[111] = fieldFECPR1
                = new DecimalField(message, HEADERSIZE + 2536, 7, 0, "FECPR1");
        fields[112] = fieldFECEJ1
                = new DecimalField(message, HEADERSIZE + 2543, 7, 0, "FECEJ1");
        fields[113] = fieldOBJ1
                = new CharacterField(message, HEADERSIZE + 2550, 50, "OBJ1");
        fields[114] = fieldOBJ2
                = new CharacterField(message, HEADERSIZE + 2600, 50, "OBJ2");
        fields[115] = fieldOBJ3
                = new CharacterField(message, HEADERSIZE + 2650, 50, "OBJ3");
        fields[116] = fieldOBJ5
                = new CharacterField(message, HEADERSIZE + 2700, 50, "OBJ5");
        fields[117] = fieldOBJ4
                = new CharacterField(message, HEADERSIZE + 2750, 50, "OBJ4");
        fields[118] = fieldNROPRO
                = new CharacterField(message, HEADERSIZE + 2800, 20, "NROPRO");
        fields[119] = fieldCUEN1
                = new CharacterField(message, HEADERSIZE + 2820, 20, "CUEN1");
        fields[120] = fieldCUEN2
                = new CharacterField(message, HEADERSIZE + 2840, 20, "CUEN2");
        fields[121] = fieldCUEN3
                = new CharacterField(message, HEADERSIZE + 2860, 20, "CUEN3");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field POSCUR using a String value.
     */
    public void setPOSCUR(String newvalue) {
        fieldPOSCUR.setString(newvalue);
    }

    /**
     * Get value of field POSCUR as a String.
     */
    public String getPOSCUR() {
        return fieldPOSCUR.getString();
    }

    /**
     * Set numeric field POSCUR using a BigDecimal value.
     */
    public void setPOSCUR(BigDecimal newvalue) {
        fieldPOSCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field POSCUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalPOSCUR() {
        return fieldPOSCUR.getBigDecimal();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field NUCONT using a String value.
     */
    public void setNUCONT(String newvalue) {
        fieldNUCONT.setString(newvalue);
    }

    /**
     * Get value of field NUCONT as a String.
     */
    public String getNUCONT() {
        return fieldNUCONT.getString();
    }

    /**
     * Set numeric field NUCONT using a BigDecimal value.
     */
    public void setNUCONT(BigDecimal newvalue) {
        fieldNUCONT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NUCONT as a BigDecimal.
     */
    public BigDecimal getBigDecimalNUCONT() {
        return fieldNUCONT.getBigDecimal();
    }

    /**
     * Set field NUMAPO using a String value.
     */
    public void setNUMAPO(String newvalue) {
        fieldNUMAPO.setString(newvalue);
    }

    /**
     * Get value of field NUMAPO as a String.
     */
    public String getNUMAPO() {
        return fieldNUMAPO.getString();
    }

    /**
     * Set numeric field NUMAPO using a BigDecimal value.
     */
    public void setNUMAPO(BigDecimal newvalue) {
        fieldNUMAPO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NUMAPO as a BigDecimal.
     */
    public BigDecimal getBigDecimalNUMAPO() {
        return fieldNUMAPO.getBigDecimal();
    }

    /**
     * Set field NUMOFI using a String value.
     */
    public void setNUMOFI(String newvalue) {
        fieldNUMOFI.setString(newvalue);
    }

    /**
     * Get value of field NUMOFI as a String.
     */
    public String getNUMOFI() {
        return fieldNUMOFI.getString();
    }

    /**
     * Set numeric field NUMOFI using a BigDecimal value.
     */
    public void setNUMOFI(BigDecimal newvalue) {
        fieldNUMOFI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NUMOFI as a BigDecimal.
     */
    public BigDecimal getBigDecimalNUMOFI() {
        return fieldNUMOFI.getBigDecimal();
    }

    /**
     * Set field OFINOM using a String value.
     */
    public void setOFINOM(String newvalue) {
        fieldOFINOM.setString(newvalue);
    }

    /**
     * Get value of field OFINOM as a String.
     */
    public String getOFINOM() {
        return fieldOFINOM.getString();
    }

    /**
     * Set field CLINIF using a String value.
     */
    public void setCLINIF(String newvalue) {
        fieldCLINIF.setString(newvalue);
    }

    /**
     * Get value of field CLINIF as a String.
     */
    public String getCLINIF() {
        return fieldCLINIF.getString();
    }

    /**
     * Set field TODO using a String value.
     */
    public void setTODO(String newvalue) {
        fieldTODO.setString(newvalue);
    }

    /**
     * Get value of field TODO as a String.
     */
    public String getTODO() {
        return fieldTODO.getString();
    }

    /**
     * Set field CEDFID using a String value.
     */
    public void setCEDFID(String newvalue) {
        fieldCEDFID.setString(newvalue);
    }

    /**
     * Get value of field CEDFID as a String.
     */
    public String getCEDFID() {
        return fieldCEDFID.getString();
    }

    /**
     * Set field NOMFID using a String value.
     */
    public void setNOMFID(String newvalue) {
        fieldNOMFID.setString(newvalue);
    }

    /**
     * Get value of field NOMFID as a String.
     */
    public String getNOMFID() {
        return fieldNOMFID.getString();
    }

    /**
     * Set field CEEMP using a String value.
     */
    public void setCEEMP(String newvalue) {
        fieldCEEMP.setString(newvalue);
    }

    /**
     * Get value of field CEEMP as a String.
     */
    public String getCEEMP() {
        return fieldCEEMP.getString();
    }

    /**
     * Set field RP using a String value.
     */
    public void setRP(String newvalue) {
        fieldRP.setString(newvalue);
    }

    /**
     * Get value of field RP as a String.
     */
    public String getRP() {
        return fieldRP.getString();
    }

    /**
     * Set field NOMRE using a String value.
     */
    public void setNOMRE(String newvalue) {
        fieldNOMRE.setString(newvalue);
    }

    /**
     * Get value of field NOMRE as a String.
     */
    public String getNOMRE() {
        return fieldNOMRE.getString();
    }

    /**
     * Set field CEDRE using a String value.
     */
    public void setCEDRE(String newvalue) {
        fieldCEDRE.setString(newvalue);
    }

    /**
     * Get value of field CEDRE as a String.
     */
    public String getCEDRE() {
        return fieldCEDRE.getString();
    }

    /**
     * Set field ECRE using a String value.
     */
    public void setECRE(String newvalue) {
        fieldECRE.setString(newvalue);
    }

    /**
     * Get value of field ECRE as a String.
     */
    public String getECRE() {
        return fieldECRE.getString();
    }

    /**
     * Set field PRORE using a String value.
     */
    public void setPRORE(String newvalue) {
        fieldPRORE.setString(newvalue);
    }

    /**
     * Get value of field PRORE as a String.
     */
    public String getPRORE() {
        return fieldPRORE.getString();
    }

    /**
     * Set field POBRE using a String value.
     */
    public void setPOBRE(String newvalue) {
        fieldPOBRE.setString(newvalue);
    }

    /**
     * Get value of field POBRE as a String.
     */
    public String getPOBRE() {
        return fieldPOBRE.getString();
    }

    /**
     * Set field CERE using a String value.
     */
    public void setCERE(String newvalue) {
        fieldCERE.setString(newvalue);
    }

    /**
     * Get value of field CERE as a String.
     */
    public String getCERE() {
        return fieldCERE.getString();
    }

    /**
     * Set field TOMRE using a String value.
     */
    public void setTOMRE(String newvalue) {
        fieldTOMRE.setString(newvalue);
    }

    /**
     * Get value of field TOMRE as a String.
     */
    public String getTOMRE() {
        return fieldTOMRE.getString();
    }

    /**
     * Set field FOLRE using a String value.
     */
    public void setFOLRE(String newvalue) {
        fieldFOLRE.setString(newvalue);
    }

    /**
     * Get value of field FOLRE as a String.
     */
    public String getFOLRE() {
        return fieldFOLRE.getString();
    }

    /**
     * Set field ASIRE using a String value.
     */
    public void setASIRE(String newvalue) {
        fieldASIRE.setString(newvalue);
    }

    /**
     * Get value of field ASIRE as a String.
     */
    public String getASIRE() {
        return fieldASIRE.getString();
    }

    /**
     * Set field OPCION using a String value.
     */
    public void setOPCION(String newvalue) {
        fieldOPCION.setString(newvalue);
    }

    /**
     * Get value of field OPCION as a String.
     */
    public String getOPCION() {
        return fieldOPCION.getString();
    }

    /**
     * Set field COSDIV using a String value.
     */
    public void setCOSDIV(String newvalue) {
        fieldCOSDIV.setString(newvalue);
    }

    /**
     * Get value of field COSDIV as a String.
     */
    public String getCOSDIV() {
        return fieldCOSDIV.getString();
    }

    /**
     * Set numeric field COSDIV using a BigDecimal value.
     */
    public void setCOSDIV(BigDecimal newvalue) {
        fieldCOSDIV.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COSDIV as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOSDIV() {
        return fieldCOSDIV.getBigDecimal();
    }

    /**
     * Set field TEX2 using a String value.
     */
    public void setTEX2(String newvalue) {
        fieldTEX2.setString(newvalue);
    }

    /**
     * Get value of field TEX2 as a String.
     */
    public String getTEX2() {
        return fieldTEX2.getString();
    }

    /**
     * Set field CONMNT using a String value.
     */
    public void setCONMNT(String newvalue) {
        fieldCONMNT.setString(newvalue);
    }

    /**
     * Get value of field CONMNT as a String.
     */
    public String getCONMNT() {
        return fieldCONMNT.getString();
    }

    /**
     * Set numeric field CONMNT using a BigDecimal value.
     */
    public void setCONMNT(BigDecimal newvalue) {
        fieldCONMNT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CONMNT as a BigDecimal.
     */
    public BigDecimal getBigDecimalCONMNT() {
        return fieldCONMNT.getBigDecimal();
    }

    /**
     * Set field NTAB using a String value.
     */
    public void setNTAB(String newvalue) {
        fieldNTAB.setString(newvalue);
    }

    /**
     * Get value of field NTAB as a String.
     */
    public String getNTAB() {
        return fieldNTAB.getString();
    }

    /**
     * Set numeric field NTAB using a BigDecimal value.
     */
    public void setNTAB(BigDecimal newvalue) {
        fieldNTAB.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NTAB as a BigDecimal.
     */
    public BigDecimal getBigDecimalNTAB() {
        return fieldNTAB.getBigDecimal();
    }

    /**
     * Set field NOMTAB using a String value.
     */
    public void setNOMTAB(String newvalue) {
        fieldNOMTAB.setString(newvalue);
    }

    /**
     * Get value of field NOMTAB as a String.
     */
    public String getNOMTAB() {
        return fieldNOMTAB.getString();
    }

    /**
     * Set field FIJVAR using a String value.
     */
    public void setFIJVAR(String newvalue) {
        fieldFIJVAR.setString(newvalue);
    }

    /**
     * Get value of field FIJVAR as a String.
     */
    public String getFIJVAR() {
        return fieldFIJVAR.getString();
    }

    /**
     * Set field COMANF using a String value.
     */
    public void setCOMANF(String newvalue) {
        fieldCOMANF.setString(newvalue);
    }

    /**
     * Get value of field COMANF as a String.
     */
    public String getCOMANF() {
        return fieldCOMANF.getString();
    }

    /**
     * Set numeric field COMANF using a BigDecimal value.
     */
    public void setCOMANF(BigDecimal newvalue) {
        fieldCOMANF.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMANF as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMANF() {
        return fieldCOMANF.getBigDecimal();
    }

    /**
     * Set field MNTCO1 using a String value.
     */
    public void setMNTCO1(String newvalue) {
        fieldMNTCO1.setString(newvalue);
    }

    /**
     * Get value of field MNTCO1 as a String.
     */
    public String getMNTCO1() {
        return fieldMNTCO1.getString();
    }

    /**
     * Set numeric field MNTCO1 using a BigDecimal value.
     */
    public void setMNTCO1(BigDecimal newvalue) {
        fieldMNTCO1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MNTCO1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalMNTCO1() {
        return fieldMNTCO1.getBigDecimal();
    }

    /**
     * Set field COMAPF using a String value.
     */
    public void setCOMAPF(String newvalue) {
        fieldCOMAPF.setString(newvalue);
    }

    /**
     * Get value of field COMAPF as a String.
     */
    public String getCOMAPF() {
        return fieldCOMAPF.getString();
    }

    /**
     * Set numeric field COMAPF using a BigDecimal value.
     */
    public void setCOMAPF(BigDecimal newvalue) {
        fieldCOMAPF.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMAPF as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMAPF() {
        return fieldCOMAPF.getBigDecimal();
    }

    /**
     * Set field COMAEF using a String value.
     */
    public void setCOMAEF(String newvalue) {
        fieldCOMAEF.setString(newvalue);
    }

    /**
     * Get value of field COMAEF as a String.
     */
    public String getCOMAEF() {
        return fieldCOMAEF.getString();
    }

    /**
     * Set numeric field COMAEF using a BigDecimal value.
     */
    public void setCOMAEF(BigDecimal newvalue) {
        fieldCOMAEF.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMAEF as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMAEF() {
        return fieldCOMAEF.getBigDecimal();
    }

    /**
     * Set field COMCOF using a String value.
     */
    public void setCOMCOF(String newvalue) {
        fieldCOMCOF.setString(newvalue);
    }

    /**
     * Get value of field COMCOF as a String.
     */
    public String getCOMCOF() {
        return fieldCOMCOF.getString();
    }

    /**
     * Set numeric field COMCOF using a BigDecimal value.
     */
    public void setCOMCOF(BigDecimal newvalue) {
        fieldCOMCOF.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMCOF as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMCOF() {
        return fieldCOMCOF.getBigDecimal();
    }

    /**
     * Set field COMMOF using a String value.
     */
    public void setCOMMOF(String newvalue) {
        fieldCOMMOF.setString(newvalue);
    }

    /**
     * Get value of field COMMOF as a String.
     */
    public String getCOMMOF() {
        return fieldCOMMOF.getString();
    }

    /**
     * Set numeric field COMMOF using a BigDecimal value.
     */
    public void setCOMMOF(BigDecimal newvalue) {
        fieldCOMMOF.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMMOF as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMMOF() {
        return fieldCOMMOF.getBigDecimal();
    }

    /**
     * Set field MNTCOM using a String value.
     */
    public void setMNTCOM(String newvalue) {
        fieldMNTCOM.setString(newvalue);
    }

    /**
     * Get value of field MNTCOM as a String.
     */
    public String getMNTCOM() {
        return fieldMNTCOM.getString();
    }

    /**
     * Set numeric field MNTCOM using a BigDecimal value.
     */
    public void setMNTCOM(BigDecimal newvalue) {
        fieldMNTCOM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MNTCOM as a BigDecimal.
     */
    public BigDecimal getBigDecimalMNTCOM() {
        return fieldMNTCOM.getBigDecimal();
    }

    /**
     * Set field CONFFI using a String value.
     */
    public void setCONFFI(String newvalue) {
        fieldCONFFI.setString(newvalue);
    }

    /**
     * Get value of field CONFFI as a String.
     */
    public String getCONFFI() {
        return fieldCONFFI.getString();
    }

    /**
     * Set numeric field CONFFI using a BigDecimal value.
     */
    public void setCONFFI(BigDecimal newvalue) {
        fieldCONFFI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CONFFI as a BigDecimal.
     */
    public BigDecimal getBigDecimalCONFFI() {
        return fieldCONFFI.getBigDecimal();
    }

    /**
     * Set field FRMPA using a String value.
     */
    public void setFRMPA(String newvalue) {
        fieldFRMPA.setString(newvalue);
    }

    /**
     * Get value of field FRMPA as a String.
     */
    public String getFRMPA() {
        return fieldFRMPA.getString();
    }

    /**
     * Set numeric field FRMPA using a BigDecimal value.
     */
    public void setFRMPA(BigDecimal newvalue) {
        fieldFRMPA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FRMPA as a BigDecimal.
     */
    public BigDecimal getBigDecimalFRMPA() {
        return fieldFRMPA.getBigDecimal();
    }

    /**
     * Set field TEXT1 using a String value.
     */
    public void setTEXT1(String newvalue) {
        fieldTEXT1.setString(newvalue);
    }

    /**
     * Get value of field TEXT1 as a String.
     */
    public String getTEXT1() {
        return fieldTEXT1.getString();
    }

    /**
     * Set field RENOV using a String value.
     */
    public void setRENOV(String newvalue) {
        fieldRENOV.setString(newvalue);
    }

    /**
     * Get value of field RENOV as a String.
     */
    public String getRENOV() {
        return fieldRENOV.getString();
    }

    /**
     * Set field CODCTA using a String value.
     */
    public void setCODCTA(String newvalue) {
        fieldCODCTA.setString(newvalue);
    }

    /**
     * Get value of field CODCTA as a String.
     */
    public String getCODCTA() {
        return fieldCODCTA.getString();
    }

    /**
     * Set field FECVT using a String value.
     */
    public void setFECVT(String newvalue) {
        fieldFECVT.setString(newvalue);
    }

    /**
     * Get value of field FECVT as a String.
     */
    public String getFECVT() {
        return fieldFECVT.getString();
    }

    /**
     * Set numeric field FECVT using a BigDecimal value.
     */
    public void setFECVT(BigDecimal newvalue) {
        fieldFECVT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECVT as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECVT() {
        return fieldFECVT.getBigDecimal();
    }

    /**
     * Set field SECCI using a String value.
     */
    public void setSECCI(String newvalue) {
        fieldSECCI.setString(newvalue);
    }

    /**
     * Get value of field SECCI as a String.
     */
    public String getSECCI() {
        return fieldSECCI.getString();
    }

    /**
     * Set field VIGEN using a String value.
     */
    public void setVIGEN(String newvalue) {
        fieldVIGEN.setString(newvalue);
    }

    /**
     * Get value of field VIGEN as a String.
     */
    public String getVIGEN() {
        return fieldVIGEN.getString();
    }

    /**
     * Set field CEDUL1 using a String value.
     */
    public void setCEDUL1(String newvalue) {
        fieldCEDUL1.setString(newvalue);
    }

    /**
     * Get value of field CEDUL1 as a String.
     */
    public String getCEDUL1() {
        return fieldCEDUL1.getString();
    }

    /**
     * Set field PEAUT1 using a String value.
     */
    public void setPEAUT1(String newvalue) {
        fieldPEAUT1.setString(newvalue);
    }

    /**
     * Get value of field PEAUT1 as a String.
     */
    public String getPEAUT1() {
        return fieldPEAUT1.getString();
    }

    /**
     * Set field CEDUL2 using a String value.
     */
    public void setCEDUL2(String newvalue) {
        fieldCEDUL2.setString(newvalue);
    }

    /**
     * Get value of field CEDUL2 as a String.
     */
    public String getCEDUL2() {
        return fieldCEDUL2.getString();
    }

    /**
     * Set field PEAUT2 using a String value.
     */
    public void setPEAUT2(String newvalue) {
        fieldPEAUT2.setString(newvalue);
    }

    /**
     * Get value of field PEAUT2 as a String.
     */
    public String getPEAUT2() {
        return fieldPEAUT2.getString();
    }

    /**
     * Set field CEDUL3 using a String value.
     */
    public void setCEDUL3(String newvalue) {
        fieldCEDUL3.setString(newvalue);
    }

    /**
     * Get value of field CEDUL3 as a String.
     */
    public String getCEDUL3() {
        return fieldCEDUL3.getString();
    }

    /**
     * Set field PEAUT3 using a String value.
     */
    public void setPEAUT3(String newvalue) {
        fieldPEAUT3.setString(newvalue);
    }

    /**
     * Get value of field PEAUT3 as a String.
     */
    public String getPEAUT3() {
        return fieldPEAUT3.getString();
    }

    /**
     * Set field OPC1 using a String value.
     */
    public void setOPC1(String newvalue) {
        fieldOPC1.setString(newvalue);
    }

    /**
     * Get value of field OPC1 as a String.
     */
    public String getOPC1() {
        return fieldOPC1.getString();
    }

    /**
     * Set field OPC2 using a String value.
     */
    public void setOPC2(String newvalue) {
        fieldOPC2.setString(newvalue);
    }

    /**
     * Get value of field OPC2 as a String.
     */
    public String getOPC2() {
        return fieldOPC2.getString();
    }

    /**
     * Set field TEXERR using a String value.
     */
    public void setTEXERR(String newvalue) {
        fieldTEXERR.setString(newvalue);
    }

    /**
     * Get value of field TEXERR as a String.
     */
    public String getTEXERR() {
        return fieldTEXERR.getString();
    }

    /**
     * Set field CTEI using a String value.
     */
    public void setCTEI(String newvalue) {
        fieldCTEI.setString(newvalue);
    }

    /**
     * Get value of field CTEI as a String.
     */
    public String getCTEI() {
        return fieldCTEI.getString();
    }

    /**
     * Set field NCTEI using a String value.
     */
    public void setNCTEI(String newvalue) {
        fieldNCTEI.setString(newvalue);
    }

    /**
     * Get value of field NCTEI as a String.
     */
    public String getNCTEI() {
        return fieldNCTEI.getString();
    }

    /**
     * Set field CTEP using a String value.
     */
    public void setCTEP(String newvalue) {
        fieldCTEP.setString(newvalue);
    }

    /**
     * Get value of field CTEP as a String.
     */
    public String getCTEP() {
        return fieldCTEP.getString();
    }

    /**
     * Set field NCTEP using a String value.
     */
    public void setNCTEP(String newvalue) {
        fieldNCTEP.setString(newvalue);
    }

    /**
     * Get value of field NCTEP as a String.
     */
    public String getNCTEP() {
        return fieldNCTEP.getString();
    }

    /**
     * Set field AHOI using a String value.
     */
    public void setAHOI(String newvalue) {
        fieldAHOI.setString(newvalue);
    }

    /**
     * Get value of field AHOI as a String.
     */
    public String getAHOI() {
        return fieldAHOI.getString();
    }

    /**
     * Set field NAHOI using a String value.
     */
    public void setNAHOI(String newvalue) {
        fieldNAHOI.setString(newvalue);
    }

    /**
     * Get value of field NAHOI as a String.
     */
    public String getNAHOI() {
        return fieldNAHOI.getString();
    }

    /**
     * Set field AHOP using a String value.
     */
    public void setAHOP(String newvalue) {
        fieldAHOP.setString(newvalue);
    }

    /**
     * Get value of field AHOP as a String.
     */
    public String getAHOP() {
        return fieldAHOP.getString();
    }

    /**
     * Set field NAHOP using a String value.
     */
    public void setNAHOP(String newvalue) {
        fieldNAHOP.setString(newvalue);
    }

    /**
     * Get value of field NAHOP as a String.
     */
    public String getNAHOP() {
        return fieldNAHOP.getString();
    }

    /**
     * Set field FALI using a String value.
     */
    public void setFALI(String newvalue) {
        fieldFALI.setString(newvalue);
    }

    /**
     * Get value of field FALI as a String.
     */
    public String getFALI() {
        return fieldFALI.getString();
    }

    /**
     * Set field NFALI using a String value.
     */
    public void setNFALI(String newvalue) {
        fieldNFALI.setString(newvalue);
    }

    /**
     * Get value of field NFALI as a String.
     */
    public String getNFALI() {
        return fieldNFALI.getString();
    }

    /**
     * Set field FALO using a String value.
     */
    public void setFALO(String newvalue) {
        fieldFALO.setString(newvalue);
    }

    /**
     * Get value of field FALO as a String.
     */
    public String getFALO() {
        return fieldFALO.getString();
    }

    /**
     * Set field NFALP using a String value.
     */
    public void setNFALP(String newvalue) {
        fieldNFALP.setString(newvalue);
    }

    /**
     * Get value of field NFALP as a String.
     */
    public String getNFALP() {
        return fieldNFALP.getString();
    }

    /**
     * Set field CHEI using a String value.
     */
    public void setCHEI(String newvalue) {
        fieldCHEI.setString(newvalue);
    }

    /**
     * Get value of field CHEI as a String.
     */
    public String getCHEI() {
        return fieldCHEI.getString();
    }

    /**
     * Set field CHEP using a String value.
     */
    public void setCHEP(String newvalue) {
        fieldCHEP.setString(newvalue);
    }

    /**
     * Get value of field CHEP as a String.
     */
    public String getCHEP() {
        return fieldCHEP.getString();
    }

    /**
     * Set field REII using a String value.
     */
    public void setREII(String newvalue) {
        fieldREII.setString(newvalue);
    }

    /**
     * Get value of field REII as a String.
     */
    public String getREII() {
        return fieldREII.getString();
    }

    /**
     * Set field REIP using a String value.
     */
    public void setREIP(String newvalue) {
        fieldREIP.setString(newvalue);
    }

    /**
     * Get value of field REIP as a String.
     */
    public String getREIP() {
        return fieldREIP.getString();
    }

    /**
     * Set field DATGA1 using a String value.
     */
    public void setDATGA1(String newvalue) {
        fieldDATGA1.setString(newvalue);
    }

    /**
     * Get value of field DATGA1 as a String.
     */
    public String getDATGA1() {
        return fieldDATGA1.getString();
    }

    /**
     * Set numeric field DATGA1 using a BigDecimal value.
     */
    public void setDATGA1(BigDecimal newvalue) {
        fieldDATGA1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATGA1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATGA1() {
        return fieldDATGA1.getBigDecimal();
    }

    /**
     * Set field DATGA2 using a String value.
     */
    public void setDATGA2(String newvalue) {
        fieldDATGA2.setString(newvalue);
    }

    /**
     * Get value of field DATGA2 as a String.
     */
    public String getDATGA2() {
        return fieldDATGA2.getString();
    }

    /**
     * Set numeric field DATGA2 using a BigDecimal value.
     */
    public void setDATGA2(BigDecimal newvalue) {
        fieldDATGA2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATGA2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATGA2() {
        return fieldDATGA2.getBigDecimal();
    }

    /**
     * Set field COMAPO using a String value.
     */
    public void setCOMAPO(String newvalue) {
        fieldCOMAPO.setString(newvalue);
    }

    /**
     * Get value of field COMAPO as a String.
     */
    public String getCOMAPO() {
        return fieldCOMAPO.getString();
    }

    /**
     * Set numeric field COMAPO using a BigDecimal value.
     */
    public void setCOMAPO(BigDecimal newvalue) {
        fieldCOMAPO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMAPO as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMAPO() {
        return fieldCOMAPO.getBigDecimal();
    }

    /**
     * Set field ICOAPO using a String value.
     */
    public void setICOAPO(String newvalue) {
        fieldICOAPO.setString(newvalue);
    }

    /**
     * Get value of field ICOAPO as a String.
     */
    public String getICOAPO() {
        return fieldICOAPO.getString();
    }

    /**
     * Set numeric field ICOAPO using a BigDecimal value.
     */
    public void setICOAPO(BigDecimal newvalue) {
        fieldICOAPO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field ICOAPO as a BigDecimal.
     */
    public BigDecimal getBigDecimalICOAPO() {
        return fieldICOAPO.getBigDecimal();
    }

    /**
     * Set field COMRET using a String value.
     */
    public void setCOMRET(String newvalue) {
        fieldCOMRET.setString(newvalue);
    }

    /**
     * Get value of field COMRET as a String.
     */
    public String getCOMRET() {
        return fieldCOMRET.getString();
    }

    /**
     * Set numeric field COMRET using a BigDecimal value.
     */
    public void setCOMRET(BigDecimal newvalue) {
        fieldCOMRET.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMRET as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMRET() {
        return fieldCOMRET.getBigDecimal();
    }

    /**
     * Set field ICORET using a String value.
     */
    public void setICORET(String newvalue) {
        fieldICORET.setString(newvalue);
    }

    /**
     * Get value of field ICORET as a String.
     */
    public String getICORET() {
        return fieldICORET.getString();
    }

    /**
     * Set numeric field ICORET using a BigDecimal value.
     */
    public void setICORET(BigDecimal newvalue) {
        fieldICORET.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field ICORET as a BigDecimal.
     */
    public BigDecimal getBigDecimalICORET() {
        return fieldICORET.getBigDecimal();
    }

    /**
     * Set field COMFIN using a String value.
     */
    public void setCOMFIN(String newvalue) {
        fieldCOMFIN.setString(newvalue);
    }

    /**
     * Get value of field COMFIN as a String.
     */
    public String getCOMFIN() {
        return fieldCOMFIN.getString();
    }

    /**
     * Set numeric field COMFIN using a BigDecimal value.
     */
    public void setCOMFIN(BigDecimal newvalue) {
        fieldCOMFIN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMFIN as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMFIN() {
        return fieldCOMFIN.getBigDecimal();
    }

    /**
     * Set field ICOFIN using a String value.
     */
    public void setICOFIN(String newvalue) {
        fieldICOFIN.setString(newvalue);
    }

    /**
     * Get value of field ICOFIN as a String.
     */
    public String getICOFIN() {
        return fieldICOFIN.getString();
    }

    /**
     * Set numeric field ICOFIN using a BigDecimal value.
     */
    public void setICOFIN(BigDecimal newvalue) {
        fieldICOFIN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field ICOFIN as a BigDecimal.
     */
    public BigDecimal getBigDecimalICOFIN() {
        return fieldICOFIN.getBigDecimal();
    }

    /**
     * Set field GESCOD using a String value.
     */
    public void setGESCOD(String newvalue) {
        fieldGESCOD.setString(newvalue);
    }

    /**
     * Get value of field GESCOD as a String.
     */
    public String getGESCOD() {
        return fieldGESCOD.getString();
    }

    /**
     * Set numeric field GESCOD using a BigDecimal value.
     */
    public void setGESCOD(BigDecimal newvalue) {
        fieldGESCOD.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field GESCOD as a BigDecimal.
     */
    public BigDecimal getBigDecimalGESCOD() {
        return fieldGESCOD.getBigDecimal();
    }

    /**
     * Set field NGESCOD using a String value.
     */
    public void setNGESCOD(String newvalue) {
        fieldNGESCOD.setString(newvalue);
    }

    /**
     * Get value of field NGESCOD as a String.
     */
    public String getNGESCOD() {
        return fieldNGESCOD.getString();
    }

    /**
     * Set field COAUT1 using a String value.
     */
    public void setCOAUT1(String newvalue) {
        fieldCOAUT1.setString(newvalue);
    }

    /**
     * Get value of field COAUT1 as a String.
     */
    public String getCOAUT1() {
        return fieldCOAUT1.getString();
    }

    /**
     * Set field NCOAUT1 using a String value.
     */
    public void setNCOAUT1(String newvalue) {
        fieldNCOAUT1.setString(newvalue);
    }

    /**
     * Get value of field NCOAUT1 as a String.
     */
    public String getNCOAUT1() {
        return fieldNCOAUT1.getString();
    }

    /**
     * Set field BENE1 using a String value.
     */
    public void setBENE1(String newvalue) {
        fieldBENE1.setString(newvalue);
    }

    /**
     * Get value of field BENE1 as a String.
     */
    public String getBENE1() {
        return fieldBENE1.getString();
    }

    /**
     * Set field ECBEN1 using a String value.
     */
    public void setECBEN1(String newvalue) {
        fieldECBEN1.setString(newvalue);
    }

    /**
     * Get value of field ECBEN1 as a String.
     */
    public String getECBEN1() {
        return fieldECBEN1.getString();
    }

    /**
     * Set field NABEN1 using a String value.
     */
    public void setNABEN1(String newvalue) {
        fieldNABEN1.setString(newvalue);
    }

    /**
     * Get value of field NABEN1 as a String.
     */
    public String getNABEN1() {
        return fieldNABEN1.getString();
    }

    /**
     * Set numeric field NABEN1 using a BigDecimal value.
     */
    public void setNABEN1(BigDecimal newvalue) {
        fieldNABEN1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NABEN1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalNABEN1() {
        return fieldNABEN1.getBigDecimal();
    }

    /**
     * Set field PRBEN1 using a String value.
     */
    public void setPRBEN1(String newvalue) {
        fieldPRBEN1.setString(newvalue);
    }

    /**
     * Get value of field PRBEN1 as a String.
     */
    public String getPRBEN1() {
        return fieldPRBEN1.getString();
    }

    /**
     * Set field POBEN1 using a String value.
     */
    public void setPOBEN1(String newvalue) {
        fieldPOBEN1.setString(newvalue);
    }

    /**
     * Get value of field POBEN1 as a String.
     */
    public String getPOBEN1() {
        return fieldPOBEN1.getString();
    }

    /**
     * Set field CEBEN1 using a String value.
     */
    public void setCEBEN1(String newvalue) {
        fieldCEBEN1.setString(newvalue);
    }

    /**
     * Get value of field CEBEN1 as a String.
     */
    public String getCEBEN1() {
        return fieldCEBEN1.getString();
    }

    /**
     * Set field BENE2 using a String value.
     */
    public void setBENE2(String newvalue) {
        fieldBENE2.setString(newvalue);
    }

    /**
     * Get value of field BENE2 as a String.
     */
    public String getBENE2() {
        return fieldBENE2.getString();
    }

    /**
     * Set field ECBEN2 using a String value.
     */
    public void setECBEN2(String newvalue) {
        fieldECBEN2.setString(newvalue);
    }

    /**
     * Get value of field ECBEN2 as a String.
     */
    public String getECBEN2() {
        return fieldECBEN2.getString();
    }

    /**
     * Set field NABEN2 using a String value.
     */
    public void setNABEN2(String newvalue) {
        fieldNABEN2.setString(newvalue);
    }

    /**
     * Get value of field NABEN2 as a String.
     */
    public String getNABEN2() {
        return fieldNABEN2.getString();
    }

    /**
     * Set numeric field NABEN2 using a BigDecimal value.
     */
    public void setNABEN2(BigDecimal newvalue) {
        fieldNABEN2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NABEN2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalNABEN2() {
        return fieldNABEN2.getBigDecimal();
    }

    /**
     * Set field PRBEN2 using a String value.
     */
    public void setPRBEN2(String newvalue) {
        fieldPRBEN2.setString(newvalue);
    }

    /**
     * Get value of field PRBEN2 as a String.
     */
    public String getPRBEN2() {
        return fieldPRBEN2.getString();
    }

    /**
     * Set field POBEN2 using a String value.
     */
    public void setPOBEN2(String newvalue) {
        fieldPOBEN2.setString(newvalue);
    }

    /**
     * Get value of field POBEN2 as a String.
     */
    public String getPOBEN2() {
        return fieldPOBEN2.getString();
    }

    /**
     * Set field CEBEN2 using a String value.
     */
    public void setCEBEN2(String newvalue) {
        fieldCEBEN2.setString(newvalue);
    }

    /**
     * Get value of field CEBEN2 as a String.
     */
    public String getCEBEN2() {
        return fieldCEBEN2.getString();
    }

    /**
     * Set field BENE3 using a String value.
     */
    public void setBENE3(String newvalue) {
        fieldBENE3.setString(newvalue);
    }

    /**
     * Get value of field BENE3 as a String.
     */
    public String getBENE3() {
        return fieldBENE3.getString();
    }

    /**
     * Set field ECBEN3 using a String value.
     */
    public void setECBEN3(String newvalue) {
        fieldECBEN3.setString(newvalue);
    }

    /**
     * Get value of field ECBEN3 as a String.
     */
    public String getECBEN3() {
        return fieldECBEN3.getString();
    }

    /**
     * Set field NABEN3 using a String value.
     */
    public void setNABEN3(String newvalue) {
        fieldNABEN3.setString(newvalue);
    }

    /**
     * Get value of field NABEN3 as a String.
     */
    public String getNABEN3() {
        return fieldNABEN3.getString();
    }

    /**
     * Set numeric field NABEN3 using a BigDecimal value.
     */
    public void setNABEN3(BigDecimal newvalue) {
        fieldNABEN3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NABEN3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalNABEN3() {
        return fieldNABEN3.getBigDecimal();
    }

    /**
     * Set field PRBEN3 using a String value.
     */
    public void setPRBEN3(String newvalue) {
        fieldPRBEN3.setString(newvalue);
    }

    /**
     * Get value of field PRBEN3 as a String.
     */
    public String getPRBEN3() {
        return fieldPRBEN3.getString();
    }

    /**
     * Set field POBEN3 using a String value.
     */
    public void setPOBEN3(String newvalue) {
        fieldPOBEN3.setString(newvalue);
    }

    /**
     * Get value of field POBEN3 as a String.
     */
    public String getPOBEN3() {
        return fieldPOBEN3.getString();
    }

    /**
     * Set field CEBEN3 using a String value.
     */
    public void setCEBEN3(String newvalue) {
        fieldCEBEN3.setString(newvalue);
    }

    /**
     * Get value of field CEBEN3 as a String.
     */
    public String getCEBEN3() {
        return fieldCEBEN3.getString();
    }

    /**
     * Set field TOMRE1 using a String value.
     */
    public void setTOMRE1(String newvalue) {
        fieldTOMRE1.setString(newvalue);
    }

    /**
     * Get value of field TOMRE1 as a String.
     */
    public String getTOMRE1() {
        return fieldTOMRE1.getString();
    }

    /**
     * Set field FOLRE1 using a String value.
     */
    public void setFOLRE1(String newvalue) {
        fieldFOLRE1.setString(newvalue);
    }

    /**
     * Get value of field FOLRE1 as a String.
     */
    public String getFOLRE1() {
        return fieldFOLRE1.getString();
    }

    /**
     * Set field ASIRE1 using a String value.
     */
    public void setASIRE1(String newvalue) {
        fieldASIRE1.setString(newvalue);
    }

    /**
     * Get value of field ASIRE1 as a String.
     */
    public String getASIRE1() {
        return fieldASIRE1.getString();
    }

    /**
     * Set field FECPR1 using a String value.
     */
    public void setFECPR1(String newvalue) {
        fieldFECPR1.setString(newvalue);
    }

    /**
     * Get value of field FECPR1 as a String.
     */
    public String getFECPR1() {
        return fieldFECPR1.getString();
    }

    /**
     * Set numeric field FECPR1 using a BigDecimal value.
     */
    public void setFECPR1(BigDecimal newvalue) {
        fieldFECPR1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECPR1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECPR1() {
        return fieldFECPR1.getBigDecimal();
    }

    /**
     * Set field FECEJ1 using a String value.
     */
    public void setFECEJ1(String newvalue) {
        fieldFECEJ1.setString(newvalue);
    }

    /**
     * Get value of field FECEJ1 as a String.
     */
    public String getFECEJ1() {
        return fieldFECEJ1.getString();
    }

    /**
     * Set numeric field FECEJ1 using a BigDecimal value.
     */
    public void setFECEJ1(BigDecimal newvalue) {
        fieldFECEJ1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECEJ1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECEJ1() {
        return fieldFECEJ1.getBigDecimal();
    }

    /**
     * Set field OBJ1 using a String value.
     */
    public void setOBJ1(String newvalue) {
        fieldOBJ1.setString(newvalue);
    }

    /**
     * Get value of field OBJ1 as a String.
     */
    public String getOBJ1() {
        return fieldOBJ1.getString();
    }

    /**
     * Set field OBJ2 using a String value.
     */
    public void setOBJ2(String newvalue) {
        fieldOBJ2.setString(newvalue);
    }

    /**
     * Get value of field OBJ2 as a String.
     */
    public String getOBJ2() {
        return fieldOBJ2.getString();
    }

    /**
     * Set field OBJ3 using a String value.
     */
    public void setOBJ3(String newvalue) {
        fieldOBJ3.setString(newvalue);
    }

    /**
     * Get value of field OBJ3 as a String.
     */
    public String getOBJ3() {
        return fieldOBJ3.getString();
    }

    /**
     * Set field OBJ5 using a String value.
     */
    public void setOBJ5(String newvalue) {
        fieldOBJ5.setString(newvalue);
    }

    /**
     * Get value of field OBJ5 as a String.
     */
    public String getOBJ5() {
        return fieldOBJ5.getString();
    }

    /**
     * Set field OBJ4 using a String value.
     */
    public void setOBJ4(String newvalue) {
        fieldOBJ4.setString(newvalue);
    }

    /**
     * Get value of field OBJ4 as a String.
     */
    public String getOBJ4() {
        return fieldOBJ4.getString();
    }

    /**
     * Set field NROPRO using a String value.
     */
    public void setNROPRO(String newvalue) {
        fieldNROPRO.setString(newvalue);
    }

    /**
     * Get value of field NROPRO as a String.
     */
    public String getNROPRO() {
        return fieldNROPRO.getString();
    }

    /**
     * Set field CUEN1 using a String value.
     */
    public void setCUEN1(String newvalue) {
        fieldCUEN1.setString(newvalue);
    }

    /**
     * Get value of field CUEN1 as a String.
     */
    public String getCUEN1() {
        return fieldCUEN1.getString();
    }

    /**
     * Set field CUEN2 using a String value.
     */
    public void setCUEN2(String newvalue) {
        fieldCUEN2.setString(newvalue);
    }

    /**
     * Get value of field CUEN2 as a String.
     */
    public String getCUEN2() {
        return fieldCUEN2.getString();
    }

    /**
     * Set field CUEN3 using a String value.
     */
    public void setCUEN3(String newvalue) {
        fieldCUEN3.setString(newvalue);
    }

    /**
     * Get value of field CUEN3 as a String.
     */
    public String getCUEN3() {
        return fieldCUEN3.getString();
    }

}
