package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from FLUCAJCFM physical file
 * definition.
 * 
* File level identifier is 1140202180025. Record format level identifier is
 * 474D491E6B3E6.
 */
public class FLUCAJCFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "CUR",
        "FIDE",
        "CODFID",
        "CLIENT",
        "RIFCLI",
        "NOMBAN",
        "SFSEL",
        "SFTIP",
        "SFCON",
        "SFNRO",
        "NRR",
        "NOMBRE",
        "TIPO",
        "NOMCON",
        "ORDEN",
        "FLSSWFT"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "CUR",
        "FIDE",
        "CODFID",
        "CLIENT",
        "RIFCLI",
        "NOMBAN",
        "SFSEL",
        "SFTIP",
        "SFCON",
        "SFNRO",
        "NRR",
        "NOMBRE",
        "TIPO",
        "NOMCON",
        "ORDEN",
        "FLSSWFT"
    };
    final static String fid = "1140202180025";
    final static String rid = "474D491E6B3E6";
    final static String fmtname = "FLUCAJCFM";
    final int FIELDCOUNT = 27;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldCUR = null;
    private CharacterField fieldFIDE = null;
    private CharacterField fieldCODFID = null;
    private DecimalField fieldCLIENT = null;
    private CharacterField fieldRIFCLI = null;
    private CharacterField fieldNOMBAN = null;
    private CharacterField fieldSFSEL = null;
    private CharacterField fieldSFTIP = null;
    private CharacterField fieldSFCON = null;
    private DecimalField fieldSFNRO = null;
    private DecimalField fieldNRR = null;
    private CharacterField fieldNOMBRE = null;
    private CharacterField fieldTIPO = null;
    private CharacterField fieldNOMCON = null;
    private DecimalField fieldORDEN = null;
    private CharacterField fieldFLSSWFT = null;

    /**
     * Constructor for FLUCAJCFMMessage.
     */
    public FLUCAJCFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 367;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 171, 10, "CAMCUR");
        fields[11] = fieldCUR
                = new DecimalField(message, HEADERSIZE + 181, 5, 0, "CUR");
        fields[12] = fieldFIDE
                = new CharacterField(message, HEADERSIZE + 186, 35, "FIDE");
        fields[13] = fieldCODFID
                = new CharacterField(message, HEADERSIZE + 221, 4, "CODFID");
        fields[14] = fieldCLIENT
                = new DecimalField(message, HEADERSIZE + 225, 8, 0, "CLIENT");
        fields[15] = fieldRIFCLI
                = new CharacterField(message, HEADERSIZE + 233, 12, "RIFCLI");
        fields[16] = fieldNOMBAN
                = new CharacterField(message, HEADERSIZE + 245, 15, "NOMBAN");
        fields[17] = fieldSFSEL
                = new CharacterField(message, HEADERSIZE + 260, 1, "SFSEL");
        fields[18] = fieldSFTIP
                = new CharacterField(message, HEADERSIZE + 261, 1, "SFTIP");
        fields[19] = fieldSFCON
                = new CharacterField(message, HEADERSIZE + 262, 30, "SFCON");
        fields[20] = fieldSFNRO
                = new DecimalField(message, HEADERSIZE + 292, 4, 0, "SFNRO");
        fields[21] = fieldNRR
                = new DecimalField(message, HEADERSIZE + 296, 5, 0, "NRR");
        fields[22] = fieldNOMBRE
                = new CharacterField(message, HEADERSIZE + 301, 30, "NOMBRE");
        fields[23] = fieldTIPO
                = new CharacterField(message, HEADERSIZE + 331, 1, "TIPO");
        fields[24] = fieldNOMCON
                = new CharacterField(message, HEADERSIZE + 332, 30, "NOMCON");
        fields[25] = fieldORDEN
                = new DecimalField(message, HEADERSIZE + 362, 4, 0, "ORDEN");
        fields[26] = fieldFLSSWFT
                = new CharacterField(message, HEADERSIZE + 366, 1, "FLSSWFT");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field CUR using a String value.
     */
    public void setCUR(String newvalue) {
        fieldCUR.setString(newvalue);
    }

    /**
     * Get value of field CUR as a String.
     */
    public String getCUR() {
        return fieldCUR.getString();
    }

    /**
     * Set numeric field CUR using a BigDecimal value.
     */
    public void setCUR(BigDecimal newvalue) {
        fieldCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalCUR() {
        return fieldCUR.getBigDecimal();
    }

    /**
     * Set field FIDE using a String value.
     */
    public void setFIDE(String newvalue) {
        fieldFIDE.setString(newvalue);
    }

    /**
     * Get value of field FIDE as a String.
     */
    public String getFIDE() {
        return fieldFIDE.getString();
    }

    /**
     * Set field CODFID using a String value.
     */
    public void setCODFID(String newvalue) {
        fieldCODFID.setString(newvalue);
    }

    /**
     * Get value of field CODFID as a String.
     */
    public String getCODFID() {
        return fieldCODFID.getString();
    }

    /**
     * Set field CLIENT using a String value.
     */
    public void setCLIENT(String newvalue) {
        fieldCLIENT.setString(newvalue);
    }

    /**
     * Get value of field CLIENT as a String.
     */
    public String getCLIENT() {
        return fieldCLIENT.getString();
    }

    /**
     * Set numeric field CLIENT using a BigDecimal value.
     */
    public void setCLIENT(BigDecimal newvalue) {
        fieldCLIENT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLIENT as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLIENT() {
        return fieldCLIENT.getBigDecimal();
    }

    /**
     * Set field RIFCLI using a String value.
     */
    public void setRIFCLI(String newvalue) {
        fieldRIFCLI.setString(newvalue);
    }

    /**
     * Get value of field RIFCLI as a String.
     */
    public String getRIFCLI() {
        return fieldRIFCLI.getString();
    }

    /**
     * Set field NOMBAN using a String value.
     */
    public void setNOMBAN(String newvalue) {
        fieldNOMBAN.setString(newvalue);
    }

    /**
     * Get value of field NOMBAN as a String.
     */
    public String getNOMBAN() {
        return fieldNOMBAN.getString();
    }

    /**
     * Set field SFSEL using a String value.
     */
    public void setSFSEL(String newvalue) {
        fieldSFSEL.setString(newvalue);
    }

    /**
     * Get value of field SFSEL as a String.
     */
    public String getSFSEL() {
        return fieldSFSEL.getString();
    }

    /**
     * Set field SFTIP using a String value.
     */
    public void setSFTIP(String newvalue) {
        fieldSFTIP.setString(newvalue);
    }

    /**
     * Get value of field SFTIP as a String.
     */
    public String getSFTIP() {
        return fieldSFTIP.getString();
    }

    /**
     * Set field SFCON using a String value.
     */
    public void setSFCON(String newvalue) {
        fieldSFCON.setString(newvalue);
    }

    /**
     * Get value of field SFCON as a String.
     */
    public String getSFCON() {
        return fieldSFCON.getString();
    }

    /**
     * Set field SFNRO using a String value.
     */
    public void setSFNRO(String newvalue) {
        fieldSFNRO.setString(newvalue);
    }

    /**
     * Get value of field SFNRO as a String.
     */
    public String getSFNRO() {
        return fieldSFNRO.getString();
    }

    /**
     * Set numeric field SFNRO using a BigDecimal value.
     */
    public void setSFNRO(BigDecimal newvalue) {
        fieldSFNRO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SFNRO as a BigDecimal.
     */
    public BigDecimal getBigDecimalSFNRO() {
        return fieldSFNRO.getBigDecimal();
    }

    /**
     * Set field NRR using a String value.
     */
    public void setNRR(String newvalue) {
        fieldNRR.setString(newvalue);
    }

    /**
     * Get value of field NRR as a String.
     */
    public String getNRR() {
        return fieldNRR.getString();
    }

    /**
     * Set numeric field NRR using a BigDecimal value.
     */
    public void setNRR(BigDecimal newvalue) {
        fieldNRR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NRR as a BigDecimal.
     */
    public BigDecimal getBigDecimalNRR() {
        return fieldNRR.getBigDecimal();
    }

    /**
     * Set field NOMBRE using a String value.
     */
    public void setNOMBRE(String newvalue) {
        fieldNOMBRE.setString(newvalue);
    }

    /**
     * Get value of field NOMBRE as a String.
     */
    public String getNOMBRE() {
        return fieldNOMBRE.getString();
    }

    /**
     * Set field TIPO using a String value.
     */
    public void setTIPO(String newvalue) {
        fieldTIPO.setString(newvalue);
    }

    /**
     * Get value of field TIPO as a String.
     */
    public String getTIPO() {
        return fieldTIPO.getString();
    }

    /**
     * Set field NOMCON using a String value.
     */
    public void setNOMCON(String newvalue) {
        fieldNOMCON.setString(newvalue);
    }

    /**
     * Get value of field NOMCON as a String.
     */
    public String getNOMCON() {
        return fieldNOMCON.getString();
    }

    /**
     * Set field ORDEN using a String value.
     */
    public void setORDEN(String newvalue) {
        fieldORDEN.setString(newvalue);
    }

    /**
     * Get value of field ORDEN as a String.
     */
    public String getORDEN() {
        return fieldORDEN.getString();
    }

    /**
     * Set numeric field ORDEN using a BigDecimal value.
     */
    public void setORDEN(BigDecimal newvalue) {
        fieldORDEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field ORDEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalORDEN() {
        return fieldORDEN.getBigDecimal();
    }

    /**
     * Set field FLSSWFT using a String value.
     */
    public void setFLSSWFT(String newvalue) {
        fieldFLSSWFT.setString(newvalue);
    }

    /**
     * Get value of field FLSSWFT as a String.
     */
    public String getFLSSWFT() {
        return fieldFLSSWFT.getString();
    }

}
