package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from FLUCAJGFM physical file
 * definition.
 * 
* File level identifier is 1140213200904. Record format level identifier is
 * 44EDC12033260.
 */
public class FLUCAJGFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "CUR",
        "CODFID",
        "FIDEP",
        "FECIN",
        "CLIENT",
        "RIFCLI",
        "NOMBAN",
        "SFCOD",
        "SFCLO",
        "SFCOP",
        "SFTIP",
        "IMPO1",
        "IMPO2",
        "IMPO3",
        "NRR",
        "NOMBRE",
        "ENCA1",
        "ENCA2",
        "ENCA3",
        "FECS1",
        "FECS2",
        "FECS3",
        "SALA1",
        "SALA2",
        "SALA3",
        "MOTN1",
        "MOTN2",
        "MOTN3",
        "MOVN1",
        "MOVN2",
        "MOVN3",
        "SATA1",
        "SATA2",
        "SATA3",
        "INVAL",
        "INVTO",
        "INTAS",
        "INNOM",
        "ININT",
        "INTOT",
        "NRI",
        "FECINV"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "CUR",
        "CODFID",
        "FIDEP",
        "FECIN",
        "CLIENT",
        "RIFCLI",
        "NOMBAN",
        "SFCOD",
        "SFCLO",
        "SFCOP",
        "SFTIP",
        "IMPO1",
        "IMPO2",
        "IMPO3",
        "NRR",
        "NOMBRE",
        "ENCA1",
        "ENCA2",
        "ENCA3",
        "FECS1",
        "FECS2",
        "FECS3",
        "SALA1",
        "SALA2",
        "SALA3",
        "MOTN1",
        "MOTN2",
        "MOTN3",
        "MOVN1",
        "MOVN2",
        "MOVN3",
        "SATA1",
        "SATA2",
        "SATA3",
        "INVAL",
        "INVTO",
        "INTAS",
        "INNOM",
        "ININT",
        "INTOT",
        "NRI",
        "FECINV"
    };
    final static String fid = "1140213200904";
    final static String rid = "44EDC12033260";
    final static String fmtname = "FLUCAJGFM";
    final int FIELDCOUNT = 53;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldCUR = null;
    private CharacterField fieldCODFID = null;
    private CharacterField fieldFIDEP = null;
    private DecimalField fieldFECIN = null;
    private DecimalField fieldCLIENT = null;
    private CharacterField fieldRIFCLI = null;
    private CharacterField fieldNOMBAN = null;
    private DecimalField fieldSFCOD = null;
    private DecimalField fieldSFCLO = null;
    private CharacterField fieldSFCOP = null;
    private CharacterField fieldSFTIP = null;
    private DecimalField fieldIMPO1 = null;
    private DecimalField fieldIMPO2 = null;
    private DecimalField fieldIMPO3 = null;
    private DecimalField fieldNRR = null;
    private CharacterField fieldNOMBRE = null;
    private DecimalField fieldENCA1 = null;
    private DecimalField fieldENCA2 = null;
    private DecimalField fieldENCA3 = null;
    private DecimalField fieldFECS1 = null;
    private DecimalField fieldFECS2 = null;
    private DecimalField fieldFECS3 = null;
    private DecimalField fieldSALA1 = null;
    private DecimalField fieldSALA2 = null;
    private DecimalField fieldSALA3 = null;
    private DecimalField fieldMOTN1 = null;
    private DecimalField fieldMOTN2 = null;
    private DecimalField fieldMOTN3 = null;
    private DecimalField fieldMOVN1 = null;
    private DecimalField fieldMOVN2 = null;
    private DecimalField fieldMOVN3 = null;
    private DecimalField fieldSATA1 = null;
    private DecimalField fieldSATA2 = null;
    private DecimalField fieldSATA3 = null;
    private CharacterField fieldINVAL = null;
    private DecimalField fieldINVTO = null;
    private DecimalField fieldINTAS = null;
    private DecimalField fieldINNOM = null;
    private DecimalField fieldININT = null;
    private DecimalField fieldINTOT = null;
    private DecimalField fieldNRI = null;
    private DecimalField fieldFECINV = null;

    /**
     * Constructor for FLUCAJGFMMessage.
     */
    public FLUCAJGFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 703;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 171, 10, "CAMCUR");
        fields[11] = fieldCUR
                = new DecimalField(message, HEADERSIZE + 181, 5, 0, "CUR");
        fields[12] = fieldCODFID
                = new CharacterField(message, HEADERSIZE + 186, 4, "CODFID");
        fields[13] = fieldFIDEP
                = new CharacterField(message, HEADERSIZE + 190, 35, "FIDEP");
        fields[14] = fieldFECIN
                = new DecimalField(message, HEADERSIZE + 225, 7, 0, "FECIN");
        fields[15] = fieldCLIENT
                = new DecimalField(message, HEADERSIZE + 232, 8, 0, "CLIENT");
        fields[16] = fieldRIFCLI
                = new CharacterField(message, HEADERSIZE + 240, 12, "RIFCLI");
        fields[17] = fieldNOMBAN
                = new CharacterField(message, HEADERSIZE + 252, 15, "NOMBAN");
        fields[18] = fieldSFCOD
                = new DecimalField(message, HEADERSIZE + 267, 4, 0, "SFCOD");
        fields[19] = fieldSFCLO
                = new DecimalField(message, HEADERSIZE + 271, 8, 0, "SFCLO");
        fields[20] = fieldSFCOP
                = new CharacterField(message, HEADERSIZE + 279, 20, "SFCOP");
        fields[21] = fieldSFTIP
                = new CharacterField(message, HEADERSIZE + 299, 1, "SFTIP");
        fields[22] = fieldIMPO1
                = new DecimalField(message, HEADERSIZE + 300, 15, 2, "IMPO1");
        fields[23] = fieldIMPO2
                = new DecimalField(message, HEADERSIZE + 315, 15, 2, "IMPO2");
        fields[24] = fieldIMPO3
                = new DecimalField(message, HEADERSIZE + 330, 15, 2, "IMPO3");
        fields[25] = fieldNRR
                = new DecimalField(message, HEADERSIZE + 345, 5, 0, "NRR");
        fields[26] = fieldNOMBRE
                = new CharacterField(message, HEADERSIZE + 350, 30, "NOMBRE");
        fields[27] = fieldENCA1
                = new DecimalField(message, HEADERSIZE + 380, 15, 2, "ENCA1");
        fields[28] = fieldENCA2
                = new DecimalField(message, HEADERSIZE + 395, 15, 2, "ENCA2");
        fields[29] = fieldENCA3
                = new DecimalField(message, HEADERSIZE + 410, 15, 2, "ENCA3");
        fields[30] = fieldFECS1
                = new DecimalField(message, HEADERSIZE + 425, 7, 0, "FECS1");
        fields[31] = fieldFECS2
                = new DecimalField(message, HEADERSIZE + 432, 7, 0, "FECS2");
        fields[32] = fieldFECS3
                = new DecimalField(message, HEADERSIZE + 439, 7, 0, "FECS3");
        fields[33] = fieldSALA1
                = new DecimalField(message, HEADERSIZE + 446, 15, 2, "SALA1");
        fields[34] = fieldSALA2
                = new DecimalField(message, HEADERSIZE + 461, 15, 2, "SALA2");
        fields[35] = fieldSALA3
                = new DecimalField(message, HEADERSIZE + 476, 15, 2, "SALA3");
        fields[36] = fieldMOTN1
                = new DecimalField(message, HEADERSIZE + 491, 15, 2, "MOTN1");
        fields[37] = fieldMOTN2
                = new DecimalField(message, HEADERSIZE + 506, 15, 2, "MOTN2");
        fields[38] = fieldMOTN3
                = new DecimalField(message, HEADERSIZE + 521, 15, 2, "MOTN3");
        fields[39] = fieldMOVN1
                = new DecimalField(message, HEADERSIZE + 536, 15, 2, "MOVN1");
        fields[40] = fieldMOVN2
                = new DecimalField(message, HEADERSIZE + 551, 15, 2, "MOVN2");
        fields[41] = fieldMOVN3
                = new DecimalField(message, HEADERSIZE + 566, 15, 2, "MOVN3");
        fields[42] = fieldSATA1
                = new DecimalField(message, HEADERSIZE + 581, 15, 2, "SATA1");
        fields[43] = fieldSATA2
                = new DecimalField(message, HEADERSIZE + 596, 15, 2, "SATA2");
        fields[44] = fieldSATA3
                = new DecimalField(message, HEADERSIZE + 611, 15, 2, "SATA3");
        fields[45] = fieldINVAL
                = new CharacterField(message, HEADERSIZE + 626, 8, "INVAL");
        fields[46] = fieldINVTO
                = new DecimalField(message, HEADERSIZE + 634, 7, 0, "INVTO");
        fields[47] = fieldINTAS
                = new DecimalField(message, HEADERSIZE + 641, 6, 2, "INTAS");
        fields[48] = fieldINNOM
                = new DecimalField(message, HEADERSIZE + 647, 15, 2, "INNOM");
        fields[49] = fieldININT
                = new DecimalField(message, HEADERSIZE + 662, 14, 2, "ININT");
        fields[50] = fieldINTOT
                = new DecimalField(message, HEADERSIZE + 676, 15, 2, "INTOT");
        fields[51] = fieldNRI
                = new DecimalField(message, HEADERSIZE + 691, 5, 0, "NRI");
        fields[52] = fieldFECINV
                = new DecimalField(message, HEADERSIZE + 696, 7, 0, "FECINV");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field CUR using a String value.
     */
    public void setCUR(String newvalue) {
        fieldCUR.setString(newvalue);
    }

    /**
     * Get value of field CUR as a String.
     */
    public String getCUR() {
        return fieldCUR.getString();
    }

    /**
     * Set numeric field CUR using a BigDecimal value.
     */
    public void setCUR(BigDecimal newvalue) {
        fieldCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalCUR() {
        return fieldCUR.getBigDecimal();
    }

    /**
     * Set field CODFID using a String value.
     */
    public void setCODFID(String newvalue) {
        fieldCODFID.setString(newvalue);
    }

    /**
     * Get value of field CODFID as a String.
     */
    public String getCODFID() {
        return fieldCODFID.getString();
    }

    /**
     * Set field FIDEP using a String value.
     */
    public void setFIDEP(String newvalue) {
        fieldFIDEP.setString(newvalue);
    }

    /**
     * Get value of field FIDEP as a String.
     */
    public String getFIDEP() {
        return fieldFIDEP.getString();
    }

    /**
     * Set field FECIN using a String value.
     */
    public void setFECIN(String newvalue) {
        fieldFECIN.setString(newvalue);
    }

    /**
     * Get value of field FECIN as a String.
     */
    public String getFECIN() {
        return fieldFECIN.getString();
    }

    /**
     * Set numeric field FECIN using a BigDecimal value.
     */
    public void setFECIN(BigDecimal newvalue) {
        fieldFECIN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECIN as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECIN() {
        return fieldFECIN.getBigDecimal();
    }

    /**
     * Set field CLIENT using a String value.
     */
    public void setCLIENT(String newvalue) {
        fieldCLIENT.setString(newvalue);
    }

    /**
     * Get value of field CLIENT as a String.
     */
    public String getCLIENT() {
        return fieldCLIENT.getString();
    }

    /**
     * Set numeric field CLIENT using a BigDecimal value.
     */
    public void setCLIENT(BigDecimal newvalue) {
        fieldCLIENT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLIENT as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLIENT() {
        return fieldCLIENT.getBigDecimal();
    }

    /**
     * Set field RIFCLI using a String value.
     */
    public void setRIFCLI(String newvalue) {
        fieldRIFCLI.setString(newvalue);
    }

    /**
     * Get value of field RIFCLI as a String.
     */
    public String getRIFCLI() {
        return fieldRIFCLI.getString();
    }

    /**
     * Set field NOMBAN using a String value.
     */
    public void setNOMBAN(String newvalue) {
        fieldNOMBAN.setString(newvalue);
    }

    /**
     * Get value of field NOMBAN as a String.
     */
    public String getNOMBAN() {
        return fieldNOMBAN.getString();
    }

    /**
     * Set field SFCOD using a String value.
     */
    public void setSFCOD(String newvalue) {
        fieldSFCOD.setString(newvalue);
    }

    /**
     * Get value of field SFCOD as a String.
     */
    public String getSFCOD() {
        return fieldSFCOD.getString();
    }

    /**
     * Set numeric field SFCOD using a BigDecimal value.
     */
    public void setSFCOD(BigDecimal newvalue) {
        fieldSFCOD.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SFCOD as a BigDecimal.
     */
    public BigDecimal getBigDecimalSFCOD() {
        return fieldSFCOD.getBigDecimal();
    }

    /**
     * Set field SFCLO using a String value.
     */
    public void setSFCLO(String newvalue) {
        fieldSFCLO.setString(newvalue);
    }

    /**
     * Get value of field SFCLO as a String.
     */
    public String getSFCLO() {
        return fieldSFCLO.getString();
    }

    /**
     * Set numeric field SFCLO using a BigDecimal value.
     */
    public void setSFCLO(BigDecimal newvalue) {
        fieldSFCLO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SFCLO as a BigDecimal.
     */
    public BigDecimal getBigDecimalSFCLO() {
        return fieldSFCLO.getBigDecimal();
    }

    /**
     * Set field SFCOP using a String value.
     */
    public void setSFCOP(String newvalue) {
        fieldSFCOP.setString(newvalue);
    }

    /**
     * Get value of field SFCOP as a String.
     */
    public String getSFCOP() {
        return fieldSFCOP.getString();
    }

    /**
     * Set field SFTIP using a String value.
     */
    public void setSFTIP(String newvalue) {
        fieldSFTIP.setString(newvalue);
    }

    /**
     * Get value of field SFTIP as a String.
     */
    public String getSFTIP() {
        return fieldSFTIP.getString();
    }

    /**
     * Set field IMPO1 using a String value.
     */
    public void setIMPO1(String newvalue) {
        fieldIMPO1.setString(newvalue);
    }

    /**
     * Get value of field IMPO1 as a String.
     */
    public String getIMPO1() {
        return fieldIMPO1.getString();
    }

    /**
     * Set numeric field IMPO1 using a BigDecimal value.
     */
    public void setIMPO1(BigDecimal newvalue) {
        fieldIMPO1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IMPO1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalIMPO1() {
        return fieldIMPO1.getBigDecimal();
    }

    /**
     * Set field IMPO2 using a String value.
     */
    public void setIMPO2(String newvalue) {
        fieldIMPO2.setString(newvalue);
    }

    /**
     * Get value of field IMPO2 as a String.
     */
    public String getIMPO2() {
        return fieldIMPO2.getString();
    }

    /**
     * Set numeric field IMPO2 using a BigDecimal value.
     */
    public void setIMPO2(BigDecimal newvalue) {
        fieldIMPO2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IMPO2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalIMPO2() {
        return fieldIMPO2.getBigDecimal();
    }

    /**
     * Set field IMPO3 using a String value.
     */
    public void setIMPO3(String newvalue) {
        fieldIMPO3.setString(newvalue);
    }

    /**
     * Get value of field IMPO3 as a String.
     */
    public String getIMPO3() {
        return fieldIMPO3.getString();
    }

    /**
     * Set numeric field IMPO3 using a BigDecimal value.
     */
    public void setIMPO3(BigDecimal newvalue) {
        fieldIMPO3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IMPO3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalIMPO3() {
        return fieldIMPO3.getBigDecimal();
    }

    /**
     * Set field NRR using a String value.
     */
    public void setNRR(String newvalue) {
        fieldNRR.setString(newvalue);
    }

    /**
     * Get value of field NRR as a String.
     */
    public String getNRR() {
        return fieldNRR.getString();
    }

    /**
     * Set numeric field NRR using a BigDecimal value.
     */
    public void setNRR(BigDecimal newvalue) {
        fieldNRR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NRR as a BigDecimal.
     */
    public BigDecimal getBigDecimalNRR() {
        return fieldNRR.getBigDecimal();
    }

    /**
     * Set field NOMBRE using a String value.
     */
    public void setNOMBRE(String newvalue) {
        fieldNOMBRE.setString(newvalue);
    }

    /**
     * Get value of field NOMBRE as a String.
     */
    public String getNOMBRE() {
        return fieldNOMBRE.getString();
    }

    /**
     * Set field ENCA1 using a String value.
     */
    public void setENCA1(String newvalue) {
        fieldENCA1.setString(newvalue);
    }

    /**
     * Get value of field ENCA1 as a String.
     */
    public String getENCA1() {
        return fieldENCA1.getString();
    }

    /**
     * Set numeric field ENCA1 using a BigDecimal value.
     */
    public void setENCA1(BigDecimal newvalue) {
        fieldENCA1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field ENCA1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalENCA1() {
        return fieldENCA1.getBigDecimal();
    }

    /**
     * Set field ENCA2 using a String value.
     */
    public void setENCA2(String newvalue) {
        fieldENCA2.setString(newvalue);
    }

    /**
     * Get value of field ENCA2 as a String.
     */
    public String getENCA2() {
        return fieldENCA2.getString();
    }

    /**
     * Set numeric field ENCA2 using a BigDecimal value.
     */
    public void setENCA2(BigDecimal newvalue) {
        fieldENCA2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field ENCA2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalENCA2() {
        return fieldENCA2.getBigDecimal();
    }

    /**
     * Set field ENCA3 using a String value.
     */
    public void setENCA3(String newvalue) {
        fieldENCA3.setString(newvalue);
    }

    /**
     * Get value of field ENCA3 as a String.
     */
    public String getENCA3() {
        return fieldENCA3.getString();
    }

    /**
     * Set numeric field ENCA3 using a BigDecimal value.
     */
    public void setENCA3(BigDecimal newvalue) {
        fieldENCA3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field ENCA3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalENCA3() {
        return fieldENCA3.getBigDecimal();
    }

    /**
     * Set field FECS1 using a String value.
     */
    public void setFECS1(String newvalue) {
        fieldFECS1.setString(newvalue);
    }

    /**
     * Get value of field FECS1 as a String.
     */
    public String getFECS1() {
        return fieldFECS1.getString();
    }

    /**
     * Set numeric field FECS1 using a BigDecimal value.
     */
    public void setFECS1(BigDecimal newvalue) {
        fieldFECS1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECS1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECS1() {
        return fieldFECS1.getBigDecimal();
    }

    /**
     * Set field FECS2 using a String value.
     */
    public void setFECS2(String newvalue) {
        fieldFECS2.setString(newvalue);
    }

    /**
     * Get value of field FECS2 as a String.
     */
    public String getFECS2() {
        return fieldFECS2.getString();
    }

    /**
     * Set numeric field FECS2 using a BigDecimal value.
     */
    public void setFECS2(BigDecimal newvalue) {
        fieldFECS2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECS2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECS2() {
        return fieldFECS2.getBigDecimal();
    }

    /**
     * Set field FECS3 using a String value.
     */
    public void setFECS3(String newvalue) {
        fieldFECS3.setString(newvalue);
    }

    /**
     * Get value of field FECS3 as a String.
     */
    public String getFECS3() {
        return fieldFECS3.getString();
    }

    /**
     * Set numeric field FECS3 using a BigDecimal value.
     */
    public void setFECS3(BigDecimal newvalue) {
        fieldFECS3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECS3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECS3() {
        return fieldFECS3.getBigDecimal();
    }

    /**
     * Set field SALA1 using a String value.
     */
    public void setSALA1(String newvalue) {
        fieldSALA1.setString(newvalue);
    }

    /**
     * Get value of field SALA1 as a String.
     */
    public String getSALA1() {
        return fieldSALA1.getString();
    }

    /**
     * Set numeric field SALA1 using a BigDecimal value.
     */
    public void setSALA1(BigDecimal newvalue) {
        fieldSALA1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SALA1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalSALA1() {
        return fieldSALA1.getBigDecimal();
    }

    /**
     * Set field SALA2 using a String value.
     */
    public void setSALA2(String newvalue) {
        fieldSALA2.setString(newvalue);
    }

    /**
     * Get value of field SALA2 as a String.
     */
    public String getSALA2() {
        return fieldSALA2.getString();
    }

    /**
     * Set numeric field SALA2 using a BigDecimal value.
     */
    public void setSALA2(BigDecimal newvalue) {
        fieldSALA2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SALA2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalSALA2() {
        return fieldSALA2.getBigDecimal();
    }

    /**
     * Set field SALA3 using a String value.
     */
    public void setSALA3(String newvalue) {
        fieldSALA3.setString(newvalue);
    }

    /**
     * Get value of field SALA3 as a String.
     */
    public String getSALA3() {
        return fieldSALA3.getString();
    }

    /**
     * Set numeric field SALA3 using a BigDecimal value.
     */
    public void setSALA3(BigDecimal newvalue) {
        fieldSALA3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SALA3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalSALA3() {
        return fieldSALA3.getBigDecimal();
    }

    /**
     * Set field MOTN1 using a String value.
     */
    public void setMOTN1(String newvalue) {
        fieldMOTN1.setString(newvalue);
    }

    /**
     * Get value of field MOTN1 as a String.
     */
    public String getMOTN1() {
        return fieldMOTN1.getString();
    }

    /**
     * Set numeric field MOTN1 using a BigDecimal value.
     */
    public void setMOTN1(BigDecimal newvalue) {
        fieldMOTN1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MOTN1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalMOTN1() {
        return fieldMOTN1.getBigDecimal();
    }

    /**
     * Set field MOTN2 using a String value.
     */
    public void setMOTN2(String newvalue) {
        fieldMOTN2.setString(newvalue);
    }

    /**
     * Get value of field MOTN2 as a String.
     */
    public String getMOTN2() {
        return fieldMOTN2.getString();
    }

    /**
     * Set numeric field MOTN2 using a BigDecimal value.
     */
    public void setMOTN2(BigDecimal newvalue) {
        fieldMOTN2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MOTN2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalMOTN2() {
        return fieldMOTN2.getBigDecimal();
    }

    /**
     * Set field MOTN3 using a String value.
     */
    public void setMOTN3(String newvalue) {
        fieldMOTN3.setString(newvalue);
    }

    /**
     * Get value of field MOTN3 as a String.
     */
    public String getMOTN3() {
        return fieldMOTN3.getString();
    }

    /**
     * Set numeric field MOTN3 using a BigDecimal value.
     */
    public void setMOTN3(BigDecimal newvalue) {
        fieldMOTN3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MOTN3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalMOTN3() {
        return fieldMOTN3.getBigDecimal();
    }

    /**
     * Set field MOVN1 using a String value.
     */
    public void setMOVN1(String newvalue) {
        fieldMOVN1.setString(newvalue);
    }

    /**
     * Get value of field MOVN1 as a String.
     */
    public String getMOVN1() {
        return fieldMOVN1.getString();
    }

    /**
     * Set numeric field MOVN1 using a BigDecimal value.
     */
    public void setMOVN1(BigDecimal newvalue) {
        fieldMOVN1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MOVN1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalMOVN1() {
        return fieldMOVN1.getBigDecimal();
    }

    /**
     * Set field MOVN2 using a String value.
     */
    public void setMOVN2(String newvalue) {
        fieldMOVN2.setString(newvalue);
    }

    /**
     * Get value of field MOVN2 as a String.
     */
    public String getMOVN2() {
        return fieldMOVN2.getString();
    }

    /**
     * Set numeric field MOVN2 using a BigDecimal value.
     */
    public void setMOVN2(BigDecimal newvalue) {
        fieldMOVN2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MOVN2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalMOVN2() {
        return fieldMOVN2.getBigDecimal();
    }

    /**
     * Set field MOVN3 using a String value.
     */
    public void setMOVN3(String newvalue) {
        fieldMOVN3.setString(newvalue);
    }

    /**
     * Get value of field MOVN3 as a String.
     */
    public String getMOVN3() {
        return fieldMOVN3.getString();
    }

    /**
     * Set numeric field MOVN3 using a BigDecimal value.
     */
    public void setMOVN3(BigDecimal newvalue) {
        fieldMOVN3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MOVN3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalMOVN3() {
        return fieldMOVN3.getBigDecimal();
    }

    /**
     * Set field SATA1 using a String value.
     */
    public void setSATA1(String newvalue) {
        fieldSATA1.setString(newvalue);
    }

    /**
     * Get value of field SATA1 as a String.
     */
    public String getSATA1() {
        return fieldSATA1.getString();
    }

    /**
     * Set numeric field SATA1 using a BigDecimal value.
     */
    public void setSATA1(BigDecimal newvalue) {
        fieldSATA1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SATA1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalSATA1() {
        return fieldSATA1.getBigDecimal();
    }

    /**
     * Set field SATA2 using a String value.
     */
    public void setSATA2(String newvalue) {
        fieldSATA2.setString(newvalue);
    }

    /**
     * Get value of field SATA2 as a String.
     */
    public String getSATA2() {
        return fieldSATA2.getString();
    }

    /**
     * Set numeric field SATA2 using a BigDecimal value.
     */
    public void setSATA2(BigDecimal newvalue) {
        fieldSATA2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SATA2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalSATA2() {
        return fieldSATA2.getBigDecimal();
    }

    /**
     * Set field SATA3 using a String value.
     */
    public void setSATA3(String newvalue) {
        fieldSATA3.setString(newvalue);
    }

    /**
     * Get value of field SATA3 as a String.
     */
    public String getSATA3() {
        return fieldSATA3.getString();
    }

    /**
     * Set numeric field SATA3 using a BigDecimal value.
     */
    public void setSATA3(BigDecimal newvalue) {
        fieldSATA3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SATA3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalSATA3() {
        return fieldSATA3.getBigDecimal();
    }

    /**
     * Set field INVAL using a String value.
     */
    public void setINVAL(String newvalue) {
        fieldINVAL.setString(newvalue);
    }

    /**
     * Get value of field INVAL as a String.
     */
    public String getINVAL() {
        return fieldINVAL.getString();
    }

    /**
     * Set field INVTO using a String value.
     */
    public void setINVTO(String newvalue) {
        fieldINVTO.setString(newvalue);
    }

    /**
     * Get value of field INVTO as a String.
     */
    public String getINVTO() {
        return fieldINVTO.getString();
    }

    /**
     * Set numeric field INVTO using a BigDecimal value.
     */
    public void setINVTO(BigDecimal newvalue) {
        fieldINVTO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVTO as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVTO() {
        return fieldINVTO.getBigDecimal();
    }

    /**
     * Set field INTAS using a String value.
     */
    public void setINTAS(String newvalue) {
        fieldINTAS.setString(newvalue);
    }

    /**
     * Get value of field INTAS as a String.
     */
    public String getINTAS() {
        return fieldINTAS.getString();
    }

    /**
     * Set numeric field INTAS using a BigDecimal value.
     */
    public void setINTAS(BigDecimal newvalue) {
        fieldINTAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INTAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalINTAS() {
        return fieldINTAS.getBigDecimal();
    }

    /**
     * Set field INNOM using a String value.
     */
    public void setINNOM(String newvalue) {
        fieldINNOM.setString(newvalue);
    }

    /**
     * Get value of field INNOM as a String.
     */
    public String getINNOM() {
        return fieldINNOM.getString();
    }

    /**
     * Set numeric field INNOM using a BigDecimal value.
     */
    public void setINNOM(BigDecimal newvalue) {
        fieldINNOM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INNOM as a BigDecimal.
     */
    public BigDecimal getBigDecimalINNOM() {
        return fieldINNOM.getBigDecimal();
    }

    /**
     * Set field ININT using a String value.
     */
    public void setININT(String newvalue) {
        fieldININT.setString(newvalue);
    }

    /**
     * Get value of field ININT as a String.
     */
    public String getININT() {
        return fieldININT.getString();
    }

    /**
     * Set numeric field ININT using a BigDecimal value.
     */
    public void setININT(BigDecimal newvalue) {
        fieldININT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field ININT as a BigDecimal.
     */
    public BigDecimal getBigDecimalININT() {
        return fieldININT.getBigDecimal();
    }

    /**
     * Set field INTOT using a String value.
     */
    public void setINTOT(String newvalue) {
        fieldINTOT.setString(newvalue);
    }

    /**
     * Get value of field INTOT as a String.
     */
    public String getINTOT() {
        return fieldINTOT.getString();
    }

    /**
     * Set numeric field INTOT using a BigDecimal value.
     */
    public void setINTOT(BigDecimal newvalue) {
        fieldINTOT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INTOT as a BigDecimal.
     */
    public BigDecimal getBigDecimalINTOT() {
        return fieldINTOT.getBigDecimal();
    }

    /**
     * Set field NRI using a String value.
     */
    public void setNRI(String newvalue) {
        fieldNRI.setString(newvalue);
    }

    /**
     * Get value of field NRI as a String.
     */
    public String getNRI() {
        return fieldNRI.getString();
    }

    /**
     * Set numeric field NRI using a BigDecimal value.
     */
    public void setNRI(BigDecimal newvalue) {
        fieldNRI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NRI as a BigDecimal.
     */
    public BigDecimal getBigDecimalNRI() {
        return fieldNRI.getBigDecimal();
    }

    /**
     * Set field FECINV using a String value.
     */
    public void setFECINV(String newvalue) {
        fieldFECINV.setString(newvalue);
    }

    /**
     * Get value of field FECINV as a String.
     */
    public String getFECINV() {
        return fieldFECINV.getString();
    }

    /**
     * Set numeric field FECINV using a BigDecimal value.
     */
    public void setFECINV(BigDecimal newvalue) {
        fieldFECINV.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECINV as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECINV() {
        return fieldFECINV.getBigDecimal();
    }

}
