package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from GP0036MFM physical file
 * definition.
 * 
* File level identifier is 1140321105703. Record format level identifier is
 * 32CDD184AA287.
 */
public class GP0036MFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "TABNOM",
        "VALOR",
        "NOMVAL",
        "NOMDIV",
        "VLOFIS",
        "NOMEMI",
        "TIPVAL",
        "NROTIT",
        "VLOUDE",
        "VLOUCA",
        "FECINI",
        "FECVTO",
        "INVLIQ",
        "INVBVI",
        "INVNOP",
        "BASECA",
        "BASEDI",
        "DIEMI5",
        "DIEMI0",
        "VLOUNI",
        "DIHOY5",
        "DIHOY0",
        "VLOTAS",
        "DIVTO5",
        "DIVTO0",
        "NUMTIT",
        "INVVNO",
        "PRCCHE",
        "EFEINI",
        "IMPCHE",
        "INVPOP",
        "RENDIM",
        "INVRES",
        "COMISI",
        "INVTIM",
        "RETENC",
        "INVIBS",
        "CTASPT",
        "RENTOT",
        "INVTOT",
        "TASAX",
        "RENOBT",
        "DIEMIC",
        "INVBAS",
        "DIHOYC",
        "INVENC",
        "BASCAC",
        "DIVTOC",
        "INTTOT",
        "VALCAP",
        "VALACT",
        "AUXIL",
        "EFEFIN",
        "PRIMA",
        "TIMBRE",
        "INACUM",
        "GRUPO",
        "OPC",
        "NUMEROC",
        "AREASFL",
        "NOMSFL",
        "DISSFL",
        "IMPSFL",
        "COTDIV",
        "RESTANTE",
        "AREACTL",
        "NOMCTL",
        "DISCTL",
        "IMPCTL"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "TABNOM",
        "VALOR",
        "NOMVAL",
        "NOMDIV",
        "VLOFIS",
        "NOMEMI",
        "TIPVAL",
        "NROTIT",
        "VLOUDE",
        "VLOUCA",
        "FECINI",
        "FECVTO",
        "INVLIQ",
        "INVBVI",
        "INVNOP",
        "BASECA",
        "BASEDI",
        "DIEMI5",
        "DIEMI0",
        "VLOUNI",
        "DIHOY5",
        "DIHOY0",
        "VLOTAS",
        "DIVTO5",
        "DIVTO0",
        "NUMTIT",
        "INVVNO",
        "PRCCHE",
        "EFEINI",
        "IMPCHE",
        "INVPOP",
        "RENDIM",
        "INVRES",
        "COMISI",
        "INVTIM",
        "RETENC",
        "INVIBS",
        "CTASPT",
        "RENTOT",
        "INVTOT",
        "TASAX",
        "RENOBT",
        "DIEMIC",
        "INVBAS",
        "DIHOYC",
        "INVENC",
        "BASCAC",
        "DIVTOC",
        "INTTOT",
        "VALCAP",
        "VALACT",
        "AUXIL",
        "EFEFIN",
        "PRIMA",
        "TIMBRE",
        "INACUM",
        "GRUPO",
        "OPC",
        "NUMEROC",
        "AREASFL",
        "NOMSFL",
        "DISSFL",
        "IMPSFL",
        "COTDIV",
        "RESTANTE",
        "AREACTL",
        "NOMCTL",
        "DISCTL",
        "IMPCTL"
    };
    final static String fid = "1140321105703";
    final static String rid = "32CDD184AA287";
    final static String fmtname = "GP0036MFM";
    final int FIELDCOUNT = 78;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldTABNOM = null;
    private CharacterField fieldVALOR = null;
    private CharacterField fieldNOMVAL = null;
    private CharacterField fieldNOMDIV = null;
    private DecimalField fieldVLOFIS = null;
    private CharacterField fieldNOMEMI = null;
    private CharacterField fieldTIPVAL = null;
    private DecimalField fieldNROTIT = null;
    private DecimalField fieldVLOUDE = null;
    private DecimalField fieldVLOUCA = null;
    private DecimalField fieldFECINI = null;
    private DecimalField fieldFECVTO = null;
    private DecimalField fieldINVLIQ = null;
    private DecimalField fieldINVBVI = null;
    private DecimalField fieldINVNOP = null;
    private DecimalField fieldBASECA = null;
    private DecimalField fieldBASEDI = null;
    private DecimalField fieldDIEMI5 = null;
    private DecimalField fieldDIEMI0 = null;
    private DecimalField fieldVLOUNI = null;
    private DecimalField fieldDIHOY5 = null;
    private DecimalField fieldDIHOY0 = null;
    private DecimalField fieldVLOTAS = null;
    private DecimalField fieldDIVTO5 = null;
    private DecimalField fieldDIVTO0 = null;
    private DecimalField fieldNUMTIT = null;
    private DecimalField fieldINVVNO = null;
    private DecimalField fieldPRCCHE = null;
    private DecimalField fieldEFEINI = null;
    private DecimalField fieldIMPCHE = null;
    private DecimalField fieldINVPOP = null;
    private DecimalField fieldRENDIM = null;
    private DecimalField fieldINVRES = null;
    private DecimalField fieldCOMISI = null;
    private DecimalField fieldINVTIM = null;
    private CharacterField fieldRETENC = null;
    private CharacterField fieldINVIBS = null;
    private DecimalField fieldCTASPT = null;
    private DecimalField fieldRENTOT = null;
    private DecimalField fieldINVTOT = null;
    private DecimalField fieldTASAX = null;
    private DecimalField fieldRENOBT = null;
    private DecimalField fieldDIEMIC = null;
    private DecimalField fieldINVBAS = null;
    private DecimalField fieldDIHOYC = null;
    private DecimalField fieldINVENC = null;
    private DecimalField fieldBASCAC = null;
    private DecimalField fieldDIVTOC = null;
    private DecimalField fieldINTTOT = null;
    private DecimalField fieldVALCAP = null;
    private DecimalField fieldVALACT = null;
    private DecimalField fieldAUXIL = null;
    private DecimalField fieldEFEFIN = null;
    private DecimalField fieldPRIMA = null;
    private DecimalField fieldTIMBRE = null;
    private DecimalField fieldINACUM = null;
    private CharacterField fieldGRUPO = null;
    private CharacterField fieldOPC = null;
    private DecimalField fieldNUMEROC = null;
    private CharacterField fieldAREASFL = null;
    private CharacterField fieldNOMSFL = null;
    private DecimalField fieldDISSFL = null;
    private DecimalField fieldIMPSFL = null;
    private DecimalField fieldCOTDIV = null;
    private DecimalField fieldRESTANTE = null;
    private CharacterField fieldAREACTL = null;
    private CharacterField fieldNOMCTL = null;
    private DecimalField fieldDISCTL = null;
    private DecimalField fieldIMPCTL = null;

    /**
     * Constructor for GP0036MFMMessage.
     */
    public GP0036MFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 972;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldTABNOM
                = new CharacterField(message, HEADERSIZE + 161, 40, "TABNOM");
        fields[10] = fieldVALOR
                = new CharacterField(message, HEADERSIZE + 201, 12, "VALOR");
        fields[11] = fieldNOMVAL
                = new CharacterField(message, HEADERSIZE + 213, 34, "NOMVAL");
        fields[12] = fieldNOMDIV
                = new CharacterField(message, HEADERSIZE + 247, 20, "NOMDIV");
        fields[13] = fieldVLOFIS
                = new DecimalField(message, HEADERSIZE + 267, 8, 0, "VLOFIS");
        fields[14] = fieldNOMEMI
                = new CharacterField(message, HEADERSIZE + 275, 39, "NOMEMI");
        fields[15] = fieldTIPVAL
                = new CharacterField(message, HEADERSIZE + 314, 3, "TIPVAL");
        fields[16] = fieldNROTIT
                = new DecimalField(message, HEADERSIZE + 317, 11, 0, "NROTIT");
        fields[17] = fieldVLOUDE
                = new DecimalField(message, HEADERSIZE + 328, 7, 0, "VLOUDE");
        fields[18] = fieldVLOUCA
                = new DecimalField(message, HEADERSIZE + 335, 7, 0, "VLOUCA");
        fields[19] = fieldFECINI
                = new DecimalField(message, HEADERSIZE + 342, 7, 0, "FECINI");
        fields[20] = fieldFECVTO
                = new DecimalField(message, HEADERSIZE + 349, 7, 0, "FECVTO");
        fields[21] = fieldINVLIQ
                = new DecimalField(message, HEADERSIZE + 356, 7, 0, "INVLIQ");
        fields[22] = fieldINVBVI
                = new DecimalField(message, HEADERSIZE + 363, 8, 0, "INVBVI");
        fields[23] = fieldINVNOP
                = new DecimalField(message, HEADERSIZE + 371, 11, 0, "INVNOP");
        fields[24] = fieldBASECA
                = new DecimalField(message, HEADERSIZE + 382, 2, 0, "BASECA");
        fields[25] = fieldBASEDI
                = new DecimalField(message, HEADERSIZE + 384, 2, 0, "BASEDI");
        fields[26] = fieldDIEMI5
                = new DecimalField(message, HEADERSIZE + 386, 5, 0, "DIEMI5");
        fields[27] = fieldDIEMI0
                = new DecimalField(message, HEADERSIZE + 391, 5, 0, "DIEMI0");
        fields[28] = fieldVLOUNI
                = new DecimalField(message, HEADERSIZE + 396, 15, 2, "VLOUNI");
        fields[29] = fieldDIHOY5
                = new DecimalField(message, HEADERSIZE + 411, 5, 0, "DIHOY5");
        fields[30] = fieldDIHOY0
                = new DecimalField(message, HEADERSIZE + 416, 5, 0, "DIHOY0");
        fields[31] = fieldVLOTAS
                = new DecimalField(message, HEADERSIZE + 421, 11, 6, "VLOTAS");
        fields[32] = fieldDIVTO5
                = new DecimalField(message, HEADERSIZE + 432, 5, 0, "DIVTO5");
        fields[33] = fieldDIVTO0
                = new DecimalField(message, HEADERSIZE + 437, 5, 0, "DIVTO0");
        fields[34] = fieldNUMTIT
                = new DecimalField(message, HEADERSIZE + 442, 29, 7, "NUMTIT");
        fields[35] = fieldINVVNO
                = new DecimalField(message, HEADERSIZE + 471, 17, 2, "INVVNO");
        fields[36] = fieldPRCCHE
                = new DecimalField(message, HEADERSIZE + 488, 8, 3, "PRCCHE");
        fields[37] = fieldEFEINI
                = new DecimalField(message, HEADERSIZE + 496, 17, 2, "EFEINI");
        fields[38] = fieldIMPCHE
                = new DecimalField(message, HEADERSIZE + 513, 14, 2, "IMPCHE");
        fields[39] = fieldINVPOP
                = new DecimalField(message, HEADERSIZE + 527, 11, 6, "INVPOP");
        fields[40] = fieldRENDIM
                = new DecimalField(message, HEADERSIZE + 538, 11, 6, "RENDIM");
        fields[41] = fieldINVRES
                = new DecimalField(message, HEADERSIZE + 549, 11, 6, "INVRES");
        fields[42] = fieldCOMISI
                = new DecimalField(message, HEADERSIZE + 560, 11, 6, "COMISI");
        fields[43] = fieldINVTIM
                = new DecimalField(message, HEADERSIZE + 571, 11, 6, "INVTIM");
        fields[44] = fieldRETENC
                = new CharacterField(message, HEADERSIZE + 582, 1, "RETENC");
        fields[45] = fieldINVIBS
                = new CharacterField(message, HEADERSIZE + 583, 1, "INVIBS");
        fields[46] = fieldCTASPT
                = new DecimalField(message, HEADERSIZE + 584, 17, 2, "CTASPT");
        fields[47] = fieldRENTOT
                = new DecimalField(message, HEADERSIZE + 601, 11, 6, "RENTOT");
        fields[48] = fieldINVTOT
                = new DecimalField(message, HEADERSIZE + 612, 11, 6, "INVTOT");
        fields[49] = fieldTASAX
                = new DecimalField(message, HEADERSIZE + 623, 11, 6, "TASAX");
        fields[50] = fieldRENOBT
                = new DecimalField(message, HEADERSIZE + 634, 11, 6, "RENOBT");
        fields[51] = fieldDIEMIC
                = new DecimalField(message, HEADERSIZE + 645, 5, 0, "DIEMIC");
        fields[52] = fieldINVBAS
                = new DecimalField(message, HEADERSIZE + 650, 11, 6, "INVBAS");
        fields[53] = fieldDIHOYC
                = new DecimalField(message, HEADERSIZE + 661, 5, 0, "DIHOYC");
        fields[54] = fieldINVENC
                = new DecimalField(message, HEADERSIZE + 666, 11, 6, "INVENC");
        fields[55] = fieldBASCAC
                = new DecimalField(message, HEADERSIZE + 677, 4, 0, "BASCAC");
        fields[56] = fieldDIVTOC
                = new DecimalField(message, HEADERSIZE + 681, 5, 0, "DIVTOC");
        fields[57] = fieldINTTOT
                = new DecimalField(message, HEADERSIZE + 686, 17, 2, "INTTOT");
        fields[58] = fieldVALCAP
                = new DecimalField(message, HEADERSIZE + 703, 17, 2, "VALCAP");
        fields[59] = fieldVALACT
                = new DecimalField(message, HEADERSIZE + 720, 17, 2, "VALACT");
        fields[60] = fieldAUXIL
                = new DecimalField(message, HEADERSIZE + 737, 17, 2, "AUXIL");
        fields[61] = fieldEFEFIN
                = new DecimalField(message, HEADERSIZE + 754, 17, 2, "EFEFIN");
        fields[62] = fieldPRIMA
                = new DecimalField(message, HEADERSIZE + 771, 17, 2, "PRIMA");
        fields[63] = fieldTIMBRE
                = new DecimalField(message, HEADERSIZE + 788, 17, 2, "TIMBRE");
        fields[64] = fieldINACUM
                = new DecimalField(message, HEADERSIZE + 805, 17, 2, "INACUM");
        fields[65] = fieldGRUPO
                = new CharacterField(message, HEADERSIZE + 822, 1, "GRUPO");
        fields[66] = fieldOPC
                = new CharacterField(message, HEADERSIZE + 823, 1, "OPC");
        fields[67] = fieldNUMEROC
                = new DecimalField(message, HEADERSIZE + 824, 8, 0, "NUMEROC");
        fields[68] = fieldAREASFL
                = new CharacterField(message, HEADERSIZE + 832, 4, "AREASFL");
        fields[69] = fieldNOMSFL
                = new CharacterField(message, HEADERSIZE + 836, 15, "NOMSFL");
        fields[70] = fieldDISSFL
                = new DecimalField(message, HEADERSIZE + 851, 17, 2, "DISSFL");
        fields[71] = fieldIMPSFL
                = new DecimalField(message, HEADERSIZE + 868, 17, 2, "IMPSFL");
        fields[72] = fieldCOTDIV
                = new DecimalField(message, HEADERSIZE + 885, 17, 6, "COTDIV");
        fields[73] = fieldRESTANTE
                = new DecimalField(message, HEADERSIZE + 902, 17, 2, "RESTANTE");
        fields[74] = fieldAREACTL
                = new CharacterField(message, HEADERSIZE + 919, 4, "AREACTL");
        fields[75] = fieldNOMCTL
                = new CharacterField(message, HEADERSIZE + 923, 15, "NOMCTL");
        fields[76] = fieldDISCTL
                = new DecimalField(message, HEADERSIZE + 938, 17, 2, "DISCTL");
        fields[77] = fieldIMPCTL
                = new DecimalField(message, HEADERSIZE + 955, 17, 2, "IMPCTL");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field TABNOM using a String value.
     */
    public void setTABNOM(String newvalue) {
        fieldTABNOM.setString(newvalue);
    }

    /**
     * Get value of field TABNOM as a String.
     */
    public String getTABNOM() {
        return fieldTABNOM.getString();
    }

    /**
     * Set field VALOR using a String value.
     */
    public void setVALOR(String newvalue) {
        fieldVALOR.setString(newvalue);
    }

    /**
     * Get value of field VALOR as a String.
     */
    public String getVALOR() {
        return fieldVALOR.getString();
    }

    /**
     * Set field NOMVAL using a String value.
     */
    public void setNOMVAL(String newvalue) {
        fieldNOMVAL.setString(newvalue);
    }

    /**
     * Get value of field NOMVAL as a String.
     */
    public String getNOMVAL() {
        return fieldNOMVAL.getString();
    }

    /**
     * Set field NOMDIV using a String value.
     */
    public void setNOMDIV(String newvalue) {
        fieldNOMDIV.setString(newvalue);
    }

    /**
     * Get value of field NOMDIV as a String.
     */
    public String getNOMDIV() {
        return fieldNOMDIV.getString();
    }

    /**
     * Set field VLOFIS using a String value.
     */
    public void setVLOFIS(String newvalue) {
        fieldVLOFIS.setString(newvalue);
    }

    /**
     * Get value of field VLOFIS as a String.
     */
    public String getVLOFIS() {
        return fieldVLOFIS.getString();
    }

    /**
     * Set numeric field VLOFIS using a BigDecimal value.
     */
    public void setVLOFIS(BigDecimal newvalue) {
        fieldVLOFIS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOFIS as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOFIS() {
        return fieldVLOFIS.getBigDecimal();
    }

    /**
     * Set field NOMEMI using a String value.
     */
    public void setNOMEMI(String newvalue) {
        fieldNOMEMI.setString(newvalue);
    }

    /**
     * Get value of field NOMEMI as a String.
     */
    public String getNOMEMI() {
        return fieldNOMEMI.getString();
    }

    /**
     * Set field TIPVAL using a String value.
     */
    public void setTIPVAL(String newvalue) {
        fieldTIPVAL.setString(newvalue);
    }

    /**
     * Get value of field TIPVAL as a String.
     */
    public String getTIPVAL() {
        return fieldTIPVAL.getString();
    }

    /**
     * Set field NROTIT using a String value.
     */
    public void setNROTIT(String newvalue) {
        fieldNROTIT.setString(newvalue);
    }

    /**
     * Get value of field NROTIT as a String.
     */
    public String getNROTIT() {
        return fieldNROTIT.getString();
    }

    /**
     * Set numeric field NROTIT using a BigDecimal value.
     */
    public void setNROTIT(BigDecimal newvalue) {
        fieldNROTIT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NROTIT as a BigDecimal.
     */
    public BigDecimal getBigDecimalNROTIT() {
        return fieldNROTIT.getBigDecimal();
    }

    /**
     * Set field VLOUDE using a String value.
     */
    public void setVLOUDE(String newvalue) {
        fieldVLOUDE.setString(newvalue);
    }

    /**
     * Get value of field VLOUDE as a String.
     */
    public String getVLOUDE() {
        return fieldVLOUDE.getString();
    }

    /**
     * Set numeric field VLOUDE using a BigDecimal value.
     */
    public void setVLOUDE(BigDecimal newvalue) {
        fieldVLOUDE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUDE as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUDE() {
        return fieldVLOUDE.getBigDecimal();
    }

    /**
     * Set field VLOUCA using a String value.
     */
    public void setVLOUCA(String newvalue) {
        fieldVLOUCA.setString(newvalue);
    }

    /**
     * Get value of field VLOUCA as a String.
     */
    public String getVLOUCA() {
        return fieldVLOUCA.getString();
    }

    /**
     * Set numeric field VLOUCA using a BigDecimal value.
     */
    public void setVLOUCA(BigDecimal newvalue) {
        fieldVLOUCA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUCA as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUCA() {
        return fieldVLOUCA.getBigDecimal();
    }

    /**
     * Set field FECINI using a String value.
     */
    public void setFECINI(String newvalue) {
        fieldFECINI.setString(newvalue);
    }

    /**
     * Get value of field FECINI as a String.
     */
    public String getFECINI() {
        return fieldFECINI.getString();
    }

    /**
     * Set numeric field FECINI using a BigDecimal value.
     */
    public void setFECINI(BigDecimal newvalue) {
        fieldFECINI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECINI as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECINI() {
        return fieldFECINI.getBigDecimal();
    }

    /**
     * Set field FECVTO using a String value.
     */
    public void setFECVTO(String newvalue) {
        fieldFECVTO.setString(newvalue);
    }

    /**
     * Get value of field FECVTO as a String.
     */
    public String getFECVTO() {
        return fieldFECVTO.getString();
    }

    /**
     * Set numeric field FECVTO using a BigDecimal value.
     */
    public void setFECVTO(BigDecimal newvalue) {
        fieldFECVTO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECVTO as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECVTO() {
        return fieldFECVTO.getBigDecimal();
    }

    /**
     * Set field INVLIQ using a String value.
     */
    public void setINVLIQ(String newvalue) {
        fieldINVLIQ.setString(newvalue);
    }

    /**
     * Get value of field INVLIQ as a String.
     */
    public String getINVLIQ() {
        return fieldINVLIQ.getString();
    }

    /**
     * Set numeric field INVLIQ using a BigDecimal value.
     */
    public void setINVLIQ(BigDecimal newvalue) {
        fieldINVLIQ.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVLIQ as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVLIQ() {
        return fieldINVLIQ.getBigDecimal();
    }

    /**
     * Set field INVBVI using a String value.
     */
    public void setINVBVI(String newvalue) {
        fieldINVBVI.setString(newvalue);
    }

    /**
     * Get value of field INVBVI as a String.
     */
    public String getINVBVI() {
        return fieldINVBVI.getString();
    }

    /**
     * Set numeric field INVBVI using a BigDecimal value.
     */
    public void setINVBVI(BigDecimal newvalue) {
        fieldINVBVI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVBVI as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVBVI() {
        return fieldINVBVI.getBigDecimal();
    }

    /**
     * Set field INVNOP using a String value.
     */
    public void setINVNOP(String newvalue) {
        fieldINVNOP.setString(newvalue);
    }

    /**
     * Get value of field INVNOP as a String.
     */
    public String getINVNOP() {
        return fieldINVNOP.getString();
    }

    /**
     * Set numeric field INVNOP using a BigDecimal value.
     */
    public void setINVNOP(BigDecimal newvalue) {
        fieldINVNOP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVNOP as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVNOP() {
        return fieldINVNOP.getBigDecimal();
    }

    /**
     * Set field BASECA using a String value.
     */
    public void setBASECA(String newvalue) {
        fieldBASECA.setString(newvalue);
    }

    /**
     * Get value of field BASECA as a String.
     */
    public String getBASECA() {
        return fieldBASECA.getString();
    }

    /**
     * Set numeric field BASECA using a BigDecimal value.
     */
    public void setBASECA(BigDecimal newvalue) {
        fieldBASECA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BASECA as a BigDecimal.
     */
    public BigDecimal getBigDecimalBASECA() {
        return fieldBASECA.getBigDecimal();
    }

    /**
     * Set field BASEDI using a String value.
     */
    public void setBASEDI(String newvalue) {
        fieldBASEDI.setString(newvalue);
    }

    /**
     * Get value of field BASEDI as a String.
     */
    public String getBASEDI() {
        return fieldBASEDI.getString();
    }

    /**
     * Set numeric field BASEDI using a BigDecimal value.
     */
    public void setBASEDI(BigDecimal newvalue) {
        fieldBASEDI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BASEDI as a BigDecimal.
     */
    public BigDecimal getBigDecimalBASEDI() {
        return fieldBASEDI.getBigDecimal();
    }

    /**
     * Set field DIEMI5 using a String value.
     */
    public void setDIEMI5(String newvalue) {
        fieldDIEMI5.setString(newvalue);
    }

    /**
     * Get value of field DIEMI5 as a String.
     */
    public String getDIEMI5() {
        return fieldDIEMI5.getString();
    }

    /**
     * Set numeric field DIEMI5 using a BigDecimal value.
     */
    public void setDIEMI5(BigDecimal newvalue) {
        fieldDIEMI5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIEMI5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIEMI5() {
        return fieldDIEMI5.getBigDecimal();
    }

    /**
     * Set field DIEMI0 using a String value.
     */
    public void setDIEMI0(String newvalue) {
        fieldDIEMI0.setString(newvalue);
    }

    /**
     * Get value of field DIEMI0 as a String.
     */
    public String getDIEMI0() {
        return fieldDIEMI0.getString();
    }

    /**
     * Set numeric field DIEMI0 using a BigDecimal value.
     */
    public void setDIEMI0(BigDecimal newvalue) {
        fieldDIEMI0.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIEMI0 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIEMI0() {
        return fieldDIEMI0.getBigDecimal();
    }

    /**
     * Set field VLOUNI using a String value.
     */
    public void setVLOUNI(String newvalue) {
        fieldVLOUNI.setString(newvalue);
    }

    /**
     * Get value of field VLOUNI as a String.
     */
    public String getVLOUNI() {
        return fieldVLOUNI.getString();
    }

    /**
     * Set numeric field VLOUNI using a BigDecimal value.
     */
    public void setVLOUNI(BigDecimal newvalue) {
        fieldVLOUNI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUNI as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUNI() {
        return fieldVLOUNI.getBigDecimal();
    }

    /**
     * Set field DIHOY5 using a String value.
     */
    public void setDIHOY5(String newvalue) {
        fieldDIHOY5.setString(newvalue);
    }

    /**
     * Get value of field DIHOY5 as a String.
     */
    public String getDIHOY5() {
        return fieldDIHOY5.getString();
    }

    /**
     * Set numeric field DIHOY5 using a BigDecimal value.
     */
    public void setDIHOY5(BigDecimal newvalue) {
        fieldDIHOY5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIHOY5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIHOY5() {
        return fieldDIHOY5.getBigDecimal();
    }

    /**
     * Set field DIHOY0 using a String value.
     */
    public void setDIHOY0(String newvalue) {
        fieldDIHOY0.setString(newvalue);
    }

    /**
     * Get value of field DIHOY0 as a String.
     */
    public String getDIHOY0() {
        return fieldDIHOY0.getString();
    }

    /**
     * Set numeric field DIHOY0 using a BigDecimal value.
     */
    public void setDIHOY0(BigDecimal newvalue) {
        fieldDIHOY0.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIHOY0 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIHOY0() {
        return fieldDIHOY0.getBigDecimal();
    }

    /**
     * Set field VLOTAS using a String value.
     */
    public void setVLOTAS(String newvalue) {
        fieldVLOTAS.setString(newvalue);
    }

    /**
     * Get value of field VLOTAS as a String.
     */
    public String getVLOTAS() {
        return fieldVLOTAS.getString();
    }

    /**
     * Set numeric field VLOTAS using a BigDecimal value.
     */
    public void setVLOTAS(BigDecimal newvalue) {
        fieldVLOTAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOTAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOTAS() {
        return fieldVLOTAS.getBigDecimal();
    }

    /**
     * Set field DIVTO5 using a String value.
     */
    public void setDIVTO5(String newvalue) {
        fieldDIVTO5.setString(newvalue);
    }

    /**
     * Get value of field DIVTO5 as a String.
     */
    public String getDIVTO5() {
        return fieldDIVTO5.getString();
    }

    /**
     * Set numeric field DIVTO5 using a BigDecimal value.
     */
    public void setDIVTO5(BigDecimal newvalue) {
        fieldDIVTO5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIVTO5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIVTO5() {
        return fieldDIVTO5.getBigDecimal();
    }

    /**
     * Set field DIVTO0 using a String value.
     */
    public void setDIVTO0(String newvalue) {
        fieldDIVTO0.setString(newvalue);
    }

    /**
     * Get value of field DIVTO0 as a String.
     */
    public String getDIVTO0() {
        return fieldDIVTO0.getString();
    }

    /**
     * Set numeric field DIVTO0 using a BigDecimal value.
     */
    public void setDIVTO0(BigDecimal newvalue) {
        fieldDIVTO0.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIVTO0 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIVTO0() {
        return fieldDIVTO0.getBigDecimal();
    }

    /**
     * Set field NUMTIT using a String value.
     */
    public void setNUMTIT(String newvalue) {
        fieldNUMTIT.setString(newvalue);
    }

    /**
     * Get value of field NUMTIT as a String.
     */
    public String getNUMTIT() {
        return fieldNUMTIT.getString();
    }

    /**
     * Set numeric field NUMTIT using a BigDecimal value.
     */
    public void setNUMTIT(BigDecimal newvalue) {
        fieldNUMTIT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NUMTIT as a BigDecimal.
     */
    public BigDecimal getBigDecimalNUMTIT() {
        return fieldNUMTIT.getBigDecimal();
    }

    /**
     * Set field INVVNO using a String value.
     */
    public void setINVVNO(String newvalue) {
        fieldINVVNO.setString(newvalue);
    }

    /**
     * Get value of field INVVNO as a String.
     */
    public String getINVVNO() {
        return fieldINVVNO.getString();
    }

    /**
     * Set numeric field INVVNO using a BigDecimal value.
     */
    public void setINVVNO(BigDecimal newvalue) {
        fieldINVVNO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVVNO as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVVNO() {
        return fieldINVVNO.getBigDecimal();
    }

    /**
     * Set field PRCCHE using a String value.
     */
    public void setPRCCHE(String newvalue) {
        fieldPRCCHE.setString(newvalue);
    }

    /**
     * Get value of field PRCCHE as a String.
     */
    public String getPRCCHE() {
        return fieldPRCCHE.getString();
    }

    /**
     * Set numeric field PRCCHE using a BigDecimal value.
     */
    public void setPRCCHE(BigDecimal newvalue) {
        fieldPRCCHE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field PRCCHE as a BigDecimal.
     */
    public BigDecimal getBigDecimalPRCCHE() {
        return fieldPRCCHE.getBigDecimal();
    }

    /**
     * Set field EFEINI using a String value.
     */
    public void setEFEINI(String newvalue) {
        fieldEFEINI.setString(newvalue);
    }

    /**
     * Get value of field EFEINI as a String.
     */
    public String getEFEINI() {
        return fieldEFEINI.getString();
    }

    /**
     * Set numeric field EFEINI using a BigDecimal value.
     */
    public void setEFEINI(BigDecimal newvalue) {
        fieldEFEINI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field EFEINI as a BigDecimal.
     */
    public BigDecimal getBigDecimalEFEINI() {
        return fieldEFEINI.getBigDecimal();
    }

    /**
     * Set field IMPCHE using a String value.
     */
    public void setIMPCHE(String newvalue) {
        fieldIMPCHE.setString(newvalue);
    }

    /**
     * Get value of field IMPCHE as a String.
     */
    public String getIMPCHE() {
        return fieldIMPCHE.getString();
    }

    /**
     * Set numeric field IMPCHE using a BigDecimal value.
     */
    public void setIMPCHE(BigDecimal newvalue) {
        fieldIMPCHE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IMPCHE as a BigDecimal.
     */
    public BigDecimal getBigDecimalIMPCHE() {
        return fieldIMPCHE.getBigDecimal();
    }

    /**
     * Set field INVPOP using a String value.
     */
    public void setINVPOP(String newvalue) {
        fieldINVPOP.setString(newvalue);
    }

    /**
     * Get value of field INVPOP as a String.
     */
    public String getINVPOP() {
        return fieldINVPOP.getString();
    }

    /**
     * Set numeric field INVPOP using a BigDecimal value.
     */
    public void setINVPOP(BigDecimal newvalue) {
        fieldINVPOP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVPOP as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVPOP() {
        return fieldINVPOP.getBigDecimal();
    }

    /**
     * Set field RENDIM using a String value.
     */
    public void setRENDIM(String newvalue) {
        fieldRENDIM.setString(newvalue);
    }

    /**
     * Get value of field RENDIM as a String.
     */
    public String getRENDIM() {
        return fieldRENDIM.getString();
    }

    /**
     * Set numeric field RENDIM using a BigDecimal value.
     */
    public void setRENDIM(BigDecimal newvalue) {
        fieldRENDIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field RENDIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalRENDIM() {
        return fieldRENDIM.getBigDecimal();
    }

    /**
     * Set field INVRES using a String value.
     */
    public void setINVRES(String newvalue) {
        fieldINVRES.setString(newvalue);
    }

    /**
     * Get value of field INVRES as a String.
     */
    public String getINVRES() {
        return fieldINVRES.getString();
    }

    /**
     * Set numeric field INVRES using a BigDecimal value.
     */
    public void setINVRES(BigDecimal newvalue) {
        fieldINVRES.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVRES as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVRES() {
        return fieldINVRES.getBigDecimal();
    }

    /**
     * Set field COMISI using a String value.
     */
    public void setCOMISI(String newvalue) {
        fieldCOMISI.setString(newvalue);
    }

    /**
     * Get value of field COMISI as a String.
     */
    public String getCOMISI() {
        return fieldCOMISI.getString();
    }

    /**
     * Set numeric field COMISI using a BigDecimal value.
     */
    public void setCOMISI(BigDecimal newvalue) {
        fieldCOMISI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMISI as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMISI() {
        return fieldCOMISI.getBigDecimal();
    }

    /**
     * Set field INVTIM using a String value.
     */
    public void setINVTIM(String newvalue) {
        fieldINVTIM.setString(newvalue);
    }

    /**
     * Get value of field INVTIM as a String.
     */
    public String getINVTIM() {
        return fieldINVTIM.getString();
    }

    /**
     * Set numeric field INVTIM using a BigDecimal value.
     */
    public void setINVTIM(BigDecimal newvalue) {
        fieldINVTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVTIM() {
        return fieldINVTIM.getBigDecimal();
    }

    /**
     * Set field RETENC using a String value.
     */
    public void setRETENC(String newvalue) {
        fieldRETENC.setString(newvalue);
    }

    /**
     * Get value of field RETENC as a String.
     */
    public String getRETENC() {
        return fieldRETENC.getString();
    }

    /**
     * Set field INVIBS using a String value.
     */
    public void setINVIBS(String newvalue) {
        fieldINVIBS.setString(newvalue);
    }

    /**
     * Get value of field INVIBS as a String.
     */
    public String getINVIBS() {
        return fieldINVIBS.getString();
    }

    /**
     * Set field CTASPT using a String value.
     */
    public void setCTASPT(String newvalue) {
        fieldCTASPT.setString(newvalue);
    }

    /**
     * Get value of field CTASPT as a String.
     */
    public String getCTASPT() {
        return fieldCTASPT.getString();
    }

    /**
     * Set numeric field CTASPT using a BigDecimal value.
     */
    public void setCTASPT(BigDecimal newvalue) {
        fieldCTASPT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CTASPT as a BigDecimal.
     */
    public BigDecimal getBigDecimalCTASPT() {
        return fieldCTASPT.getBigDecimal();
    }

    /**
     * Set field RENTOT using a String value.
     */
    public void setRENTOT(String newvalue) {
        fieldRENTOT.setString(newvalue);
    }

    /**
     * Get value of field RENTOT as a String.
     */
    public String getRENTOT() {
        return fieldRENTOT.getString();
    }

    /**
     * Set numeric field RENTOT using a BigDecimal value.
     */
    public void setRENTOT(BigDecimal newvalue) {
        fieldRENTOT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field RENTOT as a BigDecimal.
     */
    public BigDecimal getBigDecimalRENTOT() {
        return fieldRENTOT.getBigDecimal();
    }

    /**
     * Set field INVTOT using a String value.
     */
    public void setINVTOT(String newvalue) {
        fieldINVTOT.setString(newvalue);
    }

    /**
     * Get value of field INVTOT as a String.
     */
    public String getINVTOT() {
        return fieldINVTOT.getString();
    }

    /**
     * Set numeric field INVTOT using a BigDecimal value.
     */
    public void setINVTOT(BigDecimal newvalue) {
        fieldINVTOT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVTOT as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVTOT() {
        return fieldINVTOT.getBigDecimal();
    }

    /**
     * Set field TASAX using a String value.
     */
    public void setTASAX(String newvalue) {
        fieldTASAX.setString(newvalue);
    }

    /**
     * Get value of field TASAX as a String.
     */
    public String getTASAX() {
        return fieldTASAX.getString();
    }

    /**
     * Set numeric field TASAX using a BigDecimal value.
     */
    public void setTASAX(BigDecimal newvalue) {
        fieldTASAX.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TASAX as a BigDecimal.
     */
    public BigDecimal getBigDecimalTASAX() {
        return fieldTASAX.getBigDecimal();
    }

    /**
     * Set field RENOBT using a String value.
     */
    public void setRENOBT(String newvalue) {
        fieldRENOBT.setString(newvalue);
    }

    /**
     * Get value of field RENOBT as a String.
     */
    public String getRENOBT() {
        return fieldRENOBT.getString();
    }

    /**
     * Set numeric field RENOBT using a BigDecimal value.
     */
    public void setRENOBT(BigDecimal newvalue) {
        fieldRENOBT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field RENOBT as a BigDecimal.
     */
    public BigDecimal getBigDecimalRENOBT() {
        return fieldRENOBT.getBigDecimal();
    }

    /**
     * Set field DIEMIC using a String value.
     */
    public void setDIEMIC(String newvalue) {
        fieldDIEMIC.setString(newvalue);
    }

    /**
     * Get value of field DIEMIC as a String.
     */
    public String getDIEMIC() {
        return fieldDIEMIC.getString();
    }

    /**
     * Set numeric field DIEMIC using a BigDecimal value.
     */
    public void setDIEMIC(BigDecimal newvalue) {
        fieldDIEMIC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIEMIC as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIEMIC() {
        return fieldDIEMIC.getBigDecimal();
    }

    /**
     * Set field INVBAS using a String value.
     */
    public void setINVBAS(String newvalue) {
        fieldINVBAS.setString(newvalue);
    }

    /**
     * Get value of field INVBAS as a String.
     */
    public String getINVBAS() {
        return fieldINVBAS.getString();
    }

    /**
     * Set numeric field INVBAS using a BigDecimal value.
     */
    public void setINVBAS(BigDecimal newvalue) {
        fieldINVBAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVBAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVBAS() {
        return fieldINVBAS.getBigDecimal();
    }

    /**
     * Set field DIHOYC using a String value.
     */
    public void setDIHOYC(String newvalue) {
        fieldDIHOYC.setString(newvalue);
    }

    /**
     * Get value of field DIHOYC as a String.
     */
    public String getDIHOYC() {
        return fieldDIHOYC.getString();
    }

    /**
     * Set numeric field DIHOYC using a BigDecimal value.
     */
    public void setDIHOYC(BigDecimal newvalue) {
        fieldDIHOYC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIHOYC as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIHOYC() {
        return fieldDIHOYC.getBigDecimal();
    }

    /**
     * Set field INVENC using a String value.
     */
    public void setINVENC(String newvalue) {
        fieldINVENC.setString(newvalue);
    }

    /**
     * Get value of field INVENC as a String.
     */
    public String getINVENC() {
        return fieldINVENC.getString();
    }

    /**
     * Set numeric field INVENC using a BigDecimal value.
     */
    public void setINVENC(BigDecimal newvalue) {
        fieldINVENC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVENC as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVENC() {
        return fieldINVENC.getBigDecimal();
    }

    /**
     * Set field BASCAC using a String value.
     */
    public void setBASCAC(String newvalue) {
        fieldBASCAC.setString(newvalue);
    }

    /**
     * Get value of field BASCAC as a String.
     */
    public String getBASCAC() {
        return fieldBASCAC.getString();
    }

    /**
     * Set numeric field BASCAC using a BigDecimal value.
     */
    public void setBASCAC(BigDecimal newvalue) {
        fieldBASCAC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BASCAC as a BigDecimal.
     */
    public BigDecimal getBigDecimalBASCAC() {
        return fieldBASCAC.getBigDecimal();
    }

    /**
     * Set field DIVTOC using a String value.
     */
    public void setDIVTOC(String newvalue) {
        fieldDIVTOC.setString(newvalue);
    }

    /**
     * Get value of field DIVTOC as a String.
     */
    public String getDIVTOC() {
        return fieldDIVTOC.getString();
    }

    /**
     * Set numeric field DIVTOC using a BigDecimal value.
     */
    public void setDIVTOC(BigDecimal newvalue) {
        fieldDIVTOC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIVTOC as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIVTOC() {
        return fieldDIVTOC.getBigDecimal();
    }

    /**
     * Set field INTTOT using a String value.
     */
    public void setINTTOT(String newvalue) {
        fieldINTTOT.setString(newvalue);
    }

    /**
     * Get value of field INTTOT as a String.
     */
    public String getINTTOT() {
        return fieldINTTOT.getString();
    }

    /**
     * Set numeric field INTTOT using a BigDecimal value.
     */
    public void setINTTOT(BigDecimal newvalue) {
        fieldINTTOT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INTTOT as a BigDecimal.
     */
    public BigDecimal getBigDecimalINTTOT() {
        return fieldINTTOT.getBigDecimal();
    }

    /**
     * Set field VALCAP using a String value.
     */
    public void setVALCAP(String newvalue) {
        fieldVALCAP.setString(newvalue);
    }

    /**
     * Get value of field VALCAP as a String.
     */
    public String getVALCAP() {
        return fieldVALCAP.getString();
    }

    /**
     * Set numeric field VALCAP using a BigDecimal value.
     */
    public void setVALCAP(BigDecimal newvalue) {
        fieldVALCAP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VALCAP as a BigDecimal.
     */
    public BigDecimal getBigDecimalVALCAP() {
        return fieldVALCAP.getBigDecimal();
    }

    /**
     * Set field VALACT using a String value.
     */
    public void setVALACT(String newvalue) {
        fieldVALACT.setString(newvalue);
    }

    /**
     * Get value of field VALACT as a String.
     */
    public String getVALACT() {
        return fieldVALACT.getString();
    }

    /**
     * Set numeric field VALACT using a BigDecimal value.
     */
    public void setVALACT(BigDecimal newvalue) {
        fieldVALACT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VALACT as a BigDecimal.
     */
    public BigDecimal getBigDecimalVALACT() {
        return fieldVALACT.getBigDecimal();
    }

    /**
     * Set field AUXIL using a String value.
     */
    public void setAUXIL(String newvalue) {
        fieldAUXIL.setString(newvalue);
    }

    /**
     * Get value of field AUXIL as a String.
     */
    public String getAUXIL() {
        return fieldAUXIL.getString();
    }

    /**
     * Set numeric field AUXIL using a BigDecimal value.
     */
    public void setAUXIL(BigDecimal newvalue) {
        fieldAUXIL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field AUXIL as a BigDecimal.
     */
    public BigDecimal getBigDecimalAUXIL() {
        return fieldAUXIL.getBigDecimal();
    }

    /**
     * Set field EFEFIN using a String value.
     */
    public void setEFEFIN(String newvalue) {
        fieldEFEFIN.setString(newvalue);
    }

    /**
     * Get value of field EFEFIN as a String.
     */
    public String getEFEFIN() {
        return fieldEFEFIN.getString();
    }

    /**
     * Set numeric field EFEFIN using a BigDecimal value.
     */
    public void setEFEFIN(BigDecimal newvalue) {
        fieldEFEFIN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field EFEFIN as a BigDecimal.
     */
    public BigDecimal getBigDecimalEFEFIN() {
        return fieldEFEFIN.getBigDecimal();
    }

    /**
     * Set field PRIMA using a String value.
     */
    public void setPRIMA(String newvalue) {
        fieldPRIMA.setString(newvalue);
    }

    /**
     * Get value of field PRIMA as a String.
     */
    public String getPRIMA() {
        return fieldPRIMA.getString();
    }

    /**
     * Set numeric field PRIMA using a BigDecimal value.
     */
    public void setPRIMA(BigDecimal newvalue) {
        fieldPRIMA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field PRIMA as a BigDecimal.
     */
    public BigDecimal getBigDecimalPRIMA() {
        return fieldPRIMA.getBigDecimal();
    }

    /**
     * Set field TIMBRE using a String value.
     */
    public void setTIMBRE(String newvalue) {
        fieldTIMBRE.setString(newvalue);
    }

    /**
     * Get value of field TIMBRE as a String.
     */
    public String getTIMBRE() {
        return fieldTIMBRE.getString();
    }

    /**
     * Set numeric field TIMBRE using a BigDecimal value.
     */
    public void setTIMBRE(BigDecimal newvalue) {
        fieldTIMBRE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TIMBRE as a BigDecimal.
     */
    public BigDecimal getBigDecimalTIMBRE() {
        return fieldTIMBRE.getBigDecimal();
    }

    /**
     * Set field INACUM using a String value.
     */
    public void setINACUM(String newvalue) {
        fieldINACUM.setString(newvalue);
    }

    /**
     * Get value of field INACUM as a String.
     */
    public String getINACUM() {
        return fieldINACUM.getString();
    }

    /**
     * Set numeric field INACUM using a BigDecimal value.
     */
    public void setINACUM(BigDecimal newvalue) {
        fieldINACUM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INACUM as a BigDecimal.
     */
    public BigDecimal getBigDecimalINACUM() {
        return fieldINACUM.getBigDecimal();
    }

    /**
     * Set field GRUPO using a String value.
     */
    public void setGRUPO(String newvalue) {
        fieldGRUPO.setString(newvalue);
    }

    /**
     * Get value of field GRUPO as a String.
     */
    public String getGRUPO() {
        return fieldGRUPO.getString();
    }

    /**
     * Set field OPC using a String value.
     */
    public void setOPC(String newvalue) {
        fieldOPC.setString(newvalue);
    }

    /**
     * Get value of field OPC as a String.
     */
    public String getOPC() {
        return fieldOPC.getString();
    }

    /**
     * Set field NUMEROC using a String value.
     */
    public void setNUMEROC(String newvalue) {
        fieldNUMEROC.setString(newvalue);
    }

    /**
     * Get value of field NUMEROC as a String.
     */
    public String getNUMEROC() {
        return fieldNUMEROC.getString();
    }

    /**
     * Set numeric field NUMEROC using a BigDecimal value.
     */
    public void setNUMEROC(BigDecimal newvalue) {
        fieldNUMEROC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NUMEROC as a BigDecimal.
     */
    public BigDecimal getBigDecimalNUMEROC() {
        return fieldNUMEROC.getBigDecimal();
    }

    /**
     * Set field AREASFL using a String value.
     */
    public void setAREASFL(String newvalue) {
        fieldAREASFL.setString(newvalue);
    }

    /**
     * Get value of field AREASFL as a String.
     */
    public String getAREASFL() {
        return fieldAREASFL.getString();
    }

    /**
     * Set field NOMSFL using a String value.
     */
    public void setNOMSFL(String newvalue) {
        fieldNOMSFL.setString(newvalue);
    }

    /**
     * Get value of field NOMSFL as a String.
     */
    public String getNOMSFL() {
        return fieldNOMSFL.getString();
    }

    /**
     * Set field DISSFL using a String value.
     */
    public void setDISSFL(String newvalue) {
        fieldDISSFL.setString(newvalue);
    }

    /**
     * Get value of field DISSFL as a String.
     */
    public String getDISSFL() {
        return fieldDISSFL.getString();
    }

    /**
     * Set numeric field DISSFL using a BigDecimal value.
     */
    public void setDISSFL(BigDecimal newvalue) {
        fieldDISSFL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DISSFL as a BigDecimal.
     */
    public BigDecimal getBigDecimalDISSFL() {
        return fieldDISSFL.getBigDecimal();
    }

    /**
     * Set field IMPSFL using a String value.
     */
    public void setIMPSFL(String newvalue) {
        fieldIMPSFL.setString(newvalue);
    }

    /**
     * Get value of field IMPSFL as a String.
     */
    public String getIMPSFL() {
        return fieldIMPSFL.getString();
    }

    /**
     * Set numeric field IMPSFL using a BigDecimal value.
     */
    public void setIMPSFL(BigDecimal newvalue) {
        fieldIMPSFL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IMPSFL as a BigDecimal.
     */
    public BigDecimal getBigDecimalIMPSFL() {
        return fieldIMPSFL.getBigDecimal();
    }

    /**
     * Set field COTDIV using a String value.
     */
    public void setCOTDIV(String newvalue) {
        fieldCOTDIV.setString(newvalue);
    }

    /**
     * Get value of field COTDIV as a String.
     */
    public String getCOTDIV() {
        return fieldCOTDIV.getString();
    }

    /**
     * Set numeric field COTDIV using a BigDecimal value.
     */
    public void setCOTDIV(BigDecimal newvalue) {
        fieldCOTDIV.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COTDIV as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOTDIV() {
        return fieldCOTDIV.getBigDecimal();
    }

    /**
     * Set field RESTANTE using a String value.
     */
    public void setRESTANTE(String newvalue) {
        fieldRESTANTE.setString(newvalue);
    }

    /**
     * Get value of field RESTANTE as a String.
     */
    public String getRESTANTE() {
        return fieldRESTANTE.getString();
    }

    /**
     * Set numeric field RESTANTE using a BigDecimal value.
     */
    public void setRESTANTE(BigDecimal newvalue) {
        fieldRESTANTE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field RESTANTE as a BigDecimal.
     */
    public BigDecimal getBigDecimalRESTANTE() {
        return fieldRESTANTE.getBigDecimal();
    }

    /**
     * Set field AREACTL using a String value.
     */
    public void setAREACTL(String newvalue) {
        fieldAREACTL.setString(newvalue);
    }

    /**
     * Get value of field AREACTL as a String.
     */
    public String getAREACTL() {
        return fieldAREACTL.getString();
    }

    /**
     * Set field NOMCTL using a String value.
     */
    public void setNOMCTL(String newvalue) {
        fieldNOMCTL.setString(newvalue);
    }

    /**
     * Get value of field NOMCTL as a String.
     */
    public String getNOMCTL() {
        return fieldNOMCTL.getString();
    }

    /**
     * Set field DISCTL using a String value.
     */
    public void setDISCTL(String newvalue) {
        fieldDISCTL.setString(newvalue);
    }

    /**
     * Get value of field DISCTL as a String.
     */
    public String getDISCTL() {
        return fieldDISCTL.getString();
    }

    /**
     * Set numeric field DISCTL using a BigDecimal value.
     */
    public void setDISCTL(BigDecimal newvalue) {
        fieldDISCTL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DISCTL as a BigDecimal.
     */
    public BigDecimal getBigDecimalDISCTL() {
        return fieldDISCTL.getBigDecimal();
    }

    /**
     * Set field IMPCTL using a String value.
     */
    public void setIMPCTL(String newvalue) {
        fieldIMPCTL.setString(newvalue);
    }

    /**
     * Get value of field IMPCTL as a String.
     */
    public String getIMPCTL() {
        return fieldIMPCTL.getString();
    }

    /**
     * Set numeric field IMPCTL using a BigDecimal value.
     */
    public void setIMPCTL(BigDecimal newvalue) {
        fieldIMPCTL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IMPCTL as a BigDecimal.
     */
    public BigDecimal getBigDecimalIMPCTL() {
        return fieldIMPCTL.getBigDecimal();
    }

}
