package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from GP0036FM physical file
 * definition.
 * 
* File level identifier is 1140321095046. Record format level identifier is
 * 4CD7C22B3C76F.
 */
public class GP0036FMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "TABNOM",
        "VALOR",
        "NOMVAL",
        "CODCLI",
        "NOMCLI",
        "NOMDIV",
        "VLOFIS",
        "NOMEMI",
        "INVINT",
        "NOMINT",
        "TIPVAL",
        "NROTIT",
        "VLOUDE",
        "VLOUCA",
        "FECINI",
        "FECVTO",
        "INVLIQ",
        "INVBVI",
        "INVNOP",
        "BASECA",
        "BASEDI",
        "DIEMI5",
        "DIEMI0",
        "VLOUNI",
        "DIHOY5",
        "DIHOY0",
        "VLOTAS",
        "DIVTO5",
        "DIVTO0",
        "NUMTIT",
        "INVVNO",
        "PRCCHE",
        "EFEINI",
        "IMPCHEP",
        "INVPOP",
        "RENDIM",
        "INVRES",
        "COMISI",
        "INVTIM",
        "RETENC",
        "INVIBS",
        "CTASPT",
        "RENTOT",
        "INVTOT",
        "TASAX",
        "RENOBT",
        "DIEMIC",
        "INVBAS",
        "DIHOYC",
        "INVENC",
        "BASCAC",
        "DIVTOC",
        "INTTOT",
        "VALCAP",
        "VALACT",
        "AUXIL",
        "EFEFIN",
        "PRIMA",
        "TIMBRE",
        "INACUM",
        "RESTO"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "TABNOM",
        "VALOR",
        "NOMVAL",
        "CODCLI",
        "NOMCLI",
        "NOMDIV",
        "VLOFIS",
        "NOMEMI",
        "INVINT",
        "NOMINT",
        "TIPVAL",
        "NROTIT",
        "VLOUDE",
        "VLOUCA",
        "FECINI",
        "FECVTO",
        "INVLIQ",
        "INVBVI",
        "INVNOP",
        "BASECA",
        "BASEDI",
        "DIEMI5",
        "DIEMI0",
        "VLOUNI",
        "DIHOY5",
        "DIHOY0",
        "VLOTAS",
        "DIVTO5",
        "DIVTO0",
        "NUMTIT",
        "INVVNO",
        "PRCCHE",
        "EFEINI",
        "IMPCHEP",
        "INVPOP",
        "RENDIM",
        "INVRES",
        "COMISI",
        "INVTIM",
        "RETENC",
        "INVIBS",
        "CTASPT",
        "RENTOT",
        "INVTOT",
        "TASAX",
        "RENOBT",
        "DIEMIC",
        "INVBAS",
        "DIHOYC",
        "INVENC",
        "BASCAC",
        "DIVTOC",
        "INTTOT",
        "VALCAP",
        "VALACT",
        "AUXIL",
        "EFEFIN",
        "PRIMA",
        "TIMBRE",
        "INACUM",
        "RESTO"
    };
    final static String fid = "1140321095046";
    final static String rid = "4CD7C22B3C76F";
    final static String fmtname = "GP0036FM";
    final int FIELDCOUNT = 70;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldTABNOM = null;
    private CharacterField fieldVALOR = null;
    private CharacterField fieldNOMVAL = null;
    private DecimalField fieldCODCLI = null;
    private CharacterField fieldNOMCLI = null;
    private CharacterField fieldNOMDIV = null;
    private DecimalField fieldVLOFIS = null;
    private CharacterField fieldNOMEMI = null;
    private DecimalField fieldINVINT = null;
    private CharacterField fieldNOMINT = null;
    private CharacterField fieldTIPVAL = null;
    private DecimalField fieldNROTIT = null;
    private DecimalField fieldVLOUDE = null;
    private DecimalField fieldVLOUCA = null;
    private DecimalField fieldFECINI = null;
    private DecimalField fieldFECVTO = null;
    private DecimalField fieldINVLIQ = null;
    private DecimalField fieldINVBVI = null;
    private DecimalField fieldINVNOP = null;
    private DecimalField fieldBASECA = null;
    private DecimalField fieldBASEDI = null;
    private DecimalField fieldDIEMI5 = null;
    private DecimalField fieldDIEMI0 = null;
    private DecimalField fieldVLOUNI = null;
    private DecimalField fieldDIHOY5 = null;
    private DecimalField fieldDIHOY0 = null;
    private DecimalField fieldVLOTAS = null;
    private DecimalField fieldDIVTO5 = null;
    private DecimalField fieldDIVTO0 = null;
    private DecimalField fieldNUMTIT = null;
    private DecimalField fieldINVVNO = null;
    private DecimalField fieldPRCCHE = null;
    private DecimalField fieldEFEINI = null;
    private DecimalField fieldIMPCHEP = null;
    private DecimalField fieldINVPOP = null;
    private DecimalField fieldRENDIM = null;
    private DecimalField fieldINVRES = null;
    private DecimalField fieldCOMISI = null;
    private DecimalField fieldINVTIM = null;
    private CharacterField fieldRETENC = null;
    private CharacterField fieldINVIBS = null;
    private DecimalField fieldCTASPT = null;
    private DecimalField fieldRENTOT = null;
    private DecimalField fieldINVTOT = null;
    private DecimalField fieldTASAX = null;
    private DecimalField fieldRENOBT = null;
    private DecimalField fieldDIEMIC = null;
    private DecimalField fieldINVBAS = null;
    private DecimalField fieldDIHOYC = null;
    private DecimalField fieldINVENC = null;
    private DecimalField fieldBASCAC = null;
    private DecimalField fieldDIVTOC = null;
    private DecimalField fieldINTTOT = null;
    private DecimalField fieldVALCAP = null;
    private DecimalField fieldVALACT = null;
    private DecimalField fieldAUXIL = null;
    private DecimalField fieldEFEFIN = null;
    private DecimalField fieldPRIMA = null;
    private DecimalField fieldTIMBRE = null;
    private DecimalField fieldINACUM = null;
    private DecimalField fieldRESTO = null;

    /**
     * Constructor for GP0036FMMessage.
     */
    public GP0036FMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 931;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldTABNOM
                = new CharacterField(message, HEADERSIZE + 161, 40, "TABNOM");
        fields[10] = fieldVALOR
                = new CharacterField(message, HEADERSIZE + 201, 12, "VALOR");
        fields[11] = fieldNOMVAL
                = new CharacterField(message, HEADERSIZE + 213, 34, "NOMVAL");
        fields[12] = fieldCODCLI
                = new DecimalField(message, HEADERSIZE + 247, 8, 0, "CODCLI");
        fields[13] = fieldNOMCLI
                = new CharacterField(message, HEADERSIZE + 255, 39, "NOMCLI");
        fields[14] = fieldNOMDIV
                = new CharacterField(message, HEADERSIZE + 294, 20, "NOMDIV");
        fields[15] = fieldVLOFIS
                = new DecimalField(message, HEADERSIZE + 314, 8, 0, "VLOFIS");
        fields[16] = fieldNOMEMI
                = new CharacterField(message, HEADERSIZE + 322, 39, "NOMEMI");
        fields[17] = fieldINVINT
                = new DecimalField(message, HEADERSIZE + 361, 8, 0, "INVINT");
        fields[18] = fieldNOMINT
                = new CharacterField(message, HEADERSIZE + 369, 39, "NOMINT");
        fields[19] = fieldTIPVAL
                = new CharacterField(message, HEADERSIZE + 408, 3, "TIPVAL");
        fields[20] = fieldNROTIT
                = new DecimalField(message, HEADERSIZE + 411, 11, 0, "NROTIT");
        fields[21] = fieldVLOUDE
                = new DecimalField(message, HEADERSIZE + 422, 7, 0, "VLOUDE");
        fields[22] = fieldVLOUCA
                = new DecimalField(message, HEADERSIZE + 429, 7, 0, "VLOUCA");
        fields[23] = fieldFECINI
                = new DecimalField(message, HEADERSIZE + 436, 7, 0, "FECINI");
        fields[24] = fieldFECVTO
                = new DecimalField(message, HEADERSIZE + 443, 7, 0, "FECVTO");
        fields[25] = fieldINVLIQ
                = new DecimalField(message, HEADERSIZE + 450, 7, 0, "INVLIQ");
        fields[26] = fieldINVBVI
                = new DecimalField(message, HEADERSIZE + 457, 8, 0, "INVBVI");
        fields[27] = fieldINVNOP
                = new DecimalField(message, HEADERSIZE + 465, 11, 0, "INVNOP");
        fields[28] = fieldBASECA
                = new DecimalField(message, HEADERSIZE + 476, 2, 0, "BASECA");
        fields[29] = fieldBASEDI
                = new DecimalField(message, HEADERSIZE + 478, 2, 0, "BASEDI");
        fields[30] = fieldDIEMI5
                = new DecimalField(message, HEADERSIZE + 480, 5, 0, "DIEMI5");
        fields[31] = fieldDIEMI0
                = new DecimalField(message, HEADERSIZE + 485, 5, 0, "DIEMI0");
        fields[32] = fieldVLOUNI
                = new DecimalField(message, HEADERSIZE + 490, 15, 2, "VLOUNI");
        fields[33] = fieldDIHOY5
                = new DecimalField(message, HEADERSIZE + 505, 5, 0, "DIHOY5");
        fields[34] = fieldDIHOY0
                = new DecimalField(message, HEADERSIZE + 510, 5, 0, "DIHOY0");
        fields[35] = fieldVLOTAS
                = new DecimalField(message, HEADERSIZE + 515, 11, 6, "VLOTAS");
        fields[36] = fieldDIVTO5
                = new DecimalField(message, HEADERSIZE + 526, 5, 0, "DIVTO5");
        fields[37] = fieldDIVTO0
                = new DecimalField(message, HEADERSIZE + 531, 5, 0, "DIVTO0");
        fields[38] = fieldNUMTIT
                = new DecimalField(message, HEADERSIZE + 536, 29, 7, "NUMTIT");
        fields[39] = fieldINVVNO
                = new DecimalField(message, HEADERSIZE + 565, 17, 2, "INVVNO");
        fields[40] = fieldPRCCHE
                = new DecimalField(message, HEADERSIZE + 582, 8, 3, "PRCCHE");
        fields[41] = fieldEFEINI
                = new DecimalField(message, HEADERSIZE + 590, 17, 2, "EFEINI");
        fields[42] = fieldIMPCHEP
                = new DecimalField(message, HEADERSIZE + 607, 12, 2, "IMPCHEP");
        fields[43] = fieldINVPOP
                = new DecimalField(message, HEADERSIZE + 619, 11, 6, "INVPOP");
        fields[44] = fieldRENDIM
                = new DecimalField(message, HEADERSIZE + 630, 11, 6, "RENDIM");
        fields[45] = fieldINVRES
                = new DecimalField(message, HEADERSIZE + 641, 11, 6, "INVRES");
        fields[46] = fieldCOMISI
                = new DecimalField(message, HEADERSIZE + 652, 11, 6, "COMISI");
        fields[47] = fieldINVTIM
                = new DecimalField(message, HEADERSIZE + 663, 11, 6, "INVTIM");
        fields[48] = fieldRETENC
                = new CharacterField(message, HEADERSIZE + 674, 1, "RETENC");
        fields[49] = fieldINVIBS
                = new CharacterField(message, HEADERSIZE + 675, 1, "INVIBS");
        fields[50] = fieldCTASPT
                = new DecimalField(message, HEADERSIZE + 676, 17, 2, "CTASPT");
        fields[51] = fieldRENTOT
                = new DecimalField(message, HEADERSIZE + 693, 11, 6, "RENTOT");
        fields[52] = fieldINVTOT
                = new DecimalField(message, HEADERSIZE + 704, 11, 6, "INVTOT");
        fields[53] = fieldTASAX
                = new DecimalField(message, HEADERSIZE + 715, 11, 6, "TASAX");
        fields[54] = fieldRENOBT
                = new DecimalField(message, HEADERSIZE + 726, 11, 6, "RENOBT");
        fields[55] = fieldDIEMIC
                = new DecimalField(message, HEADERSIZE + 737, 5, 0, "DIEMIC");
        fields[56] = fieldINVBAS
                = new DecimalField(message, HEADERSIZE + 742, 11, 6, "INVBAS");
        fields[57] = fieldDIHOYC
                = new DecimalField(message, HEADERSIZE + 753, 5, 0, "DIHOYC");
        fields[58] = fieldINVENC
                = new DecimalField(message, HEADERSIZE + 758, 11, 6, "INVENC");
        fields[59] = fieldBASCAC
                = new DecimalField(message, HEADERSIZE + 769, 4, 0, "BASCAC");
        fields[60] = fieldDIVTOC
                = new DecimalField(message, HEADERSIZE + 773, 5, 0, "DIVTOC");
        fields[61] = fieldINTTOT
                = new DecimalField(message, HEADERSIZE + 778, 17, 2, "INTTOT");
        fields[62] = fieldVALCAP
                = new DecimalField(message, HEADERSIZE + 795, 17, 2, "VALCAP");
        fields[63] = fieldVALACT
                = new DecimalField(message, HEADERSIZE + 812, 17, 2, "VALACT");
        fields[64] = fieldAUXIL
                = new DecimalField(message, HEADERSIZE + 829, 17, 2, "AUXIL");
        fields[65] = fieldEFEFIN
                = new DecimalField(message, HEADERSIZE + 846, 17, 2, "EFEFIN");
        fields[66] = fieldPRIMA
                = new DecimalField(message, HEADERSIZE + 863, 17, 2, "PRIMA");
        fields[67] = fieldTIMBRE
                = new DecimalField(message, HEADERSIZE + 880, 17, 2, "TIMBRE");
        fields[68] = fieldINACUM
                = new DecimalField(message, HEADERSIZE + 897, 17, 2, "INACUM");
        fields[69] = fieldRESTO
                = new DecimalField(message, HEADERSIZE + 914, 17, 2, "RESTO");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field TABNOM using a String value.
     */
    public void setTABNOM(String newvalue) {
        fieldTABNOM.setString(newvalue);
    }

    /**
     * Get value of field TABNOM as a String.
     */
    public String getTABNOM() {
        return fieldTABNOM.getString();
    }

    /**
     * Set field VALOR using a String value.
     */
    public void setVALOR(String newvalue) {
        fieldVALOR.setString(newvalue);
    }

    /**
     * Get value of field VALOR as a String.
     */
    public String getVALOR() {
        return fieldVALOR.getString();
    }

    /**
     * Set field NOMVAL using a String value.
     */
    public void setNOMVAL(String newvalue) {
        fieldNOMVAL.setString(newvalue);
    }

    /**
     * Get value of field NOMVAL as a String.
     */
    public String getNOMVAL() {
        return fieldNOMVAL.getString();
    }

    /**
     * Set field CODCLI using a String value.
     */
    public void setCODCLI(String newvalue) {
        fieldCODCLI.setString(newvalue);
    }

    /**
     * Get value of field CODCLI as a String.
     */
    public String getCODCLI() {
        return fieldCODCLI.getString();
    }

    /**
     * Set numeric field CODCLI using a BigDecimal value.
     */
    public void setCODCLI(BigDecimal newvalue) {
        fieldCODCLI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CODCLI as a BigDecimal.
     */
    public BigDecimal getBigDecimalCODCLI() {
        return fieldCODCLI.getBigDecimal();
    }

    /**
     * Set field NOMCLI using a String value.
     */
    public void setNOMCLI(String newvalue) {
        fieldNOMCLI.setString(newvalue);
    }

    /**
     * Get value of field NOMCLI as a String.
     */
    public String getNOMCLI() {
        return fieldNOMCLI.getString();
    }

    /**
     * Set field NOMDIV using a String value.
     */
    public void setNOMDIV(String newvalue) {
        fieldNOMDIV.setString(newvalue);
    }

    /**
     * Get value of field NOMDIV as a String.
     */
    public String getNOMDIV() {
        return fieldNOMDIV.getString();
    }

    /**
     * Set field VLOFIS using a String value.
     */
    public void setVLOFIS(String newvalue) {
        fieldVLOFIS.setString(newvalue);
    }

    /**
     * Get value of field VLOFIS as a String.
     */
    public String getVLOFIS() {
        return fieldVLOFIS.getString();
    }

    /**
     * Set numeric field VLOFIS using a BigDecimal value.
     */
    public void setVLOFIS(BigDecimal newvalue) {
        fieldVLOFIS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOFIS as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOFIS() {
        return fieldVLOFIS.getBigDecimal();
    }

    /**
     * Set field NOMEMI using a String value.
     */
    public void setNOMEMI(String newvalue) {
        fieldNOMEMI.setString(newvalue);
    }

    /**
     * Get value of field NOMEMI as a String.
     */
    public String getNOMEMI() {
        return fieldNOMEMI.getString();
    }

    /**
     * Set field INVINT using a String value.
     */
    public void setINVINT(String newvalue) {
        fieldINVINT.setString(newvalue);
    }

    /**
     * Get value of field INVINT as a String.
     */
    public String getINVINT() {
        return fieldINVINT.getString();
    }

    /**
     * Set numeric field INVINT using a BigDecimal value.
     */
    public void setINVINT(BigDecimal newvalue) {
        fieldINVINT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVINT as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVINT() {
        return fieldINVINT.getBigDecimal();
    }

    /**
     * Set field NOMINT using a String value.
     */
    public void setNOMINT(String newvalue) {
        fieldNOMINT.setString(newvalue);
    }

    /**
     * Get value of field NOMINT as a String.
     */
    public String getNOMINT() {
        return fieldNOMINT.getString();
    }

    /**
     * Set field TIPVAL using a String value.
     */
    public void setTIPVAL(String newvalue) {
        fieldTIPVAL.setString(newvalue);
    }

    /**
     * Get value of field TIPVAL as a String.
     */
    public String getTIPVAL() {
        return fieldTIPVAL.getString();
    }

    /**
     * Set field NROTIT using a String value.
     */
    public void setNROTIT(String newvalue) {
        fieldNROTIT.setString(newvalue);
    }

    /**
     * Get value of field NROTIT as a String.
     */
    public String getNROTIT() {
        return fieldNROTIT.getString();
    }

    /**
     * Set numeric field NROTIT using a BigDecimal value.
     */
    public void setNROTIT(BigDecimal newvalue) {
        fieldNROTIT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NROTIT as a BigDecimal.
     */
    public BigDecimal getBigDecimalNROTIT() {
        return fieldNROTIT.getBigDecimal();
    }

    /**
     * Set field VLOUDE using a String value.
     */
    public void setVLOUDE(String newvalue) {
        fieldVLOUDE.setString(newvalue);
    }

    /**
     * Get value of field VLOUDE as a String.
     */
    public String getVLOUDE() {
        return fieldVLOUDE.getString();
    }

    /**
     * Set numeric field VLOUDE using a BigDecimal value.
     */
    public void setVLOUDE(BigDecimal newvalue) {
        fieldVLOUDE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUDE as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUDE() {
        return fieldVLOUDE.getBigDecimal();
    }

    /**
     * Set field VLOUCA using a String value.
     */
    public void setVLOUCA(String newvalue) {
        fieldVLOUCA.setString(newvalue);
    }

    /**
     * Get value of field VLOUCA as a String.
     */
    public String getVLOUCA() {
        return fieldVLOUCA.getString();
    }

    /**
     * Set numeric field VLOUCA using a BigDecimal value.
     */
    public void setVLOUCA(BigDecimal newvalue) {
        fieldVLOUCA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUCA as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUCA() {
        return fieldVLOUCA.getBigDecimal();
    }

    /**
     * Set field FECINI using a String value.
     */
    public void setFECINI(String newvalue) {
        fieldFECINI.setString(newvalue);
    }

    /**
     * Get value of field FECINI as a String.
     */
    public String getFECINI() {
        return fieldFECINI.getString();
    }

    /**
     * Set numeric field FECINI using a BigDecimal value.
     */
    public void setFECINI(BigDecimal newvalue) {
        fieldFECINI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECINI as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECINI() {
        return fieldFECINI.getBigDecimal();
    }

    /**
     * Set field FECVTO using a String value.
     */
    public void setFECVTO(String newvalue) {
        fieldFECVTO.setString(newvalue);
    }

    /**
     * Get value of field FECVTO as a String.
     */
    public String getFECVTO() {
        return fieldFECVTO.getString();
    }

    /**
     * Set numeric field FECVTO using a BigDecimal value.
     */
    public void setFECVTO(BigDecimal newvalue) {
        fieldFECVTO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECVTO as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECVTO() {
        return fieldFECVTO.getBigDecimal();
    }

    /**
     * Set field INVLIQ using a String value.
     */
    public void setINVLIQ(String newvalue) {
        fieldINVLIQ.setString(newvalue);
    }

    /**
     * Get value of field INVLIQ as a String.
     */
    public String getINVLIQ() {
        return fieldINVLIQ.getString();
    }

    /**
     * Set numeric field INVLIQ using a BigDecimal value.
     */
    public void setINVLIQ(BigDecimal newvalue) {
        fieldINVLIQ.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVLIQ as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVLIQ() {
        return fieldINVLIQ.getBigDecimal();
    }

    /**
     * Set field INVBVI using a String value.
     */
    public void setINVBVI(String newvalue) {
        fieldINVBVI.setString(newvalue);
    }

    /**
     * Get value of field INVBVI as a String.
     */
    public String getINVBVI() {
        return fieldINVBVI.getString();
    }

    /**
     * Set numeric field INVBVI using a BigDecimal value.
     */
    public void setINVBVI(BigDecimal newvalue) {
        fieldINVBVI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVBVI as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVBVI() {
        return fieldINVBVI.getBigDecimal();
    }

    /**
     * Set field INVNOP using a String value.
     */
    public void setINVNOP(String newvalue) {
        fieldINVNOP.setString(newvalue);
    }

    /**
     * Get value of field INVNOP as a String.
     */
    public String getINVNOP() {
        return fieldINVNOP.getString();
    }

    /**
     * Set numeric field INVNOP using a BigDecimal value.
     */
    public void setINVNOP(BigDecimal newvalue) {
        fieldINVNOP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVNOP as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVNOP() {
        return fieldINVNOP.getBigDecimal();
    }

    /**
     * Set field BASECA using a String value.
     */
    public void setBASECA(String newvalue) {
        fieldBASECA.setString(newvalue);
    }

    /**
     * Get value of field BASECA as a String.
     */
    public String getBASECA() {
        return fieldBASECA.getString();
    }

    /**
     * Set numeric field BASECA using a BigDecimal value.
     */
    public void setBASECA(BigDecimal newvalue) {
        fieldBASECA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BASECA as a BigDecimal.
     */
    public BigDecimal getBigDecimalBASECA() {
        return fieldBASECA.getBigDecimal();
    }

    /**
     * Set field BASEDI using a String value.
     */
    public void setBASEDI(String newvalue) {
        fieldBASEDI.setString(newvalue);
    }

    /**
     * Get value of field BASEDI as a String.
     */
    public String getBASEDI() {
        return fieldBASEDI.getString();
    }

    /**
     * Set numeric field BASEDI using a BigDecimal value.
     */
    public void setBASEDI(BigDecimal newvalue) {
        fieldBASEDI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BASEDI as a BigDecimal.
     */
    public BigDecimal getBigDecimalBASEDI() {
        return fieldBASEDI.getBigDecimal();
    }

    /**
     * Set field DIEMI5 using a String value.
     */
    public void setDIEMI5(String newvalue) {
        fieldDIEMI5.setString(newvalue);
    }

    /**
     * Get value of field DIEMI5 as a String.
     */
    public String getDIEMI5() {
        return fieldDIEMI5.getString();
    }

    /**
     * Set numeric field DIEMI5 using a BigDecimal value.
     */
    public void setDIEMI5(BigDecimal newvalue) {
        fieldDIEMI5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIEMI5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIEMI5() {
        return fieldDIEMI5.getBigDecimal();
    }

    /**
     * Set field DIEMI0 using a String value.
     */
    public void setDIEMI0(String newvalue) {
        fieldDIEMI0.setString(newvalue);
    }

    /**
     * Get value of field DIEMI0 as a String.
     */
    public String getDIEMI0() {
        return fieldDIEMI0.getString();
    }

    /**
     * Set numeric field DIEMI0 using a BigDecimal value.
     */
    public void setDIEMI0(BigDecimal newvalue) {
        fieldDIEMI0.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIEMI0 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIEMI0() {
        return fieldDIEMI0.getBigDecimal();
    }

    /**
     * Set field VLOUNI using a String value.
     */
    public void setVLOUNI(String newvalue) {
        fieldVLOUNI.setString(newvalue);
    }

    /**
     * Get value of field VLOUNI as a String.
     */
    public String getVLOUNI() {
        return fieldVLOUNI.getString();
    }

    /**
     * Set numeric field VLOUNI using a BigDecimal value.
     */
    public void setVLOUNI(BigDecimal newvalue) {
        fieldVLOUNI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUNI as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUNI() {
        return fieldVLOUNI.getBigDecimal();
    }

    /**
     * Set field DIHOY5 using a String value.
     */
    public void setDIHOY5(String newvalue) {
        fieldDIHOY5.setString(newvalue);
    }

    /**
     * Get value of field DIHOY5 as a String.
     */
    public String getDIHOY5() {
        return fieldDIHOY5.getString();
    }

    /**
     * Set numeric field DIHOY5 using a BigDecimal value.
     */
    public void setDIHOY5(BigDecimal newvalue) {
        fieldDIHOY5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIHOY5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIHOY5() {
        return fieldDIHOY5.getBigDecimal();
    }

    /**
     * Set field DIHOY0 using a String value.
     */
    public void setDIHOY0(String newvalue) {
        fieldDIHOY0.setString(newvalue);
    }

    /**
     * Get value of field DIHOY0 as a String.
     */
    public String getDIHOY0() {
        return fieldDIHOY0.getString();
    }

    /**
     * Set numeric field DIHOY0 using a BigDecimal value.
     */
    public void setDIHOY0(BigDecimal newvalue) {
        fieldDIHOY0.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIHOY0 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIHOY0() {
        return fieldDIHOY0.getBigDecimal();
    }

    /**
     * Set field VLOTAS using a String value.
     */
    public void setVLOTAS(String newvalue) {
        fieldVLOTAS.setString(newvalue);
    }

    /**
     * Get value of field VLOTAS as a String.
     */
    public String getVLOTAS() {
        return fieldVLOTAS.getString();
    }

    /**
     * Set numeric field VLOTAS using a BigDecimal value.
     */
    public void setVLOTAS(BigDecimal newvalue) {
        fieldVLOTAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOTAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOTAS() {
        return fieldVLOTAS.getBigDecimal();
    }

    /**
     * Set field DIVTO5 using a String value.
     */
    public void setDIVTO5(String newvalue) {
        fieldDIVTO5.setString(newvalue);
    }

    /**
     * Get value of field DIVTO5 as a String.
     */
    public String getDIVTO5() {
        return fieldDIVTO5.getString();
    }

    /**
     * Set numeric field DIVTO5 using a BigDecimal value.
     */
    public void setDIVTO5(BigDecimal newvalue) {
        fieldDIVTO5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIVTO5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIVTO5() {
        return fieldDIVTO5.getBigDecimal();
    }

    /**
     * Set field DIVTO0 using a String value.
     */
    public void setDIVTO0(String newvalue) {
        fieldDIVTO0.setString(newvalue);
    }

    /**
     * Get value of field DIVTO0 as a String.
     */
    public String getDIVTO0() {
        return fieldDIVTO0.getString();
    }

    /**
     * Set numeric field DIVTO0 using a BigDecimal value.
     */
    public void setDIVTO0(BigDecimal newvalue) {
        fieldDIVTO0.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIVTO0 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIVTO0() {
        return fieldDIVTO0.getBigDecimal();
    }

    /**
     * Set field NUMTIT using a String value.
     */
    public void setNUMTIT(String newvalue) {
        fieldNUMTIT.setString(newvalue);
    }

    /**
     * Get value of field NUMTIT as a String.
     */
    public String getNUMTIT() {
        return fieldNUMTIT.getString();
    }

    /**
     * Set numeric field NUMTIT using a BigDecimal value.
     */
    public void setNUMTIT(BigDecimal newvalue) {
        fieldNUMTIT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NUMTIT as a BigDecimal.
     */
    public BigDecimal getBigDecimalNUMTIT() {
        return fieldNUMTIT.getBigDecimal();
    }

    /**
     * Set field INVVNO using a String value.
     */
    public void setINVVNO(String newvalue) {
        fieldINVVNO.setString(newvalue);
    }

    /**
     * Get value of field INVVNO as a String.
     */
    public String getINVVNO() {
        return fieldINVVNO.getString();
    }

    /**
     * Set numeric field INVVNO using a BigDecimal value.
     */
    public void setINVVNO(BigDecimal newvalue) {
        fieldINVVNO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVVNO as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVVNO() {
        return fieldINVVNO.getBigDecimal();
    }

    /**
     * Set field PRCCHE using a String value.
     */
    public void setPRCCHE(String newvalue) {
        fieldPRCCHE.setString(newvalue);
    }

    /**
     * Get value of field PRCCHE as a String.
     */
    public String getPRCCHE() {
        return fieldPRCCHE.getString();
    }

    /**
     * Set numeric field PRCCHE using a BigDecimal value.
     */
    public void setPRCCHE(BigDecimal newvalue) {
        fieldPRCCHE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field PRCCHE as a BigDecimal.
     */
    public BigDecimal getBigDecimalPRCCHE() {
        return fieldPRCCHE.getBigDecimal();
    }

    /**
     * Set field EFEINI using a String value.
     */
    public void setEFEINI(String newvalue) {
        fieldEFEINI.setString(newvalue);
    }

    /**
     * Get value of field EFEINI as a String.
     */
    public String getEFEINI() {
        return fieldEFEINI.getString();
    }

    /**
     * Set numeric field EFEINI using a BigDecimal value.
     */
    public void setEFEINI(BigDecimal newvalue) {
        fieldEFEINI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field EFEINI as a BigDecimal.
     */
    public BigDecimal getBigDecimalEFEINI() {
        return fieldEFEINI.getBigDecimal();
    }

    /**
     * Set field IMPCHEP using a String value.
     */
    public void setIMPCHEP(String newvalue) {
        fieldIMPCHEP.setString(newvalue);
    }

    /**
     * Get value of field IMPCHEP as a String.
     */
    public String getIMPCHEP() {
        return fieldIMPCHEP.getString();
    }

    /**
     * Set numeric field IMPCHEP using a BigDecimal value.
     */
    public void setIMPCHEP(BigDecimal newvalue) {
        fieldIMPCHEP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IMPCHEP as a BigDecimal.
     */
    public BigDecimal getBigDecimalIMPCHEP() {
        return fieldIMPCHEP.getBigDecimal();
    }

    /**
     * Set field INVPOP using a String value.
     */
    public void setINVPOP(String newvalue) {
        fieldINVPOP.setString(newvalue);
    }

    /**
     * Get value of field INVPOP as a String.
     */
    public String getINVPOP() {
        return fieldINVPOP.getString();
    }

    /**
     * Set numeric field INVPOP using a BigDecimal value.
     */
    public void setINVPOP(BigDecimal newvalue) {
        fieldINVPOP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVPOP as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVPOP() {
        return fieldINVPOP.getBigDecimal();
    }

    /**
     * Set field RENDIM using a String value.
     */
    public void setRENDIM(String newvalue) {
        fieldRENDIM.setString(newvalue);
    }

    /**
     * Get value of field RENDIM as a String.
     */
    public String getRENDIM() {
        return fieldRENDIM.getString();
    }

    /**
     * Set numeric field RENDIM using a BigDecimal value.
     */
    public void setRENDIM(BigDecimal newvalue) {
        fieldRENDIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field RENDIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalRENDIM() {
        return fieldRENDIM.getBigDecimal();
    }

    /**
     * Set field INVRES using a String value.
     */
    public void setINVRES(String newvalue) {
        fieldINVRES.setString(newvalue);
    }

    /**
     * Get value of field INVRES as a String.
     */
    public String getINVRES() {
        return fieldINVRES.getString();
    }

    /**
     * Set numeric field INVRES using a BigDecimal value.
     */
    public void setINVRES(BigDecimal newvalue) {
        fieldINVRES.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVRES as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVRES() {
        return fieldINVRES.getBigDecimal();
    }

    /**
     * Set field COMISI using a String value.
     */
    public void setCOMISI(String newvalue) {
        fieldCOMISI.setString(newvalue);
    }

    /**
     * Get value of field COMISI as a String.
     */
    public String getCOMISI() {
        return fieldCOMISI.getString();
    }

    /**
     * Set numeric field COMISI using a BigDecimal value.
     */
    public void setCOMISI(BigDecimal newvalue) {
        fieldCOMISI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field COMISI as a BigDecimal.
     */
    public BigDecimal getBigDecimalCOMISI() {
        return fieldCOMISI.getBigDecimal();
    }

    /**
     * Set field INVTIM using a String value.
     */
    public void setINVTIM(String newvalue) {
        fieldINVTIM.setString(newvalue);
    }

    /**
     * Get value of field INVTIM as a String.
     */
    public String getINVTIM() {
        return fieldINVTIM.getString();
    }

    /**
     * Set numeric field INVTIM using a BigDecimal value.
     */
    public void setINVTIM(BigDecimal newvalue) {
        fieldINVTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVTIM() {
        return fieldINVTIM.getBigDecimal();
    }

    /**
     * Set field RETENC using a String value.
     */
    public void setRETENC(String newvalue) {
        fieldRETENC.setString(newvalue);
    }

    /**
     * Get value of field RETENC as a String.
     */
    public String getRETENC() {
        return fieldRETENC.getString();
    }

    /**
     * Set field INVIBS using a String value.
     */
    public void setINVIBS(String newvalue) {
        fieldINVIBS.setString(newvalue);
    }

    /**
     * Get value of field INVIBS as a String.
     */
    public String getINVIBS() {
        return fieldINVIBS.getString();
    }

    /**
     * Set field CTASPT using a String value.
     */
    public void setCTASPT(String newvalue) {
        fieldCTASPT.setString(newvalue);
    }

    /**
     * Get value of field CTASPT as a String.
     */
    public String getCTASPT() {
        return fieldCTASPT.getString();
    }

    /**
     * Set numeric field CTASPT using a BigDecimal value.
     */
    public void setCTASPT(BigDecimal newvalue) {
        fieldCTASPT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CTASPT as a BigDecimal.
     */
    public BigDecimal getBigDecimalCTASPT() {
        return fieldCTASPT.getBigDecimal();
    }

    /**
     * Set field RENTOT using a String value.
     */
    public void setRENTOT(String newvalue) {
        fieldRENTOT.setString(newvalue);
    }

    /**
     * Get value of field RENTOT as a String.
     */
    public String getRENTOT() {
        return fieldRENTOT.getString();
    }

    /**
     * Set numeric field RENTOT using a BigDecimal value.
     */
    public void setRENTOT(BigDecimal newvalue) {
        fieldRENTOT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field RENTOT as a BigDecimal.
     */
    public BigDecimal getBigDecimalRENTOT() {
        return fieldRENTOT.getBigDecimal();
    }

    /**
     * Set field INVTOT using a String value.
     */
    public void setINVTOT(String newvalue) {
        fieldINVTOT.setString(newvalue);
    }

    /**
     * Get value of field INVTOT as a String.
     */
    public String getINVTOT() {
        return fieldINVTOT.getString();
    }

    /**
     * Set numeric field INVTOT using a BigDecimal value.
     */
    public void setINVTOT(BigDecimal newvalue) {
        fieldINVTOT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVTOT as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVTOT() {
        return fieldINVTOT.getBigDecimal();
    }

    /**
     * Set field TASAX using a String value.
     */
    public void setTASAX(String newvalue) {
        fieldTASAX.setString(newvalue);
    }

    /**
     * Get value of field TASAX as a String.
     */
    public String getTASAX() {
        return fieldTASAX.getString();
    }

    /**
     * Set numeric field TASAX using a BigDecimal value.
     */
    public void setTASAX(BigDecimal newvalue) {
        fieldTASAX.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TASAX as a BigDecimal.
     */
    public BigDecimal getBigDecimalTASAX() {
        return fieldTASAX.getBigDecimal();
    }

    /**
     * Set field RENOBT using a String value.
     */
    public void setRENOBT(String newvalue) {
        fieldRENOBT.setString(newvalue);
    }

    /**
     * Get value of field RENOBT as a String.
     */
    public String getRENOBT() {
        return fieldRENOBT.getString();
    }

    /**
     * Set numeric field RENOBT using a BigDecimal value.
     */
    public void setRENOBT(BigDecimal newvalue) {
        fieldRENOBT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field RENOBT as a BigDecimal.
     */
    public BigDecimal getBigDecimalRENOBT() {
        return fieldRENOBT.getBigDecimal();
    }

    /**
     * Set field DIEMIC using a String value.
     */
    public void setDIEMIC(String newvalue) {
        fieldDIEMIC.setString(newvalue);
    }

    /**
     * Get value of field DIEMIC as a String.
     */
    public String getDIEMIC() {
        return fieldDIEMIC.getString();
    }

    /**
     * Set numeric field DIEMIC using a BigDecimal value.
     */
    public void setDIEMIC(BigDecimal newvalue) {
        fieldDIEMIC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIEMIC as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIEMIC() {
        return fieldDIEMIC.getBigDecimal();
    }

    /**
     * Set field INVBAS using a String value.
     */
    public void setINVBAS(String newvalue) {
        fieldINVBAS.setString(newvalue);
    }

    /**
     * Get value of field INVBAS as a String.
     */
    public String getINVBAS() {
        return fieldINVBAS.getString();
    }

    /**
     * Set numeric field INVBAS using a BigDecimal value.
     */
    public void setINVBAS(BigDecimal newvalue) {
        fieldINVBAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVBAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVBAS() {
        return fieldINVBAS.getBigDecimal();
    }

    /**
     * Set field DIHOYC using a String value.
     */
    public void setDIHOYC(String newvalue) {
        fieldDIHOYC.setString(newvalue);
    }

    /**
     * Get value of field DIHOYC as a String.
     */
    public String getDIHOYC() {
        return fieldDIHOYC.getString();
    }

    /**
     * Set numeric field DIHOYC using a BigDecimal value.
     */
    public void setDIHOYC(BigDecimal newvalue) {
        fieldDIHOYC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIHOYC as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIHOYC() {
        return fieldDIHOYC.getBigDecimal();
    }

    /**
     * Set field INVENC using a String value.
     */
    public void setINVENC(String newvalue) {
        fieldINVENC.setString(newvalue);
    }

    /**
     * Get value of field INVENC as a String.
     */
    public String getINVENC() {
        return fieldINVENC.getString();
    }

    /**
     * Set numeric field INVENC using a BigDecimal value.
     */
    public void setINVENC(BigDecimal newvalue) {
        fieldINVENC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INVENC as a BigDecimal.
     */
    public BigDecimal getBigDecimalINVENC() {
        return fieldINVENC.getBigDecimal();
    }

    /**
     * Set field BASCAC using a String value.
     */
    public void setBASCAC(String newvalue) {
        fieldBASCAC.setString(newvalue);
    }

    /**
     * Get value of field BASCAC as a String.
     */
    public String getBASCAC() {
        return fieldBASCAC.getString();
    }

    /**
     * Set numeric field BASCAC using a BigDecimal value.
     */
    public void setBASCAC(BigDecimal newvalue) {
        fieldBASCAC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BASCAC as a BigDecimal.
     */
    public BigDecimal getBigDecimalBASCAC() {
        return fieldBASCAC.getBigDecimal();
    }

    /**
     * Set field DIVTOC using a String value.
     */
    public void setDIVTOC(String newvalue) {
        fieldDIVTOC.setString(newvalue);
    }

    /**
     * Get value of field DIVTOC as a String.
     */
    public String getDIVTOC() {
        return fieldDIVTOC.getString();
    }

    /**
     * Set numeric field DIVTOC using a BigDecimal value.
     */
    public void setDIVTOC(BigDecimal newvalue) {
        fieldDIVTOC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DIVTOC as a BigDecimal.
     */
    public BigDecimal getBigDecimalDIVTOC() {
        return fieldDIVTOC.getBigDecimal();
    }

    /**
     * Set field INTTOT using a String value.
     */
    public void setINTTOT(String newvalue) {
        fieldINTTOT.setString(newvalue);
    }

    /**
     * Get value of field INTTOT as a String.
     */
    public String getINTTOT() {
        return fieldINTTOT.getString();
    }

    /**
     * Set numeric field INTTOT using a BigDecimal value.
     */
    public void setINTTOT(BigDecimal newvalue) {
        fieldINTTOT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INTTOT as a BigDecimal.
     */
    public BigDecimal getBigDecimalINTTOT() {
        return fieldINTTOT.getBigDecimal();
    }

    /**
     * Set field VALCAP using a String value.
     */
    public void setVALCAP(String newvalue) {
        fieldVALCAP.setString(newvalue);
    }

    /**
     * Get value of field VALCAP as a String.
     */
    public String getVALCAP() {
        return fieldVALCAP.getString();
    }

    /**
     * Set numeric field VALCAP using a BigDecimal value.
     */
    public void setVALCAP(BigDecimal newvalue) {
        fieldVALCAP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VALCAP as a BigDecimal.
     */
    public BigDecimal getBigDecimalVALCAP() {
        return fieldVALCAP.getBigDecimal();
    }

    /**
     * Set field VALACT using a String value.
     */
    public void setVALACT(String newvalue) {
        fieldVALACT.setString(newvalue);
    }

    /**
     * Get value of field VALACT as a String.
     */
    public String getVALACT() {
        return fieldVALACT.getString();
    }

    /**
     * Set numeric field VALACT using a BigDecimal value.
     */
    public void setVALACT(BigDecimal newvalue) {
        fieldVALACT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VALACT as a BigDecimal.
     */
    public BigDecimal getBigDecimalVALACT() {
        return fieldVALACT.getBigDecimal();
    }

    /**
     * Set field AUXIL using a String value.
     */
    public void setAUXIL(String newvalue) {
        fieldAUXIL.setString(newvalue);
    }

    /**
     * Get value of field AUXIL as a String.
     */
    public String getAUXIL() {
        return fieldAUXIL.getString();
    }

    /**
     * Set numeric field AUXIL using a BigDecimal value.
     */
    public void setAUXIL(BigDecimal newvalue) {
        fieldAUXIL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field AUXIL as a BigDecimal.
     */
    public BigDecimal getBigDecimalAUXIL() {
        return fieldAUXIL.getBigDecimal();
    }

    /**
     * Set field EFEFIN using a String value.
     */
    public void setEFEFIN(String newvalue) {
        fieldEFEFIN.setString(newvalue);
    }

    /**
     * Get value of field EFEFIN as a String.
     */
    public String getEFEFIN() {
        return fieldEFEFIN.getString();
    }

    /**
     * Set numeric field EFEFIN using a BigDecimal value.
     */
    public void setEFEFIN(BigDecimal newvalue) {
        fieldEFEFIN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field EFEFIN as a BigDecimal.
     */
    public BigDecimal getBigDecimalEFEFIN() {
        return fieldEFEFIN.getBigDecimal();
    }

    /**
     * Set field PRIMA using a String value.
     */
    public void setPRIMA(String newvalue) {
        fieldPRIMA.setString(newvalue);
    }

    /**
     * Get value of field PRIMA as a String.
     */
    public String getPRIMA() {
        return fieldPRIMA.getString();
    }

    /**
     * Set numeric field PRIMA using a BigDecimal value.
     */
    public void setPRIMA(BigDecimal newvalue) {
        fieldPRIMA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field PRIMA as a BigDecimal.
     */
    public BigDecimal getBigDecimalPRIMA() {
        return fieldPRIMA.getBigDecimal();
    }

    /**
     * Set field TIMBRE using a String value.
     */
    public void setTIMBRE(String newvalue) {
        fieldTIMBRE.setString(newvalue);
    }

    /**
     * Get value of field TIMBRE as a String.
     */
    public String getTIMBRE() {
        return fieldTIMBRE.getString();
    }

    /**
     * Set numeric field TIMBRE using a BigDecimal value.
     */
    public void setTIMBRE(BigDecimal newvalue) {
        fieldTIMBRE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TIMBRE as a BigDecimal.
     */
    public BigDecimal getBigDecimalTIMBRE() {
        return fieldTIMBRE.getBigDecimal();
    }

    /**
     * Set field INACUM using a String value.
     */
    public void setINACUM(String newvalue) {
        fieldINACUM.setString(newvalue);
    }

    /**
     * Get value of field INACUM as a String.
     */
    public String getINACUM() {
        return fieldINACUM.getString();
    }

    /**
     * Set numeric field INACUM using a BigDecimal value.
     */
    public void setINACUM(BigDecimal newvalue) {
        fieldINACUM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field INACUM as a BigDecimal.
     */
    public BigDecimal getBigDecimalINACUM() {
        return fieldINACUM.getBigDecimal();
    }

    /**
     * Set field RESTO using a String value.
     */
    public void setRESTO(String newvalue) {
        fieldRESTO.setString(newvalue);
    }

    /**
     * Get value of field RESTO as a String.
     */
    public String getRESTO() {
        return fieldRESTO.getString();
    }

    /**
     * Set numeric field RESTO using a BigDecimal value.
     */
    public void setRESTO(BigDecimal newvalue) {
        fieldRESTO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field RESTO as a BigDecimal.
     */
    public BigDecimal getBigDecimalRESTO() {
        return fieldRESTO.getBigDecimal();
    }

}
