package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from LIPOCLFM physical file
 * definition.
 * 
* File level identifier is 1140322162525. Record format level identifier is
 * 44695BD7B07AA.
 */
public class LIPOCLFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "FIDE1",
        "NFIDE1",
        "FIDE2",
        "NFIDE2",
        "FECPRO",
        "SITU"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "FIDE1",
        "NFIDE1",
        "FIDE2",
        "NFIDE2",
        "FECPRO",
        "SITU"
    };
    final static String fid = "1140322162525";
    final static String rid = "44695BD7B07AA";
    final static String fmtname = "LIPOCLFM";
    final int FIELDCOUNT = 15;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldFIDE1 = null;
    private CharacterField fieldNFIDE1 = null;
    private CharacterField fieldFIDE2 = null;
    private CharacterField fieldNFIDE2 = null;
    private DecimalField fieldFECPRO = null;
    private CharacterField fieldSITU = null;

    /**
     * Constructor for LIPOCLFMMessage.
     */
    public LIPOCLFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 277;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldFIDE1
                = new CharacterField(message, HEADERSIZE + 161, 4, "FIDE1");
        fields[10] = fieldNFIDE1
                = new CharacterField(message, HEADERSIZE + 165, 50, "NFIDE1");
        fields[11] = fieldFIDE2
                = new CharacterField(message, HEADERSIZE + 215, 4, "FIDE2");
        fields[12] = fieldNFIDE2
                = new CharacterField(message, HEADERSIZE + 219, 50, "NFIDE2");
        fields[13] = fieldFECPRO
                = new DecimalField(message, HEADERSIZE + 269, 7, 0, "FECPRO");
        fields[14] = fieldSITU
                = new CharacterField(message, HEADERSIZE + 276, 1, "SITU");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field FIDE1 using a String value.
     */
    public void setFIDE1(String newvalue) {
        fieldFIDE1.setString(newvalue);
    }

    /**
     * Get value of field FIDE1 as a String.
     */
    public String getFIDE1() {
        return fieldFIDE1.getString();
    }

    /**
     * Set field NFIDE1 using a String value.
     */
    public void setNFIDE1(String newvalue) {
        fieldNFIDE1.setString(newvalue);
    }

    /**
     * Get value of field NFIDE1 as a String.
     */
    public String getNFIDE1() {
        return fieldNFIDE1.getString();
    }

    /**
     * Set field FIDE2 using a String value.
     */
    public void setFIDE2(String newvalue) {
        fieldFIDE2.setString(newvalue);
    }

    /**
     * Get value of field FIDE2 as a String.
     */
    public String getFIDE2() {
        return fieldFIDE2.getString();
    }

    /**
     * Set field NFIDE2 using a String value.
     */
    public void setNFIDE2(String newvalue) {
        fieldNFIDE2.setString(newvalue);
    }

    /**
     * Get value of field NFIDE2 as a String.
     */
    public String getNFIDE2() {
        return fieldNFIDE2.getString();
    }

    /**
     * Set field FECPRO using a String value.
     */
    public void setFECPRO(String newvalue) {
        fieldFECPRO.setString(newvalue);
    }

    /**
     * Get value of field FECPRO as a String.
     */
    public String getFECPRO() {
        return fieldFECPRO.getString();
    }

    /**
     * Set numeric field FECPRO using a BigDecimal value.
     */
    public void setFECPRO(BigDecimal newvalue) {
        fieldFECPRO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECPRO as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECPRO() {
        return fieldFECPRO.getBigDecimal();
    }

    /**
     * Set field SITU using a String value.
     */
    public void setSITU(String newvalue) {
        fieldSITU.setString(newvalue);
    }

    /**
     * Get value of field SITU as a String.
     */
    public String getSITU() {
        return fieldSITU.getString();
    }

}
