package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from MAXMINFM physical file
 * definition.
 * 
* File level identifier is 1140213212527. Record format level identifier is
 * 40F333F8F9D5C.
 */
public class MAXMINFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "TEXTO",
        "MAXIMO",
        "MINIMO",
        "CGMDS1",
        "CGMHS1",
        "CGMPR1",
        "CGMDS2",
        "CGMHS2",
        "CGMPR2",
        "CGMDS3",
        "CGMHS3",
        "CGMPR3",
        "CGMDS4",
        "CGMHS4",
        "CGMPR4",
        "CGMDS5",
        "CGMHS5",
        "CGMPR5",
        "CGMDS6",
        "CGMHS6",
        "CGMPR6"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "TEXTO",
        "MAXIMO",
        "MINIMO",
        "CGMDS1",
        "CGMHS1",
        "CGMPR1",
        "CGMDS2",
        "CGMHS2",
        "CGMPR2",
        "CGMDS3",
        "CGMHS3",
        "CGMPR3",
        "CGMDS4",
        "CGMHS4",
        "CGMPR4",
        "CGMDS5",
        "CGMHS5",
        "CGMPR5",
        "CGMDS6",
        "CGMHS6",
        "CGMPR6"
    };
    final static String fid = "1140213212527";
    final static String rid = "40F333F8F9D5C";
    final static String fmtname = "MAXMINFM";
    final int FIELDCOUNT = 30;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldTEXTO = null;
    private DecimalField fieldMAXIMO = null;
    private DecimalField fieldMINIMO = null;
    private DecimalField fieldCGMDS1 = null;
    private DecimalField fieldCGMHS1 = null;
    private DecimalField fieldCGMPR1 = null;
    private DecimalField fieldCGMDS2 = null;
    private DecimalField fieldCGMHS2 = null;
    private DecimalField fieldCGMPR2 = null;
    private DecimalField fieldCGMDS3 = null;
    private DecimalField fieldCGMHS3 = null;
    private DecimalField fieldCGMPR3 = null;
    private DecimalField fieldCGMDS4 = null;
    private DecimalField fieldCGMHS4 = null;
    private DecimalField fieldCGMPR4 = null;
    private DecimalField fieldCGMDS5 = null;
    private DecimalField fieldCGMHS5 = null;
    private DecimalField fieldCGMPR5 = null;
    private DecimalField fieldCGMDS6 = null;
    private DecimalField fieldCGMHS6 = null;
    private DecimalField fieldCGMPR6 = null;

    /**
     * Constructor for MAXMINFMMessage.
     */
    public MAXMINFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 482;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldTEXTO
                = new CharacterField(message, HEADERSIZE + 161, 31, "TEXTO");
        fields[10] = fieldMAXIMO
                = new DecimalField(message, HEADERSIZE + 192, 16, 2, "MAXIMO");
        fields[11] = fieldMINIMO
                = new DecimalField(message, HEADERSIZE + 208, 16, 2, "MINIMO");
        fields[12] = fieldCGMDS1
                = new DecimalField(message, HEADERSIZE + 224, 16, 2, "CGMDS1");
        fields[13] = fieldCGMHS1
                = new DecimalField(message, HEADERSIZE + 240, 16, 2, "CGMHS1");
        fields[14] = fieldCGMPR1
                = new DecimalField(message, HEADERSIZE + 256, 11, 6, "CGMPR1");
        fields[15] = fieldCGMDS2
                = new DecimalField(message, HEADERSIZE + 267, 16, 2, "CGMDS2");
        fields[16] = fieldCGMHS2
                = new DecimalField(message, HEADERSIZE + 283, 16, 2, "CGMHS2");
        fields[17] = fieldCGMPR2
                = new DecimalField(message, HEADERSIZE + 299, 11, 6, "CGMPR2");
        fields[18] = fieldCGMDS3
                = new DecimalField(message, HEADERSIZE + 310, 16, 2, "CGMDS3");
        fields[19] = fieldCGMHS3
                = new DecimalField(message, HEADERSIZE + 326, 16, 2, "CGMHS3");
        fields[20] = fieldCGMPR3
                = new DecimalField(message, HEADERSIZE + 342, 11, 6, "CGMPR3");
        fields[21] = fieldCGMDS4
                = new DecimalField(message, HEADERSIZE + 353, 16, 2, "CGMDS4");
        fields[22] = fieldCGMHS4
                = new DecimalField(message, HEADERSIZE + 369, 16, 2, "CGMHS4");
        fields[23] = fieldCGMPR4
                = new DecimalField(message, HEADERSIZE + 385, 11, 6, "CGMPR4");
        fields[24] = fieldCGMDS5
                = new DecimalField(message, HEADERSIZE + 396, 16, 2, "CGMDS5");
        fields[25] = fieldCGMHS5
                = new DecimalField(message, HEADERSIZE + 412, 16, 2, "CGMHS5");
        fields[26] = fieldCGMPR5
                = new DecimalField(message, HEADERSIZE + 428, 11, 6, "CGMPR5");
        fields[27] = fieldCGMDS6
                = new DecimalField(message, HEADERSIZE + 439, 16, 2, "CGMDS6");
        fields[28] = fieldCGMHS6
                = new DecimalField(message, HEADERSIZE + 455, 16, 2, "CGMHS6");
        fields[29] = fieldCGMPR6
                = new DecimalField(message, HEADERSIZE + 471, 11, 6, "CGMPR6");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field TEXTO using a String value.
     */
    public void setTEXTO(String newvalue) {
        fieldTEXTO.setString(newvalue);
    }

    /**
     * Get value of field TEXTO as a String.
     */
    public String getTEXTO() {
        return fieldTEXTO.getString();
    }

    /**
     * Set field MAXIMO using a String value.
     */
    public void setMAXIMO(String newvalue) {
        fieldMAXIMO.setString(newvalue);
    }

    /**
     * Get value of field MAXIMO as a String.
     */
    public String getMAXIMO() {
        return fieldMAXIMO.getString();
    }

    /**
     * Set numeric field MAXIMO using a BigDecimal value.
     */
    public void setMAXIMO(BigDecimal newvalue) {
        fieldMAXIMO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MAXIMO as a BigDecimal.
     */
    public BigDecimal getBigDecimalMAXIMO() {
        return fieldMAXIMO.getBigDecimal();
    }

    /**
     * Set field MINIMO using a String value.
     */
    public void setMINIMO(String newvalue) {
        fieldMINIMO.setString(newvalue);
    }

    /**
     * Get value of field MINIMO as a String.
     */
    public String getMINIMO() {
        return fieldMINIMO.getString();
    }

    /**
     * Set numeric field MINIMO using a BigDecimal value.
     */
    public void setMINIMO(BigDecimal newvalue) {
        fieldMINIMO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MINIMO as a BigDecimal.
     */
    public BigDecimal getBigDecimalMINIMO() {
        return fieldMINIMO.getBigDecimal();
    }

    /**
     * Set field CGMDS1 using a String value.
     */
    public void setCGMDS1(String newvalue) {
        fieldCGMDS1.setString(newvalue);
    }

    /**
     * Get value of field CGMDS1 as a String.
     */
    public String getCGMDS1() {
        return fieldCGMDS1.getString();
    }

    /**
     * Set numeric field CGMDS1 using a BigDecimal value.
     */
    public void setCGMDS1(BigDecimal newvalue) {
        fieldCGMDS1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMDS1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMDS1() {
        return fieldCGMDS1.getBigDecimal();
    }

    /**
     * Set field CGMHS1 using a String value.
     */
    public void setCGMHS1(String newvalue) {
        fieldCGMHS1.setString(newvalue);
    }

    /**
     * Get value of field CGMHS1 as a String.
     */
    public String getCGMHS1() {
        return fieldCGMHS1.getString();
    }

    /**
     * Set numeric field CGMHS1 using a BigDecimal value.
     */
    public void setCGMHS1(BigDecimal newvalue) {
        fieldCGMHS1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMHS1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMHS1() {
        return fieldCGMHS1.getBigDecimal();
    }

    /**
     * Set field CGMPR1 using a String value.
     */
    public void setCGMPR1(String newvalue) {
        fieldCGMPR1.setString(newvalue);
    }

    /**
     * Get value of field CGMPR1 as a String.
     */
    public String getCGMPR1() {
        return fieldCGMPR1.getString();
    }

    /**
     * Set numeric field CGMPR1 using a BigDecimal value.
     */
    public void setCGMPR1(BigDecimal newvalue) {
        fieldCGMPR1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMPR1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMPR1() {
        return fieldCGMPR1.getBigDecimal();
    }

    /**
     * Set field CGMDS2 using a String value.
     */
    public void setCGMDS2(String newvalue) {
        fieldCGMDS2.setString(newvalue);
    }

    /**
     * Get value of field CGMDS2 as a String.
     */
    public String getCGMDS2() {
        return fieldCGMDS2.getString();
    }

    /**
     * Set numeric field CGMDS2 using a BigDecimal value.
     */
    public void setCGMDS2(BigDecimal newvalue) {
        fieldCGMDS2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMDS2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMDS2() {
        return fieldCGMDS2.getBigDecimal();
    }

    /**
     * Set field CGMHS2 using a String value.
     */
    public void setCGMHS2(String newvalue) {
        fieldCGMHS2.setString(newvalue);
    }

    /**
     * Get value of field CGMHS2 as a String.
     */
    public String getCGMHS2() {
        return fieldCGMHS2.getString();
    }

    /**
     * Set numeric field CGMHS2 using a BigDecimal value.
     */
    public void setCGMHS2(BigDecimal newvalue) {
        fieldCGMHS2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMHS2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMHS2() {
        return fieldCGMHS2.getBigDecimal();
    }

    /**
     * Set field CGMPR2 using a String value.
     */
    public void setCGMPR2(String newvalue) {
        fieldCGMPR2.setString(newvalue);
    }

    /**
     * Get value of field CGMPR2 as a String.
     */
    public String getCGMPR2() {
        return fieldCGMPR2.getString();
    }

    /**
     * Set numeric field CGMPR2 using a BigDecimal value.
     */
    public void setCGMPR2(BigDecimal newvalue) {
        fieldCGMPR2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMPR2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMPR2() {
        return fieldCGMPR2.getBigDecimal();
    }

    /**
     * Set field CGMDS3 using a String value.
     */
    public void setCGMDS3(String newvalue) {
        fieldCGMDS3.setString(newvalue);
    }

    /**
     * Get value of field CGMDS3 as a String.
     */
    public String getCGMDS3() {
        return fieldCGMDS3.getString();
    }

    /**
     * Set numeric field CGMDS3 using a BigDecimal value.
     */
    public void setCGMDS3(BigDecimal newvalue) {
        fieldCGMDS3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMDS3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMDS3() {
        return fieldCGMDS3.getBigDecimal();
    }

    /**
     * Set field CGMHS3 using a String value.
     */
    public void setCGMHS3(String newvalue) {
        fieldCGMHS3.setString(newvalue);
    }

    /**
     * Get value of field CGMHS3 as a String.
     */
    public String getCGMHS3() {
        return fieldCGMHS3.getString();
    }

    /**
     * Set numeric field CGMHS3 using a BigDecimal value.
     */
    public void setCGMHS3(BigDecimal newvalue) {
        fieldCGMHS3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMHS3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMHS3() {
        return fieldCGMHS3.getBigDecimal();
    }

    /**
     * Set field CGMPR3 using a String value.
     */
    public void setCGMPR3(String newvalue) {
        fieldCGMPR3.setString(newvalue);
    }

    /**
     * Get value of field CGMPR3 as a String.
     */
    public String getCGMPR3() {
        return fieldCGMPR3.getString();
    }

    /**
     * Set numeric field CGMPR3 using a BigDecimal value.
     */
    public void setCGMPR3(BigDecimal newvalue) {
        fieldCGMPR3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMPR3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMPR3() {
        return fieldCGMPR3.getBigDecimal();
    }

    /**
     * Set field CGMDS4 using a String value.
     */
    public void setCGMDS4(String newvalue) {
        fieldCGMDS4.setString(newvalue);
    }

    /**
     * Get value of field CGMDS4 as a String.
     */
    public String getCGMDS4() {
        return fieldCGMDS4.getString();
    }

    /**
     * Set numeric field CGMDS4 using a BigDecimal value.
     */
    public void setCGMDS4(BigDecimal newvalue) {
        fieldCGMDS4.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMDS4 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMDS4() {
        return fieldCGMDS4.getBigDecimal();
    }

    /**
     * Set field CGMHS4 using a String value.
     */
    public void setCGMHS4(String newvalue) {
        fieldCGMHS4.setString(newvalue);
    }

    /**
     * Get value of field CGMHS4 as a String.
     */
    public String getCGMHS4() {
        return fieldCGMHS4.getString();
    }

    /**
     * Set numeric field CGMHS4 using a BigDecimal value.
     */
    public void setCGMHS4(BigDecimal newvalue) {
        fieldCGMHS4.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMHS4 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMHS4() {
        return fieldCGMHS4.getBigDecimal();
    }

    /**
     * Set field CGMPR4 using a String value.
     */
    public void setCGMPR4(String newvalue) {
        fieldCGMPR4.setString(newvalue);
    }

    /**
     * Get value of field CGMPR4 as a String.
     */
    public String getCGMPR4() {
        return fieldCGMPR4.getString();
    }

    /**
     * Set numeric field CGMPR4 using a BigDecimal value.
     */
    public void setCGMPR4(BigDecimal newvalue) {
        fieldCGMPR4.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMPR4 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMPR4() {
        return fieldCGMPR4.getBigDecimal();
    }

    /**
     * Set field CGMDS5 using a String value.
     */
    public void setCGMDS5(String newvalue) {
        fieldCGMDS5.setString(newvalue);
    }

    /**
     * Get value of field CGMDS5 as a String.
     */
    public String getCGMDS5() {
        return fieldCGMDS5.getString();
    }

    /**
     * Set numeric field CGMDS5 using a BigDecimal value.
     */
    public void setCGMDS5(BigDecimal newvalue) {
        fieldCGMDS5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMDS5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMDS5() {
        return fieldCGMDS5.getBigDecimal();
    }

    /**
     * Set field CGMHS5 using a String value.
     */
    public void setCGMHS5(String newvalue) {
        fieldCGMHS5.setString(newvalue);
    }

    /**
     * Get value of field CGMHS5 as a String.
     */
    public String getCGMHS5() {
        return fieldCGMHS5.getString();
    }

    /**
     * Set numeric field CGMHS5 using a BigDecimal value.
     */
    public void setCGMHS5(BigDecimal newvalue) {
        fieldCGMHS5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMHS5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMHS5() {
        return fieldCGMHS5.getBigDecimal();
    }

    /**
     * Set field CGMPR5 using a String value.
     */
    public void setCGMPR5(String newvalue) {
        fieldCGMPR5.setString(newvalue);
    }

    /**
     * Get value of field CGMPR5 as a String.
     */
    public String getCGMPR5() {
        return fieldCGMPR5.getString();
    }

    /**
     * Set numeric field CGMPR5 using a BigDecimal value.
     */
    public void setCGMPR5(BigDecimal newvalue) {
        fieldCGMPR5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMPR5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMPR5() {
        return fieldCGMPR5.getBigDecimal();
    }

    /**
     * Set field CGMDS6 using a String value.
     */
    public void setCGMDS6(String newvalue) {
        fieldCGMDS6.setString(newvalue);
    }

    /**
     * Get value of field CGMDS6 as a String.
     */
    public String getCGMDS6() {
        return fieldCGMDS6.getString();
    }

    /**
     * Set numeric field CGMDS6 using a BigDecimal value.
     */
    public void setCGMDS6(BigDecimal newvalue) {
        fieldCGMDS6.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMDS6 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMDS6() {
        return fieldCGMDS6.getBigDecimal();
    }

    /**
     * Set field CGMHS6 using a String value.
     */
    public void setCGMHS6(String newvalue) {
        fieldCGMHS6.setString(newvalue);
    }

    /**
     * Get value of field CGMHS6 as a String.
     */
    public String getCGMHS6() {
        return fieldCGMHS6.getString();
    }

    /**
     * Set numeric field CGMHS6 using a BigDecimal value.
     */
    public void setCGMHS6(BigDecimal newvalue) {
        fieldCGMHS6.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMHS6 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMHS6() {
        return fieldCGMHS6.getBigDecimal();
    }

    /**
     * Set field CGMPR6 using a String value.
     */
    public void setCGMPR6(String newvalue) {
        fieldCGMPR6.setString(newvalue);
    }

    /**
     * Get value of field CGMPR6 as a String.
     */
    public String getCGMPR6() {
        return fieldCGMPR6.getString();
    }

    /**
     * Set numeric field CGMPR6 using a BigDecimal value.
     */
    public void setCGMPR6(BigDecimal newvalue) {
        fieldCGMPR6.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CGMPR6 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCGMPR6() {
        return fieldCGMPR6.getBigDecimal();
    }

}
