package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from PETFE6FM physical file
 * definition.
 * 
* File level identifier is 1140314004838. Record format level identifier is
 * 415464C38898B.
 */
public class PETFE6FMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "CLIDES",
        "CLIHAS",
        "TIFDES",
        "TIFHAS",
        "FIDDES",
        "FIDHAS",
        "FECDES",
        "FECHAS",
        "USUA",
        "LST1",
        "LST2",
        "LST3",
        "LST4",
        "LST5",
        "FIA"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "CLIDES",
        "CLIHAS",
        "TIFDES",
        "TIFHAS",
        "FIDDES",
        "FIDHAS",
        "FECDES",
        "FECHAS",
        "USUA",
        "LST1",
        "LST2",
        "LST3",
        "LST4",
        "LST5",
        "FIA"
    };
    final static String fid = "1140314004838";
    final static String rid = "415464C38898B";
    final static String fmtname = "PETFE6FM";
    final int FIELDCOUNT = 27;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldPOSCUR = null;
    private DecimalField fieldCLIDES = null;
    private DecimalField fieldCLIHAS = null;
    private DecimalField fieldTIFDES = null;
    private DecimalField fieldTIFHAS = null;
    private CharacterField fieldFIDDES = null;
    private CharacterField fieldFIDHAS = null;
    private DecimalField fieldFECDES = null;
    private DecimalField fieldFECHAS = null;
    private CharacterField fieldUSUA = null;
    private CharacterField fieldLST1 = null;
    private CharacterField fieldLST2 = null;
    private CharacterField fieldLST3 = null;
    private CharacterField fieldLST4 = null;
    private CharacterField fieldLST5 = null;
    private CharacterField fieldFIA = null;

    /**
     * Constructor for PETFE6FMMessage.
     */
    public PETFE6FMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 237;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 171, 10, "CAMCUR");
        fields[11] = fieldPOSCUR
                = new DecimalField(message, HEADERSIZE + 181, 5, 0, "POSCUR");
        fields[12] = fieldCLIDES
                = new DecimalField(message, HEADERSIZE + 186, 8, 0, "CLIDES");
        fields[13] = fieldCLIHAS
                = new DecimalField(message, HEADERSIZE + 194, 8, 0, "CLIHAS");
        fields[14] = fieldTIFDES
                = new DecimalField(message, HEADERSIZE + 202, 3, 0, "TIFDES");
        fields[15] = fieldTIFHAS
                = new DecimalField(message, HEADERSIZE + 205, 3, 0, "TIFHAS");
        fields[16] = fieldFIDDES
                = new CharacterField(message, HEADERSIZE + 208, 4, "FIDDES");
        fields[17] = fieldFIDHAS
                = new CharacterField(message, HEADERSIZE + 212, 4, "FIDHAS");
        fields[18] = fieldFECDES
                = new DecimalField(message, HEADERSIZE + 216, 7, 0, "FECDES");
        fields[19] = fieldFECHAS
                = new DecimalField(message, HEADERSIZE + 223, 7, 0, "FECHAS");
        fields[20] = fieldUSUA
                = new CharacterField(message, HEADERSIZE + 230, 1, "USUA");
        fields[21] = fieldLST1
                = new CharacterField(message, HEADERSIZE + 231, 1, "LST1");
        fields[22] = fieldLST2
                = new CharacterField(message, HEADERSIZE + 232, 1, "LST2");
        fields[23] = fieldLST3
                = new CharacterField(message, HEADERSIZE + 233, 1, "LST3");
        fields[24] = fieldLST4
                = new CharacterField(message, HEADERSIZE + 234, 1, "LST4");
        fields[25] = fieldLST5
                = new CharacterField(message, HEADERSIZE + 235, 1, "LST5");
        fields[26] = fieldFIA
                = new CharacterField(message, HEADERSIZE + 236, 1, "FIA");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field POSCUR using a String value.
     */
    public void setPOSCUR(String newvalue) {
        fieldPOSCUR.setString(newvalue);
    }

    /**
     * Get value of field POSCUR as a String.
     */
    public String getPOSCUR() {
        return fieldPOSCUR.getString();
    }

    /**
     * Set numeric field POSCUR using a BigDecimal value.
     */
    public void setPOSCUR(BigDecimal newvalue) {
        fieldPOSCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field POSCUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalPOSCUR() {
        return fieldPOSCUR.getBigDecimal();
    }

    /**
     * Set field CLIDES using a String value.
     */
    public void setCLIDES(String newvalue) {
        fieldCLIDES.setString(newvalue);
    }

    /**
     * Get value of field CLIDES as a String.
     */
    public String getCLIDES() {
        return fieldCLIDES.getString();
    }

    /**
     * Set numeric field CLIDES using a BigDecimal value.
     */
    public void setCLIDES(BigDecimal newvalue) {
        fieldCLIDES.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLIDES as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLIDES() {
        return fieldCLIDES.getBigDecimal();
    }

    /**
     * Set field CLIHAS using a String value.
     */
    public void setCLIHAS(String newvalue) {
        fieldCLIHAS.setString(newvalue);
    }

    /**
     * Get value of field CLIHAS as a String.
     */
    public String getCLIHAS() {
        return fieldCLIHAS.getString();
    }

    /**
     * Set numeric field CLIHAS using a BigDecimal value.
     */
    public void setCLIHAS(BigDecimal newvalue) {
        fieldCLIHAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLIHAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLIHAS() {
        return fieldCLIHAS.getBigDecimal();
    }

    /**
     * Set field TIFDES using a String value.
     */
    public void setTIFDES(String newvalue) {
        fieldTIFDES.setString(newvalue);
    }

    /**
     * Get value of field TIFDES as a String.
     */
    public String getTIFDES() {
        return fieldTIFDES.getString();
    }

    /**
     * Set numeric field TIFDES using a BigDecimal value.
     */
    public void setTIFDES(BigDecimal newvalue) {
        fieldTIFDES.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TIFDES as a BigDecimal.
     */
    public BigDecimal getBigDecimalTIFDES() {
        return fieldTIFDES.getBigDecimal();
    }

    /**
     * Set field TIFHAS using a String value.
     */
    public void setTIFHAS(String newvalue) {
        fieldTIFHAS.setString(newvalue);
    }

    /**
     * Get value of field TIFHAS as a String.
     */
    public String getTIFHAS() {
        return fieldTIFHAS.getString();
    }

    /**
     * Set numeric field TIFHAS using a BigDecimal value.
     */
    public void setTIFHAS(BigDecimal newvalue) {
        fieldTIFHAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TIFHAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalTIFHAS() {
        return fieldTIFHAS.getBigDecimal();
    }

    /**
     * Set field FIDDES using a String value.
     */
    public void setFIDDES(String newvalue) {
        fieldFIDDES.setString(newvalue);
    }

    /**
     * Get value of field FIDDES as a String.
     */
    public String getFIDDES() {
        return fieldFIDDES.getString();
    }

    /**
     * Set field FIDHAS using a String value.
     */
    public void setFIDHAS(String newvalue) {
        fieldFIDHAS.setString(newvalue);
    }

    /**
     * Get value of field FIDHAS as a String.
     */
    public String getFIDHAS() {
        return fieldFIDHAS.getString();
    }

    /**
     * Set field FECDES using a String value.
     */
    public void setFECDES(String newvalue) {
        fieldFECDES.setString(newvalue);
    }

    /**
     * Get value of field FECDES as a String.
     */
    public String getFECDES() {
        return fieldFECDES.getString();
    }

    /**
     * Set numeric field FECDES using a BigDecimal value.
     */
    public void setFECDES(BigDecimal newvalue) {
        fieldFECDES.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECDES as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECDES() {
        return fieldFECDES.getBigDecimal();
    }

    /**
     * Set field FECHAS using a String value.
     */
    public void setFECHAS(String newvalue) {
        fieldFECHAS.setString(newvalue);
    }

    /**
     * Get value of field FECHAS as a String.
     */
    public String getFECHAS() {
        return fieldFECHAS.getString();
    }

    /**
     * Set numeric field FECHAS using a BigDecimal value.
     */
    public void setFECHAS(BigDecimal newvalue) {
        fieldFECHAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECHAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECHAS() {
        return fieldFECHAS.getBigDecimal();
    }

    /**
     * Set field USUA using a String value.
     */
    public void setUSUA(String newvalue) {
        fieldUSUA.setString(newvalue);
    }

    /**
     * Get value of field USUA as a String.
     */
    public String getUSUA() {
        return fieldUSUA.getString();
    }

    /**
     * Set field LST1 using a String value.
     */
    public void setLST1(String newvalue) {
        fieldLST1.setString(newvalue);
    }

    /**
     * Get value of field LST1 as a String.
     */
    public String getLST1() {
        return fieldLST1.getString();
    }

    /**
     * Set field LST2 using a String value.
     */
    public void setLST2(String newvalue) {
        fieldLST2.setString(newvalue);
    }

    /**
     * Get value of field LST2 as a String.
     */
    public String getLST2() {
        return fieldLST2.getString();
    }

    /**
     * Set field LST3 using a String value.
     */
    public void setLST3(String newvalue) {
        fieldLST3.setString(newvalue);
    }

    /**
     * Get value of field LST3 as a String.
     */
    public String getLST3() {
        return fieldLST3.getString();
    }

    /**
     * Set field LST4 using a String value.
     */
    public void setLST4(String newvalue) {
        fieldLST4.setString(newvalue);
    }

    /**
     * Get value of field LST4 as a String.
     */
    public String getLST4() {
        return fieldLST4.getString();
    }

    /**
     * Set field LST5 using a String value.
     */
    public void setLST5(String newvalue) {
        fieldLST5.setString(newvalue);
    }

    /**
     * Get value of field LST5 as a String.
     */
    public String getLST5() {
        return fieldLST5.getString();
    }

    /**
     * Set field FIA using a String value.
     */
    public void setFIA(String newvalue) {
        fieldFIA.setString(newvalue);
    }

    /**
     * Get value of field FIA as a String.
     */
    public String getFIA() {
        return fieldFIA.getString();
    }

}
