package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from PWD3FM physical file
 * definition.
 * 
* File level identifier is 1140315195807. Record format level identifier is
 * 35BF9C7CDCB66.
 */
public class PWD3FMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "CLAAUT",
        "FERROR",
        "DATDIS",
        "DATMES",
        "DATDIA",
        "DATMEA"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "CLAAUT",
        "FERROR",
        "DATDIS",
        "DATMES",
        "DATDIA",
        "DATMEA"
    };
    final static String fid = "1140315195807";
    final static String rid = "35BF9C7CDCB66";
    final static String fmtname = "PWD3FM";
    final int FIELDCOUNT = 15;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldCLAAUT = null;
    private DecimalField fieldFERROR = null;
    private DecimalField fieldDATDIS = null;
    private DecimalField fieldDATMES = null;
    private DecimalField fieldDATDIA = null;
    private DecimalField fieldDATMEA = null;

    /**
     * Constructor for PWD3FMMessage.
     */
    public PWD3FMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 186;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldCLAAUT
                = new CharacterField(message, HEADERSIZE + 161, 6, "CLAAUT");
        fields[10] = fieldFERROR
                = new DecimalField(message, HEADERSIZE + 167, 7, 0, "FERROR");
        fields[11] = fieldDATDIS
                = new DecimalField(message, HEADERSIZE + 174, 3, 0, "DATDIS");
        fields[12] = fieldDATMES
                = new DecimalField(message, HEADERSIZE + 177, 3, 0, "DATMES");
        fields[13] = fieldDATDIA
                = new DecimalField(message, HEADERSIZE + 180, 3, 0, "DATDIA");
        fields[14] = fieldDATMEA
                = new DecimalField(message, HEADERSIZE + 183, 3, 0, "DATMEA");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field CLAAUT using a String value.
     */
    public void setCLAAUT(String newvalue) {
        fieldCLAAUT.setString(newvalue);
    }

    /**
     * Get value of field CLAAUT as a String.
     */
    public String getCLAAUT() {
        return fieldCLAAUT.getString();
    }

    /**
     * Set field FERROR using a String value.
     */
    public void setFERROR(String newvalue) {
        fieldFERROR.setString(newvalue);
    }

    /**
     * Get value of field FERROR as a String.
     */
    public String getFERROR() {
        return fieldFERROR.getString();
    }

    /**
     * Set numeric field FERROR using a BigDecimal value.
     */
    public void setFERROR(BigDecimal newvalue) {
        fieldFERROR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FERROR as a BigDecimal.
     */
    public BigDecimal getBigDecimalFERROR() {
        return fieldFERROR.getBigDecimal();
    }

    /**
     * Set field DATDIS using a String value.
     */
    public void setDATDIS(String newvalue) {
        fieldDATDIS.setString(newvalue);
    }

    /**
     * Get value of field DATDIS as a String.
     */
    public String getDATDIS() {
        return fieldDATDIS.getString();
    }

    /**
     * Set numeric field DATDIS using a BigDecimal value.
     */
    public void setDATDIS(BigDecimal newvalue) {
        fieldDATDIS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATDIS as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATDIS() {
        return fieldDATDIS.getBigDecimal();
    }

    /**
     * Set field DATMES using a String value.
     */
    public void setDATMES(String newvalue) {
        fieldDATMES.setString(newvalue);
    }

    /**
     * Get value of field DATMES as a String.
     */
    public String getDATMES() {
        return fieldDATMES.getString();
    }

    /**
     * Set numeric field DATMES using a BigDecimal value.
     */
    public void setDATMES(BigDecimal newvalue) {
        fieldDATMES.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATMES as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATMES() {
        return fieldDATMES.getBigDecimal();
    }

    /**
     * Set field DATDIA using a String value.
     */
    public void setDATDIA(String newvalue) {
        fieldDATDIA.setString(newvalue);
    }

    /**
     * Get value of field DATDIA as a String.
     */
    public String getDATDIA() {
        return fieldDATDIA.getString();
    }

    /**
     * Set numeric field DATDIA using a BigDecimal value.
     */
    public void setDATDIA(BigDecimal newvalue) {
        fieldDATDIA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATDIA as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATDIA() {
        return fieldDATDIA.getBigDecimal();
    }

    /**
     * Set field DATMEA using a String value.
     */
    public void setDATMEA(String newvalue) {
        fieldDATMEA.setString(newvalue);
    }

    /**
     * Get value of field DATMEA as a String.
     */
    public String getDATMEA() {
        return fieldDATMEA.getString();
    }

    /**
     * Set numeric field DATMEA using a BigDecimal value.
     */
    public void setDATMEA(BigDecimal newvalue) {
        fieldDATMEA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATMEA as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATMEA() {
        return fieldDATMEA.getBigDecimal();
    }

}
