package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from RECAPMFM physical file
 * definition.
 * 
* File level identifier is 1140322124747. Record format level identifier is
 * 399865E6B3F4E.
 */
public class RECAPMFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "CLAV",
        "FIDNOM",
        "TIPO",
        "CLINIF",
        "FECAP",
        "DISMNT",
        "MOVPGO",
        "TEXTO",
        "DATMIN",
        "DATMAE",
        "NOMBRE",
        "HMOINT",
        "CLINOM",
        "CLIAPE",
        "CLIAP2",
        "CTA",
        "TCT"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "CLAV",
        "FIDNOM",
        "TIPO",
        "CLINIF",
        "FECAP",
        "DISMNT",
        "MOVPGO",
        "TEXTO",
        "DATMIN",
        "DATMAE",
        "NOMBRE",
        "HMOINT",
        "CLINOM",
        "CLIAPE",
        "CLIAP2",
        "CTA",
        "TCT"
    };
    final static String fid = "1140322124747";
    final static String rid = "399865E6B3F4E";
    final static String fmtname = "RECAPMFM";
    final int FIELDCOUNT = 29;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldPOSCUR = null;
    private CharacterField fieldCLAV = null;
    private CharacterField fieldFIDNOM = null;
    private CharacterField fieldTIPO = null;
    private CharacterField fieldCLINIF = null;
    private DecimalField fieldFECAP = null;
    private DecimalField fieldDISMNT = null;
    private DecimalField fieldMOVPGO = null;
    private CharacterField fieldTEXTO = null;
    private DecimalField fieldDATMIN = null;
    private DecimalField fieldDATMAE = null;
    private CharacterField fieldNOMBRE = null;
    private DecimalField fieldHMOINT = null;
    private CharacterField fieldCLINOM = null;
    private CharacterField fieldCLIAPE = null;
    private CharacterField fieldCLIAP2 = null;
    private CharacterField fieldCTA = null;
    private CharacterField fieldTCT = null;

    /**
     * Constructor for RECAPMFMMessage.
     */
    public RECAPMFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 485;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 171, 10, "CAMCUR");
        fields[11] = fieldPOSCUR
                = new DecimalField(message, HEADERSIZE + 181, 5, 0, "POSCUR");
        fields[12] = fieldCLAV
                = new CharacterField(message, HEADERSIZE + 186, 4, "CLAV");
        fields[13] = fieldFIDNOM
                = new CharacterField(message, HEADERSIZE + 190, 40, "FIDNOM");
        fields[14] = fieldTIPO
                = new CharacterField(message, HEADERSIZE + 230, 20, "TIPO");
        fields[15] = fieldCLINIF
                = new CharacterField(message, HEADERSIZE + 250, 12, "CLINIF");
        fields[16] = fieldFECAP
                = new DecimalField(message, HEADERSIZE + 262, 7, 0, "FECAP");
        fields[17] = fieldDISMNT
                = new DecimalField(message, HEADERSIZE + 269, 17, 2, "DISMNT");
        fields[18] = fieldMOVPGO
                = new DecimalField(message, HEADERSIZE + 286, 3, 0, "MOVPGO");
        fields[19] = fieldTEXTO
                = new CharacterField(message, HEADERSIZE + 289, 30, "TEXTO");
        fields[20] = fieldDATMIN
                = new DecimalField(message, HEADERSIZE + 319, 14, 2, "DATMIN");
        fields[21] = fieldDATMAE
                = new DecimalField(message, HEADERSIZE + 333, 14, 2, "DATMAE");
        fields[22] = fieldNOMBRE
                = new CharacterField(message, HEADERSIZE + 347, 50, "NOMBRE");
        fields[23] = fieldHMOINT
                = new DecimalField(message, HEADERSIZE + 397, 17, 2, "HMOINT");
        fields[24] = fieldCLINOM
                = new CharacterField(message, HEADERSIZE + 414, 20, "CLINOM");
        fields[25] = fieldCLIAPE
                = new CharacterField(message, HEADERSIZE + 434, 15, "CLIAPE");
        fields[26] = fieldCLIAP2
                = new CharacterField(message, HEADERSIZE + 449, 15, "CLIAP2");
        fields[27] = fieldCTA
                = new CharacterField(message, HEADERSIZE + 464, 20, "CTA");
        fields[28] = fieldTCT
                = new CharacterField(message, HEADERSIZE + 484, 1, "TCT");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field POSCUR using a String value.
     */
    public void setPOSCUR(String newvalue) {
        fieldPOSCUR.setString(newvalue);
    }

    /**
     * Get value of field POSCUR as a String.
     */
    public String getPOSCUR() {
        return fieldPOSCUR.getString();
    }

    /**
     * Set numeric field POSCUR using a BigDecimal value.
     */
    public void setPOSCUR(BigDecimal newvalue) {
        fieldPOSCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field POSCUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalPOSCUR() {
        return fieldPOSCUR.getBigDecimal();
    }

    /**
     * Set field CLAV using a String value.
     */
    public void setCLAV(String newvalue) {
        fieldCLAV.setString(newvalue);
    }

    /**
     * Get value of field CLAV as a String.
     */
    public String getCLAV() {
        return fieldCLAV.getString();
    }

    /**
     * Set field FIDNOM using a String value.
     */
    public void setFIDNOM(String newvalue) {
        fieldFIDNOM.setString(newvalue);
    }

    /**
     * Get value of field FIDNOM as a String.
     */
    public String getFIDNOM() {
        return fieldFIDNOM.getString();
    }

    /**
     * Set field TIPO using a String value.
     */
    public void setTIPO(String newvalue) {
        fieldTIPO.setString(newvalue);
    }

    /**
     * Get value of field TIPO as a String.
     */
    public String getTIPO() {
        return fieldTIPO.getString();
    }

    /**
     * Set field CLINIF using a String value.
     */
    public void setCLINIF(String newvalue) {
        fieldCLINIF.setString(newvalue);
    }

    /**
     * Get value of field CLINIF as a String.
     */
    public String getCLINIF() {
        return fieldCLINIF.getString();
    }

    /**
     * Set field FECAP using a String value.
     */
    public void setFECAP(String newvalue) {
        fieldFECAP.setString(newvalue);
    }

    /**
     * Get value of field FECAP as a String.
     */
    public String getFECAP() {
        return fieldFECAP.getString();
    }

    /**
     * Set numeric field FECAP using a BigDecimal value.
     */
    public void setFECAP(BigDecimal newvalue) {
        fieldFECAP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECAP as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECAP() {
        return fieldFECAP.getBigDecimal();
    }

    /**
     * Set field DISMNT using a String value.
     */
    public void setDISMNT(String newvalue) {
        fieldDISMNT.setString(newvalue);
    }

    /**
     * Get value of field DISMNT as a String.
     */
    public String getDISMNT() {
        return fieldDISMNT.getString();
    }

    /**
     * Set numeric field DISMNT using a BigDecimal value.
     */
    public void setDISMNT(BigDecimal newvalue) {
        fieldDISMNT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DISMNT as a BigDecimal.
     */
    public BigDecimal getBigDecimalDISMNT() {
        return fieldDISMNT.getBigDecimal();
    }

    /**
     * Set field MOVPGO using a String value.
     */
    public void setMOVPGO(String newvalue) {
        fieldMOVPGO.setString(newvalue);
    }

    /**
     * Get value of field MOVPGO as a String.
     */
    public String getMOVPGO() {
        return fieldMOVPGO.getString();
    }

    /**
     * Set numeric field MOVPGO using a BigDecimal value.
     */
    public void setMOVPGO(BigDecimal newvalue) {
        fieldMOVPGO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field MOVPGO as a BigDecimal.
     */
    public BigDecimal getBigDecimalMOVPGO() {
        return fieldMOVPGO.getBigDecimal();
    }

    /**
     * Set field TEXTO using a String value.
     */
    public void setTEXTO(String newvalue) {
        fieldTEXTO.setString(newvalue);
    }

    /**
     * Get value of field TEXTO as a String.
     */
    public String getTEXTO() {
        return fieldTEXTO.getString();
    }

    /**
     * Set field DATMIN using a String value.
     */
    public void setDATMIN(String newvalue) {
        fieldDATMIN.setString(newvalue);
    }

    /**
     * Get value of field DATMIN as a String.
     */
    public String getDATMIN() {
        return fieldDATMIN.getString();
    }

    /**
     * Set numeric field DATMIN using a BigDecimal value.
     */
    public void setDATMIN(BigDecimal newvalue) {
        fieldDATMIN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATMIN as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATMIN() {
        return fieldDATMIN.getBigDecimal();
    }

    /**
     * Set field DATMAE using a String value.
     */
    public void setDATMAE(String newvalue) {
        fieldDATMAE.setString(newvalue);
    }

    /**
     * Get value of field DATMAE as a String.
     */
    public String getDATMAE() {
        return fieldDATMAE.getString();
    }

    /**
     * Set numeric field DATMAE using a BigDecimal value.
     */
    public void setDATMAE(BigDecimal newvalue) {
        fieldDATMAE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DATMAE as a BigDecimal.
     */
    public BigDecimal getBigDecimalDATMAE() {
        return fieldDATMAE.getBigDecimal();
    }

    /**
     * Set field NOMBRE using a String value.
     */
    public void setNOMBRE(String newvalue) {
        fieldNOMBRE.setString(newvalue);
    }

    /**
     * Get value of field NOMBRE as a String.
     */
    public String getNOMBRE() {
        return fieldNOMBRE.getString();
    }

    /**
     * Set field HMOINT using a String value.
     */
    public void setHMOINT(String newvalue) {
        fieldHMOINT.setString(newvalue);
    }

    /**
     * Get value of field HMOINT as a String.
     */
    public String getHMOINT() {
        return fieldHMOINT.getString();
    }

    /**
     * Set numeric field HMOINT using a BigDecimal value.
     */
    public void setHMOINT(BigDecimal newvalue) {
        fieldHMOINT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HMOINT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHMOINT() {
        return fieldHMOINT.getBigDecimal();
    }

    /**
     * Set field CLINOM using a String value.
     */
    public void setCLINOM(String newvalue) {
        fieldCLINOM.setString(newvalue);
    }

    /**
     * Get value of field CLINOM as a String.
     */
    public String getCLINOM() {
        return fieldCLINOM.getString();
    }

    /**
     * Set field CLIAPE using a String value.
     */
    public void setCLIAPE(String newvalue) {
        fieldCLIAPE.setString(newvalue);
    }

    /**
     * Get value of field CLIAPE as a String.
     */
    public String getCLIAPE() {
        return fieldCLIAPE.getString();
    }

    /**
     * Set field CLIAP2 using a String value.
     */
    public void setCLIAP2(String newvalue) {
        fieldCLIAP2.setString(newvalue);
    }

    /**
     * Get value of field CLIAP2 as a String.
     */
    public String getCLIAP2() {
        return fieldCLIAP2.getString();
    }

    /**
     * Set field CTA using a String value.
     */
    public void setCTA(String newvalue) {
        fieldCTA.setString(newvalue);
    }

    /**
     * Get value of field CTA as a String.
     */
    public String getCTA() {
        return fieldCTA.getString();
    }

    /**
     * Set field TCT using a String value.
     */
    public void setTCT(String newvalue) {
        fieldTCT.setString(newvalue);
    }

    /**
     * Get value of field TCT as a String.
     */
    public String getTCT() {
        return fieldTCT.getString();
    }

}
