package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
* Class generated by AS/400 CRTCLASS command from RECIBOFM physical file definition.
* 
* File level identifier is 1140204152648.
* Record format level identifier is 4E04B79DDC62F.
*/

public class RECIBOFMMessage extends MessageRecord
{
  final static String fldnames[] = {
                                     "HDAT",
                                     "HTIM",
                                     "HUSR",
                                     "HENV",
                                     "HXML",
                                     "HSEC",
                                     "HFIL",
                                     "HLEN",
                                     "INDICA",
                                     "CAMCUR",
                                     "REGCUR",
                                     "POSCUR",
                                     "MONTO",
                                     "TXTERR",
                                     "OFI1",
                                     "CTA1",
                                     "MNT1",
                                     "OFI2",
                                     "CTA2",
                                     "MNT2",
                                     "OFI3",
                                     "CTA3",
                                     "MNT3",
                                     "OFI4",
                                     "CTA4",
                                     "MNT4",
                                     "OFI5",
                                     "CTA5",
                                     "MNT5",
                                     "EMI1",
                                     "VAL1",
                                     "VTO1",
                                     "EMI2",
                                     "VAL2",
                                     "VTO2",
                                     "EMI3",
                                     "VAL3",
                                     "VTO3",
                                     "EMI4",
                                     "VAL4",
                                     "VTO4",
                                     "EMI5",
                                     "VAL5",
                                     "VTO5",
                                     "CHE1",
                                     "FEC1",
                                     "CHE2",
                                     "FEC2",
                                     "CHE3",
                                     "FEC3",
                                     "CHE4",
                                     "FEC4",
                                     "CHE5",
                                     "FEC5",
                                     "LIN11",
                                     "LIN2",
                                     "LIN21",
                                     "LIN3",
                                     "LIN31",
                                     "LIN4",
                                     "SINO"
                                   };
  final static String tnames[] = {
                                   "HDAT",
                                   "HTIM",
                                   "HUSR",
                                   "HENV",
                                   "HXML",
                                   "HSEC",
                                   "HFIL",
                                   "HLEN",
                                   "INDICA",
                                   "CAMCUR",
                                   "REGCUR",
                                   "POSCUR",
                                   "MONTO",
                                   "TXTERR",
                                   "OFI1",
                                   "CTA1",
                                   "MNT1",
                                   "OFI2",
                                   "CTA2",
                                   "MNT2",
                                   "OFI3",
                                   "CTA3",
                                   "MNT3",
                                   "OFI4",
                                   "CTA4",
                                   "MNT4",
                                   "OFI5",
                                   "CTA5",
                                   "MNT5",
                                   "EMI1",
                                   "VAL1",
                                   "VTO1",
                                   "EMI2",
                                   "VAL2",
                                   "VTO2",
                                   "EMI3",
                                   "VAL3",
                                   "VTO3",
                                   "EMI4",
                                   "VAL4",
                                   "VTO4",
                                   "EMI5",
                                   "VAL5",
                                   "VTO5",
                                   "CHE1",
                                   "FEC1",
                                   "CHE2",
                                   "FEC2",
                                   "CHE3",
                                   "FEC3",
                                   "CHE4",
                                   "FEC4",
                                   "CHE5",
                                   "FEC5",
                                   "LIN11",
                                   "LIN2",
                                   "LIN21",
                                   "LIN3",
                                   "LIN31",
                                   "LIN4",
                                   "SINO"
                                 };
  final static String fid = "1140204152648";
  final static String rid = "4E04B79DDC62F";
  final static String fmtname = "RECIBOFM";
  final int FIELDCOUNT = 61;
  private static Hashtable tlookup = new Hashtable();
  private DecimalField fieldHDAT = null;
  private DecimalField fieldHTIM = null;
  private CharacterField fieldHUSR = null;
  private CharacterField fieldHENV = null;
  private CharacterField fieldHXML = null;
  private CharacterField fieldHSEC = null;
  private CharacterField fieldHFIL = null;
  private DecimalField fieldHLEN = null;
  private CharacterField fieldINDICA = null;
  private CharacterField fieldCAMCUR = null;
  private CharacterField fieldREGCUR = null;
  private DecimalField fieldPOSCUR = null;
  private DecimalField fieldMONTO = null;
  private CharacterField fieldTXTERR = null;
  private DecimalField fieldOFI1 = null;
  private CharacterField fieldCTA1 = null;
  private DecimalField fieldMNT1 = null;
  private DecimalField fieldOFI2 = null;
  private CharacterField fieldCTA2 = null;
  private DecimalField fieldMNT2 = null;
  private DecimalField fieldOFI3 = null;
  private CharacterField fieldCTA3 = null;
  private DecimalField fieldMNT3 = null;
  private DecimalField fieldOFI4 = null;
  private CharacterField fieldCTA4 = null;
  private DecimalField fieldMNT4 = null;
  private DecimalField fieldOFI5 = null;
  private CharacterField fieldCTA5 = null;
  private DecimalField fieldMNT5 = null;
  private DecimalField fieldEMI1 = null;
  private CharacterField fieldVAL1 = null;
  private DecimalField fieldVTO1 = null;
  private DecimalField fieldEMI2 = null;
  private CharacterField fieldVAL2 = null;
  private DecimalField fieldVTO2 = null;
  private DecimalField fieldEMI3 = null;
  private CharacterField fieldVAL3 = null;
  private DecimalField fieldVTO3 = null;
  private DecimalField fieldEMI4 = null;
  private CharacterField fieldVAL4 = null;
  private DecimalField fieldVTO4 = null;
  private DecimalField fieldEMI5 = null;
  private CharacterField fieldVAL5 = null;
  private DecimalField fieldVTO5 = null;
  private DecimalField fieldCHE1 = null;
  private DecimalField fieldFEC1 = null;
  private DecimalField fieldCHE2 = null;
  private DecimalField fieldFEC2 = null;
  private DecimalField fieldCHE3 = null;
  private DecimalField fieldFEC3 = null;
  private DecimalField fieldCHE4 = null;
  private DecimalField fieldFEC4 = null;
  private DecimalField fieldCHE5 = null;
  private DecimalField fieldFEC5 = null;
  private CharacterField fieldLIN11 = null;
  private CharacterField fieldLIN2 = null;
  private CharacterField fieldLIN21 = null;
  private CharacterField fieldLIN3 = null;
  private CharacterField fieldLIN31 = null;
  private CharacterField fieldLIN4 = null;
  private CharacterField fieldSINO = null;

  /**
  * Constructor for RECIBOFMMessage.
  */
  public RECIBOFMMessage()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 1088;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldHDAT =
    new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
    fields[1] = fieldHTIM =
    new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
    fields[2] = fieldHUSR =
    new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
    fields[3] = fieldHENV =
    new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
    fields[4] = fieldHXML =
    new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
    fields[5] = fieldHSEC =
    new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
    fields[6] = fieldHFIL =
    new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
    fields[7] = fieldHLEN =
    new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
    fields[8] = fieldINDICA =
    new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
    fields[9] = fieldCAMCUR =
    new CharacterField(message, HEADERSIZE + 161, 10, "CAMCUR");
    fields[10] = fieldREGCUR =
    new CharacterField(message, HEADERSIZE + 171, 10, "REGCUR");
    fields[11] = fieldPOSCUR =
    new DecimalField(message, HEADERSIZE + 181, 5, 0, "POSCUR");
    fields[12] = fieldMONTO =
    new DecimalField(message, HEADERSIZE + 186, 16, 2, "MONTO");
    fields[13] = fieldTXTERR =
    new CharacterField(message, HEADERSIZE + 202, 30, "TXTERR");
    fields[14] = fieldOFI1 =
    new DecimalField(message, HEADERSIZE + 232, 8, 0, "OFI1");
    fields[15] = fieldCTA1 =
    new CharacterField(message, HEADERSIZE + 240, 20, "CTA1");
    fields[16] = fieldMNT1 =
    new DecimalField(message, HEADERSIZE + 260, 16, 2, "MNT1");
    fields[17] = fieldOFI2 =
    new DecimalField(message, HEADERSIZE + 276, 8, 0, "OFI2");
    fields[18] = fieldCTA2 =
    new CharacterField(message, HEADERSIZE + 284, 20, "CTA2");
    fields[19] = fieldMNT2 =
    new DecimalField(message, HEADERSIZE + 304, 16, 2, "MNT2");
    fields[20] = fieldOFI3 =
    new DecimalField(message, HEADERSIZE + 320, 8, 0, "OFI3");
    fields[21] = fieldCTA3 =
    new CharacterField(message, HEADERSIZE + 328, 20, "CTA3");
    fields[22] = fieldMNT3 =
    new DecimalField(message, HEADERSIZE + 348, 16, 2, "MNT3");
    fields[23] = fieldOFI4 =
    new DecimalField(message, HEADERSIZE + 364, 8, 0, "OFI4");
    fields[24] = fieldCTA4 =
    new CharacterField(message, HEADERSIZE + 372, 20, "CTA4");
    fields[25] = fieldMNT4 =
    new DecimalField(message, HEADERSIZE + 392, 16, 2, "MNT4");
    fields[26] = fieldOFI5 =
    new DecimalField(message, HEADERSIZE + 408, 8, 0, "OFI5");
    fields[27] = fieldCTA5 =
    new CharacterField(message, HEADERSIZE + 416, 20, "CTA5");
    fields[28] = fieldMNT5 =
    new DecimalField(message, HEADERSIZE + 436, 16, 2, "MNT5");
    fields[29] = fieldEMI1 =
    new DecimalField(message, HEADERSIZE + 452, 8, 0, "EMI1");
    fields[30] = fieldVAL1 =
    new CharacterField(message, HEADERSIZE + 460, 12, "VAL1");
    fields[31] = fieldVTO1 =
    new DecimalField(message, HEADERSIZE + 472, 7, 0, "VTO1");
    fields[32] = fieldEMI2 =
    new DecimalField(message, HEADERSIZE + 479, 8, 0, "EMI2");
    fields[33] = fieldVAL2 =
    new CharacterField(message, HEADERSIZE + 487, 12, "VAL2");
    fields[34] = fieldVTO2 =
    new DecimalField(message, HEADERSIZE + 499, 7, 0, "VTO2");
    fields[35] = fieldEMI3 =
    new DecimalField(message, HEADERSIZE + 506, 8, 0, "EMI3");
    fields[36] = fieldVAL3 =
    new CharacterField(message, HEADERSIZE + 514, 12, "VAL3");
    fields[37] = fieldVTO3 =
    new DecimalField(message, HEADERSIZE + 526, 7, 0, "VTO3");
    fields[38] = fieldEMI4 =
    new DecimalField(message, HEADERSIZE + 533, 8, 0, "EMI4");
    fields[39] = fieldVAL4 =
    new CharacterField(message, HEADERSIZE + 541, 12, "VAL4");
    fields[40] = fieldVTO4 =
    new DecimalField(message, HEADERSIZE + 553, 7, 0, "VTO4");
    fields[41] = fieldEMI5 =
    new DecimalField(message, HEADERSIZE + 560, 8, 0, "EMI5");
    fields[42] = fieldVAL5 =
    new CharacterField(message, HEADERSIZE + 568, 12, "VAL5");
    fields[43] = fieldVTO5 =
    new DecimalField(message, HEADERSIZE + 580, 7, 0, "VTO5");
    fields[44] = fieldCHE1 =
    new DecimalField(message, HEADERSIZE + 587, 9, 0, "CHE1");
    fields[45] = fieldFEC1 =
    new DecimalField(message, HEADERSIZE + 596, 7, 0, "FEC1");
    fields[46] = fieldCHE2 =
    new DecimalField(message, HEADERSIZE + 603, 9, 0, "CHE2");
    fields[47] = fieldFEC2 =
    new DecimalField(message, HEADERSIZE + 612, 7, 0, "FEC2");
    fields[48] = fieldCHE3 =
    new DecimalField(message, HEADERSIZE + 619, 9, 0, "CHE3");
    fields[49] = fieldFEC3 =
    new DecimalField(message, HEADERSIZE + 628, 7, 0, "FEC3");
    fields[50] = fieldCHE4 =
    new DecimalField(message, HEADERSIZE + 635, 9, 0, "CHE4");
    fields[51] = fieldFEC4 =
    new DecimalField(message, HEADERSIZE + 644, 7, 0, "FEC4");
    fields[52] = fieldCHE5 =
    new DecimalField(message, HEADERSIZE + 651, 9, 0, "CHE5");
    fields[53] = fieldFEC5 =
    new DecimalField(message, HEADERSIZE + 660, 7, 0, "FEC5");
    fields[54] = fieldLIN11 =
    new CharacterField(message, HEADERSIZE + 667, 70, "LIN11");
    fields[55] = fieldLIN2 =
    new CharacterField(message, HEADERSIZE + 737, 70, "LIN2");
    fields[56] = fieldLIN21 =
    new CharacterField(message, HEADERSIZE + 807, 70, "LIN21");
    fields[57] = fieldLIN3 =
    new CharacterField(message, HEADERSIZE + 877, 70, "LIN3");
    fields[58] = fieldLIN31 =
    new CharacterField(message, HEADERSIZE + 947, 70, "LIN31");
    fields[59] = fieldLIN4 =
    new CharacterField(message, HEADERSIZE + 1017, 70, "LIN4");
    fields[60] = fieldSINO =
    new CharacterField(message, HEADERSIZE + 1087, 1, "SINO");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field HDAT using a String value.
  */
  public void setHDAT(String newvalue)
  {
    fieldHDAT.setString(newvalue);
  }

  /**
  * Get value of field HDAT as a String.
  */
  public String getHDAT()
  {
    return fieldHDAT.getString();
  }

  /**
  * Set numeric field HDAT using a BigDecimal value.
  */
  public void setHDAT(BigDecimal newvalue)
  {
    fieldHDAT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HDAT as a BigDecimal.
  */
  public BigDecimal getBigDecimalHDAT()
  {
    return fieldHDAT.getBigDecimal();
  }

  /**
  * Set field HTIM using a String value.
  */
  public void setHTIM(String newvalue)
  {
    fieldHTIM.setString(newvalue);
  }

  /**
  * Get value of field HTIM as a String.
  */
  public String getHTIM()
  {
    return fieldHTIM.getString();
  }

  /**
  * Set numeric field HTIM using a BigDecimal value.
  */
  public void setHTIM(BigDecimal newvalue)
  {
    fieldHTIM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HTIM as a BigDecimal.
  */
  public BigDecimal getBigDecimalHTIM()
  {
    return fieldHTIM.getBigDecimal();
  }

  /**
  * Set field HUSR using a String value.
  */
  public void setHUSR(String newvalue)
  {
    fieldHUSR.setString(newvalue);
  }

  /**
  * Get value of field HUSR as a String.
  */
  public String getHUSR()
  {
    return fieldHUSR.getString();
  }

  /**
  * Set field HENV using a String value.
  */
  public void setHENV(String newvalue)
  {
    fieldHENV.setString(newvalue);
  }

  /**
  * Get value of field HENV as a String.
  */
  public String getHENV()
  {
    return fieldHENV.getString();
  }

  /**
  * Set field HXML using a String value.
  */
  public void setHXML(String newvalue)
  {
    fieldHXML.setString(newvalue);
  }

  /**
  * Get value of field HXML as a String.
  */
  public String getHXML()
  {
    return fieldHXML.getString();
  }

  /**
  * Set field HSEC using a String value.
  */
  public void setHSEC(String newvalue)
  {
    fieldHSEC.setString(newvalue);
  }

  /**
  * Get value of field HSEC as a String.
  */
  public String getHSEC()
  {
    return fieldHSEC.getString();
  }

  /**
  * Set field HFIL using a String value.
  */
  public void setHFIL(String newvalue)
  {
    fieldHFIL.setString(newvalue);
  }

  /**
  * Get value of field HFIL as a String.
  */
  public String getHFIL()
  {
    return fieldHFIL.getString();
  }

  /**
  * Set field HLEN using a String value.
  */
  public void setHLEN(String newvalue)
  {
    fieldHLEN.setString(newvalue);
  }

  /**
  * Get value of field HLEN as a String.
  */
  public String getHLEN()
  {
    return fieldHLEN.getString();
  }

  /**
  * Set numeric field HLEN using a BigDecimal value.
  */
  public void setHLEN(BigDecimal newvalue)
  {
    fieldHLEN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HLEN as a BigDecimal.
  */
  public BigDecimal getBigDecimalHLEN()
  {
    return fieldHLEN.getBigDecimal();
  }

  /**
  * Set field INDICA using a String value.
  */
  public void setINDICA(String newvalue)
  {
    fieldINDICA.setString(newvalue);
  }

  /**
  * Get value of field INDICA as a String.
  */
  public String getINDICA()
  {
    return fieldINDICA.getString();
  }

  /**
  * Set field CAMCUR using a String value.
  */
  public void setCAMCUR(String newvalue)
  {
    fieldCAMCUR.setString(newvalue);
  }

  /**
  * Get value of field CAMCUR as a String.
  */
  public String getCAMCUR()
  {
    return fieldCAMCUR.getString();
  }

  /**
  * Set field REGCUR using a String value.
  */
  public void setREGCUR(String newvalue)
  {
    fieldREGCUR.setString(newvalue);
  }

  /**
  * Get value of field REGCUR as a String.
  */
  public String getREGCUR()
  {
    return fieldREGCUR.getString();
  }

  /**
  * Set field POSCUR using a String value.
  */
  public void setPOSCUR(String newvalue)
  {
    fieldPOSCUR.setString(newvalue);
  }

  /**
  * Get value of field POSCUR as a String.
  */
  public String getPOSCUR()
  {
    return fieldPOSCUR.getString();
  }

  /**
  * Set numeric field POSCUR using a BigDecimal value.
  */
  public void setPOSCUR(BigDecimal newvalue)
  {
    fieldPOSCUR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field POSCUR as a BigDecimal.
  */
  public BigDecimal getBigDecimalPOSCUR()
  {
    return fieldPOSCUR.getBigDecimal();
  }

  /**
  * Set field MONTO using a String value.
  */
  public void setMONTO(String newvalue)
  {
    fieldMONTO.setString(newvalue);
  }

  /**
  * Get value of field MONTO as a String.
  */
  public String getMONTO()
  {
    return fieldMONTO.getString();
  }

  /**
  * Set numeric field MONTO using a BigDecimal value.
  */
  public void setMONTO(BigDecimal newvalue)
  {
    fieldMONTO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field MONTO as a BigDecimal.
  */
  public BigDecimal getBigDecimalMONTO()
  {
    return fieldMONTO.getBigDecimal();
  }

  /**
  * Set field TXTERR using a String value.
  */
  public void setTXTERR(String newvalue)
  {
    fieldTXTERR.setString(newvalue);
  }

  /**
  * Get value of field TXTERR as a String.
  */
  public String getTXTERR()
  {
    return fieldTXTERR.getString();
  }

  /**
  * Set field OFI1 using a String value.
  */
  public void setOFI1(String newvalue)
  {
    fieldOFI1.setString(newvalue);
  }

  /**
  * Get value of field OFI1 as a String.
  */
  public String getOFI1()
  {
    return fieldOFI1.getString();
  }

  /**
  * Set numeric field OFI1 using a BigDecimal value.
  */
  public void setOFI1(BigDecimal newvalue)
  {
    fieldOFI1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field OFI1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalOFI1()
  {
    return fieldOFI1.getBigDecimal();
  }

  /**
  * Set field CTA1 using a String value.
  */
  public void setCTA1(String newvalue)
  {
    fieldCTA1.setString(newvalue);
  }

  /**
  * Get value of field CTA1 as a String.
  */
  public String getCTA1()
  {
    return fieldCTA1.getString();
  }

  /**
  * Set field MNT1 using a String value.
  */
  public void setMNT1(String newvalue)
  {
    fieldMNT1.setString(newvalue);
  }

  /**
  * Get value of field MNT1 as a String.
  */
  public String getMNT1()
  {
    return fieldMNT1.getString();
  }

  /**
  * Set numeric field MNT1 using a BigDecimal value.
  */
  public void setMNT1(BigDecimal newvalue)
  {
    fieldMNT1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field MNT1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalMNT1()
  {
    return fieldMNT1.getBigDecimal();
  }

  /**
  * Set field OFI2 using a String value.
  */
  public void setOFI2(String newvalue)
  {
    fieldOFI2.setString(newvalue);
  }

  /**
  * Get value of field OFI2 as a String.
  */
  public String getOFI2()
  {
    return fieldOFI2.getString();
  }

  /**
  * Set numeric field OFI2 using a BigDecimal value.
  */
  public void setOFI2(BigDecimal newvalue)
  {
    fieldOFI2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field OFI2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalOFI2()
  {
    return fieldOFI2.getBigDecimal();
  }

  /**
  * Set field CTA2 using a String value.
  */
  public void setCTA2(String newvalue)
  {
    fieldCTA2.setString(newvalue);
  }

  /**
  * Get value of field CTA2 as a String.
  */
  public String getCTA2()
  {
    return fieldCTA2.getString();
  }

  /**
  * Set field MNT2 using a String value.
  */
  public void setMNT2(String newvalue)
  {
    fieldMNT2.setString(newvalue);
  }

  /**
  * Get value of field MNT2 as a String.
  */
  public String getMNT2()
  {
    return fieldMNT2.getString();
  }

  /**
  * Set numeric field MNT2 using a BigDecimal value.
  */
  public void setMNT2(BigDecimal newvalue)
  {
    fieldMNT2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field MNT2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalMNT2()
  {
    return fieldMNT2.getBigDecimal();
  }

  /**
  * Set field OFI3 using a String value.
  */
  public void setOFI3(String newvalue)
  {
    fieldOFI3.setString(newvalue);
  }

  /**
  * Get value of field OFI3 as a String.
  */
  public String getOFI3()
  {
    return fieldOFI3.getString();
  }

  /**
  * Set numeric field OFI3 using a BigDecimal value.
  */
  public void setOFI3(BigDecimal newvalue)
  {
    fieldOFI3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field OFI3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalOFI3()
  {
    return fieldOFI3.getBigDecimal();
  }

  /**
  * Set field CTA3 using a String value.
  */
  public void setCTA3(String newvalue)
  {
    fieldCTA3.setString(newvalue);
  }

  /**
  * Get value of field CTA3 as a String.
  */
  public String getCTA3()
  {
    return fieldCTA3.getString();
  }

  /**
  * Set field MNT3 using a String value.
  */
  public void setMNT3(String newvalue)
  {
    fieldMNT3.setString(newvalue);
  }

  /**
  * Get value of field MNT3 as a String.
  */
  public String getMNT3()
  {
    return fieldMNT3.getString();
  }

  /**
  * Set numeric field MNT3 using a BigDecimal value.
  */
  public void setMNT3(BigDecimal newvalue)
  {
    fieldMNT3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field MNT3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalMNT3()
  {
    return fieldMNT3.getBigDecimal();
  }

  /**
  * Set field OFI4 using a String value.
  */
  public void setOFI4(String newvalue)
  {
    fieldOFI4.setString(newvalue);
  }

  /**
  * Get value of field OFI4 as a String.
  */
  public String getOFI4()
  {
    return fieldOFI4.getString();
  }

  /**
  * Set numeric field OFI4 using a BigDecimal value.
  */
  public void setOFI4(BigDecimal newvalue)
  {
    fieldOFI4.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field OFI4 as a BigDecimal.
  */
  public BigDecimal getBigDecimalOFI4()
  {
    return fieldOFI4.getBigDecimal();
  }

  /**
  * Set field CTA4 using a String value.
  */
  public void setCTA4(String newvalue)
  {
    fieldCTA4.setString(newvalue);
  }

  /**
  * Get value of field CTA4 as a String.
  */
  public String getCTA4()
  {
    return fieldCTA4.getString();
  }

  /**
  * Set field MNT4 using a String value.
  */
  public void setMNT4(String newvalue)
  {
    fieldMNT4.setString(newvalue);
  }

  /**
  * Get value of field MNT4 as a String.
  */
  public String getMNT4()
  {
    return fieldMNT4.getString();
  }

  /**
  * Set numeric field MNT4 using a BigDecimal value.
  */
  public void setMNT4(BigDecimal newvalue)
  {
    fieldMNT4.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field MNT4 as a BigDecimal.
  */
  public BigDecimal getBigDecimalMNT4()
  {
    return fieldMNT4.getBigDecimal();
  }

  /**
  * Set field OFI5 using a String value.
  */
  public void setOFI5(String newvalue)
  {
    fieldOFI5.setString(newvalue);
  }

  /**
  * Get value of field OFI5 as a String.
  */
  public String getOFI5()
  {
    return fieldOFI5.getString();
  }

  /**
  * Set numeric field OFI5 using a BigDecimal value.
  */
  public void setOFI5(BigDecimal newvalue)
  {
    fieldOFI5.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field OFI5 as a BigDecimal.
  */
  public BigDecimal getBigDecimalOFI5()
  {
    return fieldOFI5.getBigDecimal();
  }

  /**
  * Set field CTA5 using a String value.
  */
  public void setCTA5(String newvalue)
  {
    fieldCTA5.setString(newvalue);
  }

  /**
  * Get value of field CTA5 as a String.
  */
  public String getCTA5()
  {
    return fieldCTA5.getString();
  }

  /**
  * Set field MNT5 using a String value.
  */
  public void setMNT5(String newvalue)
  {
    fieldMNT5.setString(newvalue);
  }

  /**
  * Get value of field MNT5 as a String.
  */
  public String getMNT5()
  {
    return fieldMNT5.getString();
  }

  /**
  * Set numeric field MNT5 using a BigDecimal value.
  */
  public void setMNT5(BigDecimal newvalue)
  {
    fieldMNT5.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field MNT5 as a BigDecimal.
  */
  public BigDecimal getBigDecimalMNT5()
  {
    return fieldMNT5.getBigDecimal();
  }

  /**
  * Set field EMI1 using a String value.
  */
  public void setEMI1(String newvalue)
  {
    fieldEMI1.setString(newvalue);
  }

  /**
  * Get value of field EMI1 as a String.
  */
  public String getEMI1()
  {
    return fieldEMI1.getString();
  }

  /**
  * Set numeric field EMI1 using a BigDecimal value.
  */
  public void setEMI1(BigDecimal newvalue)
  {
    fieldEMI1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field EMI1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalEMI1()
  {
    return fieldEMI1.getBigDecimal();
  }

  /**
  * Set field VAL1 using a String value.
  */
  public void setVAL1(String newvalue)
  {
    fieldVAL1.setString(newvalue);
  }

  /**
  * Get value of field VAL1 as a String.
  */
  public String getVAL1()
  {
    return fieldVAL1.getString();
  }

  /**
  * Set field VTO1 using a String value.
  */
  public void setVTO1(String newvalue)
  {
    fieldVTO1.setString(newvalue);
  }

  /**
  * Get value of field VTO1 as a String.
  */
  public String getVTO1()
  {
    return fieldVTO1.getString();
  }

  /**
  * Set numeric field VTO1 using a BigDecimal value.
  */
  public void setVTO1(BigDecimal newvalue)
  {
    fieldVTO1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field VTO1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalVTO1()
  {
    return fieldVTO1.getBigDecimal();
  }

  /**
  * Set field EMI2 using a String value.
  */
  public void setEMI2(String newvalue)
  {
    fieldEMI2.setString(newvalue);
  }

  /**
  * Get value of field EMI2 as a String.
  */
  public String getEMI2()
  {
    return fieldEMI2.getString();
  }

  /**
  * Set numeric field EMI2 using a BigDecimal value.
  */
  public void setEMI2(BigDecimal newvalue)
  {
    fieldEMI2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field EMI2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalEMI2()
  {
    return fieldEMI2.getBigDecimal();
  }

  /**
  * Set field VAL2 using a String value.
  */
  public void setVAL2(String newvalue)
  {
    fieldVAL2.setString(newvalue);
  }

  /**
  * Get value of field VAL2 as a String.
  */
  public String getVAL2()
  {
    return fieldVAL2.getString();
  }

  /**
  * Set field VTO2 using a String value.
  */
  public void setVTO2(String newvalue)
  {
    fieldVTO2.setString(newvalue);
  }

  /**
  * Get value of field VTO2 as a String.
  */
  public String getVTO2()
  {
    return fieldVTO2.getString();
  }

  /**
  * Set numeric field VTO2 using a BigDecimal value.
  */
  public void setVTO2(BigDecimal newvalue)
  {
    fieldVTO2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field VTO2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalVTO2()
  {
    return fieldVTO2.getBigDecimal();
  }

  /**
  * Set field EMI3 using a String value.
  */
  public void setEMI3(String newvalue)
  {
    fieldEMI3.setString(newvalue);
  }

  /**
  * Get value of field EMI3 as a String.
  */
  public String getEMI3()
  {
    return fieldEMI3.getString();
  }

  /**
  * Set numeric field EMI3 using a BigDecimal value.
  */
  public void setEMI3(BigDecimal newvalue)
  {
    fieldEMI3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field EMI3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalEMI3()
  {
    return fieldEMI3.getBigDecimal();
  }

  /**
  * Set field VAL3 using a String value.
  */
  public void setVAL3(String newvalue)
  {
    fieldVAL3.setString(newvalue);
  }

  /**
  * Get value of field VAL3 as a String.
  */
  public String getVAL3()
  {
    return fieldVAL3.getString();
  }

  /**
  * Set field VTO3 using a String value.
  */
  public void setVTO3(String newvalue)
  {
    fieldVTO3.setString(newvalue);
  }

  /**
  * Get value of field VTO3 as a String.
  */
  public String getVTO3()
  {
    return fieldVTO3.getString();
  }

  /**
  * Set numeric field VTO3 using a BigDecimal value.
  */
  public void setVTO3(BigDecimal newvalue)
  {
    fieldVTO3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field VTO3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalVTO3()
  {
    return fieldVTO3.getBigDecimal();
  }

  /**
  * Set field EMI4 using a String value.
  */
  public void setEMI4(String newvalue)
  {
    fieldEMI4.setString(newvalue);
  }

  /**
  * Get value of field EMI4 as a String.
  */
  public String getEMI4()
  {
    return fieldEMI4.getString();
  }

  /**
  * Set numeric field EMI4 using a BigDecimal value.
  */
  public void setEMI4(BigDecimal newvalue)
  {
    fieldEMI4.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field EMI4 as a BigDecimal.
  */
  public BigDecimal getBigDecimalEMI4()
  {
    return fieldEMI4.getBigDecimal();
  }

  /**
  * Set field VAL4 using a String value.
  */
  public void setVAL4(String newvalue)
  {
    fieldVAL4.setString(newvalue);
  }

  /**
  * Get value of field VAL4 as a String.
  */
  public String getVAL4()
  {
    return fieldVAL4.getString();
  }

  /**
  * Set field VTO4 using a String value.
  */
  public void setVTO4(String newvalue)
  {
    fieldVTO4.setString(newvalue);
  }

  /**
  * Get value of field VTO4 as a String.
  */
  public String getVTO4()
  {
    return fieldVTO4.getString();
  }

  /**
  * Set numeric field VTO4 using a BigDecimal value.
  */
  public void setVTO4(BigDecimal newvalue)
  {
    fieldVTO4.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field VTO4 as a BigDecimal.
  */
  public BigDecimal getBigDecimalVTO4()
  {
    return fieldVTO4.getBigDecimal();
  }

  /**
  * Set field EMI5 using a String value.
  */
  public void setEMI5(String newvalue)
  {
    fieldEMI5.setString(newvalue);
  }

  /**
  * Get value of field EMI5 as a String.
  */
  public String getEMI5()
  {
    return fieldEMI5.getString();
  }

  /**
  * Set numeric field EMI5 using a BigDecimal value.
  */
  public void setEMI5(BigDecimal newvalue)
  {
    fieldEMI5.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field EMI5 as a BigDecimal.
  */
  public BigDecimal getBigDecimalEMI5()
  {
    return fieldEMI5.getBigDecimal();
  }

  /**
  * Set field VAL5 using a String value.
  */
  public void setVAL5(String newvalue)
  {
    fieldVAL5.setString(newvalue);
  }

  /**
  * Get value of field VAL5 as a String.
  */
  public String getVAL5()
  {
    return fieldVAL5.getString();
  }

  /**
  * Set field VTO5 using a String value.
  */
  public void setVTO5(String newvalue)
  {
    fieldVTO5.setString(newvalue);
  }

  /**
  * Get value of field VTO5 as a String.
  */
  public String getVTO5()
  {
    return fieldVTO5.getString();
  }

  /**
  * Set numeric field VTO5 using a BigDecimal value.
  */
  public void setVTO5(BigDecimal newvalue)
  {
    fieldVTO5.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field VTO5 as a BigDecimal.
  */
  public BigDecimal getBigDecimalVTO5()
  {
    return fieldVTO5.getBigDecimal();
  }

  /**
  * Set field CHE1 using a String value.
  */
  public void setCHE1(String newvalue)
  {
    fieldCHE1.setString(newvalue);
  }

  /**
  * Get value of field CHE1 as a String.
  */
  public String getCHE1()
  {
    return fieldCHE1.getString();
  }

  /**
  * Set numeric field CHE1 using a BigDecimal value.
  */
  public void setCHE1(BigDecimal newvalue)
  {
    fieldCHE1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field CHE1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalCHE1()
  {
    return fieldCHE1.getBigDecimal();
  }

  /**
  * Set field FEC1 using a String value.
  */
  public void setFEC1(String newvalue)
  {
    fieldFEC1.setString(newvalue);
  }

  /**
  * Get value of field FEC1 as a String.
  */
  public String getFEC1()
  {
    return fieldFEC1.getString();
  }

  /**
  * Set numeric field FEC1 using a BigDecimal value.
  */
  public void setFEC1(BigDecimal newvalue)
  {
    fieldFEC1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field FEC1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalFEC1()
  {
    return fieldFEC1.getBigDecimal();
  }

  /**
  * Set field CHE2 using a String value.
  */
  public void setCHE2(String newvalue)
  {
    fieldCHE2.setString(newvalue);
  }

  /**
  * Get value of field CHE2 as a String.
  */
  public String getCHE2()
  {
    return fieldCHE2.getString();
  }

  /**
  * Set numeric field CHE2 using a BigDecimal value.
  */
  public void setCHE2(BigDecimal newvalue)
  {
    fieldCHE2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field CHE2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalCHE2()
  {
    return fieldCHE2.getBigDecimal();
  }

  /**
  * Set field FEC2 using a String value.
  */
  public void setFEC2(String newvalue)
  {
    fieldFEC2.setString(newvalue);
  }

  /**
  * Get value of field FEC2 as a String.
  */
  public String getFEC2()
  {
    return fieldFEC2.getString();
  }

  /**
  * Set numeric field FEC2 using a BigDecimal value.
  */
  public void setFEC2(BigDecimal newvalue)
  {
    fieldFEC2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field FEC2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalFEC2()
  {
    return fieldFEC2.getBigDecimal();
  }

  /**
  * Set field CHE3 using a String value.
  */
  public void setCHE3(String newvalue)
  {
    fieldCHE3.setString(newvalue);
  }

  /**
  * Get value of field CHE3 as a String.
  */
  public String getCHE3()
  {
    return fieldCHE3.getString();
  }

  /**
  * Set numeric field CHE3 using a BigDecimal value.
  */
  public void setCHE3(BigDecimal newvalue)
  {
    fieldCHE3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field CHE3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalCHE3()
  {
    return fieldCHE3.getBigDecimal();
  }

  /**
  * Set field FEC3 using a String value.
  */
  public void setFEC3(String newvalue)
  {
    fieldFEC3.setString(newvalue);
  }

  /**
  * Get value of field FEC3 as a String.
  */
  public String getFEC3()
  {
    return fieldFEC3.getString();
  }

  /**
  * Set numeric field FEC3 using a BigDecimal value.
  */
  public void setFEC3(BigDecimal newvalue)
  {
    fieldFEC3.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field FEC3 as a BigDecimal.
  */
  public BigDecimal getBigDecimalFEC3()
  {
    return fieldFEC3.getBigDecimal();
  }

  /**
  * Set field CHE4 using a String value.
  */
  public void setCHE4(String newvalue)
  {
    fieldCHE4.setString(newvalue);
  }

  /**
  * Get value of field CHE4 as a String.
  */
  public String getCHE4()
  {
    return fieldCHE4.getString();
  }

  /**
  * Set numeric field CHE4 using a BigDecimal value.
  */
  public void setCHE4(BigDecimal newvalue)
  {
    fieldCHE4.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field CHE4 as a BigDecimal.
  */
  public BigDecimal getBigDecimalCHE4()
  {
    return fieldCHE4.getBigDecimal();
  }

  /**
  * Set field FEC4 using a String value.
  */
  public void setFEC4(String newvalue)
  {
    fieldFEC4.setString(newvalue);
  }

  /**
  * Get value of field FEC4 as a String.
  */
  public String getFEC4()
  {
    return fieldFEC4.getString();
  }

  /**
  * Set numeric field FEC4 using a BigDecimal value.
  */
  public void setFEC4(BigDecimal newvalue)
  {
    fieldFEC4.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field FEC4 as a BigDecimal.
  */
  public BigDecimal getBigDecimalFEC4()
  {
    return fieldFEC4.getBigDecimal();
  }

  /**
  * Set field CHE5 using a String value.
  */
  public void setCHE5(String newvalue)
  {
    fieldCHE5.setString(newvalue);
  }

  /**
  * Get value of field CHE5 as a String.
  */
  public String getCHE5()
  {
    return fieldCHE5.getString();
  }

  /**
  * Set numeric field CHE5 using a BigDecimal value.
  */
  public void setCHE5(BigDecimal newvalue)
  {
    fieldCHE5.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field CHE5 as a BigDecimal.
  */
  public BigDecimal getBigDecimalCHE5()
  {
    return fieldCHE5.getBigDecimal();
  }

  /**
  * Set field FEC5 using a String value.
  */
  public void setFEC5(String newvalue)
  {
    fieldFEC5.setString(newvalue);
  }

  /**
  * Get value of field FEC5 as a String.
  */
  public String getFEC5()
  {
    return fieldFEC5.getString();
  }

  /**
  * Set numeric field FEC5 using a BigDecimal value.
  */
  public void setFEC5(BigDecimal newvalue)
  {
    fieldFEC5.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field FEC5 as a BigDecimal.
  */
  public BigDecimal getBigDecimalFEC5()
  {
    return fieldFEC5.getBigDecimal();
  }

  /**
  * Set field LIN11 using a String value.
  */
  public void setLIN11(String newvalue)
  {
    fieldLIN11.setString(newvalue);
  }

  /**
  * Get value of field LIN11 as a String.
  */
  public String getLIN11()
  {
    return fieldLIN11.getString();
  }

  /**
  * Set field LIN2 using a String value.
  */
  public void setLIN2(String newvalue)
  {
    fieldLIN2.setString(newvalue);
  }

  /**
  * Get value of field LIN2 as a String.
  */
  public String getLIN2()
  {
    return fieldLIN2.getString();
  }

  /**
  * Set field LIN21 using a String value.
  */
  public void setLIN21(String newvalue)
  {
    fieldLIN21.setString(newvalue);
  }

  /**
  * Get value of field LIN21 as a String.
  */
  public String getLIN21()
  {
    return fieldLIN21.getString();
  }

  /**
  * Set field LIN3 using a String value.
  */
  public void setLIN3(String newvalue)
  {
    fieldLIN3.setString(newvalue);
  }

  /**
  * Get value of field LIN3 as a String.
  */
  public String getLIN3()
  {
    return fieldLIN3.getString();
  }

  /**
  * Set field LIN31 using a String value.
  */
  public void setLIN31(String newvalue)
  {
    fieldLIN31.setString(newvalue);
  }

  /**
  * Get value of field LIN31 as a String.
  */
  public String getLIN31()
  {
    return fieldLIN31.getString();
  }

  /**
  * Set field LIN4 using a String value.
  */
  public void setLIN4(String newvalue)
  {
    fieldLIN4.setString(newvalue);
  }

  /**
  * Get value of field LIN4 as a String.
  */
  public String getLIN4()
  {
    return fieldLIN4.getString();
  }

  /**
  * Set field SINO using a String value.
  */
  public void setSINO(String newvalue)
  {
    fieldSINO.setString(newvalue);
  }

  /**
  * Get value of field SINO as a String.
  */
  public String getSINO()
  {
    return fieldSINO.getString();
  }

}
