package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
* Class generated by AS/400 CRTCLASS command from SALMINFM physical file definition.
* 
* File level identifier is 1140213212853.
* Record format level identifier is 5045BB7B1C956.
*/

public class SALMINFMMessage extends MessageRecord
{
  final static String fldnames[] = {
                                     "HDAT",
                                     "HTIM",
                                     "HUSR",
                                     "HENV",
                                     "HXML",
                                     "HSEC",
                                     "HFIL",
                                     "HLEN",
                                     "INDICA",
                                     "COSAMI",
                                     "MOSAMI",
                                     "SALMIN"
                                   };
  final static String tnames[] = {
                                   "HDAT",
                                   "HTIM",
                                   "HUSR",
                                   "HENV",
                                   "HXML",
                                   "HSEC",
                                   "HFIL",
                                   "HLEN",
                                   "INDICA",
                                   "COSAMI",
                                   "MOSAMI",
                                   "SALMIN"
                                 };
  final static String fid = "1140213212853";
  final static String rid = "5045BB7B1C956";
  final static String fmtname = "SALMINFM";
  final int FIELDCOUNT = 12;
  private static Hashtable tlookup = new Hashtable();
  private DecimalField fieldHDAT = null;
  private DecimalField fieldHTIM = null;
  private CharacterField fieldHUSR = null;
  private CharacterField fieldHENV = null;
  private CharacterField fieldHXML = null;
  private CharacterField fieldHSEC = null;
  private CharacterField fieldHFIL = null;
  private DecimalField fieldHLEN = null;
  private CharacterField fieldINDICA = null;
  private DecimalField fieldCOSAMI = null;
  private DecimalField fieldMOSAMI = null;
  private DecimalField fieldSALMIN = null;

  /**
  * Constructor for SALMINFMMessage.
  */
  public SALMINFMMessage()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 206;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldHDAT =
    new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
    fields[1] = fieldHTIM =
    new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
    fields[2] = fieldHUSR =
    new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
    fields[3] = fieldHENV =
    new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
    fields[4] = fieldHXML =
    new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
    fields[5] = fieldHSEC =
    new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
    fields[6] = fieldHFIL =
    new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
    fields[7] = fieldHLEN =
    new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
    fields[8] = fieldINDICA =
    new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
    fields[9] = fieldCOSAMI =
    new DecimalField(message, HEADERSIZE + 161, 11, 6, "COSAMI");
    fields[10] = fieldMOSAMI =
    new DecimalField(message, HEADERSIZE + 172, 17, 2, "MOSAMI");
    fields[11] = fieldSALMIN =
    new DecimalField(message, HEADERSIZE + 189, 17, 2, "SALMIN");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field HDAT using a String value.
  */
  public void setHDAT(String newvalue)
  {
    fieldHDAT.setString(newvalue);
  }

  /**
  * Get value of field HDAT as a String.
  */
  public String getHDAT()
  {
    return fieldHDAT.getString();
  }

  /**
  * Set numeric field HDAT using a BigDecimal value.
  */
  public void setHDAT(BigDecimal newvalue)
  {
    fieldHDAT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HDAT as a BigDecimal.
  */
  public BigDecimal getBigDecimalHDAT()
  {
    return fieldHDAT.getBigDecimal();
  }

  /**
  * Set field HTIM using a String value.
  */
  public void setHTIM(String newvalue)
  {
    fieldHTIM.setString(newvalue);
  }

  /**
  * Get value of field HTIM as a String.
  */
  public String getHTIM()
  {
    return fieldHTIM.getString();
  }

  /**
  * Set numeric field HTIM using a BigDecimal value.
  */
  public void setHTIM(BigDecimal newvalue)
  {
    fieldHTIM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HTIM as a BigDecimal.
  */
  public BigDecimal getBigDecimalHTIM()
  {
    return fieldHTIM.getBigDecimal();
  }

  /**
  * Set field HUSR using a String value.
  */
  public void setHUSR(String newvalue)
  {
    fieldHUSR.setString(newvalue);
  }

  /**
  * Get value of field HUSR as a String.
  */
  public String getHUSR()
  {
    return fieldHUSR.getString();
  }

  /**
  * Set field HENV using a String value.
  */
  public void setHENV(String newvalue)
  {
    fieldHENV.setString(newvalue);
  }

  /**
  * Get value of field HENV as a String.
  */
  public String getHENV()
  {
    return fieldHENV.getString();
  }

  /**
  * Set field HXML using a String value.
  */
  public void setHXML(String newvalue)
  {
    fieldHXML.setString(newvalue);
  }

  /**
  * Get value of field HXML as a String.
  */
  public String getHXML()
  {
    return fieldHXML.getString();
  }

  /**
  * Set field HSEC using a String value.
  */
  public void setHSEC(String newvalue)
  {
    fieldHSEC.setString(newvalue);
  }

  /**
  * Get value of field HSEC as a String.
  */
  public String getHSEC()
  {
    return fieldHSEC.getString();
  }

  /**
  * Set field HFIL using a String value.
  */
  public void setHFIL(String newvalue)
  {
    fieldHFIL.setString(newvalue);
  }

  /**
  * Get value of field HFIL as a String.
  */
  public String getHFIL()
  {
    return fieldHFIL.getString();
  }

  /**
  * Set field HLEN using a String value.
  */
  public void setHLEN(String newvalue)
  {
    fieldHLEN.setString(newvalue);
  }

  /**
  * Get value of field HLEN as a String.
  */
  public String getHLEN()
  {
    return fieldHLEN.getString();
  }

  /**
  * Set numeric field HLEN using a BigDecimal value.
  */
  public void setHLEN(BigDecimal newvalue)
  {
    fieldHLEN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field HLEN as a BigDecimal.
  */
  public BigDecimal getBigDecimalHLEN()
  {
    return fieldHLEN.getBigDecimal();
  }

  /**
  * Set field INDICA using a String value.
  */
  public void setINDICA(String newvalue)
  {
    fieldINDICA.setString(newvalue);
  }

  /**
  * Get value of field INDICA as a String.
  */
  public String getINDICA()
  {
    return fieldINDICA.getString();
  }

  /**
  * Set field COSAMI using a String value.
  */
  public void setCOSAMI(String newvalue)
  {
    fieldCOSAMI.setString(newvalue);
  }

  /**
  * Get value of field COSAMI as a String.
  */
  public String getCOSAMI()
  {
    return fieldCOSAMI.getString();
  }

  /**
  * Set numeric field COSAMI using a BigDecimal value.
  */
  public void setCOSAMI(BigDecimal newvalue)
  {
    fieldCOSAMI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field COSAMI as a BigDecimal.
  */
  public BigDecimal getBigDecimalCOSAMI()
  {
    return fieldCOSAMI.getBigDecimal();
  }

  /**
  * Set field MOSAMI using a String value.
  */
  public void setMOSAMI(String newvalue)
  {
    fieldMOSAMI.setString(newvalue);
  }

  /**
  * Get value of field MOSAMI as a String.
  */
  public String getMOSAMI()
  {
    return fieldMOSAMI.getString();
  }

  /**
  * Set numeric field MOSAMI using a BigDecimal value.
  */
  public void setMOSAMI(BigDecimal newvalue)
  {
    fieldMOSAMI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field MOSAMI as a BigDecimal.
  */
  public BigDecimal getBigDecimalMOSAMI()
  {
    return fieldMOSAMI.getBigDecimal();
  }

  /**
  * Set field SALMIN using a String value.
  */
  public void setSALMIN(String newvalue)
  {
    fieldSALMIN.setString(newvalue);
  }

  /**
  * Get value of field SALMIN as a String.
  */
  public String getSALMIN()
  {
    return fieldSALMIN.getString();
  }

  /**
  * Set numeric field SALMIN using a BigDecimal value.
  */
  public void setSALMIN(BigDecimal newvalue)
  {
    fieldSALMIN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field SALMIN as a BigDecimal.
  */
  public BigDecimal getBigDecimalSALMIN()
  {
    return fieldSALMIN.getBigDecimal();
  }

}
