package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from VARI02FM physical file
 * definition.
 * 
* File level identifier is 1140325224703. Record format level identifier is
 * 37A588D6E4C87.
 */
public class VARI02FMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "TABNOM",
        "CLIDUP",
        "SELECC",
        "TRAIDE",
        "TRANOM",
        "TRAMAX",
        "TRAUTI",
        "OK1",
        "TEXERR",
        "CABEC1",
        "FECAPO",
        "CABEC9",
        "FECADQ",
        "FECLIQ",
        "DOCCLI",
        "NOMCLI",
        "CODCOR",
        "NOMVAL",
        "CODINT",
        "NOMINT",
        "NUMTIT",
        "NUMOPE",
        "CAMVIO",
        "BRUTO",
        "GASTO1",
        "IGAST1",
        "GASTO2",
        "IGAST2",
        "GASTO5",
        "IGAST5",
        "GASTO3",
        "IGAST3",
        "GASTO4",
        "IGAST4",
        "CLAAUT",
        "WOTIMP",
        "TOTIMP",
        "OK3",
        "DAMVIO",
        "DRUTO",
        "DGAST1",
        "DGAST2",
        "DGAST5",
        "DGAST3",
        "DGAST4",
        "CAMAPL",
        "DOTIMP",
        "XOTIMP",
        "DERDER",
        "NOMDER",
        "DERVAL",
        "DERINI",
        "DERFIN",
        "DEROLD",
        "DERNEW",
        "DERDES",
        "DERPTA",
        "DERNVA",
        "NEWNOM",
        "OK4",
        "CAJOLD",
        "NOMOLD",
        "CAJNEW",
        "NOMNEW",
        "CAJPOL",
        "CAJPNE",
        "CAJGAS",
        "CAJFEC",
        "OK5",
        "CAJRED",
        "CAMFEC",
        "CAMVAL",
        "NBXOLD",
        "NOXOLD",
        "CAMNNW",
        "CAMCA1",
        "CAMCA2",
        "OK6",
        "EQUOLD",
        "NOYOLD",
        "EQUNEW",
        "OK7",
        "EQUFEC",
        "CODCLI",
        "VALOR",
        "CODIN1",
        "NOMIN1",
        "CODIN2",
        "NOMIN2",
        "FECOPE",
        "OK8",
        "SELOPE",
        "CONCEP",
        "NOMCL9",
        "INFLUE",
        "NOMVA9",
        "NOMIN9",
        "GASTOS",
        "OK9"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "TABNOM",
        "CLIDUP",
        "SELECC",
        "TRAIDE",
        "TRANOM",
        "TRAMAX",
        "TRAUTI",
        "OK1",
        "TEXERR",
        "CABEC1",
        "FECAPO",
        "CABEC9",
        "FECADQ",
        "FECLIQ",
        "DOCCLI",
        "NOMCLI",
        "CODCOR",
        "NOMVAL",
        "CODINT",
        "NOMINT",
        "NUMTIT",
        "NUMOPE",
        "CAMVIO",
        "BRUTO",
        "GASTO1",
        "IGAST1",
        "GASTO2",
        "IGAST2",
        "GASTO5",
        "IGAST5",
        "GASTO3",
        "IGAST3",
        "GASTO4",
        "IGAST4",
        "CLAAUT",
        "WOTIMP",
        "TOTIMP",
        "OK3",
        "DAMVIO",
        "DRUTO",
        "DGAST1",
        "DGAST2",
        "DGAST5",
        "DGAST3",
        "DGAST4",
        "CAMAPL",
        "DOTIMP",
        "XOTIMP",
        "DERDER",
        "NOMDER",
        "DERVAL",
        "DERINI",
        "DERFIN",
        "DEROLD",
        "DERNEW",
        "DERDES",
        "DERPTA",
        "DERNVA",
        "NEWNOM",
        "OK4",
        "CAJOLD",
        "NOMOLD",
        "CAJNEW",
        "NOMNEW",
        "CAJPOL",
        "CAJPNE",
        "CAJGAS",
        "CAJFEC",
        "OK5",
        "CAJRED",
        "CAMFEC",
        "CAMVAL",
        "NBXOLD",
        "NOXOLD",
        "CAMNNW",
        "CAMCA1",
        "CAMCA2",
        "OK6",
        "EQUOLD",
        "NOYOLD",
        "EQUNEW",
        "OK7",
        "EQUFEC",
        "CODCLI",
        "VALOR",
        "CODIN1",
        "NOMIN1",
        "CODIN2",
        "NOMIN2",
        "FECOPE",
        "OK8",
        "SELOPE",
        "CONCEP",
        "NOMCL9",
        "INFLUE",
        "NOMVA9",
        "NOMIN9",
        "GASTOS",
        "OK9"
    };
    final static String fid = "1140325224703";
    final static String rid = "37A588D6E4C87";
    final static String fmtname = "VARI02FM";
    final int FIELDCOUNT = 108;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldTABNOM = null;
    private DecimalField fieldCLIDUP = null;
    private DecimalField fieldSELECC = null;
    private DecimalField fieldTRAIDE = null;
    private CharacterField fieldTRANOM = null;
    private DecimalField fieldTRAMAX = null;
    private DecimalField fieldTRAUTI = null;
    private CharacterField fieldOK1 = null;
    private CharacterField fieldTEXERR = null;
    private CharacterField fieldCABEC1 = null;
    private DecimalField fieldFECAPO = null;
    private CharacterField fieldCABEC9 = null;
    private DecimalField fieldFECADQ = null;
    private DecimalField fieldFECLIQ = null;
    private DecimalField fieldDOCCLI = null;
    private CharacterField fieldNOMCLI = null;
    private CharacterField fieldCODCOR = null;
    private CharacterField fieldNOMVAL = null;
    private DecimalField fieldCODINT = null;
    private CharacterField fieldNOMINT = null;
    private DecimalField fieldNUMTIT = null;
    private DecimalField fieldNUMOPE = null;
    private DecimalField fieldCAMVIO = null;
    private DecimalField fieldBRUTO = null;
    private CharacterField fieldGASTO1 = null;
    private DecimalField fieldIGAST1 = null;
    private CharacterField fieldGASTO2 = null;
    private DecimalField fieldIGAST2 = null;
    private CharacterField fieldGASTO5 = null;
    private DecimalField fieldIGAST5 = null;
    private CharacterField fieldGASTO3 = null;
    private DecimalField fieldIGAST3 = null;
    private CharacterField fieldGASTO4 = null;
    private DecimalField fieldIGAST4 = null;
    private CharacterField fieldCLAAUT = null;
    private DecimalField fieldWOTIMP = null;
    private DecimalField fieldTOTIMP = null;
    private CharacterField fieldOK3 = null;
    private DecimalField fieldDAMVIO = null;
    private DecimalField fieldDRUTO = null;
    private DecimalField fieldDGAST1 = null;
    private DecimalField fieldDGAST2 = null;
    private DecimalField fieldDGAST5 = null;
    private DecimalField fieldDGAST3 = null;
    private DecimalField fieldDGAST4 = null;
    private DecimalField fieldCAMAPL = null;
    private DecimalField fieldDOTIMP = null;
    private DecimalField fieldXOTIMP = null;
    private CharacterField fieldDERDER = null;
    private CharacterField fieldNOMDER = null;
    private CharacterField fieldDERVAL = null;
    private DecimalField fieldDERINI = null;
    private DecimalField fieldDERFIN = null;
    private DecimalField fieldDEROLD = null;
    private DecimalField fieldDERNEW = null;
    private CharacterField fieldDERDES = null;
    private DecimalField fieldDERPTA = null;
    private CharacterField fieldDERNVA = null;
    private CharacterField fieldNEWNOM = null;
    private CharacterField fieldOK4 = null;
    private CharacterField fieldCAJOLD = null;
    private CharacterField fieldNOMOLD = null;
    private CharacterField fieldCAJNEW = null;
    private CharacterField fieldNOMNEW = null;
    private DecimalField fieldCAJPOL = null;
    private DecimalField fieldCAJPNE = null;
    private DecimalField fieldCAJGAS = null;
    private DecimalField fieldCAJFEC = null;
    private CharacterField fieldOK5 = null;
    private CharacterField fieldCAJRED = null;
    private DecimalField fieldCAMFEC = null;
    private CharacterField fieldCAMVAL = null;
    private CharacterField fieldNBXOLD = null;
    private DecimalField fieldNOXOLD = null;
    private DecimalField fieldCAMNNW = null;
    private CharacterField fieldCAMCA1 = null;
    private CharacterField fieldCAMCA2 = null;
    private CharacterField fieldOK6 = null;
    private CharacterField fieldEQUOLD = null;
    private CharacterField fieldNOYOLD = null;
    private CharacterField fieldEQUNEW = null;
    private CharacterField fieldOK7 = null;
    private DecimalField fieldEQUFEC = null;
    private DecimalField fieldCODCLI = null;
    private CharacterField fieldVALOR = null;
    private DecimalField fieldCODIN1 = null;
    private CharacterField fieldNOMIN1 = null;
    private DecimalField fieldCODIN2 = null;
    private CharacterField fieldNOMIN2 = null;
    private DecimalField fieldFECOPE = null;
    private CharacterField fieldOK8 = null;
    private DecimalField fieldSELOPE = null;
    private CharacterField fieldCONCEP = null;
    private CharacterField fieldNOMCL9 = null;
    private CharacterField fieldINFLUE = null;
    private CharacterField fieldNOMVA9 = null;
    private CharacterField fieldNOMIN9 = null;
    private DecimalField fieldGASTOS = null;
    private CharacterField fieldOK9 = null;

    /**
     * Constructor for VARI02FMMessage.
     */
    public VARI02FMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 1798;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldTABNOM
                = new CharacterField(message, HEADERSIZE + 161, 40, "TABNOM");
        fields[10] = fieldCLIDUP
                = new DecimalField(message, HEADERSIZE + 201, 8, 0, "CLIDUP");
        fields[11] = fieldSELECC
                = new DecimalField(message, HEADERSIZE + 209, 3, 0, "SELECC");
        fields[12] = fieldTRAIDE
                = new DecimalField(message, HEADERSIZE + 212, 4, 0, "TRAIDE");
        fields[13] = fieldTRANOM
                = new CharacterField(message, HEADERSIZE + 216, 40, "TRANOM");
        fields[14] = fieldTRAMAX
                = new DecimalField(message, HEADERSIZE + 256, 16, 0, "TRAMAX");
        fields[15] = fieldTRAUTI
                = new DecimalField(message, HEADERSIZE + 272, 16, 0, "TRAUTI");
        fields[16] = fieldOK1
                = new CharacterField(message, HEADERSIZE + 288, 1, "OK1");
        fields[17] = fieldTEXERR
                = new CharacterField(message, HEADERSIZE + 289, 60, "TEXERR");
        fields[18] = fieldCABEC1
                = new CharacterField(message, HEADERSIZE + 349, 40, "CABEC1");
        fields[19] = fieldFECAPO
                = new DecimalField(message, HEADERSIZE + 389, 7, 0, "FECAPO");
        fields[20] = fieldCABEC9
                = new CharacterField(message, HEADERSIZE + 396, 21, "CABEC9");
        fields[21] = fieldFECADQ
                = new DecimalField(message, HEADERSIZE + 417, 7, 0, "FECADQ");
        fields[22] = fieldFECLIQ
                = new DecimalField(message, HEADERSIZE + 424, 7, 0, "FECLIQ");
        fields[23] = fieldDOCCLI
                = new DecimalField(message, HEADERSIZE + 431, 8, 0, "DOCCLI");
        fields[24] = fieldNOMCLI
                = new CharacterField(message, HEADERSIZE + 439, 40, "NOMCLI");
        fields[25] = fieldCODCOR
                = new CharacterField(message, HEADERSIZE + 479, 12, "CODCOR");
        fields[26] = fieldNOMVAL
                = new CharacterField(message, HEADERSIZE + 491, 40, "NOMVAL");
        fields[27] = fieldCODINT
                = new DecimalField(message, HEADERSIZE + 531, 8, 0, "CODINT");
        fields[28] = fieldNOMINT
                = new CharacterField(message, HEADERSIZE + 539, 40, "NOMINT");
        fields[29] = fieldNUMTIT
                = new DecimalField(message, HEADERSIZE + 579, 29, 7, "NUMTIT");
        fields[30] = fieldNUMOPE
                = new DecimalField(message, HEADERSIZE + 608, 11, 0, "NUMOPE");
        fields[31] = fieldCAMVIO
                = new DecimalField(message, HEADERSIZE + 619, 15, 5, "CAMVIO");
        fields[32] = fieldBRUTO
                = new DecimalField(message, HEADERSIZE + 634, 19, 2, "BRUTO");
        fields[33] = fieldGASTO1
                = new CharacterField(message, HEADERSIZE + 653, 15, "GASTO1");
        fields[34] = fieldIGAST1
                = new DecimalField(message, HEADERSIZE + 668, 19, 2, "IGAST1");
        fields[35] = fieldGASTO2
                = new CharacterField(message, HEADERSIZE + 687, 15, "GASTO2");
        fields[36] = fieldIGAST2
                = new DecimalField(message, HEADERSIZE + 702, 19, 2, "IGAST2");
        fields[37] = fieldGASTO5
                = new CharacterField(message, HEADERSIZE + 721, 15, "GASTO5");
        fields[38] = fieldIGAST5
                = new DecimalField(message, HEADERSIZE + 736, 19, 2, "IGAST5");
        fields[39] = fieldGASTO3
                = new CharacterField(message, HEADERSIZE + 755, 15, "GASTO3");
        fields[40] = fieldIGAST3
                = new DecimalField(message, HEADERSIZE + 770, 19, 2, "IGAST3");
        fields[41] = fieldGASTO4
                = new CharacterField(message, HEADERSIZE + 789, 15, "GASTO4");
        fields[42] = fieldIGAST4
                = new DecimalField(message, HEADERSIZE + 804, 19, 2, "IGAST4");
        fields[43] = fieldCLAAUT
                = new CharacterField(message, HEADERSIZE + 823, 4, "CLAAUT");
        fields[44] = fieldWOTIMP
                = new DecimalField(message, HEADERSIZE + 827, 19, 2, "WOTIMP");
        fields[45] = fieldTOTIMP
                = new DecimalField(message, HEADERSIZE + 846, 19, 2, "TOTIMP");
        fields[46] = fieldOK3
                = new CharacterField(message, HEADERSIZE + 865, 1, "OK3");
        fields[47] = fieldDAMVIO
                = new DecimalField(message, HEADERSIZE + 866, 15, 5, "DAMVIO");
        fields[48] = fieldDRUTO
                = new DecimalField(message, HEADERSIZE + 881, 19, 2, "DRUTO");
        fields[49] = fieldDGAST1
                = new DecimalField(message, HEADERSIZE + 900, 19, 2, "DGAST1");
        fields[50] = fieldDGAST2
                = new DecimalField(message, HEADERSIZE + 919, 19, 2, "DGAST2");
        fields[51] = fieldDGAST5
                = new DecimalField(message, HEADERSIZE + 938, 19, 2, "DGAST5");
        fields[52] = fieldDGAST3
                = new DecimalField(message, HEADERSIZE + 957, 19, 2, "DGAST3");
        fields[53] = fieldDGAST4
                = new DecimalField(message, HEADERSIZE + 976, 19, 2, "DGAST4");
        fields[54] = fieldCAMAPL
                = new DecimalField(message, HEADERSIZE + 995, 12, 6, "CAMAPL");
        fields[55] = fieldDOTIMP
                = new DecimalField(message, HEADERSIZE + 1007, 19, 2, "DOTIMP");
        fields[56] = fieldXOTIMP
                = new DecimalField(message, HEADERSIZE + 1026, 19, 2, "XOTIMP");
        fields[57] = fieldDERDER
                = new CharacterField(message, HEADERSIZE + 1045, 12, "DERDER");
        fields[58] = fieldNOMDER
                = new CharacterField(message, HEADERSIZE + 1057, 40, "NOMDER");
        fields[59] = fieldDERVAL
                = new CharacterField(message, HEADERSIZE + 1097, 12, "DERVAL");
        fields[60] = fieldDERINI
                = new DecimalField(message, HEADERSIZE + 1109, 7, 0, "DERINI");
        fields[61] = fieldDERFIN
                = new DecimalField(message, HEADERSIZE + 1116, 7, 0, "DERFIN");
        fields[62] = fieldDEROLD
                = new DecimalField(message, HEADERSIZE + 1123, 6, 0, "DEROLD");
        fields[63] = fieldDERNEW
                = new DecimalField(message, HEADERSIZE + 1129, 6, 0, "DERNEW");
        fields[64] = fieldDERDES
                = new CharacterField(message, HEADERSIZE + 1135, 1, "DERDES");
        fields[65] = fieldDERPTA
                = new DecimalField(message, HEADERSIZE + 1136, 13, 2, "DERPTA");
        fields[66] = fieldDERNVA
                = new CharacterField(message, HEADERSIZE + 1149, 12, "DERNVA");
        fields[67] = fieldNEWNOM
                = new CharacterField(message, HEADERSIZE + 1161, 40, "NEWNOM");
        fields[68] = fieldOK4
                = new CharacterField(message, HEADERSIZE + 1201, 1, "OK4");
        fields[69] = fieldCAJOLD
                = new CharacterField(message, HEADERSIZE + 1202, 12, "CAJOLD");
        fields[70] = fieldNOMOLD
                = new CharacterField(message, HEADERSIZE + 1214, 40, "NOMOLD");
        fields[71] = fieldCAJNEW
                = new CharacterField(message, HEADERSIZE + 1254, 12, "CAJNEW");
        fields[72] = fieldNOMNEW
                = new CharacterField(message, HEADERSIZE + 1266, 40, "NOMNEW");
        fields[73] = fieldCAJPOL
                = new DecimalField(message, HEADERSIZE + 1306, 17, 5, "CAJPOL");
        fields[74] = fieldCAJPNE
                = new DecimalField(message, HEADERSIZE + 1323, 17, 5, "CAJPNE");
        fields[75] = fieldCAJGAS
                = new DecimalField(message, HEADERSIZE + 1340, 12, 0, "CAJGAS");
        fields[76] = fieldCAJFEC
                = new DecimalField(message, HEADERSIZE + 1352, 7, 0, "CAJFEC");
        fields[77] = fieldOK5
                = new CharacterField(message, HEADERSIZE + 1359, 1, "OK5");
        fields[78] = fieldCAJRED
                = new CharacterField(message, HEADERSIZE + 1360, 1, "CAJRED");
        fields[79] = fieldCAMFEC
                = new DecimalField(message, HEADERSIZE + 1361, 7, 0, "CAMFEC");
        fields[80] = fieldCAMVAL
                = new CharacterField(message, HEADERSIZE + 1368, 12, "CAMVAL");
        fields[81] = fieldNBXOLD
                = new CharacterField(message, HEADERSIZE + 1380, 40, "NBXOLD");
        fields[82] = fieldNOXOLD
                = new DecimalField(message, HEADERSIZE + 1420, 10, 0, "NOXOLD");
        fields[83] = fieldCAMNNW
                = new DecimalField(message, HEADERSIZE + 1430, 8, 0, "CAMNNW");
        fields[84] = fieldCAMCA1
                = new CharacterField(message, HEADERSIZE + 1438, 1, "CAMCA1");
        fields[85] = fieldCAMCA2
                = new CharacterField(message, HEADERSIZE + 1439, 1, "CAMCA2");
        fields[86] = fieldOK6
                = new CharacterField(message, HEADERSIZE + 1440, 1, "OK6");
        fields[87] = fieldEQUOLD
                = new CharacterField(message, HEADERSIZE + 1441, 12, "EQUOLD");
        fields[88] = fieldNOYOLD
                = new CharacterField(message, HEADERSIZE + 1453, 40, "NOYOLD");
        fields[89] = fieldEQUNEW
                = new CharacterField(message, HEADERSIZE + 1493, 12, "EQUNEW");
        fields[90] = fieldOK7
                = new CharacterField(message, HEADERSIZE + 1505, 1, "OK7");
        fields[91] = fieldEQUFEC
                = new DecimalField(message, HEADERSIZE + 1506, 7, 0, "EQUFEC");
        fields[92] = fieldCODCLI
                = new DecimalField(message, HEADERSIZE + 1513, 8, 0, "CODCLI");
        fields[93] = fieldVALOR
                = new CharacterField(message, HEADERSIZE + 1521, 12, "VALOR");
        fields[94] = fieldCODIN1
                = new DecimalField(message, HEADERSIZE + 1533, 8, 0, "CODIN1");
        fields[95] = fieldNOMIN1
                = new CharacterField(message, HEADERSIZE + 1541, 40, "NOMIN1");
        fields[96] = fieldCODIN2
                = new DecimalField(message, HEADERSIZE + 1581, 8, 0, "CODIN2");
        fields[97] = fieldNOMIN2
                = new CharacterField(message, HEADERSIZE + 1589, 40, "NOMIN2");
        fields[98] = fieldFECOPE
                = new DecimalField(message, HEADERSIZE + 1629, 7, 0, "FECOPE");
        fields[99] = fieldOK8
                = new CharacterField(message, HEADERSIZE + 1636, 1, "OK8");
        fields[100] = fieldSELOPE
                = new DecimalField(message, HEADERSIZE + 1637, 3, 0, "SELOPE");
        fields[101] = fieldCONCEP
                = new CharacterField(message, HEADERSIZE + 1640, 35, "CONCEP");
        fields[102] = fieldNOMCL9
                = new CharacterField(message, HEADERSIZE + 1675, 35, "NOMCL9");
        fields[103] = fieldINFLUE
                = new CharacterField(message, HEADERSIZE + 1710, 1, "INFLUE");
        fields[104] = fieldNOMVA9
                = new CharacterField(message, HEADERSIZE + 1711, 35, "NOMVA9");
        fields[105] = fieldNOMIN9
                = new CharacterField(message, HEADERSIZE + 1746, 35, "NOMIN9");
        fields[106] = fieldGASTOS
                = new DecimalField(message, HEADERSIZE + 1781, 16, 0, "GASTOS");
        fields[107] = fieldOK9
                = new CharacterField(message, HEADERSIZE + 1797, 1, "OK9");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field TABNOM using a String value.
     */
    public void setTABNOM(String newvalue) {
        fieldTABNOM.setString(newvalue);
    }

    /**
     * Get value of field TABNOM as a String.
     */
    public String getTABNOM() {
        return fieldTABNOM.getString();
    }

    /**
     * Set field CLIDUP using a String value.
     */
    public void setCLIDUP(String newvalue) {
        fieldCLIDUP.setString(newvalue);
    }

    /**
     * Get value of field CLIDUP as a String.
     */
    public String getCLIDUP() {
        return fieldCLIDUP.getString();
    }

    /**
     * Set numeric field CLIDUP using a BigDecimal value.
     */
    public void setCLIDUP(BigDecimal newvalue) {
        fieldCLIDUP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CLIDUP as a BigDecimal.
     */
    public BigDecimal getBigDecimalCLIDUP() {
        return fieldCLIDUP.getBigDecimal();
    }

    /**
     * Set field SELECC using a String value.
     */
    public void setSELECC(String newvalue) {
        fieldSELECC.setString(newvalue);
    }

    /**
     * Get value of field SELECC as a String.
     */
    public String getSELECC() {
        return fieldSELECC.getString();
    }

    /**
     * Set numeric field SELECC using a BigDecimal value.
     */
    public void setSELECC(BigDecimal newvalue) {
        fieldSELECC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SELECC as a BigDecimal.
     */
    public BigDecimal getBigDecimalSELECC() {
        return fieldSELECC.getBigDecimal();
    }

    /**
     * Set field TRAIDE using a String value.
     */
    public void setTRAIDE(String newvalue) {
        fieldTRAIDE.setString(newvalue);
    }

    /**
     * Get value of field TRAIDE as a String.
     */
    public String getTRAIDE() {
        return fieldTRAIDE.getString();
    }

    /**
     * Set numeric field TRAIDE using a BigDecimal value.
     */
    public void setTRAIDE(BigDecimal newvalue) {
        fieldTRAIDE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TRAIDE as a BigDecimal.
     */
    public BigDecimal getBigDecimalTRAIDE() {
        return fieldTRAIDE.getBigDecimal();
    }

    /**
     * Set field TRANOM using a String value.
     */
    public void setTRANOM(String newvalue) {
        fieldTRANOM.setString(newvalue);
    }

    /**
     * Get value of field TRANOM as a String.
     */
    public String getTRANOM() {
        return fieldTRANOM.getString();
    }

    /**
     * Set field TRAMAX using a String value.
     */
    public void setTRAMAX(String newvalue) {
        fieldTRAMAX.setString(newvalue);
    }

    /**
     * Get value of field TRAMAX as a String.
     */
    public String getTRAMAX() {
        return fieldTRAMAX.getString();
    }

    /**
     * Set numeric field TRAMAX using a BigDecimal value.
     */
    public void setTRAMAX(BigDecimal newvalue) {
        fieldTRAMAX.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TRAMAX as a BigDecimal.
     */
    public BigDecimal getBigDecimalTRAMAX() {
        return fieldTRAMAX.getBigDecimal();
    }

    /**
     * Set field TRAUTI using a String value.
     */
    public void setTRAUTI(String newvalue) {
        fieldTRAUTI.setString(newvalue);
    }

    /**
     * Get value of field TRAUTI as a String.
     */
    public String getTRAUTI() {
        return fieldTRAUTI.getString();
    }

    /**
     * Set numeric field TRAUTI using a BigDecimal value.
     */
    public void setTRAUTI(BigDecimal newvalue) {
        fieldTRAUTI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TRAUTI as a BigDecimal.
     */
    public BigDecimal getBigDecimalTRAUTI() {
        return fieldTRAUTI.getBigDecimal();
    }

    /**
     * Set field OK1 using a String value.
     */
    public void setOK1(String newvalue) {
        fieldOK1.setString(newvalue);
    }

    /**
     * Get value of field OK1 as a String.
     */
    public String getOK1() {
        return fieldOK1.getString();
    }

    /**
     * Set field TEXERR using a String value.
     */
    public void setTEXERR(String newvalue) {
        fieldTEXERR.setString(newvalue);
    }

    /**
     * Get value of field TEXERR as a String.
     */
    public String getTEXERR() {
        return fieldTEXERR.getString();
    }

    /**
     * Set field CABEC1 using a String value.
     */
    public void setCABEC1(String newvalue) {
        fieldCABEC1.setString(newvalue);
    }

    /**
     * Get value of field CABEC1 as a String.
     */
    public String getCABEC1() {
        return fieldCABEC1.getString();
    }

    /**
     * Set field FECAPO using a String value.
     */
    public void setFECAPO(String newvalue) {
        fieldFECAPO.setString(newvalue);
    }

    /**
     * Get value of field FECAPO as a String.
     */
    public String getFECAPO() {
        return fieldFECAPO.getString();
    }

    /**
     * Set numeric field FECAPO using a BigDecimal value.
     */
    public void setFECAPO(BigDecimal newvalue) {
        fieldFECAPO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECAPO as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECAPO() {
        return fieldFECAPO.getBigDecimal();
    }

    /**
     * Set field CABEC9 using a String value.
     */
    public void setCABEC9(String newvalue) {
        fieldCABEC9.setString(newvalue);
    }

    /**
     * Get value of field CABEC9 as a String.
     */
    public String getCABEC9() {
        return fieldCABEC9.getString();
    }

    /**
     * Set field FECADQ using a String value.
     */
    public void setFECADQ(String newvalue) {
        fieldFECADQ.setString(newvalue);
    }

    /**
     * Get value of field FECADQ as a String.
     */
    public String getFECADQ() {
        return fieldFECADQ.getString();
    }

    /**
     * Set numeric field FECADQ using a BigDecimal value.
     */
    public void setFECADQ(BigDecimal newvalue) {
        fieldFECADQ.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECADQ as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECADQ() {
        return fieldFECADQ.getBigDecimal();
    }

    /**
     * Set field FECLIQ using a String value.
     */
    public void setFECLIQ(String newvalue) {
        fieldFECLIQ.setString(newvalue);
    }

    /**
     * Get value of field FECLIQ as a String.
     */
    public String getFECLIQ() {
        return fieldFECLIQ.getString();
    }

    /**
     * Set numeric field FECLIQ using a BigDecimal value.
     */
    public void setFECLIQ(BigDecimal newvalue) {
        fieldFECLIQ.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECLIQ as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECLIQ() {
        return fieldFECLIQ.getBigDecimal();
    }

    /**
     * Set field DOCCLI using a String value.
     */
    public void setDOCCLI(String newvalue) {
        fieldDOCCLI.setString(newvalue);
    }

    /**
     * Get value of field DOCCLI as a String.
     */
    public String getDOCCLI() {
        return fieldDOCCLI.getString();
    }

    /**
     * Set numeric field DOCCLI using a BigDecimal value.
     */
    public void setDOCCLI(BigDecimal newvalue) {
        fieldDOCCLI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DOCCLI as a BigDecimal.
     */
    public BigDecimal getBigDecimalDOCCLI() {
        return fieldDOCCLI.getBigDecimal();
    }

    /**
     * Set field NOMCLI using a String value.
     */
    public void setNOMCLI(String newvalue) {
        fieldNOMCLI.setString(newvalue);
    }

    /**
     * Get value of field NOMCLI as a String.
     */
    public String getNOMCLI() {
        return fieldNOMCLI.getString();
    }

    /**
     * Set field CODCOR using a String value.
     */
    public void setCODCOR(String newvalue) {
        fieldCODCOR.setString(newvalue);
    }

    /**
     * Get value of field CODCOR as a String.
     */
    public String getCODCOR() {
        return fieldCODCOR.getString();
    }

    /**
     * Set field NOMVAL using a String value.
     */
    public void setNOMVAL(String newvalue) {
        fieldNOMVAL.setString(newvalue);
    }

    /**
     * Get value of field NOMVAL as a String.
     */
    public String getNOMVAL() {
        return fieldNOMVAL.getString();
    }

    /**
     * Set field CODINT using a String value.
     */
    public void setCODINT(String newvalue) {
        fieldCODINT.setString(newvalue);
    }

    /**
     * Get value of field CODINT as a String.
     */
    public String getCODINT() {
        return fieldCODINT.getString();
    }

    /**
     * Set numeric field CODINT using a BigDecimal value.
     */
    public void setCODINT(BigDecimal newvalue) {
        fieldCODINT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CODINT as a BigDecimal.
     */
    public BigDecimal getBigDecimalCODINT() {
        return fieldCODINT.getBigDecimal();
    }

    /**
     * Set field NOMINT using a String value.
     */
    public void setNOMINT(String newvalue) {
        fieldNOMINT.setString(newvalue);
    }

    /**
     * Get value of field NOMINT as a String.
     */
    public String getNOMINT() {
        return fieldNOMINT.getString();
    }

    /**
     * Set field NUMTIT using a String value.
     */
    public void setNUMTIT(String newvalue) {
        fieldNUMTIT.setString(newvalue);
    }

    /**
     * Get value of field NUMTIT as a String.
     */
    public String getNUMTIT() {
        return fieldNUMTIT.getString();
    }

    /**
     * Set numeric field NUMTIT using a BigDecimal value.
     */
    public void setNUMTIT(BigDecimal newvalue) {
        fieldNUMTIT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NUMTIT as a BigDecimal.
     */
    public BigDecimal getBigDecimalNUMTIT() {
        return fieldNUMTIT.getBigDecimal();
    }

    /**
     * Set field NUMOPE using a String value.
     */
    public void setNUMOPE(String newvalue) {
        fieldNUMOPE.setString(newvalue);
    }

    /**
     * Get value of field NUMOPE as a String.
     */
    public String getNUMOPE() {
        return fieldNUMOPE.getString();
    }

    /**
     * Set numeric field NUMOPE using a BigDecimal value.
     */
    public void setNUMOPE(BigDecimal newvalue) {
        fieldNUMOPE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NUMOPE as a BigDecimal.
     */
    public BigDecimal getBigDecimalNUMOPE() {
        return fieldNUMOPE.getBigDecimal();
    }

    /**
     * Set field CAMVIO using a String value.
     */
    public void setCAMVIO(String newvalue) {
        fieldCAMVIO.setString(newvalue);
    }

    /**
     * Get value of field CAMVIO as a String.
     */
    public String getCAMVIO() {
        return fieldCAMVIO.getString();
    }

    /**
     * Set numeric field CAMVIO using a BigDecimal value.
     */
    public void setCAMVIO(BigDecimal newvalue) {
        fieldCAMVIO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CAMVIO as a BigDecimal.
     */
    public BigDecimal getBigDecimalCAMVIO() {
        return fieldCAMVIO.getBigDecimal();
    }

    /**
     * Set field BRUTO using a String value.
     */
    public void setBRUTO(String newvalue) {
        fieldBRUTO.setString(newvalue);
    }

    /**
     * Get value of field BRUTO as a String.
     */
    public String getBRUTO() {
        return fieldBRUTO.getString();
    }

    /**
     * Set numeric field BRUTO using a BigDecimal value.
     */
    public void setBRUTO(BigDecimal newvalue) {
        fieldBRUTO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field BRUTO as a BigDecimal.
     */
    public BigDecimal getBigDecimalBRUTO() {
        return fieldBRUTO.getBigDecimal();
    }

    /**
     * Set field GASTO1 using a String value.
     */
    public void setGASTO1(String newvalue) {
        fieldGASTO1.setString(newvalue);
    }

    /**
     * Get value of field GASTO1 as a String.
     */
    public String getGASTO1() {
        return fieldGASTO1.getString();
    }

    /**
     * Set field IGAST1 using a String value.
     */
    public void setIGAST1(String newvalue) {
        fieldIGAST1.setString(newvalue);
    }

    /**
     * Get value of field IGAST1 as a String.
     */
    public String getIGAST1() {
        return fieldIGAST1.getString();
    }

    /**
     * Set numeric field IGAST1 using a BigDecimal value.
     */
    public void setIGAST1(BigDecimal newvalue) {
        fieldIGAST1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IGAST1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalIGAST1() {
        return fieldIGAST1.getBigDecimal();
    }

    /**
     * Set field GASTO2 using a String value.
     */
    public void setGASTO2(String newvalue) {
        fieldGASTO2.setString(newvalue);
    }

    /**
     * Get value of field GASTO2 as a String.
     */
    public String getGASTO2() {
        return fieldGASTO2.getString();
    }

    /**
     * Set field IGAST2 using a String value.
     */
    public void setIGAST2(String newvalue) {
        fieldIGAST2.setString(newvalue);
    }

    /**
     * Get value of field IGAST2 as a String.
     */
    public String getIGAST2() {
        return fieldIGAST2.getString();
    }

    /**
     * Set numeric field IGAST2 using a BigDecimal value.
     */
    public void setIGAST2(BigDecimal newvalue) {
        fieldIGAST2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IGAST2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalIGAST2() {
        return fieldIGAST2.getBigDecimal();
    }

    /**
     * Set field GASTO5 using a String value.
     */
    public void setGASTO5(String newvalue) {
        fieldGASTO5.setString(newvalue);
    }

    /**
     * Get value of field GASTO5 as a String.
     */
    public String getGASTO5() {
        return fieldGASTO5.getString();
    }

    /**
     * Set field IGAST5 using a String value.
     */
    public void setIGAST5(String newvalue) {
        fieldIGAST5.setString(newvalue);
    }

    /**
     * Get value of field IGAST5 as a String.
     */
    public String getIGAST5() {
        return fieldIGAST5.getString();
    }

    /**
     * Set numeric field IGAST5 using a BigDecimal value.
     */
    public void setIGAST5(BigDecimal newvalue) {
        fieldIGAST5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IGAST5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalIGAST5() {
        return fieldIGAST5.getBigDecimal();
    }

    /**
     * Set field GASTO3 using a String value.
     */
    public void setGASTO3(String newvalue) {
        fieldGASTO3.setString(newvalue);
    }

    /**
     * Get value of field GASTO3 as a String.
     */
    public String getGASTO3() {
        return fieldGASTO3.getString();
    }

    /**
     * Set field IGAST3 using a String value.
     */
    public void setIGAST3(String newvalue) {
        fieldIGAST3.setString(newvalue);
    }

    /**
     * Get value of field IGAST3 as a String.
     */
    public String getIGAST3() {
        return fieldIGAST3.getString();
    }

    /**
     * Set numeric field IGAST3 using a BigDecimal value.
     */
    public void setIGAST3(BigDecimal newvalue) {
        fieldIGAST3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IGAST3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalIGAST3() {
        return fieldIGAST3.getBigDecimal();
    }

    /**
     * Set field GASTO4 using a String value.
     */
    public void setGASTO4(String newvalue) {
        fieldGASTO4.setString(newvalue);
    }

    /**
     * Get value of field GASTO4 as a String.
     */
    public String getGASTO4() {
        return fieldGASTO4.getString();
    }

    /**
     * Set field IGAST4 using a String value.
     */
    public void setIGAST4(String newvalue) {
        fieldIGAST4.setString(newvalue);
    }

    /**
     * Get value of field IGAST4 as a String.
     */
    public String getIGAST4() {
        return fieldIGAST4.getString();
    }

    /**
     * Set numeric field IGAST4 using a BigDecimal value.
     */
    public void setIGAST4(BigDecimal newvalue) {
        fieldIGAST4.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field IGAST4 as a BigDecimal.
     */
    public BigDecimal getBigDecimalIGAST4() {
        return fieldIGAST4.getBigDecimal();
    }

    /**
     * Set field CLAAUT using a String value.
     */
    public void setCLAAUT(String newvalue) {
        fieldCLAAUT.setString(newvalue);
    }

    /**
     * Get value of field CLAAUT as a String.
     */
    public String getCLAAUT() {
        return fieldCLAAUT.getString();
    }

    /**
     * Set field WOTIMP using a String value.
     */
    public void setWOTIMP(String newvalue) {
        fieldWOTIMP.setString(newvalue);
    }

    /**
     * Get value of field WOTIMP as a String.
     */
    public String getWOTIMP() {
        return fieldWOTIMP.getString();
    }

    /**
     * Set numeric field WOTIMP using a BigDecimal value.
     */
    public void setWOTIMP(BigDecimal newvalue) {
        fieldWOTIMP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field WOTIMP as a BigDecimal.
     */
    public BigDecimal getBigDecimalWOTIMP() {
        return fieldWOTIMP.getBigDecimal();
    }

    /**
     * Set field TOTIMP using a String value.
     */
    public void setTOTIMP(String newvalue) {
        fieldTOTIMP.setString(newvalue);
    }

    /**
     * Get value of field TOTIMP as a String.
     */
    public String getTOTIMP() {
        return fieldTOTIMP.getString();
    }

    /**
     * Set numeric field TOTIMP using a BigDecimal value.
     */
    public void setTOTIMP(BigDecimal newvalue) {
        fieldTOTIMP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field TOTIMP as a BigDecimal.
     */
    public BigDecimal getBigDecimalTOTIMP() {
        return fieldTOTIMP.getBigDecimal();
    }

    /**
     * Set field OK3 using a String value.
     */
    public void setOK3(String newvalue) {
        fieldOK3.setString(newvalue);
    }

    /**
     * Get value of field OK3 as a String.
     */
    public String getOK3() {
        return fieldOK3.getString();
    }

    /**
     * Set field DAMVIO using a String value.
     */
    public void setDAMVIO(String newvalue) {
        fieldDAMVIO.setString(newvalue);
    }

    /**
     * Get value of field DAMVIO as a String.
     */
    public String getDAMVIO() {
        return fieldDAMVIO.getString();
    }

    /**
     * Set numeric field DAMVIO using a BigDecimal value.
     */
    public void setDAMVIO(BigDecimal newvalue) {
        fieldDAMVIO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DAMVIO as a BigDecimal.
     */
    public BigDecimal getBigDecimalDAMVIO() {
        return fieldDAMVIO.getBigDecimal();
    }

    /**
     * Set field DRUTO using a String value.
     */
    public void setDRUTO(String newvalue) {
        fieldDRUTO.setString(newvalue);
    }

    /**
     * Get value of field DRUTO as a String.
     */
    public String getDRUTO() {
        return fieldDRUTO.getString();
    }

    /**
     * Set numeric field DRUTO using a BigDecimal value.
     */
    public void setDRUTO(BigDecimal newvalue) {
        fieldDRUTO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DRUTO as a BigDecimal.
     */
    public BigDecimal getBigDecimalDRUTO() {
        return fieldDRUTO.getBigDecimal();
    }

    /**
     * Set field DGAST1 using a String value.
     */
    public void setDGAST1(String newvalue) {
        fieldDGAST1.setString(newvalue);
    }

    /**
     * Get value of field DGAST1 as a String.
     */
    public String getDGAST1() {
        return fieldDGAST1.getString();
    }

    /**
     * Set numeric field DGAST1 using a BigDecimal value.
     */
    public void setDGAST1(BigDecimal newvalue) {
        fieldDGAST1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DGAST1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDGAST1() {
        return fieldDGAST1.getBigDecimal();
    }

    /**
     * Set field DGAST2 using a String value.
     */
    public void setDGAST2(String newvalue) {
        fieldDGAST2.setString(newvalue);
    }

    /**
     * Get value of field DGAST2 as a String.
     */
    public String getDGAST2() {
        return fieldDGAST2.getString();
    }

    /**
     * Set numeric field DGAST2 using a BigDecimal value.
     */
    public void setDGAST2(BigDecimal newvalue) {
        fieldDGAST2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DGAST2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDGAST2() {
        return fieldDGAST2.getBigDecimal();
    }

    /**
     * Set field DGAST5 using a String value.
     */
    public void setDGAST5(String newvalue) {
        fieldDGAST5.setString(newvalue);
    }

    /**
     * Get value of field DGAST5 as a String.
     */
    public String getDGAST5() {
        return fieldDGAST5.getString();
    }

    /**
     * Set numeric field DGAST5 using a BigDecimal value.
     */
    public void setDGAST5(BigDecimal newvalue) {
        fieldDGAST5.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DGAST5 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDGAST5() {
        return fieldDGAST5.getBigDecimal();
    }

    /**
     * Set field DGAST3 using a String value.
     */
    public void setDGAST3(String newvalue) {
        fieldDGAST3.setString(newvalue);
    }

    /**
     * Get value of field DGAST3 as a String.
     */
    public String getDGAST3() {
        return fieldDGAST3.getString();
    }

    /**
     * Set numeric field DGAST3 using a BigDecimal value.
     */
    public void setDGAST3(BigDecimal newvalue) {
        fieldDGAST3.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DGAST3 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDGAST3() {
        return fieldDGAST3.getBigDecimal();
    }

    /**
     * Set field DGAST4 using a String value.
     */
    public void setDGAST4(String newvalue) {
        fieldDGAST4.setString(newvalue);
    }

    /**
     * Get value of field DGAST4 as a String.
     */
    public String getDGAST4() {
        return fieldDGAST4.getString();
    }

    /**
     * Set numeric field DGAST4 using a BigDecimal value.
     */
    public void setDGAST4(BigDecimal newvalue) {
        fieldDGAST4.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DGAST4 as a BigDecimal.
     */
    public BigDecimal getBigDecimalDGAST4() {
        return fieldDGAST4.getBigDecimal();
    }

    /**
     * Set field CAMAPL using a String value.
     */
    public void setCAMAPL(String newvalue) {
        fieldCAMAPL.setString(newvalue);
    }

    /**
     * Get value of field CAMAPL as a String.
     */
    public String getCAMAPL() {
        return fieldCAMAPL.getString();
    }

    /**
     * Set numeric field CAMAPL using a BigDecimal value.
     */
    public void setCAMAPL(BigDecimal newvalue) {
        fieldCAMAPL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CAMAPL as a BigDecimal.
     */
    public BigDecimal getBigDecimalCAMAPL() {
        return fieldCAMAPL.getBigDecimal();
    }

    /**
     * Set field DOTIMP using a String value.
     */
    public void setDOTIMP(String newvalue) {
        fieldDOTIMP.setString(newvalue);
    }

    /**
     * Get value of field DOTIMP as a String.
     */
    public String getDOTIMP() {
        return fieldDOTIMP.getString();
    }

    /**
     * Set numeric field DOTIMP using a BigDecimal value.
     */
    public void setDOTIMP(BigDecimal newvalue) {
        fieldDOTIMP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DOTIMP as a BigDecimal.
     */
    public BigDecimal getBigDecimalDOTIMP() {
        return fieldDOTIMP.getBigDecimal();
    }

    /**
     * Set field XOTIMP using a String value.
     */
    public void setXOTIMP(String newvalue) {
        fieldXOTIMP.setString(newvalue);
    }

    /**
     * Get value of field XOTIMP as a String.
     */
    public String getXOTIMP() {
        return fieldXOTIMP.getString();
    }

    /**
     * Set numeric field XOTIMP using a BigDecimal value.
     */
    public void setXOTIMP(BigDecimal newvalue) {
        fieldXOTIMP.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field XOTIMP as a BigDecimal.
     */
    public BigDecimal getBigDecimalXOTIMP() {
        return fieldXOTIMP.getBigDecimal();
    }

    /**
     * Set field DERDER using a String value.
     */
    public void setDERDER(String newvalue) {
        fieldDERDER.setString(newvalue);
    }

    /**
     * Get value of field DERDER as a String.
     */
    public String getDERDER() {
        return fieldDERDER.getString();
    }

    /**
     * Set field NOMDER using a String value.
     */
    public void setNOMDER(String newvalue) {
        fieldNOMDER.setString(newvalue);
    }

    /**
     * Get value of field NOMDER as a String.
     */
    public String getNOMDER() {
        return fieldNOMDER.getString();
    }

    /**
     * Set field DERVAL using a String value.
     */
    public void setDERVAL(String newvalue) {
        fieldDERVAL.setString(newvalue);
    }

    /**
     * Get value of field DERVAL as a String.
     */
    public String getDERVAL() {
        return fieldDERVAL.getString();
    }

    /**
     * Set field DERINI using a String value.
     */
    public void setDERINI(String newvalue) {
        fieldDERINI.setString(newvalue);
    }

    /**
     * Get value of field DERINI as a String.
     */
    public String getDERINI() {
        return fieldDERINI.getString();
    }

    /**
     * Set numeric field DERINI using a BigDecimal value.
     */
    public void setDERINI(BigDecimal newvalue) {
        fieldDERINI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DERINI as a BigDecimal.
     */
    public BigDecimal getBigDecimalDERINI() {
        return fieldDERINI.getBigDecimal();
    }

    /**
     * Set field DERFIN using a String value.
     */
    public void setDERFIN(String newvalue) {
        fieldDERFIN.setString(newvalue);
    }

    /**
     * Get value of field DERFIN as a String.
     */
    public String getDERFIN() {
        return fieldDERFIN.getString();
    }

    /**
     * Set numeric field DERFIN using a BigDecimal value.
     */
    public void setDERFIN(BigDecimal newvalue) {
        fieldDERFIN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DERFIN as a BigDecimal.
     */
    public BigDecimal getBigDecimalDERFIN() {
        return fieldDERFIN.getBigDecimal();
    }

    /**
     * Set field DEROLD using a String value.
     */
    public void setDEROLD(String newvalue) {
        fieldDEROLD.setString(newvalue);
    }

    /**
     * Get value of field DEROLD as a String.
     */
    public String getDEROLD() {
        return fieldDEROLD.getString();
    }

    /**
     * Set numeric field DEROLD using a BigDecimal value.
     */
    public void setDEROLD(BigDecimal newvalue) {
        fieldDEROLD.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DEROLD as a BigDecimal.
     */
    public BigDecimal getBigDecimalDEROLD() {
        return fieldDEROLD.getBigDecimal();
    }

    /**
     * Set field DERNEW using a String value.
     */
    public void setDERNEW(String newvalue) {
        fieldDERNEW.setString(newvalue);
    }

    /**
     * Get value of field DERNEW as a String.
     */
    public String getDERNEW() {
        return fieldDERNEW.getString();
    }

    /**
     * Set numeric field DERNEW using a BigDecimal value.
     */
    public void setDERNEW(BigDecimal newvalue) {
        fieldDERNEW.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DERNEW as a BigDecimal.
     */
    public BigDecimal getBigDecimalDERNEW() {
        return fieldDERNEW.getBigDecimal();
    }

    /**
     * Set field DERDES using a String value.
     */
    public void setDERDES(String newvalue) {
        fieldDERDES.setString(newvalue);
    }

    /**
     * Get value of field DERDES as a String.
     */
    public String getDERDES() {
        return fieldDERDES.getString();
    }

    /**
     * Set field DERPTA using a String value.
     */
    public void setDERPTA(String newvalue) {
        fieldDERPTA.setString(newvalue);
    }

    /**
     * Get value of field DERPTA as a String.
     */
    public String getDERPTA() {
        return fieldDERPTA.getString();
    }

    /**
     * Set numeric field DERPTA using a BigDecimal value.
     */
    public void setDERPTA(BigDecimal newvalue) {
        fieldDERPTA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field DERPTA as a BigDecimal.
     */
    public BigDecimal getBigDecimalDERPTA() {
        return fieldDERPTA.getBigDecimal();
    }

    /**
     * Set field DERNVA using a String value.
     */
    public void setDERNVA(String newvalue) {
        fieldDERNVA.setString(newvalue);
    }

    /**
     * Get value of field DERNVA as a String.
     */
    public String getDERNVA() {
        return fieldDERNVA.getString();
    }

    /**
     * Set field NEWNOM using a String value.
     */
    public void setNEWNOM(String newvalue) {
        fieldNEWNOM.setString(newvalue);
    }

    /**
     * Get value of field NEWNOM as a String.
     */
    public String getNEWNOM() {
        return fieldNEWNOM.getString();
    }

    /**
     * Set field OK4 using a String value.
     */
    public void setOK4(String newvalue) {
        fieldOK4.setString(newvalue);
    }

    /**
     * Get value of field OK4 as a String.
     */
    public String getOK4() {
        return fieldOK4.getString();
    }

    /**
     * Set field CAJOLD using a String value.
     */
    public void setCAJOLD(String newvalue) {
        fieldCAJOLD.setString(newvalue);
    }

    /**
     * Get value of field CAJOLD as a String.
     */
    public String getCAJOLD() {
        return fieldCAJOLD.getString();
    }

    /**
     * Set field NOMOLD using a String value.
     */
    public void setNOMOLD(String newvalue) {
        fieldNOMOLD.setString(newvalue);
    }

    /**
     * Get value of field NOMOLD as a String.
     */
    public String getNOMOLD() {
        return fieldNOMOLD.getString();
    }

    /**
     * Set field CAJNEW using a String value.
     */
    public void setCAJNEW(String newvalue) {
        fieldCAJNEW.setString(newvalue);
    }

    /**
     * Get value of field CAJNEW as a String.
     */
    public String getCAJNEW() {
        return fieldCAJNEW.getString();
    }

    /**
     * Set field NOMNEW using a String value.
     */
    public void setNOMNEW(String newvalue) {
        fieldNOMNEW.setString(newvalue);
    }

    /**
     * Get value of field NOMNEW as a String.
     */
    public String getNOMNEW() {
        return fieldNOMNEW.getString();
    }

    /**
     * Set field CAJPOL using a String value.
     */
    public void setCAJPOL(String newvalue) {
        fieldCAJPOL.setString(newvalue);
    }

    /**
     * Get value of field CAJPOL as a String.
     */
    public String getCAJPOL() {
        return fieldCAJPOL.getString();
    }

    /**
     * Set numeric field CAJPOL using a BigDecimal value.
     */
    public void setCAJPOL(BigDecimal newvalue) {
        fieldCAJPOL.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CAJPOL as a BigDecimal.
     */
    public BigDecimal getBigDecimalCAJPOL() {
        return fieldCAJPOL.getBigDecimal();
    }

    /**
     * Set field CAJPNE using a String value.
     */
    public void setCAJPNE(String newvalue) {
        fieldCAJPNE.setString(newvalue);
    }

    /**
     * Get value of field CAJPNE as a String.
     */
    public String getCAJPNE() {
        return fieldCAJPNE.getString();
    }

    /**
     * Set numeric field CAJPNE using a BigDecimal value.
     */
    public void setCAJPNE(BigDecimal newvalue) {
        fieldCAJPNE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CAJPNE as a BigDecimal.
     */
    public BigDecimal getBigDecimalCAJPNE() {
        return fieldCAJPNE.getBigDecimal();
    }

    /**
     * Set field CAJGAS using a String value.
     */
    public void setCAJGAS(String newvalue) {
        fieldCAJGAS.setString(newvalue);
    }

    /**
     * Get value of field CAJGAS as a String.
     */
    public String getCAJGAS() {
        return fieldCAJGAS.getString();
    }

    /**
     * Set numeric field CAJGAS using a BigDecimal value.
     */
    public void setCAJGAS(BigDecimal newvalue) {
        fieldCAJGAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CAJGAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalCAJGAS() {
        return fieldCAJGAS.getBigDecimal();
    }

    /**
     * Set field CAJFEC using a String value.
     */
    public void setCAJFEC(String newvalue) {
        fieldCAJFEC.setString(newvalue);
    }

    /**
     * Get value of field CAJFEC as a String.
     */
    public String getCAJFEC() {
        return fieldCAJFEC.getString();
    }

    /**
     * Set numeric field CAJFEC using a BigDecimal value.
     */
    public void setCAJFEC(BigDecimal newvalue) {
        fieldCAJFEC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CAJFEC as a BigDecimal.
     */
    public BigDecimal getBigDecimalCAJFEC() {
        return fieldCAJFEC.getBigDecimal();
    }

    /**
     * Set field OK5 using a String value.
     */
    public void setOK5(String newvalue) {
        fieldOK5.setString(newvalue);
    }

    /**
     * Get value of field OK5 as a String.
     */
    public String getOK5() {
        return fieldOK5.getString();
    }

    /**
     * Set field CAJRED using a String value.
     */
    public void setCAJRED(String newvalue) {
        fieldCAJRED.setString(newvalue);
    }

    /**
     * Get value of field CAJRED as a String.
     */
    public String getCAJRED() {
        return fieldCAJRED.getString();
    }

    /**
     * Set field CAMFEC using a String value.
     */
    public void setCAMFEC(String newvalue) {
        fieldCAMFEC.setString(newvalue);
    }

    /**
     * Get value of field CAMFEC as a String.
     */
    public String getCAMFEC() {
        return fieldCAMFEC.getString();
    }

    /**
     * Set numeric field CAMFEC using a BigDecimal value.
     */
    public void setCAMFEC(BigDecimal newvalue) {
        fieldCAMFEC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CAMFEC as a BigDecimal.
     */
    public BigDecimal getBigDecimalCAMFEC() {
        return fieldCAMFEC.getBigDecimal();
    }

    /**
     * Set field CAMVAL using a String value.
     */
    public void setCAMVAL(String newvalue) {
        fieldCAMVAL.setString(newvalue);
    }

    /**
     * Get value of field CAMVAL as a String.
     */
    public String getCAMVAL() {
        return fieldCAMVAL.getString();
    }

    /**
     * Set field NBXOLD using a String value.
     */
    public void setNBXOLD(String newvalue) {
        fieldNBXOLD.setString(newvalue);
    }

    /**
     * Get value of field NBXOLD as a String.
     */
    public String getNBXOLD() {
        return fieldNBXOLD.getString();
    }

    /**
     * Set field NOXOLD using a String value.
     */
    public void setNOXOLD(String newvalue) {
        fieldNOXOLD.setString(newvalue);
    }

    /**
     * Get value of field NOXOLD as a String.
     */
    public String getNOXOLD() {
        return fieldNOXOLD.getString();
    }

    /**
     * Set numeric field NOXOLD using a BigDecimal value.
     */
    public void setNOXOLD(BigDecimal newvalue) {
        fieldNOXOLD.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field NOXOLD as a BigDecimal.
     */
    public BigDecimal getBigDecimalNOXOLD() {
        return fieldNOXOLD.getBigDecimal();
    }

    /**
     * Set field CAMNNW using a String value.
     */
    public void setCAMNNW(String newvalue) {
        fieldCAMNNW.setString(newvalue);
    }

    /**
     * Get value of field CAMNNW as a String.
     */
    public String getCAMNNW() {
        return fieldCAMNNW.getString();
    }

    /**
     * Set numeric field CAMNNW using a BigDecimal value.
     */
    public void setCAMNNW(BigDecimal newvalue) {
        fieldCAMNNW.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CAMNNW as a BigDecimal.
     */
    public BigDecimal getBigDecimalCAMNNW() {
        return fieldCAMNNW.getBigDecimal();
    }

    /**
     * Set field CAMCA1 using a String value.
     */
    public void setCAMCA1(String newvalue) {
        fieldCAMCA1.setString(newvalue);
    }

    /**
     * Get value of field CAMCA1 as a String.
     */
    public String getCAMCA1() {
        return fieldCAMCA1.getString();
    }

    /**
     * Set field CAMCA2 using a String value.
     */
    public void setCAMCA2(String newvalue) {
        fieldCAMCA2.setString(newvalue);
    }

    /**
     * Get value of field CAMCA2 as a String.
     */
    public String getCAMCA2() {
        return fieldCAMCA2.getString();
    }

    /**
     * Set field OK6 using a String value.
     */
    public void setOK6(String newvalue) {
        fieldOK6.setString(newvalue);
    }

    /**
     * Get value of field OK6 as a String.
     */
    public String getOK6() {
        return fieldOK6.getString();
    }

    /**
     * Set field EQUOLD using a String value.
     */
    public void setEQUOLD(String newvalue) {
        fieldEQUOLD.setString(newvalue);
    }

    /**
     * Get value of field EQUOLD as a String.
     */
    public String getEQUOLD() {
        return fieldEQUOLD.getString();
    }

    /**
     * Set field NOYOLD using a String value.
     */
    public void setNOYOLD(String newvalue) {
        fieldNOYOLD.setString(newvalue);
    }

    /**
     * Get value of field NOYOLD as a String.
     */
    public String getNOYOLD() {
        return fieldNOYOLD.getString();
    }

    /**
     * Set field EQUNEW using a String value.
     */
    public void setEQUNEW(String newvalue) {
        fieldEQUNEW.setString(newvalue);
    }

    /**
     * Get value of field EQUNEW as a String.
     */
    public String getEQUNEW() {
        return fieldEQUNEW.getString();
    }

    /**
     * Set field OK7 using a String value.
     */
    public void setOK7(String newvalue) {
        fieldOK7.setString(newvalue);
    }

    /**
     * Get value of field OK7 as a String.
     */
    public String getOK7() {
        return fieldOK7.getString();
    }

    /**
     * Set field EQUFEC using a String value.
     */
    public void setEQUFEC(String newvalue) {
        fieldEQUFEC.setString(newvalue);
    }

    /**
     * Get value of field EQUFEC as a String.
     */
    public String getEQUFEC() {
        return fieldEQUFEC.getString();
    }

    /**
     * Set numeric field EQUFEC using a BigDecimal value.
     */
    public void setEQUFEC(BigDecimal newvalue) {
        fieldEQUFEC.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field EQUFEC as a BigDecimal.
     */
    public BigDecimal getBigDecimalEQUFEC() {
        return fieldEQUFEC.getBigDecimal();
    }

    /**
     * Set field CODCLI using a String value.
     */
    public void setCODCLI(String newvalue) {
        fieldCODCLI.setString(newvalue);
    }

    /**
     * Get value of field CODCLI as a String.
     */
    public String getCODCLI() {
        return fieldCODCLI.getString();
    }

    /**
     * Set numeric field CODCLI using a BigDecimal value.
     */
    public void setCODCLI(BigDecimal newvalue) {
        fieldCODCLI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CODCLI as a BigDecimal.
     */
    public BigDecimal getBigDecimalCODCLI() {
        return fieldCODCLI.getBigDecimal();
    }

    /**
     * Set field VALOR using a String value.
     */
    public void setVALOR(String newvalue) {
        fieldVALOR.setString(newvalue);
    }

    /**
     * Get value of field VALOR as a String.
     */
    public String getVALOR() {
        return fieldVALOR.getString();
    }

    /**
     * Set field CODIN1 using a String value.
     */
    public void setCODIN1(String newvalue) {
        fieldCODIN1.setString(newvalue);
    }

    /**
     * Get value of field CODIN1 as a String.
     */
    public String getCODIN1() {
        return fieldCODIN1.getString();
    }

    /**
     * Set numeric field CODIN1 using a BigDecimal value.
     */
    public void setCODIN1(BigDecimal newvalue) {
        fieldCODIN1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CODIN1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCODIN1() {
        return fieldCODIN1.getBigDecimal();
    }

    /**
     * Set field NOMIN1 using a String value.
     */
    public void setNOMIN1(String newvalue) {
        fieldNOMIN1.setString(newvalue);
    }

    /**
     * Get value of field NOMIN1 as a String.
     */
    public String getNOMIN1() {
        return fieldNOMIN1.getString();
    }

    /**
     * Set field CODIN2 using a String value.
     */
    public void setCODIN2(String newvalue) {
        fieldCODIN2.setString(newvalue);
    }

    /**
     * Get value of field CODIN2 as a String.
     */
    public String getCODIN2() {
        return fieldCODIN2.getString();
    }

    /**
     * Set numeric field CODIN2 using a BigDecimal value.
     */
    public void setCODIN2(BigDecimal newvalue) {
        fieldCODIN2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field CODIN2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalCODIN2() {
        return fieldCODIN2.getBigDecimal();
    }

    /**
     * Set field NOMIN2 using a String value.
     */
    public void setNOMIN2(String newvalue) {
        fieldNOMIN2.setString(newvalue);
    }

    /**
     * Get value of field NOMIN2 as a String.
     */
    public String getNOMIN2() {
        return fieldNOMIN2.getString();
    }

    /**
     * Set field FECOPE using a String value.
     */
    public void setFECOPE(String newvalue) {
        fieldFECOPE.setString(newvalue);
    }

    /**
     * Get value of field FECOPE as a String.
     */
    public String getFECOPE() {
        return fieldFECOPE.getString();
    }

    /**
     * Set numeric field FECOPE using a BigDecimal value.
     */
    public void setFECOPE(BigDecimal newvalue) {
        fieldFECOPE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field FECOPE as a BigDecimal.
     */
    public BigDecimal getBigDecimalFECOPE() {
        return fieldFECOPE.getBigDecimal();
    }

    /**
     * Set field OK8 using a String value.
     */
    public void setOK8(String newvalue) {
        fieldOK8.setString(newvalue);
    }

    /**
     * Get value of field OK8 as a String.
     */
    public String getOK8() {
        return fieldOK8.getString();
    }

    /**
     * Set field SELOPE using a String value.
     */
    public void setSELOPE(String newvalue) {
        fieldSELOPE.setString(newvalue);
    }

    /**
     * Get value of field SELOPE as a String.
     */
    public String getSELOPE() {
        return fieldSELOPE.getString();
    }

    /**
     * Set numeric field SELOPE using a BigDecimal value.
     */
    public void setSELOPE(BigDecimal newvalue) {
        fieldSELOPE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field SELOPE as a BigDecimal.
     */
    public BigDecimal getBigDecimalSELOPE() {
        return fieldSELOPE.getBigDecimal();
    }

    /**
     * Set field CONCEP using a String value.
     */
    public void setCONCEP(String newvalue) {
        fieldCONCEP.setString(newvalue);
    }

    /**
     * Get value of field CONCEP as a String.
     */
    public String getCONCEP() {
        return fieldCONCEP.getString();
    }

    /**
     * Set field NOMCL9 using a String value.
     */
    public void setNOMCL9(String newvalue) {
        fieldNOMCL9.setString(newvalue);
    }

    /**
     * Get value of field NOMCL9 as a String.
     */
    public String getNOMCL9() {
        return fieldNOMCL9.getString();
    }

    /**
     * Set field INFLUE using a String value.
     */
    public void setINFLUE(String newvalue) {
        fieldINFLUE.setString(newvalue);
    }

    /**
     * Get value of field INFLUE as a String.
     */
    public String getINFLUE() {
        return fieldINFLUE.getString();
    }

    /**
     * Set field NOMVA9 using a String value.
     */
    public void setNOMVA9(String newvalue) {
        fieldNOMVA9.setString(newvalue);
    }

    /**
     * Get value of field NOMVA9 as a String.
     */
    public String getNOMVA9() {
        return fieldNOMVA9.getString();
    }

    /**
     * Set field NOMIN9 using a String value.
     */
    public void setNOMIN9(String newvalue) {
        fieldNOMIN9.setString(newvalue);
    }

    /**
     * Get value of field NOMIN9 as a String.
     */
    public String getNOMIN9() {
        return fieldNOMIN9.getString();
    }

    /**
     * Set field GASTOS using a String value.
     */
    public void setGASTOS(String newvalue) {
        fieldGASTOS.setString(newvalue);
    }

    /**
     * Get value of field GASTOS as a String.
     */
    public String getGASTOS() {
        return fieldGASTOS.getString();
    }

    /**
     * Set numeric field GASTOS using a BigDecimal value.
     */
    public void setGASTOS(BigDecimal newvalue) {
        fieldGASTOS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field GASTOS as a BigDecimal.
     */
    public BigDecimal getBigDecimalGASTOS() {
        return fieldGASTOS.getBigDecimal();
    }

    /**
     * Set field OK9 using a String value.
     */
    public void setOK9(String newvalue) {
        fieldOK9.setString(newvalue);
    }

    /**
     * Get value of field OK9 as a String.
     */
    public String getOK9() {
        return fieldOK9.getString();
    }

}
