package ve.com.sios.gpff.legacy.message;

import java.math.BigDecimal;
import java.util.Hashtable;
import ve.com.sios.gpff.legacy.sockets.CharacterField;
import ve.com.sios.gpff.legacy.sockets.DecimalField;
import ve.com.sios.gpff.legacy.sockets.MessageField;
import ve.com.sios.gpff.legacy.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from VARI01CFM physical file
 * definition.
 * 
* File level identifier is 1140216165309. Record format level identifier is
 * 558DE646301C1.
 */
public class VARI01CFMMessage extends MessageRecord {

    final static String fldnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "VLOCOA",
        "VLONOM",
        "VLOJG1",
        "VLOJG2",
        "NOMGRU",
        "VLOTUN",
        "AUVNSI",
        "VLOCAT",
        "VLOMAM",
        "VLOFIS",
        "NOMEMI",
        "VLOSE1",
        "VLOUDE",
        "VLOUCA",
        "VLOUNI",
        "VLOTAS",
        "AUVDEC",
        "AUVNEI",
        "AUVSIN",
        "VLODIV",
        "DIVNOM",
        "VLOTFO",
        "NOMPAI",
        "AUVCUS",
        "NOMCUS",
        "VLOPIN",
        "AUVCER",
        "VLOTIP",
        "VLOSPR"
    };
    final static String tnames[] = {
        "HDAT",
        "HTIM",
        "HUSR",
        "HENV",
        "HXML",
        "HSEC",
        "HFIL",
        "HLEN",
        "INDICA",
        "REGCUR",
        "CAMCUR",
        "POSCUR",
        "VLOCOA",
        "VLONOM",
        "VLOJG1",
        "VLOJG2",
        "NOMGRU",
        "VLOTUN",
        "AUVNSI",
        "VLOCAT",
        "VLOMAM",
        "VLOFIS",
        "NOMEMI",
        "VLOSE1",
        "VLOUDE",
        "VLOUCA",
        "VLOUNI",
        "VLOTAS",
        "AUVDEC",
        "AUVNEI",
        "AUVSIN",
        "VLODIV",
        "DIVNOM",
        "VLOTFO",
        "NOMPAI",
        "AUVCUS",
        "NOMCUS",
        "VLOPIN",
        "AUVCER",
        "VLOTIP",
        "VLOSPR"
    };
    final static String fid = "1140216165309";
    final static String rid = "558DE646301C1";
    final static String fmtname = "VARI01CFM";
    final int FIELDCOUNT = 41;
    private static Hashtable tlookup = new Hashtable();
    private DecimalField fieldHDAT = null;
    private DecimalField fieldHTIM = null;
    private CharacterField fieldHUSR = null;
    private CharacterField fieldHENV = null;
    private CharacterField fieldHXML = null;
    private CharacterField fieldHSEC = null;
    private CharacterField fieldHFIL = null;
    private DecimalField fieldHLEN = null;
    private CharacterField fieldINDICA = null;
    private CharacterField fieldREGCUR = null;
    private CharacterField fieldCAMCUR = null;
    private DecimalField fieldPOSCUR = null;
    private CharacterField fieldVLOCOA = null;
    private CharacterField fieldVLONOM = null;
    private DecimalField fieldVLOJG1 = null;
    private DecimalField fieldVLOJG2 = null;
    private CharacterField fieldNOMGRU = null;
    private CharacterField fieldVLOTUN = null;
    private DecimalField fieldAUVNSI = null;
    private CharacterField fieldVLOCAT = null;
    private CharacterField fieldVLOMAM = null;
    private DecimalField fieldVLOFIS = null;
    private CharacterField fieldNOMEMI = null;
    private DecimalField fieldVLOSE1 = null;
    private DecimalField fieldVLOUDE = null;
    private DecimalField fieldVLOUCA = null;
    private DecimalField fieldVLOUNI = null;
    private DecimalField fieldVLOTAS = null;
    private CharacterField fieldAUVDEC = null;
    private CharacterField fieldAUVNEI = null;
    private CharacterField fieldAUVSIN = null;
    private DecimalField fieldVLODIV = null;
    private CharacterField fieldDIVNOM = null;
    private DecimalField fieldVLOTFO = null;
    private CharacterField fieldNOMPAI = null;
    private DecimalField fieldAUVCUS = null;
    private CharacterField fieldNOMCUS = null;
    private DecimalField fieldVLOPIN = null;
    private DecimalField fieldAUVCER = null;
    private CharacterField fieldVLOTIP = null;
    private DecimalField fieldVLOSPR = null;

    /**
     * Constructor for VARI01CFMMessage.
     */
    public VARI01CFMMessage() {
        createFields();
        initialize();
    }

    /**
     * Create fields for this message. This method implements the abstract
     * method in the MessageRecord superclass.
     */
    protected void createFields() {
        recordsize = 749;
        fileid = fid;
        recordid = rid;
        message = new byte[getByteLength()];
        formatname = fmtname;
        fieldnames = fldnames;
        tagnames = tnames;
        fields = new MessageField[FIELDCOUNT];

        fields[0] = fieldHDAT
                = new DecimalField(message, HEADERSIZE + 0, 7, 0, "HDAT");
        fields[1] = fieldHTIM
                = new DecimalField(message, HEADERSIZE + 7, 7, 0, "HTIM");
        fields[2] = fieldHUSR
                = new CharacterField(message, HEADERSIZE + 14, 10, "HUSR");
        fields[3] = fieldHENV
                = new CharacterField(message, HEADERSIZE + 24, 1, "HENV");
        fields[4] = fieldHXML
                = new CharacterField(message, HEADERSIZE + 25, 10, "HXML");
        fields[5] = fieldHSEC
                = new CharacterField(message, HEADERSIZE + 35, 10, "HSEC");
        fields[6] = fieldHFIL
                = new CharacterField(message, HEADERSIZE + 45, 10, "HFIL");
        fields[7] = fieldHLEN
                = new DecimalField(message, HEADERSIZE + 55, 6, 0, "HLEN");
        fields[8] = fieldINDICA
                = new CharacterField(message, HEADERSIZE + 61, 100, "INDICA");
        fields[9] = fieldREGCUR
                = new CharacterField(message, HEADERSIZE + 161, 10, "REGCUR");
        fields[10] = fieldCAMCUR
                = new CharacterField(message, HEADERSIZE + 171, 10, "CAMCUR");
        fields[11] = fieldPOSCUR
                = new DecimalField(message, HEADERSIZE + 181, 5, 0, "POSCUR");
        fields[12] = fieldVLOCOA
                = new CharacterField(message, HEADERSIZE + 186, 12, "VLOCOA");
        fields[13] = fieldVLONOM
                = new CharacterField(message, HEADERSIZE + 198, 40, "VLONOM");
        fields[14] = fieldVLOJG1
                = new DecimalField(message, HEADERSIZE + 238, 4, 0, "VLOJG1");
        fields[15] = fieldVLOJG2
                = new DecimalField(message, HEADERSIZE + 242, 8, 0, "VLOJG2");
        fields[16] = fieldNOMGRU
                = new CharacterField(message, HEADERSIZE + 250, 40, "NOMGRU");
        fields[17] = fieldVLOTUN
                = new CharacterField(message, HEADERSIZE + 290, 20, "VLOTUN");
        fields[18] = fieldAUVNSI
                = new DecimalField(message, HEADERSIZE + 310, 3, 0, "AUVNSI");
        fields[19] = fieldVLOCAT
                = new CharacterField(message, HEADERSIZE + 313, 5, "VLOCAT");
        fields[20] = fieldVLOMAM
                = new CharacterField(message, HEADERSIZE + 318, 1, "VLOMAM");
        fields[21] = fieldVLOFIS
                = new DecimalField(message, HEADERSIZE + 319, 8, 0, "VLOFIS");
        fields[22] = fieldNOMEMI
                = new CharacterField(message, HEADERSIZE + 327, 40, "NOMEMI");
        fields[23] = fieldVLOSE1
                = new DecimalField(message, HEADERSIZE + 367, 17, 2, "VLOSE1");
        fields[24] = fieldVLOUDE
                = new DecimalField(message, HEADERSIZE + 384, 7, 0, "VLOUDE");
        fields[25] = fieldVLOUCA
                = new DecimalField(message, HEADERSIZE + 391, 7, 0, "VLOUCA");
        fields[26] = fieldVLOUNI
                = new DecimalField(message, HEADERSIZE + 398, 15, 2, "VLOUNI");
        fields[27] = fieldVLOTAS
                = new DecimalField(message, HEADERSIZE + 413, 11, 6, "VLOTAS");
        fields[28] = fieldAUVDEC
                = new CharacterField(message, HEADERSIZE + 424, 50, "AUVDEC");
        fields[29] = fieldAUVNEI
                = new CharacterField(message, HEADERSIZE + 474, 50, "AUVNEI");
        fields[30] = fieldAUVSIN
                = new CharacterField(message, HEADERSIZE + 524, 50, "AUVSIN");
        fields[31] = fieldVLODIV
                = new DecimalField(message, HEADERSIZE + 574, 4, 0, "VLODIV");
        fields[32] = fieldDIVNOM
                = new CharacterField(message, HEADERSIZE + 578, 40, "DIVNOM");
        fields[33] = fieldVLOTFO
                = new DecimalField(message, HEADERSIZE + 618, 5, 0, "VLOTFO");
        fields[34] = fieldNOMPAI
                = new CharacterField(message, HEADERSIZE + 623, 40, "NOMPAI");
        fields[35] = fieldAUVCUS
                = new DecimalField(message, HEADERSIZE + 663, 8, 0, "AUVCUS");
        fields[36] = fieldNOMCUS
                = new CharacterField(message, HEADERSIZE + 671, 40, "NOMCUS");
        fields[37] = fieldVLOPIN
                = new DecimalField(message, HEADERSIZE + 711, 10, 5, "VLOPIN");
        fields[38] = fieldAUVCER
                = new DecimalField(message, HEADERSIZE + 721, 16, 0, "AUVCER");
        fields[39] = fieldVLOTIP
                = new CharacterField(message, HEADERSIZE + 737, 5, "VLOTIP");
        fields[40] = fieldVLOSPR
                = new DecimalField(message, HEADERSIZE + 742, 7, 3, "VLOSPR");

        synchronized (tlookup) {
            if (tlookup.isEmpty()) {
                for (int i = 0; i < tnames.length; i++) {
                    tlookup.put(tnames[i], new Integer(i));
                }
            }
        }

        taglookup = tlookup;
    }

    /**
     * Set field HDAT using a String value.
     */
    public void setHDAT(String newvalue) {
        fieldHDAT.setString(newvalue);
    }

    /**
     * Get value of field HDAT as a String.
     */
    public String getHDAT() {
        return fieldHDAT.getString();
    }

    /**
     * Set numeric field HDAT using a BigDecimal value.
     */
    public void setHDAT(BigDecimal newvalue) {
        fieldHDAT.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HDAT as a BigDecimal.
     */
    public BigDecimal getBigDecimalHDAT() {
        return fieldHDAT.getBigDecimal();
    }

    /**
     * Set field HTIM using a String value.
     */
    public void setHTIM(String newvalue) {
        fieldHTIM.setString(newvalue);
    }

    /**
     * Get value of field HTIM as a String.
     */
    public String getHTIM() {
        return fieldHTIM.getString();
    }

    /**
     * Set numeric field HTIM using a BigDecimal value.
     */
    public void setHTIM(BigDecimal newvalue) {
        fieldHTIM.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HTIM as a BigDecimal.
     */
    public BigDecimal getBigDecimalHTIM() {
        return fieldHTIM.getBigDecimal();
    }

    /**
     * Set field HUSR using a String value.
     */
    public void setHUSR(String newvalue) {
        fieldHUSR.setString(newvalue);
    }

    /**
     * Get value of field HUSR as a String.
     */
    public String getHUSR() {
        return fieldHUSR.getString();
    }

    /**
     * Set field HENV using a String value.
     */
    public void setHENV(String newvalue) {
        fieldHENV.setString(newvalue);
    }

    /**
     * Get value of field HENV as a String.
     */
    public String getHENV() {
        return fieldHENV.getString();
    }

    /**
     * Set field HXML using a String value.
     */
    public void setHXML(String newvalue) {
        fieldHXML.setString(newvalue);
    }

    /**
     * Get value of field HXML as a String.
     */
    public String getHXML() {
        return fieldHXML.getString();
    }

    /**
     * Set field HSEC using a String value.
     */
    public void setHSEC(String newvalue) {
        fieldHSEC.setString(newvalue);
    }

    /**
     * Get value of field HSEC as a String.
     */
    public String getHSEC() {
        return fieldHSEC.getString();
    }

    /**
     * Set field HFIL using a String value.
     */
    public void setHFIL(String newvalue) {
        fieldHFIL.setString(newvalue);
    }

    /**
     * Get value of field HFIL as a String.
     */
    public String getHFIL() {
        return fieldHFIL.getString();
    }

    /**
     * Set field HLEN using a String value.
     */
    public void setHLEN(String newvalue) {
        fieldHLEN.setString(newvalue);
    }

    /**
     * Get value of field HLEN as a String.
     */
    public String getHLEN() {
        return fieldHLEN.getString();
    }

    /**
     * Set numeric field HLEN using a BigDecimal value.
     */
    public void setHLEN(BigDecimal newvalue) {
        fieldHLEN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field HLEN as a BigDecimal.
     */
    public BigDecimal getBigDecimalHLEN() {
        return fieldHLEN.getBigDecimal();
    }

    /**
     * Set field INDICA using a String value.
     */
    public void setINDICA(String newvalue) {
        fieldINDICA.setString(newvalue);
    }

    /**
     * Get value of field INDICA as a String.
     */
    public String getINDICA() {
        return fieldINDICA.getString();
    }

    /**
     * Set field REGCUR using a String value.
     */
    public void setREGCUR(String newvalue) {
        fieldREGCUR.setString(newvalue);
    }

    /**
     * Get value of field REGCUR as a String.
     */
    public String getREGCUR() {
        return fieldREGCUR.getString();
    }

    /**
     * Set field CAMCUR using a String value.
     */
    public void setCAMCUR(String newvalue) {
        fieldCAMCUR.setString(newvalue);
    }

    /**
     * Get value of field CAMCUR as a String.
     */
    public String getCAMCUR() {
        return fieldCAMCUR.getString();
    }

    /**
     * Set field POSCUR using a String value.
     */
    public void setPOSCUR(String newvalue) {
        fieldPOSCUR.setString(newvalue);
    }

    /**
     * Get value of field POSCUR as a String.
     */
    public String getPOSCUR() {
        return fieldPOSCUR.getString();
    }

    /**
     * Set numeric field POSCUR using a BigDecimal value.
     */
    public void setPOSCUR(BigDecimal newvalue) {
        fieldPOSCUR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field POSCUR as a BigDecimal.
     */
    public BigDecimal getBigDecimalPOSCUR() {
        return fieldPOSCUR.getBigDecimal();
    }

    /**
     * Set field VLOCOA using a String value.
     */
    public void setVLOCOA(String newvalue) {
        fieldVLOCOA.setString(newvalue);
    }

    /**
     * Get value of field VLOCOA as a String.
     */
    public String getVLOCOA() {
        return fieldVLOCOA.getString();
    }

    /**
     * Set field VLONOM using a String value.
     */
    public void setVLONOM(String newvalue) {
        fieldVLONOM.setString(newvalue);
    }

    /**
     * Get value of field VLONOM as a String.
     */
    public String getVLONOM() {
        return fieldVLONOM.getString();
    }

    /**
     * Set field VLOJG1 using a String value.
     */
    public void setVLOJG1(String newvalue) {
        fieldVLOJG1.setString(newvalue);
    }

    /**
     * Get value of field VLOJG1 as a String.
     */
    public String getVLOJG1() {
        return fieldVLOJG1.getString();
    }

    /**
     * Set numeric field VLOJG1 using a BigDecimal value.
     */
    public void setVLOJG1(BigDecimal newvalue) {
        fieldVLOJG1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOJG1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOJG1() {
        return fieldVLOJG1.getBigDecimal();
    }

    /**
     * Set field VLOJG2 using a String value.
     */
    public void setVLOJG2(String newvalue) {
        fieldVLOJG2.setString(newvalue);
    }

    /**
     * Get value of field VLOJG2 as a String.
     */
    public String getVLOJG2() {
        return fieldVLOJG2.getString();
    }

    /**
     * Set numeric field VLOJG2 using a BigDecimal value.
     */
    public void setVLOJG2(BigDecimal newvalue) {
        fieldVLOJG2.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOJG2 as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOJG2() {
        return fieldVLOJG2.getBigDecimal();
    }

    /**
     * Set field NOMGRU using a String value.
     */
    public void setNOMGRU(String newvalue) {
        fieldNOMGRU.setString(newvalue);
    }

    /**
     * Get value of field NOMGRU as a String.
     */
    public String getNOMGRU() {
        return fieldNOMGRU.getString();
    }

    /**
     * Set field VLOTUN using a String value.
     */
    public void setVLOTUN(String newvalue) {
        fieldVLOTUN.setString(newvalue);
    }

    /**
     * Get value of field VLOTUN as a String.
     */
    public String getVLOTUN() {
        return fieldVLOTUN.getString();
    }

    /**
     * Set field AUVNSI using a String value.
     */
    public void setAUVNSI(String newvalue) {
        fieldAUVNSI.setString(newvalue);
    }

    /**
     * Get value of field AUVNSI as a String.
     */
    public String getAUVNSI() {
        return fieldAUVNSI.getString();
    }

    /**
     * Set numeric field AUVNSI using a BigDecimal value.
     */
    public void setAUVNSI(BigDecimal newvalue) {
        fieldAUVNSI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field AUVNSI as a BigDecimal.
     */
    public BigDecimal getBigDecimalAUVNSI() {
        return fieldAUVNSI.getBigDecimal();
    }

    /**
     * Set field VLOCAT using a String value.
     */
    public void setVLOCAT(String newvalue) {
        fieldVLOCAT.setString(newvalue);
    }

    /**
     * Get value of field VLOCAT as a String.
     */
    public String getVLOCAT() {
        return fieldVLOCAT.getString();
    }

    /**
     * Set field VLOMAM using a String value.
     */
    public void setVLOMAM(String newvalue) {
        fieldVLOMAM.setString(newvalue);
    }

    /**
     * Get value of field VLOMAM as a String.
     */
    public String getVLOMAM() {
        return fieldVLOMAM.getString();
    }

    /**
     * Set field VLOFIS using a String value.
     */
    public void setVLOFIS(String newvalue) {
        fieldVLOFIS.setString(newvalue);
    }

    /**
     * Get value of field VLOFIS as a String.
     */
    public String getVLOFIS() {
        return fieldVLOFIS.getString();
    }

    /**
     * Set numeric field VLOFIS using a BigDecimal value.
     */
    public void setVLOFIS(BigDecimal newvalue) {
        fieldVLOFIS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOFIS as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOFIS() {
        return fieldVLOFIS.getBigDecimal();
    }

    /**
     * Set field NOMEMI using a String value.
     */
    public void setNOMEMI(String newvalue) {
        fieldNOMEMI.setString(newvalue);
    }

    /**
     * Get value of field NOMEMI as a String.
     */
    public String getNOMEMI() {
        return fieldNOMEMI.getString();
    }

    /**
     * Set field VLOSE1 using a String value.
     */
    public void setVLOSE1(String newvalue) {
        fieldVLOSE1.setString(newvalue);
    }

    /**
     * Get value of field VLOSE1 as a String.
     */
    public String getVLOSE1() {
        return fieldVLOSE1.getString();
    }

    /**
     * Set numeric field VLOSE1 using a BigDecimal value.
     */
    public void setVLOSE1(BigDecimal newvalue) {
        fieldVLOSE1.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOSE1 as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOSE1() {
        return fieldVLOSE1.getBigDecimal();
    }

    /**
     * Set field VLOUDE using a String value.
     */
    public void setVLOUDE(String newvalue) {
        fieldVLOUDE.setString(newvalue);
    }

    /**
     * Get value of field VLOUDE as a String.
     */
    public String getVLOUDE() {
        return fieldVLOUDE.getString();
    }

    /**
     * Set numeric field VLOUDE using a BigDecimal value.
     */
    public void setVLOUDE(BigDecimal newvalue) {
        fieldVLOUDE.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUDE as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUDE() {
        return fieldVLOUDE.getBigDecimal();
    }

    /**
     * Set field VLOUCA using a String value.
     */
    public void setVLOUCA(String newvalue) {
        fieldVLOUCA.setString(newvalue);
    }

    /**
     * Get value of field VLOUCA as a String.
     */
    public String getVLOUCA() {
        return fieldVLOUCA.getString();
    }

    /**
     * Set numeric field VLOUCA using a BigDecimal value.
     */
    public void setVLOUCA(BigDecimal newvalue) {
        fieldVLOUCA.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUCA as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUCA() {
        return fieldVLOUCA.getBigDecimal();
    }

    /**
     * Set field VLOUNI using a String value.
     */
    public void setVLOUNI(String newvalue) {
        fieldVLOUNI.setString(newvalue);
    }

    /**
     * Get value of field VLOUNI as a String.
     */
    public String getVLOUNI() {
        return fieldVLOUNI.getString();
    }

    /**
     * Set numeric field VLOUNI using a BigDecimal value.
     */
    public void setVLOUNI(BigDecimal newvalue) {
        fieldVLOUNI.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOUNI as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOUNI() {
        return fieldVLOUNI.getBigDecimal();
    }

    /**
     * Set field VLOTAS using a String value.
     */
    public void setVLOTAS(String newvalue) {
        fieldVLOTAS.setString(newvalue);
    }

    /**
     * Get value of field VLOTAS as a String.
     */
    public String getVLOTAS() {
        return fieldVLOTAS.getString();
    }

    /**
     * Set numeric field VLOTAS using a BigDecimal value.
     */
    public void setVLOTAS(BigDecimal newvalue) {
        fieldVLOTAS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOTAS as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOTAS() {
        return fieldVLOTAS.getBigDecimal();
    }

    /**
     * Set field AUVDEC using a String value.
     */
    public void setAUVDEC(String newvalue) {
        fieldAUVDEC.setString(newvalue);
    }

    /**
     * Get value of field AUVDEC as a String.
     */
    public String getAUVDEC() {
        return fieldAUVDEC.getString();
    }

    /**
     * Set field AUVNEI using a String value.
     */
    public void setAUVNEI(String newvalue) {
        fieldAUVNEI.setString(newvalue);
    }

    /**
     * Get value of field AUVNEI as a String.
     */
    public String getAUVNEI() {
        return fieldAUVNEI.getString();
    }

    /**
     * Set field AUVSIN using a String value.
     */
    public void setAUVSIN(String newvalue) {
        fieldAUVSIN.setString(newvalue);
    }

    /**
     * Get value of field AUVSIN as a String.
     */
    public String getAUVSIN() {
        return fieldAUVSIN.getString();
    }

    /**
     * Set field VLODIV using a String value.
     */
    public void setVLODIV(String newvalue) {
        fieldVLODIV.setString(newvalue);
    }

    /**
     * Get value of field VLODIV as a String.
     */
    public String getVLODIV() {
        return fieldVLODIV.getString();
    }

    /**
     * Set numeric field VLODIV using a BigDecimal value.
     */
    public void setVLODIV(BigDecimal newvalue) {
        fieldVLODIV.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLODIV as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLODIV() {
        return fieldVLODIV.getBigDecimal();
    }

    /**
     * Set field DIVNOM using a String value.
     */
    public void setDIVNOM(String newvalue) {
        fieldDIVNOM.setString(newvalue);
    }

    /**
     * Get value of field DIVNOM as a String.
     */
    public String getDIVNOM() {
        return fieldDIVNOM.getString();
    }

    /**
     * Set field VLOTFO using a String value.
     */
    public void setVLOTFO(String newvalue) {
        fieldVLOTFO.setString(newvalue);
    }

    /**
     * Get value of field VLOTFO as a String.
     */
    public String getVLOTFO() {
        return fieldVLOTFO.getString();
    }

    /**
     * Set numeric field VLOTFO using a BigDecimal value.
     */
    public void setVLOTFO(BigDecimal newvalue) {
        fieldVLOTFO.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOTFO as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOTFO() {
        return fieldVLOTFO.getBigDecimal();
    }

    /**
     * Set field NOMPAI using a String value.
     */
    public void setNOMPAI(String newvalue) {
        fieldNOMPAI.setString(newvalue);
    }

    /**
     * Get value of field NOMPAI as a String.
     */
    public String getNOMPAI() {
        return fieldNOMPAI.getString();
    }

    /**
     * Set field AUVCUS using a String value.
     */
    public void setAUVCUS(String newvalue) {
        fieldAUVCUS.setString(newvalue);
    }

    /**
     * Get value of field AUVCUS as a String.
     */
    public String getAUVCUS() {
        return fieldAUVCUS.getString();
    }

    /**
     * Set numeric field AUVCUS using a BigDecimal value.
     */
    public void setAUVCUS(BigDecimal newvalue) {
        fieldAUVCUS.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field AUVCUS as a BigDecimal.
     */
    public BigDecimal getBigDecimalAUVCUS() {
        return fieldAUVCUS.getBigDecimal();
    }

    /**
     * Set field NOMCUS using a String value.
     */
    public void setNOMCUS(String newvalue) {
        fieldNOMCUS.setString(newvalue);
    }

    /**
     * Get value of field NOMCUS as a String.
     */
    public String getNOMCUS() {
        return fieldNOMCUS.getString();
    }

    /**
     * Set field VLOPIN using a String value.
     */
    public void setVLOPIN(String newvalue) {
        fieldVLOPIN.setString(newvalue);
    }

    /**
     * Get value of field VLOPIN as a String.
     */
    public String getVLOPIN() {
        return fieldVLOPIN.getString();
    }

    /**
     * Set numeric field VLOPIN using a BigDecimal value.
     */
    public void setVLOPIN(BigDecimal newvalue) {
        fieldVLOPIN.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOPIN as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOPIN() {
        return fieldVLOPIN.getBigDecimal();
    }

    /**
     * Set field AUVCER using a String value.
     */
    public void setAUVCER(String newvalue) {
        fieldAUVCER.setString(newvalue);
    }

    /**
     * Get value of field AUVCER as a String.
     */
    public String getAUVCER() {
        return fieldAUVCER.getString();
    }

    /**
     * Set numeric field AUVCER using a BigDecimal value.
     */
    public void setAUVCER(BigDecimal newvalue) {
        fieldAUVCER.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field AUVCER as a BigDecimal.
     */
    public BigDecimal getBigDecimalAUVCER() {
        return fieldAUVCER.getBigDecimal();
    }

    /**
     * Set field VLOTIP using a String value.
     */
    public void setVLOTIP(String newvalue) {
        fieldVLOTIP.setString(newvalue);
    }

    /**
     * Get value of field VLOTIP as a String.
     */
    public String getVLOTIP() {
        return fieldVLOTIP.getString();
    }

    /**
     * Set field VLOSPR using a String value.
     */
    public void setVLOSPR(String newvalue) {
        fieldVLOSPR.setString(newvalue);
    }

    /**
     * Get value of field VLOSPR as a String.
     */
    public String getVLOSPR() {
        return fieldVLOSPR.getString();
    }

    /**
     * Set numeric field VLOSPR using a BigDecimal value.
     */
    public void setVLOSPR(BigDecimal newvalue) {
        fieldVLOSPR.setBigDecimal(newvalue);
    }

    /**
     * Return value of numeric field VLOSPR as a BigDecimal.
     */
    public BigDecimal getBigDecimalVLOSPR() {
        return fieldVLOSPR.getBigDecimal();
    }

}
