--DROP PROCEDURE GPSQLWEB.procCreateUserProfile
    
CREATE PROCEDURE GPSQLWEB.procCreateUserProfile
(
    IN P_USERNAME VARCHAR(128),
    IN P_DOCUMENT_NUMBER VARCHAR(10),
    IN P_FIRST_NAME VARCHAR(128),
    IN P_SECOND_NAME VARCHAR(128),
    IN P_LAST_NAME VARCHAR(128),
    IN P_SECOND_LAST_NAME VARCHAR(128),
    IN P_GENDER VARCHAR(1),
    IN P_CIVIL_STATUS VARCHAR(1),
    IN P_EMAIL VARCHAR(128),
    IN P_PHONE VARCHAR(20),
    IN P_MOBILE VARCHAR(20),
    IN P_BIRTHDAY DATE,
    IN P_ENABLED VARCHAR(1),                
    IN P_USER VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_ID INTEGER
)
LANGUAGE SQL
BEGIN
	Declare StringSQL Varchar(32000) Default '';
	Declare FullName VARCHAR(45) Default '';
        Declare Existe INTEGER Default 0;

        Set FullName = P_FIRST_NAME || ' ' || P_LAST_NAME;
	Set StringSQL = 'INSERT INTO GPSQLWEB.USER_PROFILE (USERNAME, DOCUMENT_NUMBER, FIRST_NAME, SECOND_NAME, LAST_NAME, SECOND_LAST_NAME, GENDER, CIVIL_STATUS, EMAIL, PHONE, MOBILE, BIRTHDAY, ENABLED, DELETED, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY) VALUES (?, ?, ? ,? ,? , ?, ?, ?, ?, ?, ?, ?, ?, ''N'', CURRENT_TIMESTAMP, ?, NULL , NULL )';

	PREPARE stmt FROM StringSQL;
	EXECUTE stmt USING P_USERNAME, P_DOCUMENT_NUMBER, P_FIRST_NAME, P_SECOND_NAME, P_LAST_NAME, P_SECOND_LAST_NAME, P_GENDER, P_CIVIL_STATUS ,P_EMAIL, P_PHONE, P_MOBILE, P_BIRTHDAY, P_ENABLED, P_USER;

	SELECT IDENTITY_VAL_LOCAL() AS LASTID INTO P_ID FROM SYSIBM.SYSDUMMY1;
    	
        -- Este Query es para la auditoria
        Set StringSQL = 'INSERT INTO GPSQLWEB.USER_PROFILE (USERNAME ,DOCUMENT_NUMBER ,FIRST_NAME ,SECOND_NAME ,LAST_NAME ,SECOND_LAST_NAME ,GENDER ,CIVIL_STATUS ,EMAIL ,PHONE ,MOBILE ,BIRTHDAY ,ENABLED ,DELETED ,CREATED_AT ,CREATED_BY ,UPDATED_AT ,UPDATED_BY ) VALUES ( '''
        	|| P_USERNAME || ''' , '''|| P_DOCUMENT_NUMBER || ''' , '''|| P_FIRST_NAME || ''' , '''|| P_SECOND_NAME || ''' , '''|| P_LAST_NAME || ''' , '''|| P_SECOND_LAST_NAME || ''' , '''|| P_GENDER || ''' , '''|| P_CIVIL_STATUS || ''' , '''|| P_EMAIL || ''' , '''|| P_PHONE || ''' , '''|| P_MOBILE || ''' , '''|| varchar(P_BIRTHDAY) || ''' , '''|| P_ENABLED || ''' , ''N'' , '''|| VARCHAR_FORMAT(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') || ''' , '''|| P_USER || ''' ,NULL , NULL )';
         
	CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USER, 'Crear', 'procCreateUserProfile', StringSQL);
	
        -- Crear el usuario de pantalla verde
        SELECT COUNT(1) INTO Existe FROM GPDATBAAG.Perfil WHERE PRFPRF = P_USERNAME;

        IF (Existe = 0) THEN
            Set StringSQL = 'INSERT INTO GPDATBAAG.Perfil (PRFPRF, PRFNOM, PRFCED) VALUES (?, ?, ?)';
            PREPARE stmt FROM StringSQL;
            EXECUTE stmt USING P_USERNAME, FullName, P_DOCUMENT_NUMBER;
            CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USER, 'Crear', 'procCreateUserProfile', StringSQL);
        END IF;

END
