CREATE TABLE "GPDATWEB"."AA2FEC" (
		"FECHA" NUMERIC(6 , 0) NOT NULL,
		"FECNRR" DECIMAL(5 , 0) NOT NULL,
		"FECNOM" CHAR(8) CCSID 284 NOT NULL,
		"FECCOD" NUMERIC(1 , 0) NOT NULL,
		"FECBL1" CHAR(6) CCSID 284 NOT NULL,
		"FECINA" DECIMAL(9 , 7) NOT NULL,
		"FECINB" DECIMAL(9 , 7) NOT NULL,
		"FECINC" DECIMAL(9 , 7) NOT NULL,
		"FECIND" DECIMAL(9 , 7) NOT NULL,
		"FECINE" DECIMAL(9 , 7) NOT NULL,
		"FECING" DECIMAL(9 , 7) NOT NULL,
		"FECFIE" CHAR(30) CCSID 284 NOT NULL,
		"FECAMD" NUMERIC(8 , 0) NOT NULL
	);

LABEL ON TABLE "GPDATWEB"."AA2FEC" IS
'Calendario';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECHA" IS
'DDMMAA';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECHA" TEXT IS
'DDMMAA';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECNRR" IS
'JULIANO';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECNRR" TEXT IS
'JULIANO';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECNOM" IS
'NOMBRE DEL DIA';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECNOM" TEXT IS
'NOMBRE DEL DIA';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECCOD" IS
'0=NO CONT.1=SI';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECCOD" TEXT IS
'0=NO CONT.1=SI';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECBL1" IS
'BLANCOS';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECBL1" TEXT IS
'BLANCOS';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECINA" IS
'INTERES BASICO =A';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECINA" TEXT IS
'INTERES BASICO =A';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECINB" IS
'INTERES BASICO =B';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECINB" TEXT IS
'INTERES BASICO =B';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECINC" IS
'INTERES BASICO =C';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECINC" TEXT IS
'INTERES BASICO =C';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECIND" IS
'INTERES BASICO =D';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECIND" TEXT IS
'INTERES BASICO =D';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECINE" IS
'INTERES BASICO =E';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECINE" TEXT IS
'INTERES BASICO =E';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECING" IS
'INTERES BASICO =G';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECING" TEXT IS
'INTERES BASICO =G';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECFIE" IS
'SERIE FIESTAS';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECFIE" TEXT IS
'SERIE FIESTAS';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECAMD" IS
'FECHA AAAAMMDD';

LABEL ON COLUMN "GPDATWEB"."AA2FEC"."FECAMD" TEXT IS
'FECHA AAAAMMDD';


