CREATE TABLE "GPDATWEB"."CARFIUSF" (
		"USUARF" CHAR(10) CCSID 284 NOT NULL,
		"TIPO" DECIMAL(2 , 0) NOT NULL,
		"FECGRA" DECIMAL(8 , 0) NOT NULL,
		"PANTAL" CHAR(10) CCSID 284 NOT NULL,
		"HORA" DECIMAL(6 , 0) NOT NULL,
                    "USARI" CHAR(10) CCSID 284 NOT NULL
	);

LABEL ON TABLE "GPDATWEB"."CARFIUSF" IS
'Autorizacion Usuarios por Tipo Fideicomiso';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."USUARF" IS
'USUARIO';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."USUARF" TEXT IS
'USUARIO';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."TIPO" IS
'TIPO FID.';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."TIPO" TEXT IS
'TIPO FID.';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."FECGRA" IS
'FECHA GRABACION';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."FECGRA" TEXT IS
'FECHA GRABACION';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."PANTAL" IS
'PANTALLA';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."PANTAL" TEXT IS
'PANTALLA';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."HORA" TEXT IS
'HORA';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."USARI" IS
'USUARIO GRA.';

LABEL ON COLUMN "GPDATWEB"."CARFIUSF"."USARI" TEXT IS
'USUARIO GRA.';



CREATE TABLE  `tesoreria`.`carfiusf` (
  `usuarf` varchar(10) NOT NULL,
  `tipo` decimal(2,0) NOT NULL,
  `fecgra` decimal(8,0) NOT NULL,
  `pantal` varchar(10) NOT NULL,
  `hora` decimal(6,0) NOT NULL,
  `usari` varchar(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;