--<ScriptOptions statementTerminator="GO"/>

SET SCHEMA GPDATWEB
GO
 
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(1, 'menu.welcome', 'default/home', '', 0, 0, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(2, 'menu.logout', 'auth/logout', '', 0, 99, 0, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(3, 'menu.principal', '#', '', 0, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(4, 'menu.operativa', '#', '', 0, 2, 0, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(5, 'menu.basicos', '#', '', 0, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(6, 'menu.seguridad', '#', '', 0, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(7, 'menu.setting', '#', '', 0, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(8, 'menu.aa2tpais', 'aa2tpais/list', '', 5, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(9, 'menu.webmenu', 'webmenu/list', ' ', 7, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(10, 'menu.user', 'perfil/list', 'PERFIL', 6, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(11, 'menu.principal.treasury', '#', '#', 3, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(12, 'menu.clapofid', 'call/pgm?programName=CLAPOFID', 'CLAPOFID', 11, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(13, 'menu.principal.investments', '#', '#', 3, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(14, 'menu.principal.investments.fixedrent', '#', '#', 13, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(15, 'menu.principal.investments.fixedrent.buysell', '#', '#', 14, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(16, 'menu.clvar136m', 'call/pgm?programName=CLVAR136M', 'CLVAR136M', 15, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(17, 'menu.tablehelp', 'tablehelp/list', '#', 7, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(18, 'menu.tabtc', 'tabtc/list', 'tabtc', 5, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(19, 'menu.aa2tfide', 'aa2tfide/list', '#', 6, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(20, 'menu.basicos.adminaccounting', '#', '#', 5, 15, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(21, 'menu.aa2tdiv', 'aa2tdiv/list', 'aa2tdiv', 20, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(22, 'menu.principal.clients', '#', '#', 3, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(23, 'menu.aa2mcli', 'aa2mcli/list', '#', 22, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(24, 'menu.aa2tipcl', 'aa2tipcl/list', '#', 20, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(25, '#', '#', '#', 0, 8, 0, 0)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(26, 'menu.tabta', 'tabta/list', 'tabta', 5, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(27, 'menu.tabte', 'tabte/list', 'tabte', 5, 14, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(28, 'menu.oficinas', 'oficinas/list', 'oficinas', 5, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(29, 'menu.tabfp', 'tabfp/list', '#', 5, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(30, 'menu.aa2tsect', 'aa2tsect/list', 'aa2tsect', 5, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(31, 'menu.tabntpa', 'tabntpa/list', '#', 20, 16, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(32, 'menu.tabtr', 'tabtr/list', '#', 5, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(33, 'menu.principal.accounting', '#', '#', 3, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(34, 'menu.principal.accounting.listings', '#', '#', 33, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(35, 'menu.principal.accounting.listings.dailycont', 'call/pgm?programName=CLLAPUNA22', 'CLLAPUNA22', 34, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(36, 'menu.aa2tpdto', 'aa2tpdto/list', 'aa2tpdto', 5, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(37, 'menu.principal.treasury.withdrawal', 'call/pgm?programName=CLRETFID', 'CLRETFID', 11, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(38, 'menu.tabtd', 'tabtd/list', 'tabtd', 5, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(39, 'menu.flucon', 'flucon/list', 'flucon', 11, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(40, 'menu.tabccli', 'tabccli/list', 'tabccli', 5, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(41, 'menu.aa2gesto', 'aa2gesto/list', 'aa2gesto', 20, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(42, 'menu.flucajg', 'call/pgm?programName=CLFLUCAJ', 'CLFLUCAJ', 11, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(43, 'menu.flucajrfm', 'call/pgm?programName=CLFLUCUR', 'CLFLUCUR', 11, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(44, 'menu.anarfi', 'call/pgm?programName=ANARFI', 'ANARFI', 11, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(45, 'menu.anarfib', 'call/pgm?programName=ANARFIB', 'ANARFIB', 11, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(46, 'menu.anarfid', 'call/pgm?programName=ANARFID', 'ANARFID', 11, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(47, 'menu.apofiffm', 'call/pgm?programName=CLAPOFIF', 'CLAPOFIF', 11, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(48, 'menu.retfiffm', 'call/pgm?programName=CLRETFIF', 'CLRETFIF', 11, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(49, 'menu.clcontr2', 'contrato/wizard', 'CLCONTR2', 11, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(50, 'menu.maxminfm', 'cgmaxmin/edit', 'MAXMIN', 141, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(51, 'menu.salminfm', 'contratoau/edit', 'SALMIN', 141, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(52, 'menu.contrato', 'contrato/list', 'contrato', 11, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(53, 'menu.datfidfm', 'call/pgm?programName=CLDATFID', 'CLDATFID', 11, 14, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(54, 'menu.principal.investments.portfolio', '#', '#', 13, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(55, 'menu.principal.investments.portfolio.divisa', 'aa2tdih/list', 'AA2TDIH', 54, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(56, 'menu.principal.investments.portfolio.valor', 'cotizacion/list', 'cotizacion', 54, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(57, 'menu.tabsdb', 'tabsdb/list', 'tabsdb', 54, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(58, 'menu.tabsb42', 'tabsb42/list', 'TABSB42', 54, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(59, 'menu.valora', 'valora/list', 'valora', 54, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(60, 'menu.dtdcta', 'dtdcta/list', 'dtdcta', 54, 14, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(61, 'menu.splfile', 'splfile/list', '#', 7, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(62, 'menu.cuentas', 'cuentas/list', 'cuentas', 22, 4, 0, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(63, 'menu.tabrf', 'tabrf/list', 'tabrf', 5, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(64, 'menu.aa2modal', 'aa2modal/list', 'aa2modal', 5, 19, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(65, 'menu.msgcode', 'msgcode/list', 'msgcode', 7, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(66, 'menu.aa2traid', 'aa2traid/list', 'aa2traid', 20, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(67, 'menu.clien1fm', 'call/pgm?programName=CLIEN1', 'CLIEN1', 22, 1, 0, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(68, 'menu.conclip', 'call/pgm?programName=CLCONCLIE', 'CONCLIP', 22, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(69, 'menu.reltit', 'call/pgm?programName=RELTIT', 'RELTIT', 14, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(70, 'menu.tipos', 'tipos/list', 'tipos', 6, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(71, 'menu.aa2taut', 'aa2taut/list', 'aa2taut', 6, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(72, 'menu.aa2cta', 'aa2cta/list', 'aa2cta', 20, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(73, 'menu.aa2fec', 'aa2fec/list', 'aa2fec', 5, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(74, 'menu.aa2tgru', 'aa2tgru/list', 'aa2tgru', 5, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(261, 'menu.principal.accounting.otherlistings', '#', '#', 33, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(76, 'menu.clreltit3', 'call/pgm?programName=CLRELTIT3', 'CLRELTIT3', 14, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(77, 'menu.var136fm', 'call/pgm?programName=VAR136', 'VAR136', 14, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(78, 'menu.var137fm', 'call/pgm?programName=CLVAR137', 'CLVAR137', 14, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(79, 'menu.clvari43', 'call/pgm?programName=CLVARI43', 'CLVARI43', 14, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(80, 'menu.var150', 'call/pgm?programName=VAR150', 'VAR150', 14, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(81, 'menu.invfid01', 'call/pgm?programName=INVFID01', 'INVFID01', 14, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(82, 'menu.aa2rete', 'aa2rete/list', 'aa2rete', 5, 18, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(83, 'menu.aa2ttpro', 'aa2ttpro/list', 'aa2ttpro', 20, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(84, 'menu.aa2tbder', 'aa2tbder/list', 'aa2tbder', 141, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(85, 'menu.aa2tesp', 'aa2tesp/list', 'aa2tesp', 141, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(86, 'menu.aa2balsi', 'aa2balsi/list', 'aa2balsi', 20, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(87, 'menu.aa2balss', 'aa2balss/list', 'aa2balss', 20, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(88, 'menu.aa2balxi', 'aa2balxi/list', 'aa2balxi', 20, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(89, 'menu.vari01n', 'call/pgm?programName=VARI01N', 'VARI01N', 54, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(90, 'menu.vari01cfm', 'call/pgm?programName=VARI01C', 'VARI01C', 54, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(91, 'menu.vari1cefm', 'call/pgm?programName=VARI01D', 'VARI01D', 54, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(92, 'menu.cafvvafm', 'call/pgm?programName=CAFVVA', 'CAFVVA', 54, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(93, 'menu.modvtocfm', 'call/pgm?programName=MODVTOC', 'MODVTOC', 54, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(94, 'menu.pborintfm', 'call/pgm?programName=PBORINT', 'PBORINT', 54, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(95, 'menu.clgp0036m', 'call/pgm?programName=CLGP0036M', 'CLGP0036M', 15, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(96, 'menu.renov2', 'call/pgm?programName=RENOV2', 'RENOV2', 15, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(97, 'menu.activo2', 'call/pgm?programName=ACTIVO2', 'ACTIVO2', 15, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(98, 'menu.clvar136m2', 'call/pgm?programName=CLVAR136M2', 'CLVAR136M2', 15, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(99, 'menu.clvar138m', 'call/pgm?programName=CLVAR138M', 'CLVAR138M', 15, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(100, 'menu.clgp0036f', 'call/pgm?programName=CLGP0036F', 'CLGP0036F', 15, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(101, 'menu.clgp0036e', 'call/pgm?programName=CLGP0036E', 'CLGP0036E', 15, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(102, 'menu.camodin', 'call/pgm?programName=CAMODIN', 'CAMODIN', 15, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(103, 'menu.valinv', 'call/pgm?programName=VALINV', 'VALINV', 15, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(104, 'menu.principal.investments.inquiries', '#', '#', 13, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(105, 'menu.conact', 'call/pgm?programName=CONACT', 'CONACT', 104, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(106, 'menu.clconinv', 'call/pgm?programName=CLCONINV', 'CLCONINV', 104, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(107, 'menu.conact1', 'conact1/list', 'CONACT1', 104, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(108, 'menu.principal.investments.listing', '#', '#', 13, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(109, 'menu.cllstvcto2', 'call/pgm?programName=CLLSTVCTO2', 'CLLSTVCTO2', 108, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(110, 'menu.cllcaract', 'call/pgm?programName=CLLCARACT', 'CLLCARACT', 108, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(111, 'menu.cllcaractd', 'call/pgm?programName=CLLCARACTD', 'CLLCARACTD', 108, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(112, 'menu.cllivace', 'call/pgm?programName=CLLIVACE', 'CLLIVACE', 108, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(113, 'menu.cllcarven', 'call/pgm?programName=CLLCARVEN', 'CLLCARVEN', 108, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(114, 'menu.cllcarvend', 'call/pgm?programName=CLLCARVEND', 'CLLCARVEND', 108, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(115, 'menu.cllcart102', 'call/pgm?programName=CLLCART102', 'CLLCART102', 108, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(116, 'menu.cllisinac', 'call/pgm?programName=CLLISINAC', 'CLLISINAC', 108, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(117, 'menu.cllisinem', 'call/pgm?programName=CLLISINEM', 'CLLISINEM', 108, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(118, 'menu.clvalor01', 'call/pgm?programName=CLVALOR01', 'CLVALOR01', 108, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(119, 'menu.clvalor02', 'call/pgm?programName=CLVALOR02', 'CLVALOR02', 108, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(120, 'menu.recove', 'call/pgm?programName=RECOVE', 'RECOVE', 108, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(121, 'menu.diario', 'call/pgm?programName=DIARIO', 'DIARIO', 108, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(122, 'menu.gespanjg', 'call/pgm?programName=GESPANJG', 'GESPANJG', 33, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(123, 'menu.gespanjg1', 'call/pgm?programName=GESPANJG1', 'GESPANJG1', 33, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(124, 'menu.gesal1', 'call/pgm?programName=GESAL1', 'GESAL1', 33, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(125, 'menu.clgesal2', 'call/pgm?programName=CLGESAL2', 'CLGESAL2', 33, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(126, 'menu.conapre', 'call/pgm?programName=CONAPRE', 'CONAPRE', 33, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(127, 'menu.aa2tconc', 'aa2tconc/list', 'aa2tconc', 20, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(128, 'menu.aa2tope', 'aa2tope/list', 'aa2tope', 20, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(129, 'menu.aa2coope', 'aa2coope/listGroupBy', 'aa2coope', 20, 15, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(130, 'menu.aa2toc', 'aa2toc/list', 'aa2toc', 20, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(131, 'menu.aa2amp', 'aa2amp/list', 'aa2amp', 20, 14, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(132, 'menu.aa2ato', 'aa2ato/list', 'aa2ato', 6, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(133, 'menu.aa2atoh', 'aa2atoh/list', 'aa2atoh', 6, 6, 0, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(134, 'menu.fctlcon', 'fctlcon/list', 'fctlcon', 6, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(135, 'menu.aa2cab', 'aa2cab/list', 'aa2cab', 6, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(136, 'menu.aa2cab1', 'aa2cab1/list', 'aa2cab1', 6, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(137, 'menu.gpbasi2', 'gpbasi2/list', 'gpbasi2', 6, 10, 0, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(138, 'menu.aa2emiso', 'aa2emiso/list', 'aa2emiso', 54, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(139, 'menu.tabsex', 'tabsex/list', 'tabsex', 5, 20, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(140, 'menu.aa2cocor', 'aa2cocor/list', 'aa2cocor', 5, 23, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(141, 'menu.basicos.comisiones', '#', 'comisiones', 5, 17, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(142, 'menu.cllapun', 'call/pgm?programName=CLLAPUN', 'CLLAPUN', 34, 0, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(143, 'menu.cllapuna21', 'call/pgm?programName=CLLAPUNA21', 'CLLAPUNA21', 34, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(144, 'menu.cllapuna22', 'call/pgm?programName=CLLAPUNA22', 'CLLAPUNA22', 34, 2, 0, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(145, 'menu.cllapunat3', 'call/pgm?programName=CLLAPUNAT3', 'CLLAPUNAT3', 34, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(146, 'menu.cllapunat2', 'call/pgm?programName=CLLAPUNAT2', 'CLLAPUNAT2', 34, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(147, 'menu.clemlifi', 'call/pgm?programName=CLEMLIFI', 'CLEMLIFI', 34, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(148, 'menu.cllauxmes', 'call/pgm?programName=CLLAUXMES', 'CLLAUXMES', 34, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(149, 'menu.cllauxme7', 'call/pgm?programName=CLLAUXME7', 'CLLAUXME7', 34, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(150, 'menu.cllimoct', 'call/pgm?programName=CLLIMOCT', 'CLLIMOCT', 34, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(151, 'menu.clbalsf5', 'call/pgm?programName=CLBALSF5', 'CLBALSF5', 34, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(152, 'menu.clbalsf6', 'call/pgm?programName=CLBALSF6', 'CLBALSF6', 34, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(153, 'menu.clbalsf2', 'call/pgm?programName=CLBALSF2', 'CLBALSF2', 34, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(154, 'menu.clbalsf3', 'call/pgm?programName=CLBALSF3', 'CLBALSF3', 34, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(155, 'menu.clbalss2', 'call/pgm?programName=CLBALSS2', 'CLBALSS2', 34, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(156, 'menu.clbalsf7', 'call/pgm?programName=CLBALSF7', 'CLBALSF7', 34, 14, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(157, 'menu.clbalsf4', 'call/pgm?programName=CLBALSF4', 'CLBALSF4', 34, 15, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(158, 'menu.clbalsfs', 'call/pgm?programName=CLBALSFS', 'CLBALSFS', 34, 16, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(159, 'menu.clbalsit0', 'call/pgm?programName=CLBALSIT0', 'CLBALSIT0', 34, 17, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(160, 'menu.aa2copo', 'aa2copo/listByCopCod', 'aa2copo', 5, 21, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(161, 'menu.aa2copo1', 'aa2copo/list', 'aa2copo1', 5, 22, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(162, 'menu.tabcf', 'tabcf/list', 'tabcf', 141, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(163, 'menu.menu171', '#', '#', 33, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(164, 'menu.clinpmov', 'call/pgm?programName=CLINPMOV', 'CLINPMOV', 163, 0, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(165, 'menu.findiasald', 'call/pgm?programName=FINDIASALD', 'FINDIASALD', 163, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(166, 'menu.clbalsf4e', 'call/pgm?programName=CLBALSF4E', 'CLBALSF4E', 163, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(167, 'menu.clmodcta', 'call/pgm?programName=CLMODCTA', 'CLMODCTA', 163, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(168, 'menu.ctacab', 'call/pgm?programName=CTACAB', 'CTACAB', 163, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(169, 'menu.clciemes', 'call/pgm?programName=CLCIEMES', 'CLCIEMES', 163, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(170, 'menu.clseme', 'call/pgm?programName=CLSEME', 'CLSEME', 163, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(171, 'menu.cllicofi', 'call/pgm?programName=CLLICOFI', 'CLLICOFI', 163, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(172, 'menu.clcalcomi', 'call/pgm?programName=CLCALCOMI', 'CLCALCOMI', 163, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(173, 'menu.clgenapu', 'call/pgm?programName=CLGENAPU', 'CLGENAPU', 163, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(174, 'menu.camfeco', 'call/pgm?programName=CAMFECO', 'CAMFECO', 163, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(175, 'menu.crecon', 'call/pgm?programName=CRECON', 'CRECON', 163, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(176, 'menu.clmovcta', 'call/pgm?programName=CLMOVCTA', 'CLMOVCTA', 34, 17, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(177, 'menu.clmovctag', 'call/pgm?programName=CLMOVCTAG', 'CLMOVCTAG', 34, 18, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(178, 'menu.clmovct4', 'call/pgm?programName=CLMOVCT4', 'CLMOVCT4', 34, 19, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(179, 'menu.clresulta3', 'call/pgm?programName=CLRESULTA3', 'CLRESULTA3', 34, 20, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(180, 'menu.clresulta', 'call/pgm?programName=CLRESULTA', 'CLRESULTA', 34, 21, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(181, 'menu.cllisaum', 'call/pgm?programName=CLLISAUM', 'CLLISAUM', 34, 22, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(182, 'menu.clbacomco', 'call/pgm?programName=CLBACOMCO', 'CLBACOMCO', 34, 23, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(183, 'menu.cllisecu', 'call/pgm?programName=CLLISECU', 'CLLISECU', 34, 24, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(184, 'menu.cllsdibs', 'call/pgm?programName=CLLSDIBS', 'CLLSDIBS', 34, 25, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(185, 'menu.clcerislr', 'call/pgm?programName=CLCERISLR', 'CLCERISLR', 34, 26, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(186, 'menu.cllfoncli', 'call/pgm?programName=CLLFONCLI', 'CLLFONCLI', 34, 27, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(187, 'menu.menu14', '#', '#', 3, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(188, 'menu.embargos', 'embargos/list', 'CLEMBARG', 187, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(189, 'menu.clprocomfc', 'call/pgm?programName=CLPROCOMFC', 'CLPROCOMFC', 187, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(190, 'menu.clvalfc', 'call/pgm?programName=CLVALFC', 'CLVALFC', 187, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(191, 'menu.clvalpvc', 'call/pgm?programName=CLVALPVC', 'CLVALPVC', 187, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(192, 'menu.clconbene', 'call/pgm?programName=CLCONBENE', 'CLCONBENE', 187, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(193, 'menu.clrepben2', 'call/pgm?programName=CLREPBEN2', 'CLREPBEN2', 187, 14, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(194, 'menu.clpagben', 'call/pgm?programName=CLPAGBEN', 'CLPAGBEN', 187, 15, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(195, 'menu.confce', 'call/pgm?programName=CONFCE', 'CONFCE', 187, 16, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(196, 'menu.aa2tabco', 'aa2tabco/list', 'aa2tabco', 141, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(197, 'menu.tabper', 'tabper/list', 'tabper', 141, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(198, 'menu.aa2tfis', 'aa2tfis/list', 'aa2tfis', 141, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(199, 'menu.aa2comi', 'aa2comi/edit', 'aa2comi', 141, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(200, 'menu.aa2tprcl', 'aa2tprcl/list', 'aa2tprcl', 20, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(201, 'menu.principal.investments.varrent', '#', '#', 13, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(202, 'menu.clvari02', 'call/pgm?programName=CLVARI02', 'CLVARI02', 201, 0, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(203, 'menu.clvalvar', 'call/pgm?programName=CLVALVAR', 'CLVALVAR', 201, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(204, 'menu.cobdiv', 'call/pgm?programName=COBDIV', 'COBDIV', 201, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(205, 'menu.aptacc', 'call/pgm?programName=APTACC', 'APTACC', 201, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(206, 'menu.cllisacc', 'call/pgm?programName=CLLISACC', 'CLLISACC', 201, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(207, 'menu.cupamort', 'cupamort/valora', 'cupamort', 54, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(262, 'menu.creran', 'creran/list', 'creran', 33, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(209, 'menu.menu142', '#', '#', 187, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(210, 'menu.menu143', '#', '#', 187, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(211, 'menu.menu145', '#', '#', 187, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(212, 'menu.menu146', '#', '#', 187, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(213, 'menu.menu147', '#', '#', 187, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(214, 'menu.menu141', '#', '#', 187, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(220, 'menu.clcontpso', 'contrato/colectivo', 'CLCONTPSO', 214, 0, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(221, 'menu.cldatfid', 'call/pgm?programName=CLDATFID', 'CLDATFID', 214, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(222, 'menu.clbajben', 'call/pgm?programName=CLBAJBEN', 'CLBAJBEN', 214, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(223, 'menu.clactcli', 'call/pgm?programName=CLACTCLI', 'CLACTCLI', 214, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(224, 'menu.clgpprpm02', 'call/pgm?programName=CLGPPRPM02', 'CLGPPRPM02', 214, 16, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(225, 'menu.clgpprpm03', 'call/pgm?programName=CLGPPRPM03', 'CLGPPRPM03', 214, 17, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(226, 'menu.gpprpm04', 'call/pgm?programName=GPPRPM04', 'GPPRPM04', 214, 18, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(227, 'menu.clrecapom', 'call/pgm?programName=CLRECAPOM', 'CLRECAPOM', 209, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(228, 'menu.clanuapo', 'call/pgm?programName=CLANUAPO', 'CLANUAPO', 209, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(247, 'menu.productos', 'productos/list', 'productos', 141, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(230, 'menu.clconcantb', 'call/pgm?programName=CLCONCANTB', 'CLCONCANTB', 210, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(231, 'menu.cldevoanti', 'call/pgm?programName=CLDEVOANTI', 'CLDEVOANTI', 210, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(232, 'menu.clacepblo', 'call/pgm?programName=CLACEPBLO', 'CLACEPBLO', 211, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(233, 'menu.clcanblo', 'call/pgm?programName=CLCANBLO', 'CLCANBLO', 211, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(234, 'menu.menu148', '#', '#', 187, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(235, 'menu.clacepgrt', 'call/pgm?programName=CLACEPGRT', 'CLACEPGRT', 234, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(236, 'menu.clanugrt1', 'call/pgm?programName=CLANUGRT1', 'CLANUGRT1', 234, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(237, 'menu.clconfbe', 'call/pgm?programName=CLCONFBE', 'CLCONFBE', 212, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(238, 'menu.petofi', 'call/pgm?programName=PETOFI', 'PETOFI', 212, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(239, 'menu.conmov', 'call/pgm?programName=CONMOV', 'CONMOV', 212, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(240, 'menu.cotfondo', 'cotfondo/list', 'CONCOTFON', 212, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(241, 'menu.cllipocl', 'call/pgm?programName=CLLIPOCL', 'CLLIPOCL', 213, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(242, 'menu.cllclifid', 'call/pgm?programName=CLLCLIFID', 'CLLCLIFID', 213, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(243, 'menu.clpetofi1', 'call/pgm?programName=CLPETOFI1', 'CLPETOFI1', 213, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(244, 'menu.clestctiv', 'call/pgm?programName=CLESTCTIV', 'CLESTCTIV', 213, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(245, 'menu.cllfoncli', 'call/pgm?programName=CLLFONCLI', 'CLLFONCLI', 213, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(246, 'menu.gpprpopc', 'gpprpopc/list', 'gpprpopc', 214, 19, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(248, 'menu.aa2proco', 'aa2proco/list', 'aa2proco', 141, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(249, 'menu.cltiposmnu', 'cltiposmnu/list', 'cltiposmnu', 6, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(250, 'menu.clfinfon', 'clfinfon/list', 'clfinfon', 6, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(252, 'menu.depu02', 'depu02/list', 'depu02', 6, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(253, 'menu.clbanes01', 'clbanes01/list', 'clbanes01', 6, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(254, 'menu.clareas', 'clareas/list', 'clareas', 6, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(255, 'menu.caming', 'caming/list', 'caming', 6, 14, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(256, 'menu.movare', 'movare/list', 'caming', 6, 15, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(257, 'menu.menu32', 'menu32/list', 'menu32', 5, 16, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(258, 'menu.carpro', 'call/pgm?programName=CARPRO', 'CARPRO', 141, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(259, 'menu.crecta6', 'crecta6/list', 'crecta6', 22, 2, 0, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(260, 'menu.apoderad', 'apoderad/list', 'apoderad', 11, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(263, 'menu.mantconta', 'mantconta/list', 'mantconta', 163, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(264, 'menu.actcli2', 'actcli2/list', 'actcli2', 214, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(265, 'menu.fincol', 'fincol/list', 'fincol', 214, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(266, 'menu.clrevcli', 'clrevcli/list', 'clrevcli', 214, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(267, 'menu.clcamcli', 'clcamcli/list', 'clcamcli', 214, 7, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(268, 'menu.borcli', 'borcli/list', 'borcli', 214, 8, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(269, 'menu.camclies', 'camclies/list', 'camclies', 214, 9, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(270, 'menu.calcoti', 'calcoti/list', 'calcoti', 214, 10, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(271, 'menu.clrevcol', 'clrevcol/list', 'clrevcol', 214, 11, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(272, 'menu.cllbenapa', 'cllbenapa/list', 'cllbenapa', 214, 12, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(273, 'menu.clcueban', 'clcueban/list', 'clcueban', 214, 13, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(274, 'menu.modmov', 'modmov/list', 'modmov', 214, 14, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(275, 'menu.clreingre', 'clreingre/list', 'clreingre', 214, 15, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(276, 'menu.clapotros', 'clapotros/list', 'clapotros', 209, 1, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(277, 'menu.clapt', 'clapt/list', 'clapt', 209, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(278, 'menu.clapdisk', 'clapdisk/list', 'clapdisk', 209, 3, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(279, 'menu.clanublo', 'clanublo/list', 'clanublo', 211, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(280, 'menu.clanublo1', 'clanublo1/list', 'clanublo1', 211, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(281, 'menu.clcangrt', 'clcangrt/list', 'clcangrt', 234, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(282, 'menu.clanugrt', 'clanugrt/list', 'clanugrt', 234, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(283, 'menu.clcofico', 'clcofico/list', 'clcofico', 212, 2, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(284, 'menu.clcofifi', 'clcofifi/list', 'clcofifi', 212, 5, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(285, 'menu.clconfbb', 'clconfbb/list', 'clconfbb', 212, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(286, 'menu.cllstmov', 'cllstmov/list', 'cllstmov', 213, 4, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(287, 'menu.clestcct', 'clestcct/list', 'clestcct', 213, 6, 1, 1)
GO
INSERT INTO WEBMENU(ID, NAME, URL, PGM, PARENTID, ORDERS, STATUSID, ISMENU)
  VALUES(288, 'menu.cllisclvme', 'cllisclvme/list', 'cllisclvme', 213, 8, 1, 1)
GO
