--<ScriptOptions statementTerminator="GO"/>

SET SCHEMA GPDATWEB
GO
 
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(1, '01', 'Tipos de Fideicomisos', 'GPDATWEB.TIPOSFID', 'FIDTIP', 'FIDTXT', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(2, '02', 'Divisas', 'GPDATWEB.AA2TDIV', 'DIVCLA', 'DIVNOM', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(3, '03', 'Perfiles de usuarios', 'GPDATPRUB.TIPOS', 'TIPO', 'TIPDES', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(4, '04', 'Tipo/Clasif. de Cliente', 'GPDATWEB.AA2TIPCL', 'TICCLA', 'TICNOM', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(5, '05', 'Categoria de Cliente', 'GPDATWEB.TABCCLI', 'CODIGO', 'TEXTO', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(6, '06', 'Estados', 'GPDATWEB.AA2COPO', 'COPCOD', 'COPNOM', 'COPCO1')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(7, '07', 'Municipio/codigo postal', 'GPDATWEB.AA2COPO', 'substring(REPEAT(''0'',7-LENGTH(RTRIM(CAST(COPCO1 AS CHAR(7)))))||RTRIM(CAST(COPCO1 AS CHAR(7))),1,2)', 'COPNOM', 'COPCO1 <> 0 and COPCOD')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(8, '08', 'Codigo Ejecutivo ', 'GPDATWEB.AA2GESTO', 'substring(GESCLA, 14, 2)', 'GESNOM', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(9, '09', 'Zona Geografica', 'GPDATWEB.AA2TPAIS', 'PAICLA', 'TRIM(SUBSTRING(PAINOM, 1, 25))', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(10, '10', 'Tipo de Aporte', 'GPDATWEB.TABTA', 'CODIGO', 'TEXTO', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(11, '11', 'Tipo de Contrato', 'GPDATWEB.TABTC', 'CODIG2', 'TEXTO', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(12, '12', 'Tipo de Deposito', 'GPDATWEB.TABTD ', 'CODIGO', 'TEXTO', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(13, '13', 'Forma de Pago', 'GPDATWEB.TABFP', 'CODIGO', 'TEXTO', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(14, '14', 'Codigo de Transaccion', 'GPDATWEB.FLUCON', 'FLCCOD', 'FLCCON', 'FLCTIP=''I''  AND 1')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(15, '15', 'Tipo de Retiro', 'GPDATWEB.TABTR', 'CODIGO', 'TEXTO', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(16, '16', 'CLIENTES', 'GPDATWEB.AA2MCLI', 'CLIASO', 'CLINOM', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(17, '17', 'Areas', 'GPDATWEB.aa2tfide', 'TRIM(FIDCLA)', 'FIDNOM', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(18, '18', 'Activos', 'GPDATWEB.VALORA', 'VLOCOA', 'VLONOM', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(19, '19', 'Operaciones', 'gpdatweb.INVERS', 'INVNOP', 'INVVAL || '' '' ||  INVEFI || '' '' || INVINT || '' '' || INVVTE ', 'INVEMP=''TE'' AND INVDEL=''SO'' AND INVANU<>''*'' AND INVCLI')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(20, '20', 'Tipo de Activo ', 'GPDATWEB.AA2TGRU', 'GRUCLA', 'GRUNOM', 'GRUEMP=''BA'' and GRUDEL=''SE'' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(21, '21', 'Tipos de Sectores', 'GPDATWEB.AA2TSECT', 'SECCLA', 'SECNOM', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(22, '22', 'Tipo de Emisores', 'GPDATWEB.TABTE', 'CODIGO', 'TEXTO', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(23, '23', 'Codigo Corporativo', 'gpdatweb.AA2COCOR', 'CODCOR', 'CODNOM', 'CODARE')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(24, '24', 'Emisores', 'gpdatweb.aa2emiso', 'EMICLA', 'EMINOM', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(25, '25', 'Apoderados de Contrato', 'GPDATWEB.APODERAD', 'NUMAPO', 'NOMAPO', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(26, '26', 'Oficinas', 'GPDATWEB.OFICINAS', 'OFINUM', 'OFINOM', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(27, '27', 'Representantes', 'GPDATWEB.AA2CLICO', 'CLCCLA', 'CLCNOM', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(28, '28', 'Tabla Comision', 'GPDATWEB.TABCF ', 'NTAB', 'NOMTAB', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(29, '29', 'Cuentas', 'GPDATWEB.CUENTAS', 'CTCCTA', 'CTCDES', 'CTCCLI')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(30, '30', 'Modalidades', 'gpdatweb.aa2modal', 'modcla', 'modnom', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(31, '31', 'Codigo Enlace Cta.Contable', 'gpdatweb.aa2ttpro', 'substring(PROCLA, 12, 3)', 'PRONOM', '')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(32, '32', 'CLIENTE COMPLEMENTARIO', 'GPDATWEB.AA2CLICO', 'CLCNIF', 'CLCNOM  || CLCAPE  || CLCAP2', 'CLCCLA')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(33, '33', 'CODIGO COMISION GESTION', 'GPDATWEB.AA2TABCO', 'TABTIP', 'TABNTI', ' ')
GO
INSERT INTO TableHelp(ID, CODE, NAME, TABLENAME, TABLECODE, TABLEDESC, TABLEPARENT)
  VALUES(34, '34', 'TRAIDERS', 'GPDATWEB.AA2TRAID', 'TRACLA', 'TRANOM || ''  ('' ||  TRAMAX || '')''', 'TRAEMP || TRADEL')
GO
