-- DROP PROCEDURE GPSQLWEB.procUpdateTabtr
    
CREATE PROCEDURE GPSQLWEB.procUpdateTabtr
(
IN P_CODIGO INTEGER,
IN P_TEXTO VARCHAR(30),
IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.TABTR WHERE CODIGO=P_CODIGO ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabtr', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabtr', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.TABTR SET TEXTO= P_TEXTO  WHERE CODIGO= P_CODIGO ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.TABTR SET TEXTO= '''||P_TEXTO || '''  WHERE CODIGO= '''||P_CODIGO|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabtr', StringSQL);
END
GO


