--DROP PROCEDURE GPSQLWEB.procCreateTabtr
    
CREATE PROCEDURE GPSQLWEB.procCreateTabtr
(
IN P_TEXTO VARCHAR(30),
IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_CODIGO INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SELECT COALESCE(MAX(CODIGO), 0) +1 INTO P_CODIGO FROM GPDATWEB.TABTR;
  INSERT INTO GPDATWEB.TABTR (CODIGO, TEXTO) VALUES (P_CODIGO, P_TEXTO);

  Set StringSQL = 'INSERT INTO GPDATWEB.TABTR (CODIGO, TEXTO ) VALUES (''' || P_CODIGO  ||''' ,  '''|| P_TEXTO || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateTabtr', StringSQL);
END
GO


