--DROP PROCEDURE GPSQLWEB.procCreateTabfp
    
CREATE PROCEDURE GPSQLWEB.procCreateTabfp
(
IN P_TEXTO VARCHAR(30),
IN P_CDCNX INT,
IN P_CUENTA VARCHAR(1),
IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_CODIGO INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SELECT  COALESCE(MAX(CODIGO), 0) +1 INTO P_CODIGO FROM GPDATWEB.TABFP;
  INSERT INTO GPDATWEB.TABFP (CODIGO, TEXTO ,CDCNX ,CUENTA ) VALUES (P_CODIGO,  P_TEXTO , P_CDCNX , P_CUENTA );
  Set StringSQL = 'INSERT INTO GPDATWEB.TABFP (CODIGO TEXTO ,CDCNX ,CUENTA ) VALUES (''' || P_CODIGO  ||''' ,  '''|| P_TEXTO || ''' , '''|| P_CDCNX || ''' , '''|| P_CUENTA || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateTabfp', StringSQL);
END
GO


