-- DROP PROCEDURE GPSQLWEB.procUpdateTabfp
   
CREATE PROCEDURE GPSQLWEB.procUpdateTabfp
(
IN P_CODIGO INT,
IN P_TEXTO VARCHAR(30),
IN P_CDCNX INT,
IN P_CUENTA VARCHAR(1),
IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_MSGCODE INT
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.TABFP WHERE CODIGO= P_CODIGO;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA  CODIGO '|| P_CODIGO;
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabfp', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO '|| P_CODIGO;
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabfp', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.TABFP SET TEXTO=P_TEXTO, CDCNX=P_CDCNX, CUENTA=P_CUENTA  WHERE CODIGO= P_CODIGO;
  
  SET P_MSGCODE = 0;
  Set StringSQL = 'UPDATE GPDATWEB.TABFP SET TEXTO= '''||P_TEXTO || ''' , CDCNX= '''||P_CDCNX || ''' , CUENTA= '''||P_CUENTA || '''  WHERE CODIGO= '''||P_CODIGO|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabfp', StringSQL);
  
END
GO

