
    
--DROP PROCEDURE GPSQLWEB.procCreateProductos
    
CREATE PROCEDURE GPSQLWEB.procCreateProductos
(
   IN P_PROPRO INTEGER,

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  SET P_MSGCODE = 9999;
    
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.PRODUCTOS WHERE PROPRO = P_PROPRO;

  IF V_CANT > 0 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateProductos', StringSQL);
        RETURN;
  END IF;
        INSERT INTO GPDATWEB.PRODUCTOS (PROPRO ) VALUES ( P_PROPRO );

  Set StringSQL = 'INSERT INTO GPDATWEB.PRODUCTOS (PROPRO ) VALUES ( '''|| P_PROPRO || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateProductos', StringSQL);
  SET P_MSGCODE = 0;
END
GO


