--DROP PROCEDURE GPSQLWEB.procCreateAa2ato
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2ato
(
    IN P_ATOEMP VARCHAR(2),
    IN P_ATODEL VARCHAR(2),
    IN P_ATOFEC INTEGER,
    IN P_ATODTO INTEGER,
    IN P_ATONRO BIGINT,
    IN P_ATODIV INTEGER,
    IN P_ATOCTA BIGINT,
    IN P_ATOIMD DOUBLE,
    IN P_ATOIMP DOUBLE,
    IN P_ATOCON VARCHAR(3),
    IN P_ATOVAL BIGINT,
    IN P_ATODH VARCHAR(1),
    IN P_ATOFCO BIGINT,
    IN P_ATOMAT VARCHAR(1),
    IN P_ATOBAJ VARCHAR(1),
    IN P_ATOUSU VARCHAR(6),
    IN P_ATOCLI BIGINT,
    IN P_ATOCOY BIGINT,
    IN P_ATOVAY BIGINT,
    IN P_ATORE1 VARCHAR(3),
    IN P_ATORE2 BIGINT,
    IN P_ATODPR VARCHAR(1),
    IN P_ATOBVI BIGINT,
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
    Declare StringSQL Varchar(32000) Default '';
    SET P_MSGCODE = 9999;

    INSERT INTO GPDATWEB.AA2ATO (ATOEMP, ATODEL ,ATOFEC ,ATODTO ,ATONRO ,ATODIV ,ATOCTA ,ATOIMD ,ATOIMP ,ATOCON ,ATOVAL ,ATODH ,ATOFCO ,ATOMAT ,ATOBAJ ,ATOUSU ,ATOCLI ,ATOCOY ,ATOVAY ,ATORE1 ,ATORE2 ,ATODPR ,ATOBVI ) 
        VALUES (P_ATOEMP,  P_ATODEL , P_ATOFEC , P_ATODTO , P_ATONRO , P_ATODIV , P_ATOCTA , P_ATOIMD , P_ATOIMP , P_ATOCON , P_ATOVAL , P_ATODH , P_ATOFCO , P_ATOMAT , P_ATOBAJ , P_ATOUSU , P_ATOCLI , P_ATOCOY , P_ATOVAY , P_ATORE1 , P_ATORE2 , P_ATODPR , P_ATOBVI );

    Set StringSQL = 'INSERT INTO GPDATWEB.AA2ATO (ATOEMP, ATODEL ,ATOFEC ,ATODTO ,ATONRO ,ATODIV ,ATOCTA ,ATOIMD ,ATOIMP ,ATOCON ,ATOVAL ,ATODH ,ATOFCO ,ATOMAT ,ATOBAJ ,ATOUSU ,ATOCLI ,ATOCOY ,ATOVAY ,ATORE1 ,ATORE2 ,ATODPR ,ATOBVI ) VALUES (''' || P_ATOEMP  ||''' ,  '''|| P_ATODEL || ''' , '''|| P_ATOFEC || ''' , '''|| P_ATODTO || ''' , '''|| P_ATONRO || ''' , '''|| P_ATODIV || ''' , '''|| P_ATOCTA || ''' , '''|| P_ATOIMD || ''' , '''|| P_ATOIMP || ''' , '''|| P_ATOCON || ''' , '''|| P_ATOVAL || ''' , '''|| P_ATODH || ''' , '''|| P_ATOFCO || ''' , '''|| P_ATOMAT || ''' , '''|| P_ATOBAJ || ''' , '''|| P_ATOUSU || ''' , '''|| P_ATOCLI || ''' , '''|| P_ATOCOY || ''' , '''|| P_ATOVAY || ''' , '''|| P_ATORE1 || ''' , '''|| P_ATORE2 || ''' , '''|| P_ATODPR || ''' , '''|| P_ATOBVI || ''' )'; 
    CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2ato', StringSQL);
    SET P_MSGCODE = 0;
END
GO
 