
    
--DROP PROCEDURE GPSQLWEB.procCreateAa2clico
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2clico
(
   IN P_CLCCLA BIGINT,
 IN P_CLCCTR INTEGER,
 IN P_CLCNOM VARCHAR(20),
 IN P_CLCAPE VARCHAR(15),
 IN P_CLCAP2 VARCHAR(15),
 IN P_CLCDI1 VARCHAR(30),
 IN P_CLCDI2 VARCHAR(30),
 IN P_CLCPOS VARCHAR(9),
 IN P_CLCPRO VARCHAR(25),
 IN P_CLCPAI INTEGER,
 IN P_CLCPOB VARCHAR(27),
 IN P_CLCCAL VARCHAR(2),
 IN P_CLCNUM BIGINT,
 IN P_CLCANA BIGINT,
 IN P_CLCTID VARCHAR(1),
 IN P_CLCNIF VARCHAR(12),
 IN P_CLCTEL BIGINT,
 IN P_CLCUSU VARCHAR(10),

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.AA2CLICO (CLCCLA ,CLCCTR ,CLCNOM ,CLCAPE ,CLCAP2 ,CLCDI1 ,CLCDI2 ,CLCPOS ,CLCPRO ,CLCPAI ,CLCPOB ,CLCCAL ,CLCNUM ,CLCANA ,CLCTID ,CLCNIF ,CLCTEL ,CLCUSU ) VALUES ( P_CLCCLA , P_CLCCTR , P_CLCNOM , P_CLCAPE , P_CLCAP2 , P_CLCDI1 , P_CLCDI2 , P_CLCPOS , P_CLCPRO , P_CLCPAI , P_CLCPOB , P_CLCCAL , P_CLCNUM , P_CLCANA , P_CLCTID , P_CLCNIF , P_CLCTEL , P_CLCUSU );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2CLICO (CLCCLA ,CLCCTR ,CLCNOM ,CLCAPE ,CLCAP2 ,CLCDI1 ,CLCDI2 ,CLCPOS ,CLCPRO ,CLCPAI ,CLCPOB ,CLCCAL ,CLCNUM ,CLCANA ,CLCTID ,CLCNIF ,CLCTEL ,CLCUSU ) VALUES ( '''|| P_CLCCLA || ''' , '''|| P_CLCCTR || ''' , '''|| P_CLCNOM || ''' , '''|| P_CLCAPE || ''' , '''|| P_CLCAP2 || ''' , '''|| P_CLCDI1 || ''' , '''|| P_CLCDI2 || ''' , '''|| P_CLCPOS || ''' , '''|| P_CLCPRO || ''' , '''|| P_CLCPAI || ''' , '''|| P_CLCPOB || ''' , '''|| P_CLCCAL || ''' , '''|| P_CLCNUM || ''' , '''|| P_CLCANA || ''' , '''|| P_CLCTID || ''' , '''|| P_CLCNIF || ''' , '''|| P_CLCTEL || ''' , '''|| P_CLCUSU || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2clico', StringSQL);
  SET P_MSGCODE = 0;
END
GO


