
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2clico
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2clico
(
    IN P_ROWID BIGINT,
 IN P_CLCCLA BIGINT,
 IN P_CLCCTR INTEGER,
 IN P_CLCNOM varchar(20),
 IN P_CLCAPE varchar(15),
 IN P_CLCAP2 varchar(15),
 IN P_CLCDI1 varchar(30),
 IN P_CLCDI2 varchar(30),
 IN P_CLCPOS varchar(9),
 IN P_CLCPRO varchar(25),
 IN P_CLCPAI INTEGER,
 IN P_CLCPOB varchar(27),
 IN P_CLCCAL varchar(2),
 IN P_CLCNUM BIGINT,
 IN P_CLCANA BIGINT,
 IN P_CLCTID varchar(1),
 IN P_CLCNIF varchar(12),
 IN P_CLCTEL BIGINT,
 IN P_CLCUSU varchar(10),

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2CLICO WHERE RRN(GPDATWEB.AA2CLICO) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2clico', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2clico', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2CLICO SET CLCCLA= P_CLCCLA , CLCCTR= P_CLCCTR , CLCNOM= P_CLCNOM , CLCAPE= P_CLCAPE , CLCAP2= P_CLCAP2 , CLCDI1= P_CLCDI1 , CLCDI2= P_CLCDI2 , CLCPOS= P_CLCPOS , CLCPRO= P_CLCPRO , CLCPAI= P_CLCPAI , CLCPOB= P_CLCPOB , CLCCAL= P_CLCCAL , CLCNUM= P_CLCNUM , CLCANA= P_CLCANA , CLCTID= P_CLCTID , CLCNIF= P_CLCNIF , CLCTEL= P_CLCTEL , CLCUSU= P_CLCUSU  WHERE RRN(GPDATWEB.AA2CLICO) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AA2CLICO SET CLCCLA= '''||P_CLCCLA || ''' , CLCCTR= '''||P_CLCCTR || ''' , CLCNOM= '''||P_CLCNOM || ''' , CLCAPE= '''||P_CLCAPE || ''' , CLCAP2= '''||P_CLCAP2 || ''' , CLCDI1= '''||P_CLCDI1 || ''' , CLCDI2= '''||P_CLCDI2 || ''' , CLCPOS= '''||P_CLCPOS || ''' , CLCPRO= '''||P_CLCPRO || ''' , CLCPAI= '''||P_CLCPAI || ''' , CLCPOB= '''||P_CLCPOB || ''' , CLCCAL= '''||P_CLCCAL || ''' , CLCNUM= '''||P_CLCNUM || ''' , CLCANA= '''||P_CLCANA || ''' , CLCTID= '''||P_CLCTID || ''' , CLCNIF= '''||P_CLCNIF || ''' , CLCTEL= '''||P_CLCTEL || ''' , CLCUSU= '''||P_CLCUSU || '''  WHERE RRN(GPDATWEB.AA2CLICO) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2clico', StringSQL);
END
GO


