
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2emiso
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2emiso
(
    IN P_ROWID BIGINT,
 IN P_EMIEMP varchar(2),
 IN P_EMIDEL varchar(2),
 IN P_EMICLA BIGINT,
 IN P_EMINOM varchar(40),
 IN P_EMIMAX double,
 IN P_EMIUTI BIGINT,
 IN P_EMIUFE BIGINT,
 IN P_EMITIP INTEGER,

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2EMISO WHERE RRN(GPDATWEB.AA2EMISO) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2emiso', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2emiso', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2EMISO SET EMIEMP= P_EMIEMP , EMIDEL= P_EMIDEL , EMINOM= P_EMINOM , EMIMAX= P_EMIMAX , EMIUTI= P_EMIUTI , EMIUFE= P_EMIUFE , EMITIP= P_EMITIP  WHERE RRN(GPDATWEB.AA2EMISO) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AA2EMISO SET EMIEMP= '''||P_EMIEMP || ''' , EMIDEL= '''||P_EMIDEL || ''' , EMINOM= '''||P_EMINOM || ''' , EMIMAX= '''||P_EMIMAX || ''' , EMIUTI= '''||P_EMIUTI || ''' , EMIUFE= '''||P_EMIUFE || ''' , EMITIP= '''||P_EMITIP || '''  WHERE RRN(GPDATWEB.AA2EMISO) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2emiso', StringSQL);
END
GO


