
    
--DROP PROCEDURE GPSQLWEB.procCreateAa2emiso
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2emiso
(
   IN P_EMIEMP VARCHAR(2),
 IN P_EMIDEL VARCHAR(2),
 IN P_EMINOM VARCHAR(40),
 IN P_EMIMAX DOUBLE,
 IN P_EMIUTI BIGINT,
 IN P_EMIUFE BIGINT,
 IN P_EMITIP INTEGER,

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  OUT P_EMICLA BIGINT,
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.AA2EMISO (EMIEMP ,EMIDEL ,EMINOM ,EMIMAX ,EMIUTI ,EMIUFE ,EMITIP ) VALUES ( P_EMIEMP , P_EMIDEL , P_EMINOM , P_EMIMAX , P_EMIUTI , P_EMIUFE , P_EMITIP );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2EMISO (EMIEMP ,EMIDEL ,EMINOM ,EMIMAX ,EMIUTI ,EMIUFE ,EMITIP ) VALUES ( '''|| P_EMIEMP || ''' , '''|| P_EMIDEL || ''' , '''|| P_EMINOM || ''' , '''|| P_EMIMAX || ''' , '''|| P_EMIUTI || ''' , '''|| P_EMIUFE || ''' , '''|| P_EMITIP || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2emiso', StringSQL);
  SET P_MSGCODE = 0;
END
GO


