
-- DROP PROCEDURE GPSQLWEB.procUpdateCotfondo
    
CREATE PROCEDURE GPSQLWEB.procUpdateCotfondo
(
    IN P_ROWID BIGINT,
 IN P_COFEMP varchar(2),
 IN P_COFDEL varchar(2),
 IN P_COFCLA varchar(12),
 IN P_COFFEC BIGINT,
 IN P_COFCOT double,

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.COTFONDO WHERE RRN(GPDATWEB.COTFONDO) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCotfondo', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCotfondo', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.COTFONDO SET COFEMP= P_COFEMP , COFDEL= P_COFDEL , COFCLA= P_COFCLA , COFFEC= P_COFFEC , COFCOT= P_COFCOT  WHERE RRN(GPDATWEB.COTFONDO) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.COTFONDO SET COFEMP= '''||P_COFEMP || ''' , COFDEL= '''||P_COFDEL || ''' , COFCLA= '''||P_COFCLA || ''' , COFFEC= '''||P_COFFEC || ''' , COFCOT= '''||P_COFCOT || '''  WHERE RRN(GPDATWEB.COTFONDO) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCotfondo', StringSQL);
END
GO


