
    
--DROP PROCEDURE GPSQLWEB.procCreateCotfondo
    
CREATE PROCEDURE GPSQLWEB.procCreateCotfondo
(
   IN P_COFEMP VARCHAR(2),
 IN P_COFDEL VARCHAR(2),
 IN P_COFCLA VARCHAR(12),
 IN P_COFFEC BIGINT,
 IN P_COFCOT DOUBLE,

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.COTFONDO (COFEMP ,COFDEL ,COFCLA ,COFFEC ,COFCOT ) VALUES ( P_COFEMP , P_COFDEL , P_COFCLA , P_COFFEC , P_COFCOT );

  Set StringSQL = 'INSERT INTO GPDATWEB.COTFONDO (COFEMP ,COFDEL ,COFCLA ,COFFEC ,COFCOT ) VALUES ( '''|| P_COFEMP || ''' , '''|| P_COFDEL || ''' , '''|| P_COFCLA || ''' , '''|| P_COFFEC || ''' , '''|| P_COFCOT || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateCotfondo', StringSQL);
  SET P_MSGCODE = 0;
END
GO


