
-- DROP PROCEDURE GPSQLWEB.procUpdateCountry
    
CREATE PROCEDURE GPSQLWEB.procUpdateCountry
(
     IN P_PAICLA INTEGER,
            IN P_PAINOM VARCHAR(50),
            IN P_PAICTR INTEGER,
           
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500)
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Not Null Default '';
  UPDATE GPDATBAAG.AA2TPAIS SET PAINOM= P_PAINOM , PAICTR= P_PAICTR  WHERE PAICLA= P_PAICLA ;

  Set StringSQL = 'UPDATE GPDATBAAG.AA2TPAIS SET PAINOM= '''||P_PAINOM || ''' , PAICTR= '''||P_PAICTR || '''  WHERE PAICLA= '''||P_PAICLA|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCountry', StringSQL);
END
GO


