
    
--DROP PROCEDURE GPSQLWEB.procCreateCountry
    
CREATE PROCEDURE GPSQLWEB.procCreateCountry
(
   IN P_PAINOM VARCHAR(50),
                 IN P_PAICTR INTEGER,
                
  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  OUT P_PAICLA INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Not Null Default '';
  
        SELECT MAX(PAICLA) +1 INTO P_PAICLA FROM GPDATBAAG.AA2TPAIS;
        INSERT INTO  GPDATBAAG.AA2TPAIS (PAICLA, PAINOM ,PAICTR ) VALUES (P_PAICLA,  P_PAINOM , P_PAICTR );

  Set StringSQL = 'INSERT INTO  GPDATBAAG.AA2TPAIS (PAICLA PAINOM ,PAICTR ) VALUES (''' || P_PAICLA  ||''' ,  '''|| P_PAINOM || ''' , '''|| P_PAICTR || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateCountry', StringSQL);
END
GO


