-- DROP PROCEDURE GPSQLWEB.procUpdateCupamort
    
CREATE PROCEDURE GPSQLWEB.procUpdateCupamort
(
    IN P_ROWID BIGINT,
    IN P_CUPEMP VARCHAR(2),
    IN P_CUPDEL VARCHAR(2),
    IN P_CUPTIP VARCHAR(1),
    IN P_CUPVAL VARCHAR(12),
    IN P_CUPFEC DECIMAL(8 , 0),
    IN P_CUPMNT NUMERIC(8 , 5),
    IN P_CUPIMP DECIMAL(15 , 2),
    IN P_CUPCOB DECIMAL(8 , 0),
    IN P_CUPVEN VARCHAR(1),
    IN P_CUPMCB VARCHAR(1),
    IN P_CUPCBT VARCHAR(1),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.CUPAMORT WHERE RRN(GPDATWEB.CUPAMORT) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCupamort', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCupamort', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.CUPAMORT SET CUPEMP= P_CUPEMP , CUPDEL= P_CUPDEL , CUPTIP= P_CUPTIP , CUPVAL= P_CUPVAL , CUPFEC= P_CUPFEC , CUPMNT= P_CUPMNT , CUPIMP= P_CUPIMP , CUPCOB= P_CUPCOB , CUPVEN= P_CUPVEN , CUPMCB= P_CUPMCB , CUPCBT= P_CUPCBT  WHERE RRN(GPDATWEB.CUPAMORT) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.CUPAMORT SET CUPEMP= '''||P_CUPEMP || ''' , CUPDEL= '''||P_CUPDEL || ''' , CUPTIP= '''||P_CUPTIP || ''' , CUPVAL= '''||P_CUPVAL || ''' , CUPFEC= '''||P_CUPFEC || ''' , CUPMNT= '''||P_CUPMNT || ''' , CUPIMP= '''||P_CUPIMP || ''' , CUPCOB= '''||P_CUPCOB || ''' , CUPVEN= '''||P_CUPVEN || ''' , CUPMCB= '''||P_CUPMCB || ''' , CUPCBT= '''||P_CUPCBT || '''  WHERE RRN(GPDATWEB.CUPAMORT) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateCupamort', StringSQL);
END
GO


