--DROP PROCEDURE GPSQLWEB.procCreateMsgcode
    
CREATE PROCEDURE GPSQLWEB.procCreateMsgcode
(
IN P_MSGLAN VARCHAR(1),
IN P_MSGNUM NUMERIC(4, 0),
IN P_MSGTXT VARCHAR(100),
IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_ID INTEGER
)
LANGUAGE SQL
BEGIN
	Declare StringSQL Varchar(32000) Default '';
	
	INSERT INTO GPSQLWEB.MSGCODE (MSGLAN ,MSGNUM ,MSGTXT ) VALUES ( P_MSGLAN , P_MSGNUM , P_MSGTXT );
	SELECT IDENTITY_VAL_LOCAL() AS LASTID INTO P_ID FROM SYSIBM.SYSDUMMY1;

	Set StringSQL = 'INSERT INTO GPSQLWEB.MSGCODE (MSGLAN ,MSGNUM ,MSGTXT ) VALUES ( '''|| P_MSGLAN || ''' , '''|| P_MSGNUM || ''' , '''|| P_MSGTXT || ''' )'; 
	CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateMsgcode', StringSQL);
END
GO


