
-- DROP PROCEDURE GPSQLWEB.procUpdateMsgcode
    
CREATE PROCEDURE GPSQLWEB.procUpdateMsgcode
(
IN P_ID INTEGER,
IN P_MSGLAN VARCHAR(1),
IN P_MSGNUM NUMERIC(4, 0),
IN P_MSGTXT VARCHAR(100),
IN P_USERNAME VARCHAR(50),
IN P_IPADDRESS VARCHAR(255),
IN P_USERAGENT VARCHAR(500),
OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPSQLWEB.MSGCODE WHERE ID = P_ID;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateMsgcode', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateMsgcode', StringSQL);
        RETURN;
  END IF;

  UPDATE GPSQLWEB.MSGCODE SET MSGLAN= P_MSGLAN , MSGNUM= P_MSGNUM , MSGTXT= P_MSGTXT  WHERE ID= P_ID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPSQLWEB.MSGCODE SET MSGLAN= '''||P_MSGLAN || ''' , MSGNUM= '''||P_MSGNUM || ''' , MSGTXT= '''||P_MSGTXT || '''  WHERE ID= '''||P_ID|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateMsgcode', StringSQL);
END
GO


