
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2comi
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2comi
(
    IN P_ROWID BIGINT,
IN P_COMEMP VARCHAR(2),
    IN P_COMDEL VARCHAR(2),
    IN P_COMFIC DECIMAL(8 , 0),
    IN P_COMCOB DECIMAL(9 , 6),
    IN P_COMNCO DECIMAL(9 , 6),
    IN P_COMVIV DECIMAL(9 , 6),
    IN P_COMCPJ DECIMAL(9 , 6),
    IN P_COMCFL DECIMAL(9 , 6),
    IN P_COMINP DECIMAL(9 , 6),
    IN P_COMMOP DECIMAL(9 , 6),
    IN P_COMSCF DECIMAL(9 , 6),
    IN P_COMDIS VARCHAR(12),
    IN P_COMINV VARCHAR(12),
    IN P_COMFEC DECIMAL(8 , 0),
    IN P_COMUSU VARCHAR(10),
    IN P_COMHOR DECIMAL(6 , 0),

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  Declare V_COMFIC INT DEFAULT 0;

  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2COMI WHERE RRN(GPDATWEB.AA2COMI) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2comi', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2comi', StringSQL);
        RETURN;
  END IF;

  
  SELECT COMFIC INTO V_COMFIC FROM GPDATWEB.AA2COMI WHERE RRN(GPDATWEB.AA2COMI) =  P_ROWID ;

  -- SI CAMBIA LA FECHA GUARDAR EL VALOR ACTUAL EN EL HISTORICO
  IF P_COMFIC <> V_COMFIC THEN
    INSERT INTO GPDATWEB.AA2COMIH (COHEMP ,COHDEL ,COHFIC ,COHCOB ,COHNCO ,COHVIV ,COHCPJ ,COHCFL ,COHINP ,COHMOP ,COHSCF ,COHDIS ,COHINV ,COHFEC ,COHUSU ,COHHOR ) 
    SELECT COMEMP ,COMDEL ,COMFIC ,COMCOB ,COMNCO ,COMVIV ,COMCPJ ,COMCFL ,COMINP ,COMMOP ,COMSCF ,COMDIS ,COMINV ,COMFEC ,COMUSU ,COMHOR FROM GPDATWEB.AA2COMI
        WHERE RRN(GPDATWEB.AA2COMI) =  P_ROWID ;
  END IF;

  UPDATE GPDATWEB.AA2COMI SET COMEMP= P_COMEMP , COMDEL= P_COMDEL , COMFIC= P_COMFIC , COMCOB= P_COMCOB , COMNCO= P_COMNCO , COMVIV= P_COMVIV , COMCPJ= P_COMCPJ , COMCFL= P_COMCFL , COMINP= P_COMINP , COMMOP= P_COMMOP , COMSCF= P_COMSCF , COMDIS= P_COMDIS , COMINV= P_COMINV , COMFEC= P_COMFEC , COMUSU= P_COMUSU , COMHOR= P_COMHOR  WHERE RRN(GPDATWEB.AA2COMI) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AA2COMI SET COMEMP= '''||P_COMEMP || ''' , COMDEL= '''||P_COMDEL || ''' , COMFIC= '''||P_COMFIC || ''' , COMCOB= '''||P_COMCOB || ''' , COMNCO= '''||P_COMNCO || ''' , COMVIV= '''||P_COMVIV || ''' , COMCPJ= '''||P_COMCPJ || ''' , COMCFL= '''||P_COMCFL || ''' , COMINP= '''||P_COMINP || ''' , COMMOP= '''||P_COMMOP || ''' , COMSCF= '''||P_COMSCF || ''' , COMDIS= '''||P_COMDIS || ''' , COMINV= '''||P_COMINV || ''' , COMFEC= '''||P_COMFEC || ''' , COMUSU= '''||P_COMUSU || ''' , COMHOR= '''||P_COMHOR || '''  WHERE RRN(GPDATWEB.AA2COMI) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2comi', StringSQL);
END
GO


