--DROP PROCEDURE GPSQLWEB.PROCCREATEAA2TFIDE

CREATE PROCEDURE GPSQLWEB.PROCCREATEAA2TFIDE ( 
	IN P_FIDCLA VARCHAR(4),
	IN P_FIDNOM VARCHAR(40),
	IN P_FIDTIP DECIMAL(2 , 0),
	IN P_FIDFIN VARCHAR(1),
	IN P_DIVISA DECIMAL(3 , 0),
	IN P_AREA VARCHAR(4),
	IN P_USERNAME VARCHAR(50),
	IN P_IPADDRESS VARCHAR(255),
	IN P_USERAGENT VARCHAR(500),
	OUT P_MSGCODE INTEGER )
	LANGUAGE SQL
	SPECIFIC GPSQLWEB.PROCCREATEAA2TFIDE
BEGIN
DECLARE STRINGSQL VARCHAR ( 32000 ) DEFAULT '' ;
DECLARE V_CANT INT DEFAULT 0 ;
DECLARE V_DIVISA CHAR(3);

SELECT COUNT ( 1 ) INTO V_CANT FROM GPDATWEB.AA2TFIDE  WHERE UPPER(TRIM(FIDCLA)) = UPPER(TRIM(P_FIDCLA)) ;

IF V_CANT > 0 THEN
	SET P_MSGCODE = 9001 ;
	SET STRINGSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA' ;
	CALL GPSQLWEB . PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'Crear' , 'procCreateAa2tfide' , STRINGSQL ) ;
	RETURN ;
END IF ;

INSERT INTO GPDATWEB . AA2TFIDE ( FIDCLA , FIDNOM , FIDTIP , FIDFIN ) VALUES ( '           ' || UPPER(P_FIDCLA) , P_FIDNOM , P_FIDTIP , P_FIDFIN ) ;

SET P_MSGCODE = 1;

SET STRINGSQL = 'INSERT INTO GPDATWEB.AA2TFIDE (FIDCLA FIDNOM ,FIDTIP ,FIDFIN ) VALUES (''' || UPPER(P_FIDCLA) || ''' ,  ''' || P_FIDNOM || ''' , ''' || P_FIDTIP || ''' , ''' || P_FIDFIN || ''' )' ;
CALL GPSQLWEB . PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'Crear' , 'procCreateAa2tfide' , STRINGSQL ) ;

SET STRINGSQL = 'CALL GPSQLWEB.PROCCLCOPCON(''' || P_AREA || ''', ''' || P_FIDCLA || ''', ''' || P_DIVISA || ''');';
CALL GPSQLWEB.PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'call' , 'procCreateAa2tfide', STRINGSQL ) ;

SET V_DIVISA = RIGHT(REPEAT('0', 3) || CAST(P_DIVISA as CHAR), 3) ;


CALL GPSQLWEB.PROCCLCOPCON(P_AREA, P_FIDCLA, P_DIVISA );

SET P_MSGCODE = 0;
END

--select RIGHT(REPEAT('0', 5) || CAST(FIDTIP as CHAR), 5)  from  GPDATWEB.AA2TFIDE
