
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2ttpro
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2ttpro
(
    IN P_ROWID BIGINT,
 IN P_PROEMP varchar(2),
 IN P_PRODEL varchar(2),
 IN P_PROCLA NUMERIC(15 , 0),
 IN P_PRONOM varchar(40),

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
DECLARE V_CTAEMP VARCHAR(2);
DECLARE V_CTADEL VARCHAR(2);
DECLARE V_CTAGEN VARCHAR(12);
DECLARE END_TABLE INT DEFAULT 0 ;
DECLARE V_TABCLA VARCHAR ( 4 ) DEFAULT '' ;
DECLARE C CURSOR FOR SELECT upper( TABEMP CONCAT TABDEL) FROM GPDATWEB . AA2MTAB WHERE TABORI = P_PROEMP CONCAT P_PRODEL and upper( TABEMP CONCAT TABDEL) <> P_PROEMP CONCAT P_PRODEL;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET END_TABLE = 1 ;
  

  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TTPRO WHERE RRN(GPDATWEB.AA2TTPRO) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2ttpro', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2ttpro', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2TTPRO SET PROEMP= P_PROEMP , PRODEL= P_PRODEL , PROCLA= P_PROCLA , PRONOM= P_PRONOM  WHERE RRN(GPDATWEB.AA2TTPRO) =  P_ROWID ;
  
  Set StringSQL = 'UPDATE GPDATWEB.AA2TTPRO SET PROEMP= '''||P_PROEMP || ''' , PRODEL= '''||P_PRODEL || ''' , PROCLA= '''||P_PROCLA || ''' , PRONOM= '''||P_PRONOM || '''  WHERE RRN(GPDATWEB.AA2TTPRO) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2ttpro', StringSQL);


  OPEN C ;
    FETCH FROM C INTO V_TABCLA ;
    WHILE END_TABLE = 0 DO
        IF ( V_TABCLA != ( P_PROEMP CONCAT P_PRODEL ) ) THEN
            UPDATE GPDATWEB.AA2TTPRO SET PRONOM= P_PRONOM  
                WHERE PROEMP= SUBSTR (V_TABCLA , 1 , 2 )  AND PRODEL= SUBSTR ( V_TABCLA , 3 , 2 ) AND PROCLA= P_PROCLA  ;
        END IF;
    FETCH FROM C INTO V_TABCLA ;
    END WHILE ;

  CLOSE C ;

  SET P_MSGCODE = 0;

END
GO


