-- DROP PROCEDURE GPSQLWEB.procUpdateInvers
    
CREATE PROCEDURE GPSQLWEB.procUpdateInvers
(
    IN P_ROWID BIGINT,
    IN P_INVEMP CHAR(2),
    IN P_INVDEL CHAR(2),
    IN P_INVCLI NUMERIC(7 , 0),
    IN P_INVVAL CHAR(12),
    IN P_INVINT NUMERIC(7 , 0),
    IN P_INVCLA CHAR(3),
    IN P_INVVEN CHAR(1),
    IN P_INVINE NUMERIC(6 , 0),
    IN P_INVVTE NUMERIC(6 , 0),
    IN P_INVPRE DECIMAL(9 , 6),
    IN P_INVINI NUMERIC(6 , 0),
    IN P_INVINA DECIMAL(8 , 0),
    IN P_INVVTO NUMERIC(6 , 0),
    IN P_INVVTA DECIMAL(8 , 0),
    IN P_INVEFI DECIMAL(13 , 2),
    IN P_INVEFF DECIMAL(13 , 2),
    IN P_INVPRC DECIMAL(9 , 6),
    IN P_INV036 CHAR(1),
    IN P_INVTIT DECIMAL(27 , 7),
    IN P_INVPME DECIMAL(9 , 6),
    IN P_INVPIN DECIMAL(9 , 6),
    IN P_INVINF DECIMAL(9 , 2),
    IN P_INVRDE CHAR(1),
    IN P_INVLIS CHAR(1),
    IN P_INVANU CHAR(1),
    IN P_INVSIR CHAR(1),
    IN P_INVICO DECIMAL(15 , 2),
    IN P_INVNOP DECIMAL(10 , 0),
    IN P_INVPER DECIMAL(2 , 0),
    IN P_INVFDE DECIMAL(13 , 2),
    IN P_INVFUI DECIMAL(6 , 0),
    IN P_INVNTI DECIMAL(10 , 0),
    IN P_INVAPR DECIMAL(13 , 2),
    IN P_INVIBS CHAR(1),
    IN P_INVIGC DECIMAL(15 , 2),
    IN P_INVAGD DECIMAL(15 , 2),
    IN P_INVBVI DECIMAL(7 , 0),
    IN P_INVMAR DECIMAL(9 , 6),
    IN P_INVTA1 CHAR(3),
    IN P_INVTA2 DECIMAL(5 , 2),
    IN P_INVIAN DECIMAL(13 , 2),
    IN P_INVBOL CHAR(1),
    IN P_INVIPP CHAR(1),
    IN P_INVVFV CHAR(1),
    IN P_INVPRO DECIMAL(2 , 0),
    IN P_INVPEN DECIMAL(15 , 2),
    IN P_INVPRX DECIMAL(6 , 5),
    IN P_INVVAC CHAR(12),
    IN P_INVNUC DECIMAL(10 , 0),
    IN P_INVPOP DECIMAL(9 , 6),
    IN P_INVBAD DECIMAL(1 , 0),
    IN P_INVVNO DECIMAL(15 , 2),
    IN P_INVLIQ DECIMAL(6 , 0),
    IN P_INVRES DECIMAL(9 , 6),
    IN P_INVTIM DECIMAL(9 , 6),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.INVERS WHERE RRN(GPDATWEB.INVERS) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateInvers', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateInvers', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.INVERS SET INVEMP= P_INVEMP , INVDEL= P_INVDEL , INVCLI= P_INVCLI , INVVAL= P_INVVAL , INVINT= P_INVINT , INVCLA= P_INVCLA , INVVEN= P_INVVEN , INVINE= P_INVINE , INVVTE= P_INVVTE , INVPRE= P_INVPRE , INVINI= P_INVINI , INVINA= P_INVINA , INVVTO= P_INVVTO , INVVTA= P_INVVTA , INVEFI= P_INVEFI , INVEFF= P_INVEFF , INVPRC= P_INVPRC , INV036= P_INV036 , INVTIT= P_INVTIT , INVPME= P_INVPME , INVPIN= P_INVPIN , INVINF= P_INVINF , INVRDE= P_INVRDE , INVLIS= P_INVLIS , INVANU= P_INVANU , INVSIR= P_INVSIR , INVICO= P_INVICO , INVNOP= P_INVNOP , INVPER= P_INVPER , INVFDE= P_INVFDE , INVFUI= P_INVFUI , INVNTI= P_INVNTI , INVAPR= P_INVAPR , INVIBS= P_INVIBS , INVIGC= P_INVIGC , INVAGD= P_INVAGD , INVBVI= P_INVBVI , INVMAR= P_INVMAR , INVTA1= P_INVTA1 , INVTA2= P_INVTA2 , INVIAN= P_INVIAN , INVBOL= P_INVBOL , INVIPP= P_INVIPP , INVVFV= P_INVVFV , INVPRO= P_INVPRO , INVPEN= P_INVPEN , INVPRX= P_INVPRX , INVVAC= P_INVVAC , INVNUC= P_INVNUC , INVPOP= P_INVPOP , INVBAD= P_INVBAD , INVVNO= P_INVVNO , INVLIQ= P_INVLIQ , INVRES= P_INVRES , INVTIM= P_INVTIM  WHERE RRN(GPDATWEB.INVERS) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.INVERS SET INVEMP= '''||P_INVEMP || ''' , INVDEL= '''||P_INVDEL || ''' , INVCLI= '''||P_INVCLI || ''' , INVVAL= '''||P_INVVAL || ''' , INVINT= '''||P_INVINT || ''' , INVCLA= '''||P_INVCLA || ''' , INVVEN= '''||P_INVVEN || ''' , INVINE= '''||P_INVINE || ''' , INVVTE= '''||P_INVVTE || ''' , INVPRE= '''||P_INVPRE || ''' , INVINI= '''||P_INVINI || ''' , INVINA= '''||P_INVINA || ''' , INVVTO= '''||P_INVVTO || ''' , INVVTA= '''||P_INVVTA || ''' , INVEFI= '''||P_INVEFI || ''' , INVEFF= '''||P_INVEFF || ''' , INVPRC= '''||P_INVPRC || ''' , INV036= '''||P_INV036 || ''' , INVTIT= '''||P_INVTIT || ''' , INVPME= '''||P_INVPME || ''' , INVPIN= '''||P_INVPIN || ''' , INVINF= '''||P_INVINF || ''' , INVRDE= '''||P_INVRDE || ''' , INVLIS= '''||P_INVLIS || ''' , INVANU= '''||P_INVANU || ''' , INVSIR= '''||P_INVSIR || ''' , INVICO= '''||P_INVICO || ''' , INVNOP= '''||P_INVNOP || ''' , INVPER= '''||P_INVPER || ''' , INVFDE= '''||P_INVFDE || ''' , INVFUI= '''||P_INVFUI || ''' , INVNTI= '''||P_INVNTI || ''' , INVAPR= '''||P_INVAPR || ''' , INVIBS= '''||P_INVIBS || ''' , INVIGC= '''||P_INVIGC || ''' , INVAGD= '''||P_INVAGD || ''' , INVBVI= '''||P_INVBVI || ''' , INVMAR= '''||P_INVMAR || ''' , INVTA1= '''||P_INVTA1 || ''' , INVTA2= '''||P_INVTA2 || ''' , INVIAN= '''||P_INVIAN || ''' , INVBOL= '''||P_INVBOL || ''' , INVIPP= '''||P_INVIPP || ''' , INVVFV= '''||P_INVVFV || ''' , INVPRO= '''||P_INVPRO || ''' , INVPEN= '''||P_INVPEN || ''' , INVPRX= '''||P_INVPRX || ''' , INVVAC= '''||P_INVVAC || ''' , INVNUC= '''||P_INVNUC || ''' , INVPOP= '''||P_INVPOP || ''' , INVBAD= '''||P_INVBAD || ''' , INVVNO= '''||P_INVVNO || ''' , INVLIQ= '''||P_INVLIQ || ''' , INVRES= '''||P_INVRES || ''' , INVTIM= '''||P_INVTIM || '''  WHERE RRN(GPDATWEB.INVERS) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateInvers', StringSQL);
END
GO


