
    
--DROP PROCEDURE GPSQLWEB.procCreateTabcf
    
CREATE PROCEDURE GPSQLWEB.procCreateTabcf
(
   IN P_NTAB DECIMAL(2 , 0),
IN P_NOMTAB VARCHAR(30),
IN P_COMAEF DECIMAL(10 , 2),
IN P_COMAPF DECIMAL(10 , 2),
IN P_COMANF DECIMAL(9 , 6),
IN P_COMMOF DECIMAL(10 , 2),
IN P_COMCOF DECIMAL(9 , 6),
IN P_COMMAF DECIMAL(10 , 2),
IN P_COMMIF DECIMAL(10 , 2),
IN P_COMPOL DECIMAL(9 , 6),

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;

  SET P_MSGCODE = 9999;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.TABCF WHERE NTAB =  P_NTAB ;

  IF V_CANT > 0 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabcf', StringSQL);
        RETURN;
  END IF;

  INSERT INTO GPDATWEB.TABCF (NTAB ,NOMTAB ,COMAEF ,COMAPF ,COMANF ,COMMOF ,COMCOF ,COMMAF ,COMMIF ,COMPOL ) VALUES ( P_NTAB , P_NOMTAB , P_COMAEF , P_COMAPF , P_COMANF , P_COMMOF , P_COMCOF , P_COMMAF , P_COMMIF , P_COMPOL );

  Set StringSQL = 'INSERT INTO GPDATWEB.TABCF (NTAB ,NOMTAB ,COMAEF ,COMAPF ,COMANF ,COMMOF ,COMCOF ,COMMAF ,COMMIF ,COMPOL ) VALUES ( '''|| P_NTAB || ''' , '''|| P_NOMTAB || ''' , '''|| P_COMAEF || ''' , '''|| P_COMAPF || ''' , '''|| P_COMANF || ''' , '''|| P_COMMOF || ''' , '''|| P_COMCOF || ''' , '''|| P_COMMAF || ''' , '''|| P_COMMIF || ''' , '''|| P_COMPOL || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateTabcf', StringSQL);
  SET P_MSGCODE = 0;
END
GO


