
-- DROP PROCEDURE GPSQLWEB.procUpdateTabcf
    
CREATE PROCEDURE GPSQLWEB.procUpdateTabcf
(
    IN P_ROWID BIGINT,
 IN P_NTAB DECIMAL(2 , 0),
IN P_NOMTAB VARCHAR(30),
IN P_COMAEF DECIMAL(10 , 2),
IN P_COMAPF DECIMAL(10 , 2),
IN P_COMANF DECIMAL(9 , 6),
IN P_COMMOF DECIMAL(10 , 2),
IN P_COMCOF DECIMAL(9 , 6),
IN P_COMMAF DECIMAL(10 , 2),
IN P_COMMIF DECIMAL(10 , 2),
IN P_COMPOL DECIMAL(9 , 6),

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.TABCF WHERE RRN(GPDATWEB.TABCF) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabcf', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabcf', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.TABCF SET NTAB= P_NTAB , NOMTAB= P_NOMTAB , COMAEF= P_COMAEF , COMAPF= P_COMAPF , COMANF= P_COMANF , COMMOF= P_COMMOF , COMCOF= P_COMCOF , COMMAF= P_COMMAF , COMMIF= P_COMMIF , COMPOL= P_COMPOL  WHERE RRN(GPDATWEB.TABCF) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.TABCF SET NTAB= '''||P_NTAB || ''' , NOMTAB= '''||P_NOMTAB || ''' , COMAEF= '''||P_COMAEF || ''' , COMAPF= '''||P_COMAPF || ''' , COMANF= '''||P_COMANF || ''' , COMMOF= '''||P_COMMOF || ''' , COMCOF= '''||P_COMCOF || ''' , COMMAF= '''||P_COMMAF || ''' , COMMIF= '''||P_COMMIF || ''' , COMPOL= '''||P_COMPOL || '''  WHERE RRN(GPDATWEB.TABCF) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTabcf', StringSQL);
END
GO


