
-- DROP PROCEDURE GPSQLWEB.procUpdateGpprpopc
    
CREATE PROCEDURE GPSQLWEB.procUpdateGpprpopc
(
    IN P_ROWID BIGINT,
 IN P_OPCARE varchar(4),
 IN P_OPCOPC varchar(1),
 IN P_OPCEDA INTEGER,
 IN P_OPCCLI varchar(12),
 IN P_OPCEDD INTEGER,
 IN P_OPCEDH INTEGER,
 IN P_OPCFIJ double,
 IN P_OPCVAR double,
 IN P_OPCUSR varchar(10),
 IN P_OPCDSP varchar(10),
 IN P_OPCFEC INTEGER,
 IN P_OPCTIM INTEGER,

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.GPPRPOPC WHERE RRN(GPDATWEB.GPPRPOPC) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateGpprpopc', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateGpprpopc', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.GPPRPOPC SET OPCARE= P_OPCARE , OPCOPC= P_OPCOPC , OPCEDA= P_OPCEDA , OPCCLI= P_OPCCLI , OPCEDD= P_OPCEDD , OPCEDH= P_OPCEDH , OPCFIJ= P_OPCFIJ , OPCVAR= P_OPCVAR , OPCUSR= P_OPCUSR , OPCDSP= P_OPCDSP , OPCFEC= P_OPCFEC , OPCTIM= P_OPCTIM  WHERE RRN(GPDATWEB.GPPRPOPC) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.GPPRPOPC SET OPCARE= '''||P_OPCARE || ''' , OPCOPC= '''||P_OPCOPC || ''' , OPCEDA= '''||P_OPCEDA || ''' , OPCCLI= '''||P_OPCCLI || ''' , OPCEDD= '''||P_OPCEDD || ''' , OPCEDH= '''||P_OPCEDH || ''' , OPCFIJ= '''||P_OPCFIJ || ''' , OPCVAR= '''||P_OPCVAR || ''' , OPCUSR= '''||P_OPCUSR || ''' , OPCDSP= '''||P_OPCDSP || ''' , OPCFEC= '''||P_OPCFEC || ''' , OPCTIM= '''||P_OPCTIM || '''  WHERE RRN(GPDATWEB.GPPRPOPC) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateGpprpopc', StringSQL);
END
GO


