
    
--DROP PROCEDURE GPSQLWEB.procCreateGpprpopc
    
CREATE PROCEDURE GPSQLWEB.procCreateGpprpopc
(
   IN P_OPCARE VARCHAR(4),
 IN P_OPCOPC VARCHAR(1),
 IN P_OPCEDA INTEGER,
 IN P_OPCCLI VARCHAR(12),
 IN P_OPCEDD INTEGER,
 IN P_OPCEDH INTEGER,
 IN P_OPCFIJ DOUBLE,
 IN P_OPCVAR DOUBLE,
 IN P_OPCUSR VARCHAR(10),
 IN P_OPCDSP VARCHAR(10),
 IN P_OPCFEC INTEGER,
 IN P_OPCTIM INTEGER,

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.GPPRPOPC (OPCARE ,OPCOPC ,OPCEDA ,OPCCLI ,OPCEDD ,OPCEDH ,OPCFIJ ,OPCVAR ,OPCUSR ,OPCDSP ,OPCFEC ,OPCTIM ) VALUES ( P_OPCARE , P_OPCOPC , P_OPCEDA , P_OPCCLI , P_OPCEDD , P_OPCEDH , P_OPCFIJ , P_OPCVAR , P_OPCUSR , P_OPCDSP , P_OPCFEC , P_OPCTIM );

  Set StringSQL = 'INSERT INTO GPDATWEB.GPPRPOPC (OPCARE ,OPCOPC ,OPCEDA ,OPCCLI ,OPCEDD ,OPCEDH ,OPCFIJ ,OPCVAR ,OPCUSR ,OPCDSP ,OPCFEC ,OPCTIM ) VALUES ( '''|| P_OPCARE || ''' , '''|| P_OPCOPC || ''' , '''|| P_OPCEDA || ''' , '''|| P_OPCCLI || ''' , '''|| P_OPCEDD || ''' , '''|| P_OPCEDH || ''' , '''|| P_OPCFIJ || ''' , '''|| P_OPCVAR || ''' , '''|| P_OPCUSR || ''' , '''|| P_OPCDSP || ''' , '''|| P_OPCFEC || ''' , '''|| P_OPCTIM || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateGpprpopc', StringSQL);
  SET P_MSGCODE = 0;
END
GO


