
    
--DROP PROCEDURE GPSQLWEB.procCreateAa2cab1
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2cab1
(
   IN P_AREA VARCHAR(4),
 IN P_NBANCO VARCHAR(40),
 IN P_NRIF VARCHAR(12),
 IN P_NNIF VARCHAR(12),
 IN P_NDIRE VARCHAR(60),
 IN P_NBANC INTEGER,
 IN P_NTELE VARCHAR(15),
 IN P_NRESPO VARCHAR(40),
 IN P_NFILLER VARCHAR(80),
 IN P_USUARIO VARCHAR(10),
 IN P_PANTALLA VARCHAR(10),
 IN P_FECHA INTEGER,

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.AA2CAB1 (AREA ,NBANCO ,NRIF ,NNIF ,NDIRE ,NBANC ,NTELE ,NRESPO ,NFILLER ,USUARIO ,PANTALLA ,FECHA ) VALUES ( P_AREA , P_NBANCO , P_NRIF , P_NNIF , P_NDIRE , P_NBANC , P_NTELE , P_NRESPO , P_NFILLER , P_USUARIO , P_PANTALLA , P_FECHA );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2CAB1 (AREA ,NBANCO ,NRIF ,NNIF ,NDIRE ,NBANC ,NTELE ,NRESPO ,NFILLER ,USUARIO ,PANTALLA ,FECHA ) VALUES ( '''|| P_AREA || ''' , '''|| P_NBANCO || ''' , '''|| P_NRIF || ''' , '''|| P_NNIF || ''' , '''|| P_NDIRE || ''' , '''|| P_NBANC || ''' , '''|| P_NTELE || ''' , '''|| P_NRESPO || ''' , '''|| P_NFILLER || ''' , '''|| P_USUARIO || ''' , '''|| P_PANTALLA || ''' , '''|| P_FECHA || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2cab1', StringSQL);
  SET P_MSGCODE = 0;
END
GO

