
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2cab1
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2cab1
(
     IN P_AREA VARCHAR(4),
            IN P_NBANCO VARCHAR(40),
            IN P_NRIF VARCHAR(12),
            IN P_NNIF VARCHAR(12),
            IN P_NDIRE VARCHAR(60),
            IN P_NBANC INTEGER,
            IN P_NTELE VARCHAR(15),
            IN P_NRESPO VARCHAR(40),
            IN P_NFILLER VARCHAR(80),
            IN P_USUARIO VARCHAR(10),
            IN P_PANTALLA VARCHAR(10),
            IN P_FECHA INTEGER,
           
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2CAB1 WHERE AREA = P_AREA;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2cab1', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2cab1', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2CAB1 SET NBANCO= P_NBANCO , NRIF= P_NRIF , NNIF= P_NNIF , NDIRE= P_NDIRE , NBANC= P_NBANC , NTELE= P_NTELE , NRESPO= P_NRESPO , NFILLER= P_NFILLER , USUARIO= P_USUARIO , PANTALLA= P_PANTALLA , FECHA= P_FECHA  WHERE AREA= P_AREA ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AA2CAB1 SET NBANCO= '''||P_NBANCO || ''' , NRIF= '''||P_NRIF || ''' , NNIF= '''||P_NNIF || ''' , NDIRE= '''||P_NDIRE || ''' , NBANC= '''||P_NBANC || ''' , NTELE= '''||P_NTELE || ''' , NRESPO= '''||P_NRESPO || ''' , NFILLER= '''||P_NFILLER || ''' , USUARIO= '''||P_USUARIO || ''' , PANTALLA= '''||P_PANTALLA || ''' , FECHA= '''||P_FECHA || '''  WHERE AREA= '''||P_AREA|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2cab1', StringSQL);
END
GO


