--DROP PROCEDURE GPSQLWEB.PROCCLCTLFO2PM
CREATE PROCEDURE "GPSQLWEB"."PROCCLCTLFO2PM" 
        (
        AREA CHAR(4),
        CLICLA DECIMAL(7 , 0),
        CLITC2 DECIMAL(3 , 0) 
        )
	LANGUAGE RPGLE
	PARAMETER STYLE GENERAL
	DETERMINISTIC
	NO SQL 
	SPECIFIC GPSQLWEB.PROCCLCTLFO2PM 
	NEW SAVEPOINT LEVEL
	EXTERNAL NAME 'GPPGMWEB/CLCTLFO2PM';

--CALL GPSQLWEB.PROCCLCTLFO2PM(CLICLA, CLITC1, AREA)

