--DROP PROCEDURE GPSQLWEB.PROCCLCOPCON1
CREATE PROCEDURE "GPSQLWEB"."PROCCLCOPCON1" 
        (
            AREA_ACTUAL CHAR(4)
        )
	LANGUAGE RPGLE
	PARAMETER STYLE GENERAL
	DETERMINISTIC
	NO SQL 
	SPECIFIC GPSQLWEB.PROCCLCOPCON1 
	NEW SAVEPOINT LEVEL
	EXTERNAL NAME 'GPPGMWEB/CLCOPCON1';

--CALL GPSQLWEB.PROCCLCOPCON1(AREA)

