CREATE PROCEDURE "GPSQLWEB"."PROCGES001" 
        ()
	LANGUAGE RPGLE
	PARAMETER STYLE GENERAL
	DETERMINISTIC
	NO SQL 
	SPECIFIC GPSQLWEB.PROCGES001 
	NEW SAVEPOINT LEVEL
	EXTERNAL NAME 'GPPGMBASE/GES001';
