--DROP PROCEDURE GPSQLWEB.PROCCLCRECTA4
CREATE PROCEDURE "GPSQLWEB"."PROCCLCRECTA4" 
        (
        CLICLA DECIMAL(7 , 0),
        CLITC1 DECIMAL(2 , 0) ,
        CLINOM CHAR(20),
        CLIAPE CHAR(15),
        CLIAP2 CHAR(15),
        CLISEX CHAR(1),
        AREA CHAR(4)
        )
	LANGUAGE RPGLE
	PARAMETER STYLE GENERAL
	DETERMINISTIC
	NO SQL 
	SPECIFIC GPSQLWEB.PROCCLCRECTA4 
	NEW SAVEPOINT LEVEL
	EXTERNAL NAME 'GPPGMWEB/CLCRECTA4';

--CALL GPSQLWEB.PROCCLCRECTA4(CLICLA, CLITC1, CLINOM, CLIAPE, CLIAP2, CLISEX, AREA)

