CREATE PROCEDURE "GPSQLWEB"."PROCINTCOH2I" 
        (
        IN CAMMOD CHAR(3),
        IN COMAEF DECIMAL(15 , 2),
        IN APRECI DECIMAL(15 , 2),
        IN CLICLA DECIMAL(7 , 0),
        IN VLOCOA CHAR(12),
        IN NUMOP1 DECIMAL(10 , 0),
        IN WECHA DECIMAL(6 , 0),
        IN COSDIV DECIMAL(3 , 0),
        IN CORRES DECIMAL(7 , 0),
        IN CONLIQ CHAR(1),
        IN CODOPE CHAR(3)
        )
	LANGUAGE RPGLE
	PARAMETER STYLE GENERAL
	DETERMINISTIC
	NO SQL 
	SPECIFIC GPSQLWEB.PROCINTCOH2I 
	NEW SAVEPOINT LEVEL
	EXTERNAL NAME 'GPPGMBASE/INTCOH2I';


--CALL GPSQLWEB.PROCINTCOH2I('CC2', V_COMAEF, 0, V_CLICLA, V_VLOCOA, 0, V_WECHA, V_COSDIV, 0 , 'H' , '   ')
