--DROP PROCEDURE GPSQLWEB.PROCCLCRECTA7
CREATE PROCEDURE "GPSQLWEB"."PROCCLCRECTA7" 
        (
        CLIEMP CHAR(2),
        CLIDEL CHAR(2),
        CLICLA VARCHAR(7)
        )
	LANGUAGE RPGLE
	PARAMETER STYLE GENERAL
	DETERMINISTIC
	NO SQL 
	SPECIFIC GPSQLWEB.PROCCLCRECTA7 
	NEW SAVEPOINT LEVEL
	EXTERNAL NAME 'GPPGMWEB/CLCRECTA7';

--CALL GPSQLWEB.PROCCLCRECTA7(CLIEMP, CLIDEL, CLICLA)

