--DROP PROCEDURE GPSQLWEB.PROCCLCOPCON
CREATE PROCEDURE "GPSQLWEB"."PROCCLCOPCON" 
        (
        AREA_ACTUAL CHAR(4), 
        AREA_NUEVA CHAR(4), 
        DIVISA DECIMAL(3 , 0)
        )
	LANGUAGE RPGLE
	PARAMETER STYLE GENERAL
	DETERMINISTIC
	NO SQL 
	SPECIFIC GPSQLWEB.PROCCLCOPCON 
	NEW SAVEPOINT LEVEL
	EXTERNAL NAME 'GPPGMWEB/CLCOPCON';

--CALL GPSQLWEB.PROCCLCOPCON('BASE','XXXX', 000)

