
-- DROP PROCEDURE GPSQLWEB.procUpdateTableHelp
    
CREATE PROCEDURE GPSQLWEB.procUpdateTableHelp
(
     IN P_ID INTEGER,
            IN P_CODE VARCHAR(2),
            IN P_NAME VARCHAR(100),
            IN P_TABLENAME VARCHAR(100),
            IN P_TABLECODE VARCHAR(100),
            IN P_TABLEDESC VARCHAR(100),
            IN P_TABLEPARENT VARCHAR(100),
           
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500)
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Not Null Default '';
  UPDATE GPSQLWEB.TABLEHELP SET CODE= P_CODE , NAME= P_NAME , TABLENAME= P_TABLENAME , TABLECODE= P_TABLECODE , TABLEDESC= P_TABLEDESC , TABLEPARENT= P_TABLEPARENT  WHERE ID= P_ID ;

  Set StringSQL = 'UPDATE GPSQLWEB.TABLEHELP SET CODE= '''||P_CODE || ''' , NAME= '''||P_NAME || ''' , TABLENAME= '''||P_TABLENAME || ''' , TABLECODE= '''||P_TABLECODE || ''' , TABLEDESC= '''||P_TABLEDESC || ''' , TABLEPARENT= '''||P_TABLEPARENT || '''  WHERE ID= '''||P_ID|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateTableHelp', StringSQL);
END
GO


