
--DROP PROCEDURE GPSQLWEB.procCreateAa2cta
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2cta
(
    IN P_CTAEMP VARCHAR(2),
    IN P_CTADEL VARCHAR(2),
    IN P_CTADIV NUMERIC(3 , 0),
    IN P_CTAGEN VARCHAR(12),
    IN P_CTACTE NUMERIC(14 , 0),
    IN P_CTACAT NUMERIC(2 , 0),
    IN P_CTASUB NUMERIC(2 , 0),
    IN P_CTATCT VARCHAR(1),
    IN P_CTANOM VARCHAR(40),
    IN P_CTAMDD DECIMAL(15 , 2),
    IN P_CTAMDC DECIMAL(15 , 2),
    IN P_CTAMED DECIMAL(15 , 2),
    IN P_CTAMEC DECIMAL(15 , 2),
    IN P_CTAAPE DECIMAL(7 , 0),
    IN P_CTAULM DECIMAL(7 , 0),
    IN P_CTACAN DECIMAL(7 , 0),
    IN P_CTABLO DECIMAL(7 , 0),
    IN P_CTALIQ VARCHAR(1),
    IN P_CTAFRL VARCHAR(1),
    IN P_CTAIID DECIMAL(6 , 0),
    IN P_CTAFID DECIMAL(6 , 0),
    IN P_CTATDB VARCHAR(2),
    IN P_CTASDB VARCHAR(1),
    IN P_CTAIND DECIMAL(5 , 3),
    IN P_CTAIMD DECIMAL(5 , 3),
    IN P_CTAIXD DECIMAL(5 , 3),
    IN P_CTAIIC DECIMAL(6 , 0),
    IN P_CTAFIC DECIMAL(6 , 0),
    IN P_CTATCR VARCHAR(2),
    IN P_CTASCR VARCHAR(1),
    IN P_CTAINC DECIMAL(5 , 3),
    IN P_CTAIMC DECIMAL(5 , 3),
    IN P_CTAIXC DECIMAL(5 , 3),
    IN P_CTALIM DECIMAL(11 , 0),
    IN P_CTAIEX DECIMAL(5 , 3),
    IN P_CTACOM DECIMAL(5 , 3),
    IN P_CTALCD DECIMAL(14 , 0),
    IN P_CTALCC DECIMAL(14 , 0),
    IN P_CTAILC DECIMAL(6 , 0),
    IN P_CTAILD DECIMAL(6 , 0),
    IN P_CTAAID DECIMAL(9 , 0),
    IN P_CTAAIA DECIMAL(9 , 0),
    IN P_CTAARE DECIMAL(9 , 0),
    IN P_CTABL1 DECIMAL(3 , 0),
    IN P_CTABL2 DECIMAL(3 , 0),
    IN P_CTABCD DECIMAL(8 , 0),
    IN P_CTABCC DECIMAL(8 , 0),
    IN P_CTABBD DECIMAL(10 , 0),
    IN P_CTABBC DECIMAL(10 , 0),
    IN P_CTABSD DECIMAL(10 , 0),
    IN P_CTABSC DECIMAL(10 , 0),
    IN P_CTASFD DECIMAL(15 , 2),
    IN P_CTASFP DECIMAL(15 , 2),
    IN P_CTASDI DECIMAL(15 , 2),
    IN P_CTASPT DECIMAL(15 , 2),
    IN P_CTASVD DECIMAL(15 , 2),
    IN P_CTASVP DECIMAL(15 , 2),
    IN P_CTABL4 VARCHAR(1),
    IN P_CTAFRE VARCHAR(1),
    IN P_CTASIT VARCHAR(1),
    IN P_CTARES DECIMAL(5 , 0),
    IN P_CTACGE VARCHAR(1),
    IN P_CTAADD DECIMAL(15 , 2),
    IN P_CTAADC DECIMAL(15 , 2),
    IN P_CTAAPD DECIMAL(15 , 2),
    IN P_CTAAPC DECIMAL(15 , 2),
    IN P_CTADPR VARCHAR(16),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  DECLARE END_TABLE INT DEFAULT 0 ;
  DECLARE V_TABCLA VARCHAR ( 4 ) DEFAULT '' ;
  DECLARE V_AREA VARCHAR ( 4 ) DEFAULT '' ;
  DECLARE C CURSOR FOR SELECT upper( TABEMP CONCAT TABDEL) FROM GPDATWEB . AA2MTAB WHERE TABORI = P_CTAEMP CONCAT P_CTADEL and upper( TABEMP CONCAT TABDEL) <> P_CTAEMP CONCAT P_CTADEL;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET END_TABLE = 1 ;
  SET P_MSGCODE = 9999;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2CTA WHERE CTAGEN =  P_CTAGEN and CTAEMP=P_CTAEMP and  CTADEL =P_CTADEL ;

  IF V_CANT > 0 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procCreateAa2cta', StringSQL);
        RETURN;
  END IF;

  SELECT CAST (substr( digits (DAY(current timestamp)),9) || substr( digits (MONTH(current timestamp)),9) || substr( digits (YEAR(current timestamp)),9) AS DECIMAL(8,0))
        INTO P_CTAAPE FROM SYSIBM.SYSDUMMY1;

  INSERT INTO GPDATWEB.AA2CTA (CTAEMP ,CTADEL ,CTADIV ,CTAGEN ,CTACTE ,CTACAT ,CTASUB ,CTATCT ,CTANOM ,CTAMDD ,CTAMDC ,CTAMED ,CTAMEC ,CTAAPE ,CTAULM ,CTACAN ,CTABLO ,CTALIQ ,CTAFRL ,CTAIID ,CTAFID ,CTATDB ,CTASDB ,CTAIND ,CTAIMD ,CTAIXD ,CTAIIC ,CTAFIC ,CTATCR ,CTASCR ,CTAINC ,CTAIMC ,CTAIXC ,CTALIM ,CTAIEX ,CTACOM ,CTALCD ,CTALCC ,CTAILC ,CTAILD ,CTAAID ,CTAAIA ,CTAARE ,CTABL1 ,CTABL2 ,CTABCD ,CTABCC ,CTABBD ,CTABBC ,CTABSD ,CTABSC ,CTASFD ,CTASFP ,CTASDI ,CTASPT ,CTASVD ,CTASVP ,CTABL4 ,CTAFRE ,CTASIT ,CTARES ,CTACGE ,CTAADD ,CTAADC ,CTAAPD ,CTAAPC ,CTADPR ) 
        VALUES ( P_CTAEMP , P_CTADEL , P_CTADIV , P_CTAGEN , P_CTACTE , P_CTACAT , P_CTASUB , P_CTATCT , P_CTANOM , P_CTAMDD , P_CTAMDC , P_CTAMED , P_CTAMEC , P_CTAAPE , P_CTAULM , P_CTACAN , P_CTABLO , P_CTALIQ , P_CTAFRL , P_CTAIID , P_CTAFID , P_CTATDB , P_CTASDB , P_CTAIND , P_CTAIMD , P_CTAIXD , P_CTAIIC , P_CTAFIC , P_CTATCR , P_CTASCR , P_CTAINC , P_CTAIMC , P_CTAIXC , P_CTALIM , P_CTAIEX , P_CTACOM , P_CTALCD , P_CTALCC , P_CTAILC , P_CTAILD , P_CTAAID , P_CTAAIA , P_CTAARE , P_CTABL1 , P_CTABL2 , P_CTABCD , P_CTABCC , P_CTABBD , P_CTABBC , P_CTABSD , P_CTABSC , P_CTASFD , P_CTASFP , P_CTASDI , P_CTASPT , P_CTASVD , P_CTASVP , P_CTABL4 , P_CTAFRE , P_CTASIT , P_CTARES , P_CTACGE , P_CTAADD , P_CTAADC , P_CTAAPD , P_CTAAPC , P_CTADPR );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2CTA (CTAEMP ,CTADEL ,CTADIV ,CTAGEN ,CTACTE ,CTACAT ,CTASUB ,CTATCT ,CTANOM ,CTAMDD ,CTAMDC ,CTAMED ,CTAMEC ,CTAAPE ,CTAULM ,CTACAN ,CTABLO ,CTALIQ ,CTAFRL ,CTAIID ,CTAFID ,CTATDB ,CTASDB ,CTAIND ,CTAIMD ,CTAIXD ,CTAIIC ,CTAFIC ,CTATCR ,CTASCR ,CTAINC ,CTAIMC ,CTAIXC ,CTALIM ,CTAIEX ,CTACOM ,CTALCD ,CTALCC ,CTAILC ,CTAILD ,CTAAID ,CTAAIA ,CTAARE ,CTABL1 ,CTABL2 ,CTABCD ,CTABCC ,CTABBD ,CTABBC ,CTABSD ,CTABSC ,CTASFD ,CTASFP ,CTASDI ,CTASPT ,CTASVD ,CTASVP ,CTABL4 ,CTAFRE ,CTASIT ,CTARES ,CTACGE ,CTAADD ,CTAADC ,CTAAPD ,CTAAPC ,CTADPR ) VALUES ( '''|| P_CTAEMP || ''' , '''|| P_CTADEL || ''' , '''|| P_CTADIV || ''' , '''|| P_CTAGEN || ''' , '''|| P_CTACTE || ''' , '''|| P_CTACAT || ''' , '''|| P_CTASUB || ''' , '''|| P_CTATCT || ''' , '''|| P_CTANOM || ''' , '''|| P_CTAMDD || ''' , '''|| P_CTAMDC || ''' , '''|| P_CTAMED || ''' , '''|| P_CTAMEC || ''' , '''|| P_CTAAPE || ''' , '''|| P_CTAULM || ''' , '''|| P_CTACAN || ''' , '''|| P_CTABLO || ''' , '''|| P_CTALIQ || ''' , '''|| P_CTAFRL || ''' , '''|| P_CTAIID || ''' , '''|| P_CTAFID || ''' , '''|| P_CTATDB || ''' , '''|| P_CTASDB || ''' , '''|| P_CTAIND || ''' , '''|| P_CTAIMD || ''' , '''|| P_CTAIXD || ''' , '''|| P_CTAIIC || ''' , '''|| P_CTAFIC || ''' , '''|| P_CTATCR || ''' , '''|| P_CTASCR || ''' , '''|| P_CTAINC || ''' , '''|| P_CTAIMC || ''' , '''|| P_CTAIXC || ''' , '''|| P_CTALIM || ''' , '''|| P_CTAIEX || ''' , '''|| P_CTACOM || ''' , '''|| P_CTALCD || ''' , '''|| P_CTALCC || ''' , '''|| P_CTAILC || ''' , '''|| P_CTAILD || ''' , '''|| P_CTAAID || ''' , '''|| P_CTAAIA || ''' , '''|| P_CTAARE || ''' , '''|| P_CTABL1 || ''' , '''|| P_CTABL2 || ''' , '''|| P_CTABCD || ''' , '''|| P_CTABCC || ''' , '''|| P_CTABBD || ''' , '''|| P_CTABBC || ''' , '''|| P_CTABSD || ''' , '''|| P_CTABSC || ''' , '''|| P_CTASFD || ''' , '''|| P_CTASFP || ''' , '''|| P_CTASDI || ''' , '''|| P_CTASPT || ''' , '''|| P_CTASVD || ''' , '''|| P_CTASVP || ''' , '''|| P_CTABL4 || ''' , '''|| P_CTAFRE || ''' , '''|| P_CTASIT || ''' , '''|| P_CTARES || ''' , '''|| P_CTACGE || ''' , '''|| P_CTAADD || ''' , '''|| P_CTAADC || ''' , '''|| P_CTAAPD || ''' , '''|| P_CTAAPC || ''' , '''|| P_CTADPR || ''' )'; 
  --CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2cta', StringSQL);

  OPEN C ;
    FETCH FROM C INTO V_TABCLA ;

    WHILE END_TABLE = 0 DO

        SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2CTA WHERE CTAGEN =  P_CTAGEN and CTAEMP=SUBSTR ( V_TABCLA , 1 , 2 ) and  CTADEL = SUBSTR ( V_TABCLA , 3 , 2 ) ;

        IF ( V_TABCLA != ( P_CTAEMP CONCAT P_CTADEL ) AND V_CANT = 0 ) THEN
            INSERT INTO GPDATWEB.AA2CTA (CTAEMP ,CTADEL ,CTADIV ,CTAGEN ,CTACTE ,CTACAT ,CTASUB ,CTATCT ,CTANOM ,CTAMDD ,CTAMDC ,CTAMED ,CTAMEC ,CTAAPE ,CTAULM ,CTACAN ,CTABLO ,CTALIQ ,CTAFRL ,CTAIID ,CTAFID ,CTATDB ,CTASDB ,CTAIND ,CTAIMD ,CTAIXD ,CTAIIC ,CTAFIC ,CTATCR ,CTASCR ,CTAINC ,CTAIMC ,CTAIXC ,CTALIM ,CTAIEX ,CTACOM ,CTALCD ,CTALCC ,CTAILC ,CTAILD ,CTAAID ,CTAAIA ,CTAARE ,CTABL1 ,CTABL2 ,CTABCD ,CTABCC ,CTABBD ,CTABBC ,CTABSD ,CTABSC ,CTASFD ,CTASFP ,CTASDI ,CTASPT ,CTASVD ,CTASVP ,CTABL4 ,CTAFRE ,CTASIT ,CTARES ,CTACGE ,CTAADD ,CTAADC ,CTAAPD ,CTAAPC ,CTADPR ) 
                VALUES ( SUBSTR ( V_TABCLA , 1 , 2 ) , SUBSTR ( V_TABCLA , 3 , 2 ) , P_CTADIV , P_CTAGEN , P_CTACTE , P_CTACAT , P_CTASUB , P_CTATCT , P_CTANOM , P_CTAMDD , P_CTAMDC , P_CTAMED , P_CTAMEC , P_CTAAPE , P_CTAULM , P_CTACAN , P_CTABLO , P_CTALIQ , P_CTAFRL , P_CTAIID , P_CTAFID , P_CTATDB , P_CTASDB , P_CTAIND , P_CTAIMD , P_CTAIXD , P_CTAIIC , P_CTAFIC , P_CTATCR , P_CTASCR , P_CTAINC , P_CTAIMC , P_CTAIXC , P_CTALIM , P_CTAIEX , P_CTACOM , P_CTALCD , P_CTALCC , P_CTAILC , P_CTAILD , P_CTAAID , P_CTAAIA , P_CTAARE , P_CTABL1 , P_CTABL2 , P_CTABCD , P_CTABCC , P_CTABBD , P_CTABBC , P_CTABSD , P_CTABSC , P_CTASFD , P_CTASFP , P_CTASDI , P_CTASPT , P_CTASVD , P_CTASVP , P_CTABL4 , P_CTAFRE , P_CTASIT , P_CTARES , P_CTACGE , P_CTAADD , P_CTAADC , P_CTAAPD , P_CTAAPC , P_CTADPR );
        END IF;
    FETCH FROM C INTO V_TABCLA ;
    END WHILE ;

  CLOSE C ;
  SET V_AREA = P_CTAEMP || P_CTADEL;

  CALL GPSQLWEB.PROCCLCOPCON1(V_AREA);

  SET P_MSGCODE = 0;
END
GO


