
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2cta
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2cta
(
    IN P_ROWID BIGINT,
    IN P_CTAEMP VARCHAR(2),
    IN P_CTADEL VARCHAR(2),
    IN P_CTADIV NUMERIC(3 , 0),
    IN P_CTAGEN VARCHAR(12),
    IN P_CTACTE NUMERIC(14 , 0),
    IN P_CTACAT NUMERIC(2 , 0),
    IN P_CTASUB NUMERIC(2 , 0),
    IN P_CTATCT VARCHAR(1),
    IN P_CTANOM VARCHAR(40),
    IN P_CTAMDD DECIMAL(15 , 2),
    IN P_CTAMDC DECIMAL(15 , 2),
    IN P_CTAMED DECIMAL(15 , 2),
    IN P_CTAMEC DECIMAL(15 , 2),
    IN P_CTAAPE DECIMAL(7 , 0),
    IN P_CTAULM DECIMAL(7 , 0),
    IN P_CTACAN DECIMAL(7 , 0),
    IN P_CTABLO DECIMAL(7 , 0),
    IN P_CTALIQ VARCHAR(1),
    IN P_CTAFRL VARCHAR(1),
    IN P_CTAIID DECIMAL(6 , 0),
    IN P_CTAFID DECIMAL(6 , 0),
    IN P_CTATDB VARCHAR(2),
    IN P_CTASDB VARCHAR(1),
    IN P_CTAIND DECIMAL(5 , 3),
    IN P_CTAIMD DECIMAL(5 , 3),
    IN P_CTAIXD DECIMAL(5 , 3),
    IN P_CTAIIC DECIMAL(6 , 0),
    IN P_CTAFIC DECIMAL(6 , 0),
    IN P_CTATCR VARCHAR(2),
    IN P_CTASCR VARCHAR(1),
    IN P_CTAINC DECIMAL(5 , 3),
    IN P_CTAIMC DECIMAL(5 , 3),
    IN P_CTAIXC DECIMAL(5 , 3),
    IN P_CTALIM DECIMAL(11 , 0),
    IN P_CTAIEX DECIMAL(5 , 3),
    IN P_CTACOM DECIMAL(5 , 3),
    IN P_CTALCD DECIMAL(14 , 0),
    IN P_CTALCC DECIMAL(14 , 0),
    IN P_CTAILC DECIMAL(6 , 0),
    IN P_CTAILD DECIMAL(6 , 0),
    IN P_CTAAID DECIMAL(9 , 0),
    IN P_CTAAIA DECIMAL(9 , 0),
    IN P_CTAARE DECIMAL(9 , 0),
    IN P_CTABL1 DECIMAL(3 , 0),
    IN P_CTABL2 DECIMAL(3 , 0),
    IN P_CTABCD DECIMAL(8 , 0),
    IN P_CTABCC DECIMAL(8 , 0),
    IN P_CTABBD DECIMAL(10 , 0),
    IN P_CTABBC DECIMAL(10 , 0),
    IN P_CTABSD DECIMAL(10 , 0),
    IN P_CTABSC DECIMAL(10 , 0),
    IN P_CTASFD DECIMAL(15 , 2),
    IN P_CTASFP DECIMAL(15 , 2),
    IN P_CTASDI DECIMAL(15 , 2),
    IN P_CTASPT DECIMAL(15 , 2),
    IN P_CTASVD DECIMAL(15 , 2),
    IN P_CTASVP DECIMAL(15 , 2),
    IN P_CTABL4 VARCHAR(1),
    IN P_CTAFRE VARCHAR(1),
    IN P_CTASIT VARCHAR(1),
    IN P_CTARES DECIMAL(5 , 0),
    IN P_CTACGE VARCHAR(1),
    IN P_CTAADD DECIMAL(15 , 2),
    IN P_CTAADC DECIMAL(15 , 2),
    IN P_CTAAPD DECIMAL(15 , 2),
    IN P_CTAAPC DECIMAL(15 , 2),
    IN P_CTADPR VARCHAR(16),
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  DECLARE END_TABLE INT DEFAULT 0 ;
  DECLARE V_TABCLA VARCHAR ( 4 ) DEFAULT '' ;
  DECLARE V_AREA VARCHAR ( 4 ) DEFAULT '' ;
  DECLARE C CURSOR FOR SELECT upper( TABEMP CONCAT TABDEL) FROM GPDATWEB . AA2MTAB WHERE TABORI = P_CTAEMP CONCAT P_CTADEL and upper( TABEMP CONCAT TABDEL) <> P_CTAEMP CONCAT P_CTADEL;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET END_TABLE = 1 ;
  SET P_MSGCODE = 9999;

  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2CTA WHERE RRN(GPDATWEB.AA2CTA) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2cta', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2cta', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2CTA SET CTAEMP= P_CTAEMP , CTADEL= P_CTADEL , CTADIV= P_CTADIV , CTAGEN= P_CTAGEN , CTACTE= P_CTACTE , CTACAT= P_CTACAT , CTASUB= P_CTASUB , CTATCT= P_CTATCT , CTANOM= P_CTANOM , CTAMDD= P_CTAMDD , CTAMDC= P_CTAMDC , CTAMED= P_CTAMED , CTAMEC= P_CTAMEC , CTAAPE= P_CTAAPE , CTAULM= P_CTAULM , CTACAN= P_CTACAN , CTABLO= P_CTABLO , CTALIQ= P_CTALIQ , CTAFRL= P_CTAFRL , CTAIID= P_CTAIID , CTAFID= P_CTAFID , CTATDB= P_CTATDB , CTASDB= P_CTASDB , CTAIND= P_CTAIND , CTAIMD= P_CTAIMD , CTAIXD= P_CTAIXD , CTAIIC= P_CTAIIC , CTAFIC= P_CTAFIC , CTATCR= P_CTATCR , CTASCR= P_CTASCR , CTAINC= P_CTAINC , CTAIMC= P_CTAIMC , CTAIXC= P_CTAIXC , CTALIM= P_CTALIM , CTAIEX= P_CTAIEX , CTACOM= P_CTACOM , CTALCD= P_CTALCD , CTALCC= P_CTALCC , CTAILC= P_CTAILC , CTAILD= P_CTAILD , CTAAID= P_CTAAID , CTAAIA= P_CTAAIA , CTAARE= P_CTAARE , CTABL1= P_CTABL1 , CTABL2= P_CTABL2 , CTABCD= P_CTABCD , CTABCC= P_CTABCC , CTABBD= P_CTABBD , CTABBC= P_CTABBC , CTABSD= P_CTABSD , CTABSC= P_CTABSC , CTASFD= P_CTASFD , CTASFP= P_CTASFP , CTASDI= P_CTASDI , CTASPT= P_CTASPT , CTASVD= P_CTASVD , CTASVP= P_CTASVP , CTABL4= P_CTABL4 , CTAFRE= P_CTAFRE , CTASIT= P_CTASIT , CTARES= P_CTARES , CTACGE= P_CTACGE , CTAADD= P_CTAADD , CTAADC= P_CTAADC , CTAAPD= P_CTAAPD , CTAAPC= P_CTAAPC , CTADPR= P_CTADPR  WHERE RRN(GPDATWEB.AA2CTA) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  --Set StringSQL = 'UPDATE GPDATWEB.AA2CTA SET CTAEMP= '''||P_CTAEMP || ''' , CTADEL= '''||P_CTADEL || ''' , CTADIV= '''||P_CTADIV || ''' , CTAGEN= '''||P_CTAGEN || ''' , CTACTE= '''||P_CTACTE || ''' , CTACAT= '''||P_CTACAT || ''' , CTASUB= '''||P_CTASUB || ''' , CTATCT= '''||P_CTATCT || ''' , CTANOM= '''||P_CTANOM || ''' , CTAMDD= '''||P_CTAMDD || ''' , CTAMDC= '''||P_CTAMDC || ''' , CTAMED= '''||P_CTAMED || ''' , CTAMEC= '''||P_CTAMEC || ''' , CTAAPE= '''||P_CTAAPE || ''' , CTAULM= '''||P_CTAULM || ''' , CTACAN= '''||P_CTACAN || ''' , CTABLO= '''||P_CTABLO || ''' , CTALIQ= '''||P_CTALIQ || ''' , CTAFRL= '''||P_CTAFRL || ''' , CTAIID= '''||P_CTAIID || ''' , CTAFID= '''||P_CTAFID || ''' , CTATDB= '''||P_CTATDB || ''' , CTASDB= '''||P_CTASDB || ''' , CTAIND= '''||P_CTAIND || ''' , CTAIMD= '''||P_CTAIMD || ''' , CTAIXD= '''||P_CTAIXD || ''' , CTAIIC= '''||P_CTAIIC || ''' , CTAFIC= '''||P_CTAFIC || ''' , CTATCR= '''||P_CTATCR || ''' , CTASCR= '''||P_CTASCR || ''' , CTAINC= '''||P_CTAINC || ''' , CTAIMC= '''||P_CTAIMC || ''' , CTAIXC= '''||P_CTAIXC || ''' , CTALIM= '''||P_CTALIM || ''' , CTAIEX= '''||P_CTAIEX || ''' , CTACOM= '''||P_CTACOM || ''' , CTALCD= '''||P_CTALCD || ''' , CTALCC= '''||P_CTALCC || ''' , CTAILC= '''||P_CTAILC || ''' , CTAILD= '''||P_CTAILD || ''' , CTAAID= '''||P_CTAAID || ''' , CTAAIA= '''||P_CTAAIA || ''' , CTAARE= '''||P_CTAARE || ''' , CTABL1= '''||P_CTABL1 || ''' , CTABL2= '''||P_CTABL2 || ''' , CTABCD= '''||P_CTABCD || ''' , CTABCC= '''||P_CTABCC || ''' , CTABBD= '''||P_CTABBD || ''' , CTABBC= '''||P_CTABBC || ''' , CTABSD= '''||P_CTABSD || ''' , CTABSC= '''||P_CTABSC || ''' , CTASFD= '''||P_CTASFD || ''' , CTASFP= '''||P_CTASFP || ''' , CTASDI= '''||P_CTASDI || ''' , CTASPT= '''||P_CTASPT || ''' , CTASVD= '''||P_CTASVD || ''' , CTASVP= '''||P_CTASVP || ''' , CTABL4= '''||P_CTABL4 || ''' , CTAFRE= '''||P_CTAFRE || ''' , CTASIT= '''||P_CTASIT || ''' , CTARES= '''||P_CTARES || ''' , CTACGE= '''||P_CTACGE || ''' , CTAADD= '''||P_CTAADD || ''' , CTAADC= '''||P_CTAADC || ''' , CTAAPD= '''||P_CTAAPD || ''' , CTAAPC= '''||P_CTAAPC || ''' , CTADPR= '''||P_CTADPR || '''  WHERE RRN(GPDATWEB.AA2CTA) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2cta', StringSQL);

  
  OPEN C ;
    FETCH FROM C INTO V_TABCLA ;

    WHILE END_TABLE = 0 DO
        IF ( V_TABCLA != ( P_CTAEMP CONCAT P_CTADEL ) ) THEN
            UPDATE GPDATWEB.AA2CTA SET CTADIV= P_CTADIV, CTANOM= P_CTANOM , CTARES= P_CTARES , CTABBD= P_CTABBD, CTABBC= P_CTABBC , CTABSD= P_CTABSD , CTABSC= P_CTABSC , CTABL1= P_CTABL1 , CTABL2= P_CTABL2 , CTABCD= P_CTABCD , CTABCC= P_CTABCC
                    WHERE CTAEMP=SUBSTR ( V_TABCLA , 1 , 2 )  AND CTADEL= SUBSTR ( V_TABCLA , 3 , 2 ) AND CTAGEN= P_CTAGEN ;
        END IF;
    FETCH FROM C INTO V_TABCLA ;
    END WHILE ;

  CLOSE C ;

  SET V_AREA = P_CTAEMP || P_CTADEL;

  CALL GPSQLWEB.PROCCLCOPCON1(V_AREA);

END
GO


