
    
--DROP PROCEDURE GPSQLWEB.procCreateAa2tfis
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2tfis
(
   IN P_FISEMP VARCHAR(2),
 IN P_FISDEL VARCHAR(2),
 IN P_FISCLA INTEGER,
 IN P_FISNOR DOUBLE,
 IN P_FISBEL DOUBLE,
 IN P_FISBE1 DOUBLE,
 IN P_FISDIV DOUBLE,
 IN P_FISINV DOUBLE,
 IN P_FISGIN DOUBLE,
 IN P_FISCAP DOUBLE,
 IN P_FISRDI DOUBLE,
 IN P_FISRD1 DOUBLE,
 IN P_FISCOR DOUBLE,
 IN P_FISIVA DOUBLE,

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  SET P_MSGCODE = 9999; 
  
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TFIS WHERE FISCLA =  P_FISCLA  AND  FISEMP=P_FISEMP AND FISDEL=P_FISDEL;

  IF V_CANT > 0 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2tfis', StringSQL);
        RETURN;
  END IF;

  INSERT INTO GPDATWEB.AA2TFIS (FISEMP ,FISDEL ,FISCLA ,FISNOR ,FISBEL ,FISBE1 ,FISDIV ,FISINV ,FISGIN ,FISCAP ,FISRDI ,FISRD1 ,FISCOR ,FISIVA ) VALUES ( P_FISEMP , P_FISDEL , P_FISCLA , P_FISNOR , P_FISBEL , P_FISBE1 , P_FISDIV , P_FISINV , P_FISGIN , P_FISCAP , P_FISRDI , P_FISRD1 , P_FISCOR , P_FISIVA );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2TFIS (FISEMP ,FISDEL ,FISCLA ,FISNOR ,FISBEL ,FISBE1 ,FISDIV ,FISINV ,FISGIN ,FISCAP ,FISRDI ,FISRD1 ,FISCOR ,FISIVA ) VALUES ( '''|| P_FISEMP || ''' , '''|| P_FISDEL || ''' , '''|| P_FISCLA || ''' , '''|| P_FISNOR || ''' , '''|| P_FISBEL || ''' , '''|| P_FISBE1 || ''' , '''|| P_FISDIV || ''' , '''|| P_FISINV || ''' , '''|| P_FISGIN || ''' , '''|| P_FISCAP || ''' , '''|| P_FISRDI || ''' , '''|| P_FISRD1 || ''' , '''|| P_FISCOR || ''' , '''|| P_FISIVA || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2tfis', StringSQL);
  SET P_MSGCODE = 0;
END
GO


