
CREATE PROCEDURE GPSQLWEB.PROCCREATEAA2TABCO ( IN P_TABNTI VARCHAR(40),
                                               IN P_USERNAME VARCHAR(50),
                                               IN P_IPADDRESS VARCHAR(255),
                                               IN P_USERAGENT VARCHAR(500),
                                               OUT P_TABTIP INTEGER )
	LANGUAGE SQL
	SPECIFIC GPSQLWEB.PROCCREATEAA2TABCO

BEGIN
DECLARE STRINGSQL VARCHAR ( 32000 ) DEFAULT '' ;

SELECT COALESCE ( MAX ( TABTIP ) , 0 ) + 1 INTO P_TABTIP FROM GPDATWEB . AA2TABCO ;
INSERT INTO GPDATWEB . AA2TABCO ( TABTIP , TABNTI ) VALUES ( P_TABTIP , P_TABNTI ) ;

SET STRINGSQL = 'INSERT INTO GPDATWEB.AA2TABCO (TABTIP TABNTI ) VALUES (''' || P_TABTIP || ''' ,  ''' || P_TABNTI || ''' )' ;
CALL GPSQLWEB . PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'Crear' , 'procCreateAa2tabco' , STRINGSQL ) ;
END;