

CREATE PROCEDURE GPSQLWEB.PROCCOUNTAA2TABCO ( IN P_TABTIP INTEGER,
                                              IN P_TABNTI VARCHAR(40),
                                              IN P_USERNAME VARCHAR(50),
                                              IN P_IPADDRESS VARCHAR(255),
                                              IN P_USERAGENT VARCHAR(32000),
                                              OUT TOTAL INTEGER )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC GPSQLWEB.PROCCOUNTAA2TABCO

BEGIN
DECLARE STRINGSQL VARCHAR ( 32000 ) NOT NULL DEFAULT '' ;
DECLARE WHERECLAUSE VARCHAR ( 32000 ) NOT NULL DEFAULT '' ;
DECLARE SORTCLAUSE VARCHAR ( 32000 ) NOT NULL DEFAULT '' ;
DECLARE C1 CURSOR WITH RETURN FOR STMT1 ;



IF P_TABTIP IS NOT NULL AND LENGTH ( P_TABTIP ) > 0 THEN
SET WHERECLAUSE = WHERECLAUSE || ' AND TABTIP = ' || P_TABTIP || ' ' ;
END IF ;


IF P_TABNTI IS NOT NULL AND LENGTH ( P_TABNTI ) > 0 THEN
SET P_TABNTI = UPPER ( TRIM ( P_TABNTI ) ) ;
SET WHERECLAUSE = WHERECLAUSE || ' AND TABNTI LIKE ''%' || P_TABNTI || '%'' ' ;
END IF ;

SET STRINGSQL = 'SELECT COUNT(1) FROM  GPDATWEB.AA2TABCO  WHERE 1=1 ' || WHERECLAUSE ;
PREPARE STMT1 FROM STRINGSQL ;
CALL GPSQLWEB . PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'Contar' , 'procCountAa2tabco' , STRINGSQL ) ;
OPEN C1 ;
FETCH C1 INTO TOTAL ;
CLOSE C1 ;

END;