

CREATE PROCEDURE GPSQLWEB.PROCDELETEAA2TABCO ( IN P_TABTIP INTEGER,
                                               IN P_USERNAME VARCHAR(50),
                                               IN P_IPADDRESS VARCHAR(255),
                                               IN P_USERAGENT VARCHAR(500),
                                               OUT P_MSGCODE INTEGER )
	LANGUAGE SQL
	SPECIFIC GPSQLWEB.PROCDELETEAA2TABCO

BEGIN
DECLARE STRINGSQL VARCHAR ( 32000 ) NOT NULL DEFAULT '' ;
DECLARE V_CANT INT DEFAULT 0 ;

SELECT COUNT ( 1 ) INTO V_CANT FROM GPDATWEB . AA2TABCO WHERE TABTIP = P_TABTIP ;

IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001 ;
SET STRINGSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA' ;
CALL GPSQLWEB . PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'Eliminar' , 'procDeleteAa2tabco' , STRINGSQL ) ;
RETURN ;
END IF ;

IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000 ;
SET STRINGSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR' ;
CALL GPSQLWEB . PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'Eliminar' , 'procDeleteAa2tabco' , STRINGSQL ) ;
RETURN ;
END IF ;

DELETE FROM GPDATWEB . AA2TABCO WHERE TABTIP = P_TABTIP ;
SET P_MSGCODE = 0 ;
SET STRINGSQL = 'DELETE FROM GPDATWEB.AA2TABCO WHERE TABTIP = ''' || P_TABTIP || ''';' ;
CALL GPSQLWEB . PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'Eliminar' , 'procDeleteAa2tabco' , STRINGSQL ) ;
END;
