
CREATE PROCEDURE GPSQLWEB.PROCREADAA2TABCO ( IN P_TABTIP INTEGER,
                                             IN P_TABNTI VARCHAR(40),
                                             IN P_FIRSTRESULT INTEGER,
                                             IN P_MAXRESULT INTEGER,
                                             IN P_SORT VARCHAR(255),
                                             IN P_USERNAME VARCHAR(50),
                                             IN P_IPADDRESS VARCHAR(255),
                                             IN P_USERAGENT VARCHAR(500) )
	RESULT SETS 1
	LANGUAGE SQL
	SPECIFIC GPSQLWEB.PROCREADAA2TABCO

BEGIN
DECLARE STRINGSQL VARCHAR ( 32000 ) NOT NULL DEFAULT '' ;
DECLARE WHERECLAUSE VARCHAR ( 32000 ) NOT NULL DEFAULT '' ;
DECLARE SORTCLAUSE VARCHAR ( 32000 ) NOT NULL DEFAULT '' ;
DECLARE C1 CURSOR WITH RETURN FOR STMT ;

IF P_SORT IS NOT NULL AND LENGTH ( P_SORT ) > 0 THEN
SET SORTCLAUSE = ' ORDER BY ' || P_SORT ;
END IF ;



IF P_TABTIP IS NOT NULL AND LENGTH ( P_TABTIP ) > 0 THEN
SET WHERECLAUSE = WHERECLAUSE || ' AND TABTIP = ' || P_TABTIP || ' ' ;
END IF ;


IF P_TABNTI IS NOT NULL AND LENGTH ( P_TABNTI ) > 0 THEN
SET P_TABNTI = UPPER ( TRIM ( P_TABNTI ) ) ;
SET WHERECLAUSE = WHERECLAUSE || ' AND TABNTI LIKE ''%' || P_TABNTI || '%'' ' ;
END IF ;


IF P_FIRSTRESULT > 0 AND P_MAXRESULT > 0 THEN
SET STRINGSQL = 'SELECT * FROM ( SELECT ROW_NUMBER() OVER() AS ROW__NUMBER, TABTIP ,TABNTI  FROM GPDATWEB.AA2TABCO  WHERE 1=1 ' || WHERECLAUSE || ' ) AS LIMITED__TABLE WHERE ROW__NUMBER BETWEEN ' || P_FIRSTRESULT || ' and ' || ( ( P_MAXRESULT + P_FIRSTRESULT ) - 1 ) || SORTCLAUSE ;
ELSE
IF P_MAXRESULT > 0 THEN
SET STRINGSQL = 'SELECT  TABTIP ,TABNTI  FROM  GPDATWEB.AA2TABCO WHERE 1=1 ' || WHERECLAUSE || SORTCLAUSE || ' FETCH FIRST ' || P_MAXRESULT || ' ROWS ONLY ' ;
ELSE
SET STRINGSQL = 'SELECT  TABTIP ,TABNTI  FROM  GPDATWEB.AA2TABCO WHERE 1=1 ' || WHERECLAUSE || SORTCLAUSE ;
END IF ;
END IF ;

CALL GPSQLWEB . PROCCREATEWEBAUDIT ( P_IPADDRESS , P_USERAGENT , P_USERNAME , 'Leer' , 'procReadAa2tabco' , STRINGSQL ) ;
PREPARE STMT FROM STRINGSQL ;

OPEN C1 ;
END;