
-- DROP PROCEDURE GPSQLWEB.procUpdateSplfile
    
CREATE PROCEDURE GPSQLWEB.procUpdateSplfile
(
     IN P_ID BIGINT,
    IN P_SPLDATA BLOB,
    IN P_SPLNAME VARCHAR(255),
    IN P_SPLMIME VARCHAR(100),
    IN P_SPLDATE TIMESTAMP,
    IN P_SPLTYPE VARCHAR(2),
    IN P_SPLUSER VARCHAR(10),
    IN P_SPLSTATUS VARCHAR(2),
           
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPSQLWEB.SPLFILE WHERE ID = P_ID;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Eliminar', 'procDeleteSplfile', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Eliminar', 'procDeleteSplfile', StringSQL);
        RETURN;
  END IF;

  UPDATE GPSQLWEB.SPLFILE SET SPLDATA= P_SPLDATA , SPLNAME= P_SPLNAME , SPLMIME= P_SPLMIME , SPLDATE = P_SPLDATE , SPLTYPE= P_SPLTYPE , SPLUSER= P_SPLUSER , SPLSTATUS= P_SPLSTATUS  WHERE ID= P_ID ;
  SET P_MSGCODE = 0;
  Set StringSQL = 'UPDATE GPSQLWEB.SPLFILE SET SPLDATA= ''RAWDATA'' , SPLNAME= '''||P_SPLNAME || ''' , SPLMIME= '''||P_SPLMIME || ''' , SPLDATE= '''|| VARCHAR_FORMAT(P_SPLDATE, 'YYYY-MM-DD HH24:MI:SS')    || ''' , SPLTYPE= '''||P_SPLTYPE || ''' , SPLUSER= '''||P_SPLUSER || ''' , SPLSTATUS= '''||P_SPLSTATUS || '''  WHERE ID= '''||P_ID|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateSplfile', StringSQL);
END
GO


