
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2tpais
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2tpais
(
     IN P_PAICLA BIGINT,
            IN P_PAINOM VARCHAR(40),
            IN P_PAICTR INTEGER,
           
    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2TPAIS WHERE PAICLA = P_PAICLA;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2tpais', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2tpais', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2TPAIS SET PAINOM= P_PAINOM , PAICTR= P_PAICTR  WHERE PAICLA= P_PAICLA ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AA2TPAIS SET PAINOM= '''||P_PAINOM || ''' , PAICTR= '''||P_PAICTR || '''  WHERE PAICLA= '''||P_PAICLA|| ''' ;';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2tpais', StringSQL);
END
GO


