
    
--DROP PROCEDURE GPSQLWEB.procCreateAa2mclidir
    
CREATE PROCEDURE GPSQLWEB.procCreateAa2mclidir
(
   IN P_CLINIF VARCHAR(12),
 IN P_CLIDIR VARCHAR(225),

  IN P_USERNAME VARCHAR(50),
  IN P_IPADDRESS VARCHAR(255),
  IN P_USERAGENT VARCHAR(500),
  
  OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  SET P_MSGCODE = 9999;
  
        INSERT INTO GPDATWEB.AA2MCLIDIR (CLINIF ,CLIDIR ) VALUES ( P_CLINIF , P_CLIDIR );

  Set StringSQL = 'INSERT INTO GPDATWEB.AA2MCLIDIR (CLINIF ,CLIDIR ) VALUES ( '''|| P_CLINIF || ''' , '''|| P_CLIDIR || ''' )'; 
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Crear', 'procCreateAa2mclidir', StringSQL);
  SET P_MSGCODE = 0;
END
GO


