
-- DROP PROCEDURE GPSQLWEB.procUpdateAa2mclidir
    
CREATE PROCEDURE GPSQLWEB.procUpdateAa2mclidir
(
    IN P_ROWID BIGINT,
 IN P_CLINIF varchar(12),
 IN P_CLIDIR varchar(225),

    IN P_USERNAME VARCHAR(50),
    IN P_IPADDRESS VARCHAR(255),
    IN P_USERAGENT VARCHAR(500),
    OUT P_MSGCODE INTEGER
)
LANGUAGE SQL
BEGIN
  Declare StringSQL Varchar(32000) Default '';
  Declare V_CANT INT DEFAULT 0;
  
  SELECT COUNT(1) INTO V_CANT FROM GPDATWEB.AA2MCLIDIR WHERE RRN(GPDATWEB.AA2MCLIDIR) =  P_ROWID ;

  IF V_CANT > 1 THEN
	SET P_MSGCODE = 9001;
        SET StringSQL = '9001 - HAY MAS DE UN REGISTRO CON LA CLAVE PRIMARIA';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2mclidir', StringSQL);
        RETURN;
  END IF;

  IF V_CANT = 0 THEN
	SET P_MSGCODE = 9000;
        SET StringSQL = '9000 - NO HAY REGISTROS QUE MODIFICAR CODIGO';
        CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2mclidir', StringSQL);
        RETURN;
  END IF;

  UPDATE GPDATWEB.AA2MCLIDIR SET CLINIF= P_CLINIF , CLIDIR= P_CLIDIR  WHERE RRN(GPDATWEB.AA2MCLIDIR) =  P_ROWID ;
  SET P_MSGCODE = 0;    
  Set StringSQL = 'UPDATE GPDATWEB.AA2MCLIDIR SET CLINIF= '''||P_CLINIF || ''' , CLIDIR= '''||P_CLIDIR || '''  WHERE RRN(GPDATWEB.AA2MCLIDIR) = '''|| P_ROWID || ''';';
  CALL GPSQLWEB.procCreateWebAudit (P_IPADDRESS, P_USERAGENT, P_USERNAME, 'Actualizar', 'procUpdateAa2mclidir', StringSQL);
END
GO


